// Package codegen emits reflection-free apply functions from intermediate minitoml.Document keys.
package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"strconv"
	"time"
)

// FieldKind is the Go field kind supported by the generator.
type FieldKind int

const (
	// FieldString is a string field.
	FieldString FieldKind = iota
	// FieldBool is a bool field.
	FieldBool
	// FieldInt is an int field.
	FieldInt
	// FieldDuration is a time.Duration field parsed from a Go duration string.
	FieldDuration
	// FieldStringSlice is a []string field.
	FieldStringSlice
	// FieldStruct is a nested struct field.
	FieldStruct
)

// Field describes one struct field for intermediate-form apply generation.
type Field struct {
	// GoName is the exported Go field name.
	GoName string
	// Key is the relative TOML/intermediate key segment under the parent prefix.
	Key string
	// Kind is the field type.
	Kind FieldKind
	// Nested holds child fields when Kind is FieldStruct.
	Nested []Field
	// Default is an optional default used when the key is absent (string form).
	Default string
	// Opt is an optional CLI name override ("long" or "long,short").
	Opt string
	// Env is an optional exact environment variable override, or "-" to disable it.
	Env string
	// Help is optional CLI/scaffold help text.
	Help string
	// Arg is a subcommand-only positional role: required, optional, or *.
	Arg string
	// DependsOn is the absolute parent config key from a dependon tag. When the
	// parent reads as empty, this field is omitted from provenance output.
	DependsOn string
	// Falsy is the enum choice from a falsy tag that means "off" for this field.
	// An empty value resolves to it, and it hides fields that depend on this one.
	Falsy string
}

// Spec describes one Bind-style config struct and its prefix table name.
type Spec struct {
	// TypeName is the Go struct type name (e.g. WebServiceConfig).
	TypeName string
	// Prefix is the Bind prefix / top-level TOML table (e.g. webservice).
	Prefix string
	// Fields are the struct fields.
	Fields []Field
}

// Generate emits Go source with Apply* functions that map minitoml.Document keys onto structs.
// Key paths are resolved at generation time; generated code does not use reflection or tag parsing.
func Generate(packageName string, specs []Spec) ([]byte, error) {
	if packageName == "" {
		return nil, fmt.Errorf("codegen: package name is required")
	}
	if len(specs) == 0 {
		return nil, fmt.Errorf("codegen: at least one Spec is required")
	}

	var b bytes.Buffer
	b.WriteString("// Code generated by minitoml/codegen; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", packageName)
	b.WriteString("import (\n")
	b.WriteString("\t\"fmt\"\n")
	if specsNeedTime(specs) {
		b.WriteString("\t\"time\"\n")
	}
	b.WriteString("\n")
	b.WriteString("\t\"github.com/shibukawa/tinybind-go/minitoml\"\n")
	b.WriteString(")\n\n")

	for _, spec := range specs {
		if err := emitApply(&b, spec); err != nil {
			return nil, err
		}
	}

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return b.Bytes(), fmt.Errorf("codegen: format: %w\n%s", err, b.String())
	}
	return formatted, nil
}

func emitApply(b *bytes.Buffer, spec Spec) error {
	if spec.TypeName == "" || spec.Prefix == "" {
		return fmt.Errorf("codegen: TypeName and Prefix are required")
	}
	fn := "Apply" + spec.TypeName
	fmt.Fprintf(b, "// %s maps intermediate document keys under prefix %q onto dst.\n", fn, spec.Prefix)
	fmt.Fprintf(b, "func %s(dst *%s, doc minitoml.Document) error {\n", fn, spec.TypeName)
	b.WriteString("\tif dst == nil {\n")
	b.WriteString("\t\treturn fmt.Errorf(\"minitoml: nil destination\")\n")
	b.WriteString("\t}\n")
	if err := emitFields(b, "dst", spec.Prefix, spec.Fields); err != nil {
		return err
	}
	b.WriteString("\treturn nil\n")
	b.WriteString("}\n\n")
	return nil
}

func emitFields(b *bytes.Buffer, recv, prefix string, fields []Field) error {
	for _, f := range fields {
		if f.GoName == "" || f.Key == "" {
			return fmt.Errorf("codegen: field GoName and Key are required")
		}
		fullKey := joinKey(prefix, f.Key)
		access := recv + "." + f.GoName
		switch f.Kind {
		case FieldString:
			emitStringField(b, access, fullKey, f.Default)
		case FieldBool:
			emitBoolField(b, access, fullKey, f.Default)
		case FieldInt:
			emitIntField(b, access, fullKey, f.Default)
		case FieldDuration:
			if err := emitDurationField(b, access, fullKey, f.Default); err != nil {
				return fmt.Errorf("codegen: %s: %w", f.GoName, err)
			}
		case FieldStringSlice:
			emitStringSliceField(b, access, fullKey)
		case FieldStruct:
			if err := emitFields(b, access, fullKey, f.Nested); err != nil {
				return err
			}
		default:
			return fmt.Errorf("codegen: unsupported field kind %d for %s", f.Kind, f.GoName)
		}
	}
	return nil
}

func emitStringField(b *bytes.Buffer, access, fullKey, def string) {
	fmt.Fprintf(b, "\tif v, ok := doc.Get(%q); ok {\n", fullKey)
	b.WriteString("\t\ts, err := v.AsString()\n")
	b.WriteString("\t\tif err != nil {\n")
	fmt.Fprintf(b, "\t\t\treturn fmt.Errorf(\"minitoml: %s: %%w\", err)\n", fullKey)
	b.WriteString("\t\t}\n")
	fmt.Fprintf(b, "\t\t%s = s\n", access)
	if def != "" {
		b.WriteString("\t} else {\n")
		fmt.Fprintf(b, "\t\t%s = %s\n", access, strconv.Quote(def))
		b.WriteString("\t}\n")
	} else {
		b.WriteString("\t}\n")
	}
}

func emitBoolField(b *bytes.Buffer, access, fullKey, def string) {
	fmt.Fprintf(b, "\tif v, ok := doc.Get(%q); ok {\n", fullKey)
	b.WriteString("\t\tbb, err := v.AsBool()\n")
	b.WriteString("\t\tif err != nil {\n")
	fmt.Fprintf(b, "\t\t\treturn fmt.Errorf(\"minitoml: %s: %%w\", err)\n", fullKey)
	b.WriteString("\t\t}\n")
	fmt.Fprintf(b, "\t\t%s = bb\n", access)
	if def != "" {
		b.WriteString("\t} else {\n")
		fmt.Fprintf(b, "\t\t%s = %v\n", access, def == "true")
		b.WriteString("\t}\n")
	} else {
		b.WriteString("\t}\n")
	}
}

func emitIntField(b *bytes.Buffer, access, fullKey, def string) {
	fmt.Fprintf(b, "\tif v, ok := doc.Get(%q); ok {\n", fullKey)
	b.WriteString("\t\tn, err := v.AsInt()\n")
	b.WriteString("\t\tif err != nil {\n")
	fmt.Fprintf(b, "\t\t\treturn fmt.Errorf(\"minitoml: %s: %%w\", err)\n", fullKey)
	b.WriteString("\t\t}\n")
	fmt.Fprintf(b, "\t\t%s = int(n)\n", access)
	if def != "" {
		b.WriteString("\t} else {\n")
		fmt.Fprintf(b, "\t\t%s = %s\n", access, def)
		b.WriteString("\t}\n")
	} else {
		b.WriteString("\t}\n")
	}
}

// emitDurationField reads the key as a string and parses it with
// time.ParseDuration. A bare number is rejected: the unit is never implied.
func emitDurationField(b *bytes.Buffer, access, fullKey, def string) error {
	fmt.Fprintf(b, "\tif v, ok := doc.Get(%q); ok {\n", fullKey)
	b.WriteString("\t\ts, err := v.AsString()\n")
	b.WriteString("\t\tif err != nil {\n")
	fmt.Fprintf(b, "\t\t\treturn fmt.Errorf(\"minitoml: %s: %%w\", err)\n", fullKey)
	b.WriteString("\t\t}\n")
	b.WriteString("\t\td, err := time.ParseDuration(s)\n")
	b.WriteString("\t\tif err != nil {\n")
	fmt.Fprintf(b, "\t\t\treturn fmt.Errorf(\"minitoml: %s: %%w\", err)\n", fullKey)
	b.WriteString("\t\t}\n")
	fmt.Fprintf(b, "\t\t%s = d\n", access)
	if def == "" {
		b.WriteString("\t}\n")
		return nil
	}
	value, err := time.ParseDuration(def)
	if err != nil {
		return fmt.Errorf("invalid duration default %q: %w", def, err)
	}
	b.WriteString("\t} else {\n")
	fmt.Fprintf(b, "\t\t%s = %d // %s\n", access, int64(value), value)
	b.WriteString("\t}\n")
	return nil
}

func specsNeedTime(specs []Spec) bool {
	var need func([]Field) bool
	need = func(fields []Field) bool {
		for _, f := range fields {
			if f.Kind == FieldDuration || (f.Kind == FieldStruct && need(f.Nested)) {
				return true
			}
		}
		return false
	}
	for _, spec := range specs {
		if need(spec.Fields) {
			return true
		}
	}
	return false
}

func emitStringSliceField(b *bytes.Buffer, access, fullKey string) {
	fmt.Fprintf(b, "\tif v, ok := doc.Get(%q); ok {\n", fullKey)
	b.WriteString("\t\tsl, err := v.AsStringSlice()\n")
	b.WriteString("\t\tif err != nil {\n")
	fmt.Fprintf(b, "\t\t\treturn fmt.Errorf(\"minitoml: %s: %%w\", err)\n", fullKey)
	b.WriteString("\t\t}\n")
	fmt.Fprintf(b, "\t\t%s = sl\n", access)
	b.WriteString("\t}\n")
}

func joinKey(prefix, key string) string {
	if prefix == "" {
		return key
	}
	if key == "" {
		return prefix
	}
	return prefix + "." + key
}

// WebServiceFixtureSpec returns the representative Bind-style fixture used by tests and committed gen code.
func WebServiceFixtureSpec() Spec {
	return Spec{
		TypeName: "WebServiceConfig",
		Prefix:   "webservice",
		Fields: []Field{
			{GoName: "ListenAddr", Key: "listen_addr", Kind: FieldString, Default: ":8080"},
			{GoName: "MaxConns", Key: "max_conns", Kind: FieldInt, Default: "100"},
			{GoName: "CorsOrigins", Key: "cors_origins", Kind: FieldStringSlice},
			{
				GoName: "TLS",
				Key:    "tls",
				Kind:   FieldStruct,
				Nested: []Field{
					{GoName: "Enabled", Key: "enabled", Kind: FieldBool, Default: "false"},
					{GoName: "CertPath", Key: "cert_path", Kind: FieldString},
				},
			},
		},
	}
}
