// Code generated by minitoml/codegen; DO NOT EDIT.

package fixture

import (
	"fmt"

	"github.com/shibukawa/tinybind-go/minitoml"
)

// ApplyWebServiceConfig maps intermediate document keys under prefix "webservice" onto dst.
func ApplyWebServiceConfig(dst *WebServiceConfig, doc minitoml.Document) error {
	if dst == nil {
		return fmt.Errorf("minitoml: nil destination")
	}
	if v, ok := doc.Get("webservice.listen_addr"); ok {
		s, err := v.AsString()
		if err != nil {
			return fmt.Errorf("minitoml: webservice.listen_addr: %w", err)
		}
		dst.ListenAddr = s
	} else {
		dst.ListenAddr = ":8080"
	}
	if v, ok := doc.Get("webservice.max_conns"); ok {
		n, err := v.AsInt()
		if err != nil {
			return fmt.Errorf("minitoml: webservice.max_conns: %w", err)
		}
		dst.MaxConns = int(n)
	} else {
		dst.MaxConns = 100
	}
	if v, ok := doc.Get("webservice.cors_origins"); ok {
		sl, err := v.AsStringSlice()
		if err != nil {
			return fmt.Errorf("minitoml: webservice.cors_origins: %w", err)
		}
		dst.CorsOrigins = sl
	}
	if v, ok := doc.Get("webservice.tls.enabled"); ok {
		bb, err := v.AsBool()
		if err != nil {
			return fmt.Errorf("minitoml: webservice.tls.enabled: %w", err)
		}
		dst.TLS.Enabled = bb
	} else {
		dst.TLS.Enabled = false
	}
	if v, ok := doc.Get("webservice.tls.cert_path"); ok {
		s, err := v.AsString()
		if err != nil {
			return fmt.Errorf("minitoml: webservice.tls.cert_path: %w", err)
		}
		dst.TLS.CertPath = s
	}
	if v, ok := doc.Get("webservice.listeners"); ok {
		elems1, err := v.AsTables()
		if err != nil {
			return fmt.Errorf("minitoml: webservice.listeners: %w", err)
		}
		dst.Listeners = make([]ListenerConfig, len(elems1))
		for i1 := range elems1 {
			if v, ok := elems1[i1].Get("addr"); ok {
				s, err := v.AsString()
				if err != nil {
					return fmt.Errorf("minitoml: webservice.listeners.addr: %w", err)
				}
				dst.Listeners[i1].Addr = s
			}
			if v, ok := elems1[i1].Get("port"); ok {
				n, err := v.AsInt()
				if err != nil {
					return fmt.Errorf("minitoml: webservice.listeners.port: %w", err)
				}
				dst.Listeners[i1].Port = int(n)
			} else {
				dst.Listeners[i1].Port = 80
			}
			if v, ok := elems1[i1].Get("tls.enabled"); ok {
				bb, err := v.AsBool()
				if err != nil {
					return fmt.Errorf("minitoml: webservice.listeners.tls.enabled: %w", err)
				}
				dst.Listeners[i1].TLS.Enabled = bb
			} else {
				dst.Listeners[i1].TLS.Enabled = false
			}
			if v, ok := elems1[i1].Get("tls.cert_path"); ok {
				s, err := v.AsString()
				if err != nil {
					return fmt.Errorf("minitoml: webservice.listeners.tls.cert_path: %w", err)
				}
				dst.Listeners[i1].TLS.CertPath = s
			}
		}
	}
	return nil
}
