// Code generated by minitoml/codegen; DO NOT EDIT.

package fixture

import (
	"fmt"

	"github.com/shibukawa/tinybind-go/minitoml"
)

// ApplyWebServiceConfig maps intermediate document keys under prefix "webservice" onto dst.
func ApplyWebServiceConfig(dst *WebServiceConfig, doc minitoml.Document) error {
	if dst == nil {
		return fmt.Errorf("minitoml: nil destination")
	}
	if v, ok := doc.Get("webservice.listen_addr"); ok {
		s, err := v.AsString()
		if err != nil {
			return fmt.Errorf("minitoml: webservice.listen_addr: %w", err)
		}
		dst.ListenAddr = s
	} else {
		dst.ListenAddr = ":8080"
	}
	if v, ok := doc.Get("webservice.max_conns"); ok {
		n, err := v.AsInt()
		if err != nil {
			return fmt.Errorf("minitoml: webservice.max_conns: %w", err)
		}
		dst.MaxConns = int(n)
	} else {
		dst.MaxConns = 100
	}
	if v, ok := doc.Get("webservice.cors_origins"); ok {
		sl, err := v.AsStringSlice()
		if err != nil {
			return fmt.Errorf("minitoml: webservice.cors_origins: %w", err)
		}
		dst.CorsOrigins = sl
	}
	if v, ok := doc.Get("webservice.tls.enabled"); ok {
		bb, err := v.AsBool()
		if err != nil {
			return fmt.Errorf("minitoml: webservice.tls.enabled: %w", err)
		}
		dst.TLS.Enabled = bb
	} else {
		dst.TLS.Enabled = false
	}
	if v, ok := doc.Get("webservice.tls.cert_path"); ok {
		s, err := v.AsString()
		if err != nil {
			return fmt.Errorf("minitoml: webservice.tls.cert_path: %w", err)
		}
		dst.TLS.CertPath = s
	}
	return nil
}
