// Code generated by configbind/codegen; DO NOT EDIT.

package configmodulea

import (
	"fmt"

	"github.com/shibukawa/tinybind-go/cliparser"
	"github.com/shibukawa/tinybind-go/configbind"
)

func init() {
	registerConfigDefinition0()
}

func registerConfigDefinition0() {
	configbind.Register[Config](configbind.Definition{
		TypeName: "github.com/shibukawa/tinybind-go/testdata/configmodulea.Config",
		Prefix:   "framework",
		Doc:      "Config deliberately shares its unqualified name with configmoduleb.Config",
		KnownKeys: []string{
			"framework.endpoint",
		},
		Defaults: map[string]string{
			"framework.endpoint": "framework",
		},
		FlagMetas: []cliparser.FieldMeta{
			{Prefix: "framework", Key: "endpoint", Help: "framework endpoint"},
		},
		Apply: applyConfigDefinition0,
		Scaffold: []configbind.ScaffoldField{
			{Key: "endpoint", Kind: configbind.ScaffoldString, Default: "framework", Help: "framework endpoint"},
		},
	})
}

func applyConfigDefinition0(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*Config)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply Config: bad destination")
	}
	if v, ok := o.GetString("framework.endpoint"); ok {
		p.Endpoint = v
	} else {
		p.Endpoint = "framework"
	}
	return nil
}
