package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"strconv"
)

// EmitCacheKeys generates the key method for every plan in the package.
func EmitCacheKeys(plan *CacheKeyPackagePlan) ([]byte, error) {
	return emitCacheKeysSelected(plan, nil)
}

// emitCacheKeysSelected emits the named subset of a package plan. A nil
// selection emits everything.
func emitCacheKeysSelected(plan *CacheKeyPackagePlan, selected map[string]bool) ([]byte, error) {
	if plan == nil {
		return nil, fmt.Errorf("cachekeybind: nil plan")
	}
	e := &cacheKeyEmitter{packagePath: plan.PackagePath}
	for _, key := range plan.Keys {
		if selected != nil && !selected[key.Name] {
			continue
		}
		if err := e.key(key); err != nil {
			return nil, err
		}
	}
	if e.body.Len() == 0 {
		return nil, nil
	}

	var out bytes.Buffer
	out.WriteString("// Code generated by tinybind; DO NOT EDIT.\n\n")
	fmt.Fprintf(&out, "package %s\n\n", plan.Package)
	writeCacheKeyImports(&out, e.body.Bytes())
	out.Write(e.body.Bytes())

	formatted, err := format.Source(out.Bytes())
	if err != nil {
		return out.Bytes(), fmt.Errorf("cachekeybind: format generated code: %w\n%s", err, out.String())
	}
	return formatted, nil
}

// cacheKeyImports lists every package the key emitter can reference, with the
// qualifier that proves the reference. A closure parameter is the only way a
// framed type reaches the file by name, which is why time is here at all.
var cacheKeyImports = []struct {
	qualifier string
	path      string
	stdlib    bool
}{
	{qualifier: "time", path: "time", stdlib: true},
	{qualifier: "cachekeybind", path: cachekeybindImportPath},
}

func writeCacheKeyImports(out *bytes.Buffer, body []byte) {
	var stdlib, external []string
	for _, item := range cacheKeyImports {
		if !usesQualifier(body, item.qualifier) {
			continue
		}
		if item.stdlib {
			stdlib = append(stdlib, item.path)
		} else {
			external = append(external, item.path)
		}
	}
	if len(stdlib)+len(external) == 0 {
		return
	}
	out.WriteString("import (\n")
	for _, path := range stdlib {
		fmt.Fprintf(out, "\t%q\n", path)
	}
	if len(stdlib) > 0 && len(external) > 0 {
		out.WriteString("\n")
	}
	for _, path := range external {
		fmt.Fprintf(out, "\t%q\n", path)
	}
	out.WriteString(")\n\n")
}

type cacheKeyEmitter struct {
	body        bytes.Buffer
	packagePath string
	// depth numbers the closure parameters a nested optional or array needs, so
	// an inner frame never shadows the one it is written inside.
	depth int
}

func (e *cacheKeyEmitter) key(key CacheKeyPlan) error {
	receiver := "v"
	if len(key.Fields) == 0 {
		// The collector never plans one, but EmitCacheKeys is exported and a
		// hand-built plan reaching here would emit an identity-only key: one
		// shared entry for every instance of the type.
		return fmt.Errorf("cachekeybind: %s plans no field; an identity-only key would be shared by every instance", key.Name)
	}
	framed := make([]string, 0, len(key.Fields))
	for _, field := range key.Fields {
		e.depth = 0
		call, err := e.frame(field.Type, receiver+"."+field.Name)
		if err != nil {
			return fmt.Errorf("cachekeybind: %s.%s: %w", key.Name, field.Name, err)
		}
		framed = append(framed, call)
	}
	fmt.Fprintf(&e.body, "var _ cachekeybind.CacheKey = %s{}\n\n", key.Name)
	fmt.Fprintf(&e.body, "// CacheKey reports the cache key of a %s. The identity comes first, so an\n", key.Name)
	e.body.WriteString("// entry of this type can never be read as an entry of another.\n")
	fmt.Fprintf(&e.body, "func (%s %s) CacheKey() string {\n", receiver, key.Name)
	fmt.Fprintf(&e.body, "\treturn cachekeybind.KeyString(%s)", strconv.Quote(key.Identity(e.packagePath)))
	for _, call := range framed {
		fmt.Fprintf(&e.body, " +\n\t\t%s", call)
	}
	e.body.WriteString("\n}\n\n")
	return nil
}

// frame writes the helper call that encodes one value. An unplannable kind is an
// error rather than a fallback, because every fallback here is a key missing a
// field, which is the silent wrong answer this package exists to remove.
func (e *cacheKeyEmitter) frame(t CacheKeyType, expr string) (string, error) {
	switch t.Kind {
	case CacheKeyString:
		return fmt.Sprintf("cachekeybind.KeyString(%s)", expr), nil
	case CacheKeyBool:
		return fmt.Sprintf("cachekeybind.KeyBool(%s)", expr), nil
	case CacheKeyInt:
		return fmt.Sprintf("cachekeybind.KeyInt(%s)", expr), nil
	case CacheKeyUint:
		return fmt.Sprintf("cachekeybind.KeyUint(%s)", expr), nil
	case CacheKeyFloat:
		return fmt.Sprintf("cachekeybind.KeyFloat(%s)", expr), nil
	case CacheKeyBytes:
		return fmt.Sprintf("cachekeybind.KeyBytes(%s)", expr), nil
	case CacheKeyTime:
		return fmt.Sprintf("cachekeybind.KeyTime(%s)", expr), nil
	case CacheKeyOptional:
		return e.wrap("KeyOptional", t, expr)
	case CacheKeyArray:
		return e.wrap("KeyArray", t, expr)
	default:
		return "", fmt.Errorf("kind %q has no framing helper", t.Kind)
	}
}

// wrap writes an optional or an array and the per-element encoder it frames
// through.
func (e *cacheKeyEmitter) wrap(helper string, t CacheKeyType, expr string) (string, error) {
	if t.Elem == nil {
		return "", fmt.Errorf("kind %q plans no element type", t.Kind)
	}
	e.depth++
	param := fmt.Sprintf("e%d", e.depth)
	body, err := e.frame(*t.Elem, param)
	e.depth--
	if err != nil {
		return "", err
	}
	return fmt.Sprintf("cachekeybind.%s(%s, func(%s %s) string { return %s })", helper, expr, param, t.Elem.Go, body), nil
}
