package generator_test

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/shibukawa/tinybind-go/generator"
)

// cborFixture writes a temp module holding the named files and returns its
// directory.
func cborFixture(t *testing.T, files map[string]string) string {
	t.Helper()
	dir := t.TempDir()
	writeTempModule(t, dir)
	for name, content := range files {
		path := filepath.Join(dir, name)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	tidyTempModule(t, dir)
	return dir
}

// analyzeCbor writes one source file and analyzes it. The analysis is
// go/types-based, so the module is tidied first and the test is one short mode
// skips along with every other that shells out to the toolchain.
func analyzeCbor(t *testing.T, src string) (*generator.CborPackagePlan, error) {
	t.Helper()
	dir := t.TempDir()
	writeTempModule(t, dir)
	if err := os.WriteFile(filepath.Join(dir, "main.go"), []byte(src), 0o644); err != nil {
		t.Fatal(err)
	}
	tidyTempModule(t, dir)
	return generator.AnalyzeCborCodecsWithOptions(dir, generator.DefaultOptions())
}

// generateCbor analyzes and emits, failing the test on either error.
func generateCbor(t *testing.T, src string) string {
	t.Helper()
	plan, err := analyzeCbor(t, src)
	if err != nil {
		t.Fatalf("analyze: %v", err)
	}
	code, err := generator.EmitCborCodecs(plan)
	if err != nil {
		t.Fatalf("emit: %v", err)
	}
	return string(code)
}

// fixedPointSource is the shape decision:cbor-scale-lives-in-the-type settles
// on: a declared type per scale, each carrying its own two methods, so the
// generator never sees a scale and never converts one.
const fixedPointSource = `package main

import "github.com/shibukawa/tinygodriver/encoding/cbor"

// Fixed1024 is a fixed-point value at 1/1024. The scale is the type's, which is
// why two scales are two types rather than one type and a tag.
type Fixed1024 int64

func (f Fixed1024) AppendCBORTo(dst []byte) []byte { return cbor.AppendInt(dst, int64(f)) }

func (f *Fixed1024) DecodeCBORFrom(data []byte) error {
	r := cbor.ReaderOver(data, cbor.DecoderOptions{})
	v, err := r.ReadInt()
	if err != nil {
		return err
	}
	if !r.Done() {
		return cbor.ErrExtraneousData
	}
	*f = Fixed1024(v)
	return nil
}
`

const playerInputSource = `package main

import "github.com/shibukawa/tinybind-go/cborbind"

// PlayerInput is the reference message: a fixed field order, one sized integer
// per field, and a type carrying its own encoding among them.
type PlayerInput struct {
	Tick    uint32
	MoveX   Fixed1024
	MoveY   Fixed1024
	Buttons uint16
}

var _ = cborbind.GenerateWireCodec[PlayerInput]()
`

// The wire form is the protocol. These are the bytes the driver's own
// codec_test.go pins for the same message, so a generated codec producing them
// is a generated codec that could replace the hand-written reference.
func TestWireCodecReproducesThePinnedReferenceBytes(t *testing.T) {
	dir := cborFixture(t, map[string]string{
		"fixed.go": fixedPointSource,
		"input.go": playerInputSource,
	})
	writeCborCodec(t, dir)
	writeProbe(t, dir, `
func TestPinnedBytes(t *testing.T) {
	in := PlayerInput{Tick: 1234, MoveX: -1, MoveY: 0, Buttons: 3}
	want := []byte{
		0x84,             // array of 4
		0x19, 0x04, 0xd2, // 1234
		0x20, // -1
		0x00, // 0
		0x03, // 3
	}
	got := in.AppendCBORTo(nil)
	if !bytes.Equal(got, want) {
		t.Fatalf("encoded %x, want %x", got, want)
	}
	if err := cbor.Wire().Validate(got); err != nil {
		t.Fatalf("the generated bytes are not legal under the wire profile: %v", err)
	}
}

func TestRoundTripIsBytewise(t *testing.T) {
	in := PlayerInput{Tick: 7, MoveX: -2048, MoveY: 512, Buttons: 0xffff}
	encoded := in.AppendCBORTo(nil)
	var out PlayerInput
	if err := out.DecodeCBORFrom(encoded); err != nil {
		t.Fatal(err)
	}
	if out != in {
		t.Fatalf("round trip gave %+v, want %+v", out, in)
	}
	if again := out.AppendCBORTo(nil); !bytes.Equal(again, encoded) {
		t.Fatalf("re-encoding gave %x, want %x", again, encoded)
	}
}

// A value too wide for the field it is read into is a protocol error, not a
// silent truncation, which is the whole reason the reads are width-enforcing.
func TestAWideValueInANarrowFieldIsRefused(t *testing.T) {
	wide := []byte{0x84, 0x19, 0x04, 0xd2, 0x20, 0x00, 0x1a, 0x00, 0x01, 0x00, 0x00}
	var out PlayerInput
	if err := out.DecodeCBORFrom(wide); err == nil {
		t.Fatal("a value beyond uint16 was accepted into a uint16 field")
	}
}

// An array whose count disagrees with the schema is the two ends running
// different protocols, and the wire profile has no way to be tolerant of it.
func TestAShortArrayIsRefused(t *testing.T) {
	short := []byte{0x83, 0x19, 0x04, 0xd2, 0x20, 0x00}
	var out PlayerInput
	if err := out.DecodeCBORFrom(short); err == nil {
		t.Fatal("an array of 3 was accepted for a schema of 4")
	}
}

// The steady state of a tick loop has to be free of allocation on both sides,
// with the destination buffer and the Reader owned and reused by the caller.
func TestFixedShapeMessageIsZeroAllocationInSteadyState(t *testing.T) {
	in := PlayerInput{Tick: 1234, MoveX: -1, MoveY: 2, Buttons: 3}
	buf := make([]byte, 0, 64)
	encoded := in.AppendCBORTo(nil)
	r := cbor.Wire().ReaderOver(encoded)
	var out PlayerInput

	if n := testing.AllocsPerRun(200, func() {
		buf = in.AppendCBORTo(buf[:0])
	}); n != 0 {
		t.Fatalf("encode allocated %v per run, want 0", n)
	}
	if n := testing.AllocsPerRun(200, func() {
		r.Reset(encoded)
		if err := decodePlayerInputCBORWire(&r, &out); err != nil {
			t.Fatal(err)
		}
	}); n != 0 {
		t.Fatalf("decode allocated %v per run, want 0", n)
	}
	if out != in {
		t.Fatalf("decoded %+v, want %+v", out, in)
	}
}
`)
	runProbe(t, dir)
}

// The two profiles are different contracts, and the generated code pins which
// one it reads. A wire codec handed a map is the two ends running different
// protocols, which is exactly what pinning exists to catch.
func TestAWireCodecRefusesAWorldMessage(t *testing.T) {
	dir := cborFixture(t, map[string]string{
		"fixed.go": fixedPointSource,
		"input.go": playerInputSource,
	})
	writeCborCodec(t, dir)
	writeProbe(t, dir, `
func TestAMapIsNotAWireMessage(t *testing.T) {
	// The same four values, written the way a world-profile encoder would.
	world := cbor.AppendMapHeader(nil, 4)
	world = cbor.AppendText(world, "Tick")
	world = cbor.AppendUint(world, 1234)
	world = cbor.AppendText(world, "MoveX")
	world = cbor.AppendInt(world, -1)
	world = cbor.AppendText(world, "MoveY")
	world = cbor.AppendInt(world, 0)
	world = cbor.AppendText(world, "Buttons")
	world = cbor.AppendUint(world, 3)

	var out PlayerInput
	if err := out.DecodeCBORFrom(world); err == nil {
		t.Fatal("a wire codec read a world-profile message")
	}
	// And the wire profile refuses those bytes outright, before any decoding.
	if err := cbor.Wire().Validate(world); err == nil {
		t.Fatal("the wire profile accepted a map")
	}
}
`)
	runProbe(t, dir)
}

// A world state is entities in slices, and the scalar inside them is the type
// carrying its own codec. A field silently dropped here is the worst failure
// available: both ends still agree about everything they did encode.
func TestSliceOfEntitiesCarriesATypeWithItsOwnCodec(t *testing.T) {
	dir := cborFixture(t, map[string]string{
		"fixed.go": fixedPointSource,
		"world.go": `package main

import "github.com/shibukawa/tinybind-go/cborbind"

type Entity struct {
	ID   uint32
	PosX Fixed1024
	PosY Fixed1024
}

type WorldState struct {
	Tick     uint32
	Entities []Entity
	Names    []string
}

var _ = cborbind.GenerateWorldCodec[WorldState]()
`,
	})
	writeCborCodec(t, dir)
	writeProbe(t, dir, `
func TestEntitiesRoundTrip(t *testing.T) {
	in := WorldState{
		Tick:     9,
		Entities: []Entity{{ID: 1, PosX: -1024, PosY: 2048}, {ID: 2, PosX: 0, PosY: -1}},
		Names:    []string{"alpha", "beta"},
	}
	encoded := in.AppendCBORTo(nil)
	if err := cbor.World().Validate(encoded); err != nil {
		t.Fatalf("the generated bytes are not legal under the world profile: %v", err)
	}
	var out WorldState
	if err := out.DecodeCBORFrom(encoded); err != nil {
		t.Fatal(err)
	}
	if out.Tick != in.Tick || len(out.Entities) != 2 || len(out.Names) != 2 {
		t.Fatalf("decoded %+v, want %+v", out, in)
	}
	if out.Entities[0] != in.Entities[0] || out.Entities[1] != in.Entities[1] {
		t.Fatalf("entities decoded as %+v, want %+v", out.Entities, in.Entities)
	}
	if out.Names[0] != "alpha" || out.Names[1] != "beta" {
		t.Fatalf("names decoded as %q", out.Names)
	}
	if again := out.AppendCBORTo(nil); !bytes.Equal(again, encoded) {
		t.Fatalf("re-encoding gave %x, want %x", again, encoded)
	}
}

// Skipping a key the schema does not know is the tolerance the world profile
// exists to provide, and it is what lets a snapshot outlive the version that
// wrote it.
func TestAnUnknownKeyIsSkipped(t *testing.T) {
	in := WorldState{Tick: 4, Entities: []Entity{{ID: 3}}, Names: nil}
	encoded := in.AppendCBORTo(nil)
	// Rebuild the same map with one extra pair, which is what a newer writer
	// would have produced.
	grown := cbor.AppendMapHeader(nil, 4)
	grown = cbor.AppendText(grown, "Added")
	grown = cbor.AppendUint(grown, 99)
	grown = append(grown, encoded[1:]...)

	var out WorldState
	if err := out.DecodeCBORFrom(grown); err != nil {
		t.Fatalf("an unknown key was not skipped: %v", err)
	}
	if out.Tick != 4 || len(out.Entities) != 1 || out.Entities[0].ID != 3 {
		t.Fatalf("decoded %+v after skipping, want the known fields intact", out)
	}
}
`)
	runProbe(t, dir)
}

// writeCborCodec runs the generator over dir and writes what it emitted.
func writeCborCodec(t *testing.T, dir string) {
	t.Helper()
	plan, err := generator.AnalyzeCborCodecsWithOptions(dir, generator.DefaultOptions())
	if err != nil {
		t.Fatalf("analyze: %v", err)
	}
	if len(plan.Types) == 0 {
		t.Fatal("nothing was planned")
	}
	code, err := generator.EmitCborCodecs(plan)
	if err != nil {
		t.Fatalf("emit: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "cborbind_gen.go"), code, 0o644); err != nil {
		t.Fatal(err)
	}
}

func writeProbe(t *testing.T, dir, body string) {
	t.Helper()
	probe := `package main

import (
	"bytes"
	"testing"

	"github.com/shibukawa/tinygodriver/encoding/cbor"
)

// Not every probe compares bytes or names the driver, and an unused import is
// a compile error.
var _ = bytes.Equal
var _ = cbor.Wire
` + body
	if err := os.WriteFile(filepath.Join(dir, "probe_test.go"), []byte(probe), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "main.go"), []byte("package main\n\nfunc main() {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
}

func runProbe(t *testing.T, dir string) {
	t.Helper()
	command := exec.Command("go", "test", "./...")
	command.Dir = dir
	command.Env = append(os.Environ(), "GOWORK=off", "GOFLAGS=-mod=mod")
	if output, err := command.CombinedOutput(); err != nil {
		generated, _ := os.ReadFile(filepath.Join(dir, "cborbind_gen.go"))
		t.Fatalf("generated codec failed its probe: %v\n%s\n%s", err, output, generated)
	}
}

// Every rejection below is a value that would encode, round trip, and then
// differ between two runs or two targets. A build error at the keystroke that
// caused it is the cheapest place any of them can be found.
func TestNondeterministicTypesAreRefused(t *testing.T) {
	tests := []struct {
		name  string
		field string
		want  []string
	}{
		{
			name:  "a bare float",
			field: "Ratio float64",
			want:  []string{"float64", "deterministic"},
		},
		{
			// The declared kind looks innocent, so a diagnostic naming only it
			// sends the author looking in the wrong place.
			name:  "a float behind a named type",
			field: "Ratio Scale",
			want:  []string{"Scale", "float64 underneath"},
		},
		{
			name:  "a Go map",
			field: "Lookup map[string]uint32",
			want:  []string{"randomizes iteration order", "ordered slice"},
		},
		{
			name:  "an interface",
			field: "Payload any",
			want:  []string{"interface", "concrete type"},
		},
		{
			name:  "a pointer",
			field: "Parent *Nested",
			want:  []string{"pointer", "aliasing"},
		},
		{
			name:  "a wall clock",
			field: "At time.Time",
			want:  []string{"time.Time", "tick"},
		},
		{
			// int is 64 bits on a host and 32 on wasm, so the range a field
			// accepts would depend on where the binary ran.
			name:  "a platform-width integer",
			field: "Count int",
			want:  []string{"platform-width", "int32", "int64"},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			_, err := analyzeCbor(t, `package main

import (
	"time"

	"github.com/shibukawa/tinybind-go/cborbind"
)

var _ = time.Now

type Scale float64

type Nested struct{ N uint32 }

type Message struct {
	Tick uint32
	`+tt.field+`
}

var _ = cborbind.GenerateWireCodec[Message]()
`)
			if err == nil {
				t.Fatalf("%s was accepted", tt.name)
			}
			for _, want := range tt.want {
				if !strings.Contains(err.Error(), want) {
					t.Fatalf("diagnostic %q does not name %q", err, want)
				}
			}
			if !strings.Contains(err.Error(), "Message.") {
				t.Fatalf("diagnostic %q names neither the type nor the field", err)
			}
		})
	}
}

// The version covers wire-observable shape and nothing else. Getting that wrong
// is expensive in both directions: a version that moves when the bytes did not
// makes every generator upgrade a coordinated redeploy, and one that does not
// move when they did gives two protocols one identifier.
func TestProtocolVersionCoversWireShapeOnly(t *testing.T) {
	source := func(buttons, declaration string) string {
		return `package main

import "github.com/shibukawa/tinybind-go/cborbind"

type Message struct {
	Tick    uint32
	Buttons ` + buttons + `
}

var _ = cborbind.` + declaration + `[Message]()
`
	}
	version := func(t *testing.T, src string) string {
		t.Helper()
		plan, err := analyzeCbor(t, src)
		if err != nil {
			t.Fatal(err)
		}
		if plan.Version == "" {
			t.Fatal("no version was derived")
		}
		return plan.Version
	}

	base := version(t, source("uint16", "GenerateWireCodec"))
	if again := version(t, source("uint16", "GenerateWireCodec")); again != base {
		t.Fatalf("an unchanged schema produced %s then %s", base, again)
	}
	if wider := version(t, source("uint32", "GenerateWireCodec")); wider == base {
		t.Fatalf("changing a field's width left the version at %s", base)
	}
	// Emitting only the encoder changes no byte on the wire, so it must change
	// no version: otherwise a client and a server that agree about the format
	// refuse each other over which halves they generated.
	if narrowed := version(t, source("uint16", "GenerateWireEncoder")); narrowed != base {
		t.Fatalf("narrowing the direction moved the version from %s to %s", base, narrowed)
	}
	// The profile is part of the contract, so it is part of the version.
	if world := version(t, source("uint16", "GenerateWorldCodec")); world == base {
		t.Fatalf("changing the profile left the version at %s", base)
	}
}

func TestCborDeclarationErrors(t *testing.T) {
	tests := []struct {
		name string
		src  string
		want string
	}{
		{
			name: "a type declared for both profiles",
			src: `type Message struct{ Tick uint32 }

var _ = cborbind.GenerateWireCodec[Message]()
var _ = cborbind.GenerateWorldCodec[Message]()`,
			want: "cannot publish two AppendCBORTo methods",
		},
		{
			name: "an unknown tag option",
			src: `type Message struct {
	Tick uint32 ` + "`cbor:\"tick,scale=1024\"`" + `
}

var _ = cborbind.GenerateWorldCodec[Message]()`,
			want: "unknown cbor tag option",
		},
		{
			name: "a partly numbered type",
			src: `type Message struct {
	Tick    uint32 ` + "`cbor:\"tick,key=1\"`" + `
	Buttons uint16
}

var _ = cborbind.GenerateWorldCodec[Message]()`,
			want: "give every field a key option, or none",
		},
		{
			name: "a type reaching itself",
			src: `type Message struct {
	Tick  uint32
	Inner []Message
}

var _ = cborbind.GenerateWireCodec[Message]()`,
			want: "reaches itself",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			_, err := analyzeCbor(t, "package main\n\nimport \"github.com/shibukawa/tinybind-go/cborbind\"\n\n"+tt.src+"\n")
			if err == nil {
				t.Fatalf("%s was accepted", tt.name)
			}
			if !strings.Contains(err.Error(), tt.want) {
				t.Fatalf("diagnostic %q does not say %q", err, tt.want)
			}
		})
	}
}

// A type whose author already wrote the codec has one. Generating a second
// would either fail to compile or quietly replace what they wrote, and either
// way the declaration is the thing to remove.
func TestAHandWrittenCodecRefusesTheDeclaration(t *testing.T) {
	_, err := analyzeCbor(t, `package main

import (
	"github.com/shibukawa/tinybind-go/cborbind"
	"github.com/shibukawa/tinygodriver/encoding/cbor"
)

type Message struct{ Tick uint32 }

func (m Message) AppendCBORTo(dst []byte) []byte { return cbor.AppendUint(dst, uint64(m.Tick)) }

var _ = cborbind.GenerateWireCodec[Message]()
`)
	if err == nil {
		t.Fatal("a declaration beside a hand-written codec was accepted")
	}
	if !strings.Contains(err.Error(), "already carries its own CBOR codec") {
		t.Fatalf("diagnostic %q does not explain the conflict", err)
	}
}

// A project declaring no CBOR codec must be untouched by any of this.
func TestAPackageDeclaringNoCodecEmitsNothing(t *testing.T) {
	plan, err := analyzeCbor(t, `package main

type Message struct {
	Ratio float64
	At    map[string]int
}

func main() {}
`)
	if err != nil {
		t.Fatalf("a package with no declaration was refused: %v", err)
	}
	if len(plan.Types) != 0 {
		t.Fatalf("planned %d types for a package that declared none", len(plan.Types))
	}
	code, err := generator.EmitCborCodecs(plan)
	if err != nil {
		t.Fatal(err)
	}
	if len(code) != 0 {
		t.Fatalf("emitted %d bytes for a package that declared no codec", len(code))
	}
}

// The wire profile has no field names, so a struct that reaches it as a nested
// field composes into the same array rather than growing one of its own.
func TestNestedStructAppendsIntoTheSameBuffer(t *testing.T) {
	code := generateCbor(t, `package main

import "github.com/shibukawa/tinybind-go/cborbind"

type Vec2 struct {
	X int32
	Y int32
}

type Move struct {
	Tick uint32
	At   Vec2
}

var _ = cborbind.GenerateWireCodec[Move]()
`)
	for _, want := range []string{
		"func appendMoveCBORWire(dst []byte, v Move) []byte",
		"dst = appendVec2CBORWire(dst, v.At)",
		"func appendVec2CBORWire(dst []byte, v Vec2) []byte",
		"if err := decodeVec2CBORWire(r, &v.At); err != nil",
	} {
		if !strings.Contains(code, want) {
			t.Fatalf("generated code does not contain %q\n%s", want, code)
		}
	}
	// A nested type nothing declared gets the functions and no public method:
	// a method is code size in every binary carrying the type, and nothing
	// asked for one.
	if strings.Contains(code, "func (v Vec2) AppendCBORTo") {
		t.Fatalf("a nested type acquired a public method it never asked for\n%s", code)
	}
	if !strings.Contains(code, "func (v Move) AppendCBORTo") {
		t.Fatalf("the declared type did not publish its method\n%s", code)
	}
}

// A direction the declaration did not name must not be emitted for a nested
// type either. Emitting a decoder for a message the client only ever sends is
// code size in a wasm binary, which is the whole reason the annotations name a
// direction.
func TestNarrowedDirectionReachesNestedTypes(t *testing.T) {
	code := generateCbor(t, `package main

import "github.com/shibukawa/tinybind-go/cborbind"

type Vec2 struct {
	X int32
	Y int32
}

type Move struct {
	Tick uint32
	At   Vec2
}

var _ = cborbind.GenerateWireEncoder[Move]()
`)
	for _, want := range []string{"func appendMoveCBORWire", "func appendVec2CBORWire", "func (v Move) AppendCBORTo"} {
		if !strings.Contains(code, want) {
			t.Fatalf("generated code does not contain %q\n%s", want, code)
		}
	}
	for _, unwanted := range []string{"func decodeMoveCBORWire", "func decodeVec2CBORWire", "DecodeCBORFrom", "cborWireProfile"} {
		if strings.Contains(code, unwanted) {
			t.Fatalf("an encode-only declaration emitted %q\n%s", unwanted, code)
		}
	}
}

// The mapping pass walks every package-level struct, including ones no mapping
// path will ever touch. Refusing the whole run for a field kind that would
// never have been emitted made those packages ungeneratable for a reason that
// never applied to them -- and made this mode unreachable from the combined
// CLI, since a sized integer per field is exactly what the wire profile is for.
func TestAStructNoMappingPathTouchesDoesNotFailTheRun(t *testing.T) {
	dir := t.TempDir()
	writeTempModule(t, dir)
	if err := os.WriteFile(filepath.Join(dir, "main.go"), []byte(`package main

import "github.com/shibukawa/tinybind-go/cborbind"

// PlayerInput is a CBOR message. Nothing binds it, writes it, or asks for a
// JSON codec, and its sized integers are what fieldTypeKind cannot map.
type PlayerInput struct {
	Tick    uint32
	Buttons uint16
}

var _ = cborbind.GenerateWireCodec[PlayerInput]()

func main() {}
`), 0o644); err != nil {
		t.Fatal(err)
	}
	tidyTempModule(t, dir)

	// DefaultOptions, which is what the generate command runs with.
	// AnalyzePackage sets GenerateAll, and asking for everything still means
	// asking for this one.
	if _, err := generator.AnalyzePackageWithOptions(dir, generator.DefaultOptions()); err != nil {
		t.Fatalf("a struct nothing maps failed the mapping analysis: %v", err)
	}
	plan, err := generator.AnalyzeCborCodecsWithOptions(dir, generator.DefaultOptions())
	if err != nil {
		t.Fatalf("analyze cbor: %v", err)
	}
	if len(plan.Types) != 1 {
		t.Fatalf("planned %d CBOR types, want 1", len(plan.Types))
	}
}

// The refusal is deferred, not removed. A struct something asks the mapping
// pass to map is still refused, with the diagnostic it always had, because the
// alternative is generated source naming a function nothing defined.
func TestAnUnmappableStructIsStillRefusedWhenSomethingNeedsIt(t *testing.T) {
	tests := []struct {
		name string
		src  string
		want string
	}{
		{
			name: "named by a call site",
			src: `type Reading struct{ Tick uint32 }

func main() { _ = jsonbind.EncodeJSON(os.Stdout, Reading{}) }`,
			want: "Reading: field Tick",
		},
		{
			name: "held by a struct that is used",
			src: `type Inner struct{ Tick uint32 }

type Outer struct {
	Name  string
	Inner Inner
}

func main() { _ = jsonbind.EncodeJSON(os.Stdout, Outer{}) }`,
			want: "Inner: field Tick",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir := t.TempDir()
			writeTempModule(t, dir)
			src := `package main

import (
	"os"

	"github.com/shibukawa/tinybind-go/jsonbind"
)

` + tt.src + "\n"
			if err := os.WriteFile(filepath.Join(dir, "main.go"), []byte(src), 0o644); err != nil {
				t.Fatal(err)
			}
			tidyTempModule(t, dir)
			_, err := generator.AnalyzePackage(dir)
			if err == nil {
				t.Fatal("an unmappable struct something needs was accepted")
			}
			if !strings.Contains(err.Error(), tt.want) {
				t.Fatalf("diagnostic %q does not name %q", err, tt.want)
			}
		})
	}
}

// Asking for everything means asking for this one too, so generate-all keeps
// the refusal it has always had.
func TestGenerateAllStillRefusesAnUnmappableStruct(t *testing.T) {
	dir := t.TempDir()
	writeTempModule(t, dir)
	if err := os.WriteFile(filepath.Join(dir, "main.go"), []byte(`package main

type Reading struct{ Tick uint32 }

func main() {}
`), 0o644); err != nil {
		t.Fatal(err)
	}
	tidyTempModule(t, dir)
	opts := generator.DefaultOptions()
	opts.GenerateAll = true
	if _, err := generator.AnalyzePackageWithOptions(dir, opts); err == nil {
		t.Fatal("generate-all accepted a struct it was asked to map and cannot")
	}
}

// hierarchySource is world over city over house: three entity levels, each
// collection identified, which is the shape the delta was specified against.
const hierarchySource = `package main

import "github.com/shibukawa/tinybind-go/cborbind"

type House struct {
	ID    uint32 ` + "`cbor:\"id,identity\"`" + `
	Power int32
}

type City struct {
	ID     uint32 ` + "`cbor:\"id,identity\"`" + `
	Name   string
	Houses []House
}

type World struct {
	Tick   uint32
	Cities []City
}

var _ = cborbind.GenerateWorldDelta[World]()
`

// worldProbeHelpers builds the fixture both delta probes diff against.
const worldProbeHelpers = `
func world() World {
	return World{Tick: 10, Cities: []City{
		{ID: 1, Name: "alpha", Houses: []House{{ID: 10, Power: 5}, {ID: 11, Power: 6}}},
		{ID: 2, Name: "beta", Houses: []House{{ID: 20, Power: 7}}},
	}}
}
`

// A delta names a field by its bit rather than by a path, so reaching one field
// three levels down costs the mask chain that addresses it and nothing else.
// The byte count is asserted because it is the whole claim: a delta that grew
// to snapshot size would still pass every round-trip test here.
func TestADeltaThreeLevelsDeepCarriesOnlyWhatChanged(t *testing.T) {
	dir := cborFixture(t, map[string]string{"world.go": hierarchySource})
	writeCborCodec(t, dir)
	writeProbe(t, dir, worldProbeHelpers+`
func TestDelta(t *testing.T) {
	base, cur := world(), world()
	cur.Cities[0].Houses[1].Power = -1000

	d := DiffWorld(base, cur)
	encoded := d.AppendCBORTo(nil)
	if len(encoded) > 24 {
		t.Fatalf("a one-field change three levels deep took %d bytes: %x", len(encoded), encoded)
	}
	// A full snapshot of the same world, for the comparison that matters.
	if whole := len(cur.AppendCBORTo(nil)); whole <= len(encoded)*2 {
		t.Fatalf("the delta is %d bytes against a %d-byte snapshot, which is no saving", len(encoded), whole)
	}

	var back WorldDelta
	if err := back.DecodeCBORFrom(encoded); err != nil {
		t.Fatalf("decode: %v", err)
	}
	got := world()
	if err := ApplyWorldDelta(&got, back); err != nil {
		t.Fatalf("apply: %v", err)
	}
	if !bytes.Equal(got.AppendCBORTo(nil), cur.AppendCBORTo(nil)) {
		t.Fatalf("apply produced %#v, want %#v", got, cur)
	}
}

func TestNoChangeIsAnEmptyDelta(t *testing.T) {
	d := DiffWorld(world(), world())
	if d.Present != 0 {
		t.Fatalf("an unchanged pair produced Present=%b", d.Present)
	}
}

func TestTwoRunsProduceIdenticalDeltas(t *testing.T) {
	base, cur := world(), world()
	cur.Cities[0].Houses[0].Power = 42
	a := DiffWorld(base, cur).AppendCBORTo(nil)
	b := DiffWorld(base, cur).AppendCBORTo(nil)
	if !bytes.Equal(a, b) {
		t.Fatalf("two runs differ: %x vs %x", a, b)
	}
}
`)
	runProbe(t, dir)
}

// An entity appearing or disappearing is a change the receiver cannot infer, so
// it is carried rather than left to be noticed.
func TestADeltaCarriesEntityArrivalAndDeparture(t *testing.T) {
	dir := cborFixture(t, map[string]string{"world.go": hierarchySource})
	writeCborCodec(t, dir)
	writeProbe(t, dir, worldProbeHelpers+`
func TestArrivalAndDeparture(t *testing.T) {
	base, cur := world(), world()
	cur.Tick = 11
	cur.Cities[0].Houses = append(cur.Cities[0].Houses, House{ID: 12, Power: 99})
	cur.Cities[1].Houses = nil
	cur.Cities = append(cur.Cities, City{ID: 3, Name: "gamma"})

	encoded := DiffWorld(base, cur).AppendCBORTo(nil)
	var back WorldDelta
	if err := back.DecodeCBORFrom(encoded); err != nil {
		t.Fatalf("decode: %v", err)
	}
	got := world()
	if err := ApplyWorldDelta(&got, back); err != nil {
		t.Fatalf("apply: %v", err)
	}
	// The wire carries no difference between a nil slice and an empty one, so
	// the bytes are what apply has to reproduce, not the Go value.
	if !bytes.Equal(got.AppendCBORTo(nil), cur.AppendCBORTo(nil)) {
		t.Fatalf("apply produced %#v, want %#v", got, cur)
	}
}

// A delta names entities by identity, so applying one to a value that is not
// the baseline it was diffed against is reported rather than half-applied.
func TestApplyRefusesAMismatchedBaseline(t *testing.T) {
	base, cur := world(), world()
	cur.Cities[0].Houses[0].Power = 42
	d := DiffWorld(base, cur)

	wrong := world()
	wrong.Cities[0].Houses = nil
	if err := ApplyWorldDelta(&wrong, d); err == nil {
		t.Fatal("a delta patching an entity the baseline does not hold was applied")
	}
}
`)
	runProbe(t, dir)
}

// The steady state of a tick loop is what the whole shape is built around, and
// a nested delta holding its own scratch is where it was nearly lost: a fresh
// patch slot per changed entity per tick allocated a new index map with it.
func TestDiffIntoIsAllocationFreeInSteadyState(t *testing.T) {
	dir := cborFixture(t, map[string]string{"world.go": hierarchySource})
	writeCborCodec(t, dir)
	writeProbe(t, dir, worldProbeHelpers+`
func TestDiffAllocations(t *testing.T) {
	base, cur := world(), world()
	cur.Cities[0].Houses[0].Power = 42
	var d WorldDelta
	DiffWorldInto(&d, base, cur) // prime the capacity a steady state reuses
	if n := testing.AllocsPerRun(200, func() {
		DiffWorldInto(&d, base, cur)
	}); n != 0 {
		t.Fatalf("DiffWorldInto allocates %v per run in steady state", n)
	}
}
`)
	runProbe(t, dir)
}

// A collection whose element declares no identity cannot be diffed, so it is
// carried whole. That is legal and sometimes right, and it is the failure that
// looks most like success, so the generated file says which collections it was.
func TestACollectionWithNoIdentityIsCarriedWholeAndSaysSo(t *testing.T) {
	code := generateCbor(t, `package main

import "github.com/shibukawa/tinybind-go/cborbind"

type Tile struct {
	Height int32
}

type Board struct {
	Tick  uint32
	Tiles []Tile
}

var _ = cborbind.GenerateWorldDelta[Board]()
`)
	for _, want := range []string{"carried whole", "identity", "Board.Tiles", "Tile"} {
		if !strings.Contains(code, want) {
			t.Fatalf("the generated file does not report the collection it carries whole; missing %q\n%s", want, code)
		}
	}
	// And it is carried as the slice itself rather than as a collection delta.
	if strings.Contains(code, "TileListDelta") {
		t.Fatal("a collection with no identity was given a collection delta")
	}
}

// An identity is compared and sorted, so it has to be a scalar with a total
// order, and a type can only have one name.
func TestIdentityDeclarationErrors(t *testing.T) {
	tests := []struct {
		name string
		src  string
		want string
	}{
		{
			name: "two identities",
			src:  "type E struct {\n\tA uint32 `cbor:\"a,identity\"`\n\tB uint32 `cbor:\"b,identity\"`\n}",
			want: "two identity fields",
		},
		{
			name: "an identity that is not a scalar",
			src:  "type Inner struct{ N uint32 }\n\ntype E struct {\n\tA Inner `cbor:\"a,identity\"`\n}",
			want: "must be an integer or a string",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			_, err := analyzeCbor(t, `package main

import "github.com/shibukawa/tinybind-go/cborbind"

`+tt.src+`

type Root struct {
	Items []E
}

var _ = cborbind.GenerateWorldDelta[Root]()
`)
			if err == nil {
				t.Fatal("the declaration was accepted")
			}
			if !strings.Contains(err.Error(), tt.want) {
				t.Fatalf("diagnostic %q does not say %q", err, tt.want)
			}
		})
	}
}
