package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"
)

// EmitDynamoQueries generates one function per checked declaration.
func EmitDynamoQueries(pkg string, plans []DynamoQueryPlan) ([]byte, error) {
	if len(plans) == 0 {
		return nil, nil
	}
	var body bytes.Buffer
	for _, plan := range plans {
		if err := emitDynamoQuery(&body, plan); err != nil {
			return nil, err
		}
	}

	var out bytes.Buffer
	out.WriteString("// Code generated by tinybind; DO NOT EDIT.\n\n")
	fmt.Fprintf(&out, "package %s\n\n", pkg)
	writeDynamoQueryImports(&out, body.Bytes())
	out.Write(body.Bytes())

	formatted, err := format.Source(out.Bytes())
	if err != nil {
		return out.Bytes(), fmt.Errorf("dynamobind: format generated query: %w\n%s", err, out.String())
	}
	return formatted, nil
}

var dynamoQueryImports = []struct {
	qualifier string
	path      string
	stdlib    bool
}{
	{qualifier: "context", path: "context", stdlib: true},
	{qualifier: "iter", path: "iter", stdlib: true},
	{qualifier: "time", path: "time", stdlib: true},
	{qualifier: "dynamobind", path: dynamobindImportPath},
	{qualifier: "dynamodb", path: dynamodbImportPath},
}

func writeDynamoQueryImports(out *bytes.Buffer, body []byte) {
	var stdlib, external []string
	for _, item := range dynamoQueryImports {
		if !usesQualifier(body, item.qualifier) {
			continue
		}
		if item.stdlib {
			stdlib = append(stdlib, item.path)
		} else {
			external = append(external, item.path)
		}
	}
	if len(stdlib)+len(external) == 0 {
		return
	}
	out.WriteString("import (\n")
	for _, path := range stdlib {
		fmt.Fprintf(out, "\t%q\n", path)
	}
	if len(stdlib) > 0 && len(external) > 0 {
		out.WriteString("\n")
	}
	for _, path := range external {
		fmt.Fprintf(out, "\t%q\n", path)
	}
	out.WriteString(")\n\n")
}

func emitDynamoQuery(b *bytes.Buffer, plan DynamoQueryPlan) error {
	decl := plan.Decl
	name := decl.Name
	base := lowerFirst(name)

	// The table, the expression and its aliases are constants: every name is
	// known here, so nothing is assembled at run time. Every attribute is
	// aliased whether or not it is a reserved word, which is why no reserved-word
	// list has to be carried.
	fmt.Fprintf(b, "// %sTable is the table %s declares.\n", base, name)
	fmt.Fprintf(b, "const %sTable = %s\n\n", base, strconv.Quote(decl.Table))

	fmt.Fprintf(b, "// %sKeyCondition is the key condition of %s.\n", base, name)
	fmt.Fprintf(b, "const %sKeyCondition = %s\n\n", base, strconv.Quote(plan.Expression))

	fmt.Fprintf(b, "var %sAttributeNames = map[string]string{\n", base)
	aliases := make([]string, 0, len(plan.Names))
	for alias := range plan.Names {
		aliases = append(aliases, alias)
	}
	sort.Strings(aliases)
	for _, alias := range aliases {
		fmt.Fprintf(b, "\t%s: %s,\n", strconv.Quote(alias), strconv.Quote(plan.Names[alias]))
	}
	b.WriteString("}\n\n")

	result, err := dynamoQueryResult(plan)
	if err != nil {
		return err
	}
	params := dynamoQueryParams(decl)

	// The signature carries what the declaration cannot supply and nothing else:
	// the Context, the declared parameters, and the driver's own options. The
	// table comes from the declaration and the client from the Context.
	fmt.Fprintf(b, "// %s queries %s in %s.\n", name, plan.Item.Name, decl.Table)
	fmt.Fprintf(b, "func %s(ctx context.Context%s, opts ...dynamodb.QueryOption) %s {\n", name, params, result)

	b.WriteString("\tvalues := map[string]dynamodb.AttributeValue{\n")
	for _, value := range plan.Values {
		expr, ok := dynamoScalarEncode(value.Param.Name, value.Attribute.Type)
		if !ok {
			return fmt.Errorf("dynamobind: statement %s: attribute %s cannot be a key value", name, value.Attribute.Attribute)
		}
		fmt.Fprintf(b, "\t\t%s: %s,\n", strconv.Quote(value.Placeholder), expr)
	}
	b.WriteString("\t}\n")

	// The generated options go last so a caller option never replaces the names
	// or values this condition depends on.
	b.WriteString("\topts = append(opts,\n")
	fmt.Fprintf(b, "\t\tdynamodb.WithExpressionNames(%sAttributeNames),\n", base)
	b.WriteString("\t\tdynamodb.WithExpressionValues(values),\n\t)\n")

	entry := "Query"
	if decl.Shape == DynamoPage {
		entry = "QueryPage"
	}
	fmt.Fprintf(b, "\treturn dynamobind.%s[%s](ctx, %sTable, %sKeyCondition, opts...)\n}\n\n",
		entry, plan.Item.Name, base, base)
	return nil
}

// dynamoQueryResult is the Go result type a declaration's shape selects.
func dynamoQueryResult(plan DynamoQueryPlan) (string, error) {
	switch plan.Decl.Shape {
	case DynamoPage:
		return fmt.Sprintf("(dynamobind.Page[%s], error)", plan.Item.Name), nil
	case DynamoMany:
		return fmt.Sprintf("iter.Seq2[%s, error]", plan.Item.Name), nil
	default:
		return "", fmt.Errorf("dynamobind: statement %s has no result shape", plan.Decl.Name)
	}
}

// dynamoQueryParams writes the declared parameters as a Go parameter list.
func dynamoQueryParams(decl DynamoQueryDecl) string {
	if len(decl.Params) == 0 {
		return ""
	}
	typed := make([]string, 0, len(decl.Params))
	for _, param := range decl.Params {
		typed = append(typed, param.Name+" "+param.Type)
	}
	return ", " + strings.Join(typed, ", ")
}
