package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"strconv"
)

// EmitDynamoItems generates the item codec for every plan in the package.
func EmitDynamoItems(plan *DynamoPackagePlan, emitTable bool) ([]byte, error) {
	return emitDynamoSelected(plan, nil, emitTable)
}

// emitDynamoSelected emits the named subset of a package plan. A nil selection
// emits everything.
func emitDynamoSelected(plan *DynamoPackagePlan, selected map[string]bool, emitTable bool) ([]byte, error) {
	if plan == nil {
		return nil, fmt.Errorf("dynamobind: nil plan")
	}
	e := &dynamoEmitter{table: emitTable}
	for _, item := range plan.Items {
		if selected != nil && !selected[item.Name] {
			continue
		}
		if err := e.item(item); err != nil {
			return nil, err
		}
	}
	if e.body.Len() == 0 {
		return nil, nil
	}

	var out bytes.Buffer
	out.WriteString("// Code generated by tinybind; DO NOT EDIT.\n\n")
	fmt.Fprintf(&out, "package %s\n\n", plan.Package)
	writeDynamoImports(&out, e.body.Bytes())
	out.Write(e.body.Bytes())

	formatted, err := format.Source(out.Bytes())
	if err != nil {
		return out.Bytes(), fmt.Errorf("dynamobind: format generated code: %w\n%s", err, out.String())
	}
	return formatted, nil
}

// dynamoImports lists every package the item emitter can reference, with the
// qualifier that proves the reference.
var dynamoImports = []struct {
	qualifier string
	path      string
	stdlib    bool
}{
	{qualifier: "strconv", path: "strconv", stdlib: true},
	{qualifier: "time", path: "time", stdlib: true},
	{qualifier: "dynamobind", path: dynamobindImportPath},
	{qualifier: "dynamodb", path: dynamodbImportPath},
}

func writeDynamoImports(out *bytes.Buffer, body []byte) {
	var stdlib, external []string
	for _, item := range dynamoImports {
		if !usesQualifier(body, item.qualifier) {
			continue
		}
		if item.stdlib {
			stdlib = append(stdlib, item.path)
		} else {
			external = append(external, item.path)
		}
	}
	if len(stdlib)+len(external) == 0 {
		return
	}
	out.WriteString("import (\n")
	for _, path := range stdlib {
		fmt.Fprintf(out, "\t%q\n", path)
	}
	if len(stdlib) > 0 && len(external) > 0 {
		out.WriteString("\n")
	}
	for _, path := range external {
		fmt.Fprintf(out, "\t%q\n", path)
	}
	out.WriteString(")\n\n")
}

type dynamoEmitter struct {
	body  bytes.Buffer
	table bool
	// temps numbers the locals a nested encode or decode needs, so two fields of
	// one method never collide.
	temps int
}

func (e *dynamoEmitter) temp(prefix string) string {
	e.temps++
	return fmt.Sprintf("%s%d", prefix, e.temps)
}

func (e *dynamoEmitter) item(item DynamoItemPlan) error {
	e.temps = 0
	receiver := "v"
	_, hasPartition := item.PartitionKey()
	emitKey := item.Usage&DynamoKey != 0 && hasPartition

	if item.Usage&DynamoEncode != 0 {
		fmt.Fprintf(&e.body, "var _ dynamobind.ItemEncoder = %s{}\n", item.Name)
	}
	if item.Usage&DynamoDecode != 0 {
		fmt.Fprintf(&e.body, "var _ dynamobind.ItemDecoder = (*%s)(nil)\n", item.Name)
	}
	if emitKey {
		fmt.Fprintf(&e.body, "var _ dynamobind.Keyer = %s{}\n", item.Name)
	}
	e.body.WriteString("\n")

	if item.Usage&DynamoEncode != 0 {
		if err := e.encodeItem(item, receiver); err != nil {
			return err
		}
	}
	if item.Usage&DynamoDecode != 0 {
		if err := e.decodeItem(item, receiver); err != nil {
			return err
		}
	}
	if emitKey {
		if err := e.itemKey(item, receiver); err != nil {
			return err
		}
		if e.table {
			if err := e.tableDefinition(item); err != nil {
				return err
			}
		}
	}
	return nil
}

func (e *dynamoEmitter) encodeItem(item DynamoItemPlan, receiver string) error {
	fmt.Fprintf(&e.body, "// EncodeItem converts %s into a DynamoDB item.\n", item.Name)
	fmt.Fprintf(&e.body, "func (%s %s) EncodeItem() dynamodb.Item {\n", receiver, item.Name)
	fmt.Fprintf(&e.body, "\titem := make(dynamodb.Item, %d)\n", len(item.Fields))
	for _, f := range item.Fields {
		source := receiver + "." + f.Name
		target := fmt.Sprintf("item[%s]", strconv.Quote(f.Attribute))
		indent := "\t"
		if guard, ok := dynamoEmptyGuard(f, source); ok {
			fmt.Fprintf(&e.body, "\tif %s {\n", guard)
			indent = "\t\t"
		}
		if err := e.encodeInto(target, source, f.Type, indent); err != nil {
			return fmt.Errorf("%s.%s: %w", item.Name, f.Name, err)
		}
		if _, ok := dynamoEmptyGuard(f, source); ok {
			e.body.WriteString("\t}\n")
		}
	}
	e.body.WriteString("\treturn item\n}\n\n")
	return nil
}

// dynamoEmptyGuard returns the condition under which a field is written at all.
// omitempty asks for it; a zero dynamodb.AttributeValue gets it unasked, because
// an attribute with no type set is rejected by the service and cannot be what
// the caller meant to store.
func dynamoEmptyGuard(f DynamoFieldPlan, source string) (string, bool) {
	if f.Type.Kind == DynamoRaw {
		return fmt.Sprintf("%s.Kind() != dynamodb.KindNone", source), true
	}
	if !f.OmitEmpty {
		return "", false
	}
	switch f.Type.Kind {
	case DynamoString:
		return fmt.Sprintf("%s != \"\"", source), true
	case DynamoInt, DynamoUint, DynamoFloat:
		return fmt.Sprintf("%s != 0", source), true
	case DynamoBool:
		return fmt.Sprintf("bool(%s)", source), true
	case DynamoBytes, DynamoList, DynamoMap, DynamoStringSet, DynamoNumberSet, DynamoBinarySet:
		return fmt.Sprintf("len(%s) != 0", source), true
	case DynamoTime, DynamoUnixTime:
		return fmt.Sprintf("!%s.IsZero()", source), true
	case DynamoPointer:
		return fmt.Sprintf("%s != nil", source), true
	default:
		return "", false
	}
}

// encodeInto writes the statements that assign the attribute for source to
// target. target is any assignable expression, so one function serves fields,
// list elements and map values alike.
func (e *dynamoEmitter) encodeInto(target, source string, t DynamoType, indent string) error {
	if expr, ok := dynamoScalarEncode(source, t); ok {
		fmt.Fprintf(&e.body, "%s%s = %s\n", indent, target, expr)
		return nil
	}
	switch t.Kind {
	case DynamoStruct:
		fmt.Fprintf(&e.body, "%s%s = dynamodb.Map(%s.EncodeItem())\n", indent, target, source)

	case DynamoPointer:
		fmt.Fprintf(&e.body, "%sif %s == nil {\n", indent, source)
		fmt.Fprintf(&e.body, "%s\t%s = dynamodb.Null()\n", indent, target)
		fmt.Fprintf(&e.body, "%s} else {\n", indent)
		if err := e.encodeInto(target, "(*"+source+")", *t.Elem, indent+"\t"); err != nil {
			return err
		}
		fmt.Fprintf(&e.body, "%s}\n", indent)

	case DynamoStringSet:
		name := e.temp("set")
		fmt.Fprintf(&e.body, "%s%s := make([]string, 0, len(%s))\n", indent, name, source)
		fmt.Fprintf(&e.body, "%sfor _, member := range %s {\n", indent, source)
		fmt.Fprintf(&e.body, "%s\t%s = append(%s, string(member))\n", indent, name, name)
		fmt.Fprintf(&e.body, "%s}\n", indent)
		fmt.Fprintf(&e.body, "%s%s = dynamodb.SS(%s...)\n", indent, target, name)

	case DynamoNumberSet:
		name := e.temp("set")
		fmt.Fprintf(&e.body, "%s%s := make([]string, 0, len(%s))\n", indent, name, source)
		fmt.Fprintf(&e.body, "%sfor _, member := range %s {\n", indent, source)
		fmt.Fprintf(&e.body, "%s\t%s = append(%s, %s)\n", indent, name, name, dynamoNumberText("member", *t.Elem))
		fmt.Fprintf(&e.body, "%s}\n", indent)
		fmt.Fprintf(&e.body, "%s%s = dynamodb.NS(%s...)\n", indent, target, name)

	case DynamoBinarySet:
		name := e.temp("set")
		fmt.Fprintf(&e.body, "%s%s := make([][]byte, 0, len(%s))\n", indent, name, source)
		fmt.Fprintf(&e.body, "%sfor _, member := range %s {\n", indent, source)
		fmt.Fprintf(&e.body, "%s\t%s = append(%s, []byte(member))\n", indent, name, name)
		fmt.Fprintf(&e.body, "%s}\n", indent)
		fmt.Fprintf(&e.body, "%s%s = dynamodb.BS(%s...)\n", indent, target, name)

	case DynamoList:
		name := e.temp("list")
		element := e.temp("element")
		fmt.Fprintf(&e.body, "%s%s := make([]dynamodb.AttributeValue, 0, len(%s))\n", indent, name, source)
		fmt.Fprintf(&e.body, "%sfor _, member := range %s {\n", indent, source)
		if err := e.encodeElement(element, "member", *t.Elem, indent+"\t"); err != nil {
			return err
		}
		fmt.Fprintf(&e.body, "%s\t%s = append(%s, %s)\n", indent, name, name, element)
		fmt.Fprintf(&e.body, "%s}\n", indent)
		fmt.Fprintf(&e.body, "%s%s = dynamodb.List(%s...)\n", indent, target, name)

	case DynamoMap:
		name := e.temp("entries")
		element := e.temp("element")
		fmt.Fprintf(&e.body, "%s%s := make(map[string]dynamodb.AttributeValue, len(%s))\n", indent, name, source)
		fmt.Fprintf(&e.body, "%sfor key, member := range %s {\n", indent, source)
		if err := e.encodeElement(element, "member", *t.Elem, indent+"\t"); err != nil {
			return err
		}
		fmt.Fprintf(&e.body, "%s\t%s[string(key)] = %s\n", indent, name, element)
		fmt.Fprintf(&e.body, "%s}\n", indent)
		fmt.Fprintf(&e.body, "%s%s = dynamodb.Map(%s)\n", indent, target, name)

	default:
		return fmt.Errorf("no encoder for attribute kind %s", t.Kind)
	}
	return nil
}

// encodeElement declares one collection member's attribute value. A scalar is
// one expression and needs no separate declaration; anything else is filled in
// by statements, so it is declared first.
func (e *dynamoEmitter) encodeElement(name, source string, t DynamoType, indent string) error {
	if expr, ok := dynamoScalarEncode(source, t); ok {
		fmt.Fprintf(&e.body, "%s%s := %s\n", indent, name, expr)
		return nil
	}
	fmt.Fprintf(&e.body, "%svar %s dynamodb.AttributeValue\n", indent, name)
	return e.encodeInto(name, source, t, indent)
}

// dynamoScalarEncode returns the one-expression encoding of a scalar, which is
// also what a key attribute is restricted to.
func dynamoScalarEncode(source string, t DynamoType) (string, bool) {
	switch t.Kind {
	case DynamoString:
		return fmt.Sprintf("dynamodb.S(string(%s))", source), true
	case DynamoInt, DynamoUint, DynamoFloat:
		return fmt.Sprintf("dynamodb.N(%s)", source), true
	case DynamoBool:
		return fmt.Sprintf("dynamodb.Bool(bool(%s))", source), true
	case DynamoBytes:
		return fmt.Sprintf("dynamodb.B([]byte(%s))", source), true
	case DynamoTime:
		return fmt.Sprintf("dynamodb.S(%s.UTC().Format(time.RFC3339Nano))", source), true
	case DynamoUnixTime:
		return fmt.Sprintf("dynamodb.N(%s.Unix())", source), true
	case DynamoRaw:
		return source, true
	default:
		return "", false
	}
}

// dynamoNumberText formats one number as the text DynamoDB stores. Numbers
// never pass through float64 on the way: a DynamoDB number carries 38
// significant digits and float64 does not.
func dynamoNumberText(source string, t DynamoType) string {
	switch t.Kind {
	case DynamoInt:
		return fmt.Sprintf("strconv.FormatInt(int64(%s), 10)", source)
	case DynamoUint:
		return fmt.Sprintf("strconv.FormatUint(uint64(%s), 10)", source)
	case DynamoFloat:
		bits := t.Bits
		if bits == 0 {
			bits = 64
		}
		return fmt.Sprintf("strconv.FormatFloat(float64(%s), 'g', -1, %d)", source, bits)
	default:
		return source
	}
}

func (e *dynamoEmitter) itemKey(item DynamoItemPlan, receiver string) error {
	partition, _ := item.PartitionKey()
	sortKey, hasSort := item.SortKey()
	fmt.Fprintf(&e.body, "// ItemKey returns the primary key of %s.\n", item.Name)
	fmt.Fprintf(&e.body, "func (%s %s) ItemKey() dynamodb.Key {\n", receiver, item.Name)
	e.body.WriteString("\treturn dynamodb.Key{\n")
	expr, ok := dynamoScalarEncode(receiver+"."+partition.Name, partition.Type)
	if !ok {
		return fmt.Errorf("%s.%s: no key encoding for %s", item.Name, partition.Name, partition.Type.Go)
	}
	fmt.Fprintf(&e.body, "\t\t%s: %s,\n", strconv.Quote(partition.Attribute), expr)
	if hasSort {
		expr, ok := dynamoScalarEncode(receiver+"."+sortKey.Name, sortKey.Type)
		if !ok {
			return fmt.Errorf("%s.%s: no key encoding for %s", item.Name, sortKey.Name, sortKey.Type.Go)
		}
		fmt.Fprintf(&e.body, "\t\t%s: %s,\n", strconv.Quote(sortKey.Attribute), expr)
	}
	e.body.WriteString("\t}\n}\n\n")
	return nil
}

func (e *dynamoEmitter) tableDefinition(item DynamoItemPlan) error {
	partition, _ := item.PartitionKey()
	sortKey, hasSort := item.SortKey()
	partitionType, ok := dynamoKeyAttributeType(partition.Type)
	if !ok {
		return fmt.Errorf("%s.%s: not a key attribute type", item.Name, partition.Name)
	}
	fmt.Fprintf(&e.body, "// %sTable describes the table %s is stored in. The key names come from\n", item.Name, item.Name)
	fmt.Fprintf(&e.body, "// the same tags as the codec, so they cannot drift apart.\n")
	fmt.Fprintf(&e.body, "func %sTable(name string) dynamodb.TableDefinition {\n", item.Name)
	e.body.WriteString("\treturn dynamodb.TableDefinition{\n\t\tName: name,\n")
	fmt.Fprintf(&e.body, "\t\tPartitionKey: dynamodb.KeyAttribute{Name: %s, Type: dynamodb.%s},\n", strconv.Quote(partition.Attribute), partitionType)
	if hasSort {
		sortType, ok := dynamoKeyAttributeType(sortKey.Type)
		if !ok {
			return fmt.Errorf("%s.%s: not a key attribute type", item.Name, sortKey.Name)
		}
		fmt.Fprintf(&e.body, "\t\tSortKey: &dynamodb.KeyAttribute{Name: %s, Type: dynamodb.%s},\n", strconv.Quote(sortKey.Attribute), sortType)
	}
	e.body.WriteString("\t}\n}\n\n")
	return nil
}
