package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"
)

// DynamoQueryOptions selects which of the three client-supply modes the
// generated functions use. The zero value is the Context form, which is the
// default and what every run that sets nothing generates.
type DynamoQueryOptions struct {
	// ParameterAPI gives each function a leading dynamobind.Handle parameter.
	ParameterAPI bool
	// HandleResolver names a framework function answering a dynamobind.Handle
	// for one Context. ParameterAPI takes precedence over it.
	HandleResolver *SymbolPattern
}

// resolves reports whether generated bodies call a framework resolver. A
// signature that already carries the Handle resolves nothing.
func (o DynamoQueryOptions) resolves() bool {
	return !o.ParameterAPI && o.HandleResolver != nil
}

// EmitDynamoQueries generates one function per checked declaration, in the
// Context form.
func EmitDynamoQueries(pkg string, plans []DynamoQueryPlan) ([]byte, error) {
	return EmitDynamoQueriesWithOptions(pkg, plans, DynamoQueryOptions{})
}

// EmitDynamoQueriesWithOptions is EmitDynamoQueries in the mode opts selects.
func EmitDynamoQueriesWithOptions(pkg string, plans []DynamoQueryPlan, opts DynamoQueryOptions) ([]byte, error) {
	if len(plans) == 0 {
		return nil, nil
	}
	if err := checkHandleResolver("DynamoHandleResolver", opts.HandleResolver); err != nil {
		return nil, err
	}
	var body bytes.Buffer
	for _, plan := range plans {
		if err := emitDynamoQuery(&body, plan, opts); err != nil {
			return nil, err
		}
	}

	var out bytes.Buffer
	out.WriteString("// Code generated by tinybind; DO NOT EDIT.\n\n")
	fmt.Fprintf(&out, "package %s\n\n", pkg)
	writeDynamoQueryImports(&out, body.Bytes())
	if opts.resolves() {
		fmt.Fprintf(&out, "import %s %q\n\n", resolverAlias, opts.HandleResolver.PackagePath)
	}
	out.Write(body.Bytes())

	formatted, err := format.Source(out.Bytes())
	if err != nil {
		return out.Bytes(), fmt.Errorf("dynamobind: format generated query: %w\n%s", err, out.String())
	}
	return formatted, nil
}

var dynamoQueryImports = []struct {
	qualifier string
	path      string
	stdlib    bool
}{
	{qualifier: "context", path: "context", stdlib: true},
	{qualifier: "iter", path: "iter", stdlib: true},
	{qualifier: "time", path: "time", stdlib: true},
	{qualifier: "dynamobind", path: dynamobindImportPath},
	{qualifier: "dynamodb", path: dynamodbImportPath},
}

func writeDynamoQueryImports(out *bytes.Buffer, body []byte) {
	var stdlib, external []string
	for _, item := range dynamoQueryImports {
		if !usesQualifier(body, item.qualifier) {
			continue
		}
		if item.stdlib {
			stdlib = append(stdlib, item.path)
		} else {
			external = append(external, item.path)
		}
	}
	if len(stdlib)+len(external) == 0 {
		return
	}
	out.WriteString("import (\n")
	for _, path := range stdlib {
		fmt.Fprintf(out, "\t%q\n", path)
	}
	if len(stdlib) > 0 && len(external) > 0 {
		out.WriteString("\n")
	}
	for _, path := range external {
		fmt.Fprintf(out, "\t%q\n", path)
	}
	out.WriteString(")\n\n")
}

func emitDynamoQuery(b *bytes.Buffer, plan DynamoQueryPlan, opts DynamoQueryOptions) error {
	decl := plan.Decl
	name := decl.Name
	base := lowerFirst(name)

	// The table, the expression and its aliases are constants: every name is
	// known here, so nothing is assembled at run time. Every attribute is
	// aliased whether or not it is a reserved word, which is why no reserved-word
	// list has to be carried.
	fmt.Fprintf(b, "// %sTable is the table %s declares.\n", base, name)
	fmt.Fprintf(b, "const %sTable = %s\n\n", base, strconv.Quote(decl.Table))

	fmt.Fprintf(b, "// %sKeyCondition is the key condition of %s.\n", base, name)
	fmt.Fprintf(b, "const %sKeyCondition = %s\n\n", base, strconv.Quote(plan.Expression))

	fmt.Fprintf(b, "var %sAttributeNames = map[string]string{\n", base)
	aliases := make([]string, 0, len(plan.Names))
	for alias := range plan.Names {
		aliases = append(aliases, alias)
	}
	sort.Strings(aliases)
	for _, alias := range aliases {
		fmt.Fprintf(b, "\t%s: %s,\n", strconv.Quote(alias), strconv.Quote(plan.Names[alias]))
	}
	b.WriteString("}\n\n")

	result, err := dynamoQueryResult(plan)
	if err != nil {
		return err
	}
	params := dynamoQueryParams(decl)

	// The signature carries what the declaration cannot supply and nothing else:
	// the Context, the declared parameters, and the driver's own options. The
	// table comes from the declaration, and the client from the Context unless
	// ParameterAPI moved it into the signature.
	handle := ""
	if opts.ParameterAPI {
		handle = ", h dynamobind.Handle"
	}
	fmt.Fprintf(b, "// %s queries %s in %s.\n", name, plan.Item.Name, decl.Table)
	fmt.Fprintf(b, "func %s(ctx context.Context%s%s, opts ...dynamodb.QueryOption) %s {\n", name, handle, params, result)

	b.WriteString("\tvalues := map[string]dynamodb.AttributeValue{\n")
	for _, value := range plan.Values {
		expr, ok := dynamoScalarEncode(value.Param.Name, value.Attribute.Type)
		if !ok {
			return fmt.Errorf("dynamobind: statement %s: attribute %s cannot be a key value", name, value.Attribute.Attribute)
		}
		fmt.Fprintf(b, "\t\t%s: %s,\n", strconv.Quote(value.Placeholder), expr)
	}
	b.WriteString("\t}\n")

	// The generated options go last so a caller option never replaces the names
	// or values this condition depends on.
	b.WriteString("\topts = append(opts,\n")
	fmt.Fprintf(b, "\t\tdynamodb.WithExpressionNames(%sAttributeNames),\n", base)
	b.WriteString("\t\tdynamodb.WithExpressionValues(values),\n\t)\n")

	entry := "Query"
	if decl.Shape == DynamoPage {
		entry = "QueryPage"
	}
	if opts.ParameterAPI || opts.resolves() {
		entry += "On"
	}
	if opts.resolves() {
		// The Handle comes from the framework's own Context value, so the
		// resolver's error has to be reported in the shape this declaration
		// returns rather than passed on to a runtime entry that never runs.
		fmt.Fprintf(b, "\th, err := %s.%s(ctx)\n\tif err != nil {\n", resolverAlias, opts.HandleResolver.Name)
		if decl.Shape == DynamoPage {
			fmt.Fprintf(b, "\t\treturn dynamobind.Page[%s]{}, err\n", plan.Item.Name)
		} else {
			fmt.Fprintf(b, "\t\treturn func(yield func(%s, error) bool) {\n\t\t\tvar zero %s\n\t\t\tyield(zero, err)\n\t\t}\n",
				plan.Item.Name, plan.Item.Name)
		}
		b.WriteString("\t}\n")
	}
	handleArg := ""
	if opts.ParameterAPI || opts.resolves() {
		handleArg = "h, "
	}
	fmt.Fprintf(b, "\treturn dynamobind.%s[%s](ctx, %s%sTable, %sKeyCondition, opts...)\n}\n\n",
		entry, plan.Item.Name, handleArg, base, base)
	return nil
}

// dynamoQueryResult is the Go result type a declaration's shape selects.
func dynamoQueryResult(plan DynamoQueryPlan) (string, error) {
	switch plan.Decl.Shape {
	case DynamoPage:
		return fmt.Sprintf("(dynamobind.Page[%s], error)", plan.Item.Name), nil
	case DynamoMany:
		return fmt.Sprintf("iter.Seq2[%s, error]", plan.Item.Name), nil
	default:
		return "", fmt.Errorf("dynamobind: statement %s has no result shape", plan.Decl.Name)
	}
}

// dynamoQueryParams writes the declared parameters as a Go parameter list.
func dynamoQueryParams(decl DynamoQueryDecl) string {
	if len(decl.Params) == 0 {
		return ""
	}
	typed := make([]string, 0, len(decl.Params))
	for _, param := range decl.Params {
		typed = append(typed, param.Name+" "+param.Type)
	}
	return ", " + strings.Join(typed, ", ")
}
