package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"strconv"
	"strings"
	"unicode"
)

// Emit generates Go source for type-specific binders, writers, and JSON codecs.
// The output does not import "reflect".
func Emit(plan *PackagePlan) ([]byte, error) {
	return emitSelected(plan, nil)
}

// emitSelected emits only the named subset of plan.Types. The full plan still
// provides nested type lookups, so a per-source artifact can reference helpers
// generated beside another source of the same package. A nil selection emits
// every type.
func emitSelected(plan *PackagePlan, selected map[string]bool) ([]byte, error) {
	if plan == nil {
		return nil, fmt.Errorf("nil plan")
	}
	emitted := make([]TypePlan, 0, len(plan.Types))
	for _, t := range plan.Types {
		if selected == nil || selected[t.Name] {
			emitted = append(emitted, t)
		}
	}
	var b bytes.Buffer
	needRegexp := false
	for _, t := range emitted {
		if t.Usage&UsageBind == 0 {
			continue
		}
		for _, f := range t.Fields {
			if f.Check.Pattern == "" {
				continue
			}
			needRegexp = true
			fmt.Fprintf(&b, "var checkPattern%s%s = regexp.MustCompile(%s)\n", t.Name, f.Name, strconv.Quote(f.Check.Pattern))
		}
	}
	if needRegexp {
		b.WriteString("\n")
	}

	var registrations bytes.Buffer
	for _, t := range emitted {
		if t.DirectUsage&UsageBind != 0 {
			fmt.Fprintf(&registrations, "\thttpbind.RegisterBind[%s](bind%s)\n", t.Name, t.Name)
		}
		if t.DirectUsage&UsageWrite != 0 {
			fmt.Fprintf(&registrations, "\thttpbind.RegisterWrite[%s](write%s)\n", t.Name, t.Name)
		}
		if t.DirectUsage&UsageDecodeJSON != 0 {
			fmt.Fprintf(&registrations, "\tjsonbind.RegisterDecode[%s](decode%sBytes)\n", t.Name, t.Name)
		}
		if t.DirectUsage&UsageEncodeJSON != 0 {
			fmt.Fprintf(&registrations, "\tjsonbind.RegisterEncode[%s](encode%s)\n", t.Name, t.Name)
		}
		if t.DirectUsage&UsageScanRows != 0 {
			fmt.Fprintf(&registrations, "\tsqlbind.RegisterScanRows[%s](scan%sRows)\n", t.Name, t.Name)
		}
	}
	if registrations.Len() > 0 {
		b.WriteString("func init() {\n")
		b.Write(registrations.Bytes())
		b.WriteString("}\n\n")
	}

	// Index types for nested encode helpers
	types := map[string]TypePlan{}
	for _, t := range plan.Types {
		types[t.Name] = t
	}

	for _, t := range emitted {
		if t.Usage&(UsageBind|UsageDecodeJSON) != 0 {
			emitDecodeJSON(&b, t, types)
		}
		if t.Usage&(UsageWrite|UsageEncodeJSON) != 0 {
			emitEncode(&b, t, types)
		}
		if t.Usage&UsageBind != 0 {
			emitBinder(&b, t, types)
		}
		if t.Usage&UsageWrite != 0 {
			emitWriter(&b, t, types)
		}
		if t.DirectUsage&UsageScanRows != 0 {
			if err := emitScanRows(&b, t, types); err != nil {
				return nil, err
			}
		}
	}

	var out bytes.Buffer
	out.WriteString("// Code generated by tinybind; DO NOT EDIT.\n\n")
	fmt.Fprintf(&out, "package %s\n\n", plan.Package)
	writeMappingImports(&out, b.Bytes())
	out.Write(b.Bytes())
	b = out

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return b.Bytes(), fmt.Errorf("format generated code: %w\n%s", err, b.String())
	}
	return formatted, nil
}

// mappingImports lists every package the mapping emitter can reference,
// together with the qualifier that proves the reference. Grouping keeps
// standard-library imports separated from tinybind imports.
var mappingImports = []struct {
	qualifier string
	path      string
	stdlib    bool
}{
	{qualifier: "json", path: "encoding/json", stdlib: true},
	{qualifier: "io", path: "io", stdlib: true},
	{qualifier: "regexp", path: "regexp", stdlib: true},
	{qualifier: "http", path: "net/http", stdlib: true},
	{qualifier: "sql", path: "database/sql", stdlib: true},
	{qualifier: "httpbind", path: httpbindImportPath},
	{qualifier: "jsonbind", path: jsonbindImportPath},
	{qualifier: "sqlbind", path: sqlbindImportPath},
}

// writeMappingImports emits exactly the imports body references. Deriving them
// from the emitted code keeps every artifact self-contained no matter which
// subset of types or phases produced it.
func writeMappingImports(out *bytes.Buffer, body []byte) {
	var stdlib, tinybind []string
	for _, item := range mappingImports {
		if !usesQualifier(body, item.qualifier) {
			continue
		}
		if item.stdlib {
			stdlib = append(stdlib, item.path)
		} else {
			tinybind = append(tinybind, item.path)
		}
	}
	if len(stdlib)+len(tinybind) == 0 {
		return
	}
	out.WriteString("import (\n")
	for _, path := range stdlib {
		fmt.Fprintf(out, "\t%q\n", path)
	}
	if len(stdlib) > 0 && len(tinybind) > 0 {
		out.WriteString("\n")
	}
	for _, path := range tinybind {
		fmt.Fprintf(out, "\t%q\n", path)
	}
	out.WriteString(")\n\n")
}

// usesQualifier reports whether body contains a "<qualifier>." selector that is
// not the tail of a longer identifier.
func usesQualifier(body []byte, qualifier string) bool {
	needle := []byte(qualifier + ".")
	for offset := 0; ; {
		index := bytes.Index(body[offset:], needle)
		if index < 0 {
			return false
		}
		at := offset + index
		if at == 0 || !isIdentifierByte(body[at-1]) {
			return true
		}
		offset = at + 1
	}
}

func isIdentifierByte(c byte) bool {
	return c == '_' || (c >= '0' && c <= '9') || (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z')
}

func emitScanRows(b *bytes.Buffer, root TypePlan, types map[string]TypePlan) error {
	key, err := sqlGroupKey(root)
	if err != nil {
		return fmt.Errorf("%s: %w", root.Name, err)
	}
	fmt.Fprintf(b, "func scan%sRows(rows *sql.Rows) ([]%s, error) {\n", root.Name, root.Name)
	fmt.Fprintf(b, "\tout := []%s{}\n\trootIndexes := map[string]int{}\n", root.Name)
	if err := emitSQLIndexDecls(b, root, types, root.Name, "\t"); err != nil {
		return err
	}
	b.WriteString("\terr := sqlbind.ForEach(rows, func(row sqlbind.Row) error {\n")
	fmt.Fprintf(b, "\t\trootKey, err := sqlbind.RequiredKey(row, %q)\n\t\tif err != nil { return err }\n", key.DB)
	b.WriteString("\t\trootPos, exists := rootIndexes[rootKey]\n\t\tif !exists {\n")
	fmt.Fprintf(b, "\t\t\tvar item %s\n", root.Name)
	emitSQLFill(b, root, types, "item", "\t\t\t")
	b.WriteString("\t\t\tout = append(out, item)\n\t\t\trootPos = len(out)-1\n\t\t\trootIndexes[rootKey] = rootPos\n\t\t}\n")
	if err := emitSQLChildren(b, root, types, "out[rootPos]", "rootKey", root.Name, "\t\t"); err != nil {
		return err
	}
	b.WriteString("\t\treturn nil\n\t})\n\tif err != nil { return nil, err }\n\treturn out, nil\n}\n\n")
	return nil
}

func sqlGroupKey(t TypePlan) (FieldPlan, error) {
	var out FieldPlan
	n := 0
	for _, f := range t.Fields {
		if f.GroupKey && !f.IsComposite() {
			out = f
			n++
		}
	}
	if n != 1 {
		return FieldPlan{}, fmt.Errorf("SQL grouped struct must have exactly one scalar groupkey field")
	}
	return out, nil
}

func emitSQLIndexDecls(b *bytes.Buffer, t TypePlan, types map[string]TypePlan, path, prefix string) error {
	for _, f := range t.Fields {
		if f.Kind != KindSlice || f.ElemKind != KindStruct {
			continue
		}
		child, ok := types[f.TypeName]
		if !ok {
			return fmt.Errorf("%s: missing child type %s", t.Name, f.TypeName)
		}
		if _, err := sqlGroupKey(child); err != nil {
			return fmt.Errorf("%s.%s: %w", t.Name, f.Name, err)
		}
		id := sqlIdent(path + f.Name)
		fmt.Fprintf(b, "%s%sIndexes := map[string]int{}\n", prefix, id)
		if err := emitSQLIndexDecls(b, child, types, path+f.Name, prefix); err != nil {
			return err
		}
	}
	return nil
}

func emitSQLFill(b *bytes.Buffer, t TypePlan, types map[string]TypePlan, target, prefix string) {
	for _, f := range t.Fields {
		switch f.Kind {
		case "string", "int", "int64", "bool", "float64":
			fn := strings.ToUpper(f.Kind[:1]) + f.Kind[1:]
			fmt.Fprintf(b, "%sif v, err := sqlbind.%s(row, %q); err != nil { return err } else { %s.%s = v }\n", prefix, fn, f.DB, target, f.Name)
		case KindStruct:
			if child, ok := types[f.TypeName]; ok {
				emitSQLFill(b, child, types, target+"."+f.Name, prefix)
			}
		}
	}
}

func emitSQLChildren(b *bytes.Buffer, t TypePlan, types map[string]TypePlan, target, parentKey, path, prefix string) error {
	for _, f := range t.Fields {
		if f.Kind == KindStruct {
			if child, ok := types[f.TypeName]; ok {
				if err := emitSQLChildren(b, child, types, target+"."+f.Name, parentKey, path+f.Name, prefix); err != nil {
					return err
				}
			}
			continue
		}
		if f.Kind != KindSlice || f.ElemKind != KindStruct {
			continue
		}
		child, ok := types[f.TypeName]
		if !ok {
			return fmt.Errorf("missing SQL child type %s", f.TypeName)
		}
		key, err := sqlGroupKey(child)
		if err != nil {
			return err
		}
		id := sqlIdent(path + f.Name)
		keyVar, presentVar := id+"Key", id+"Present"
		compositeVar, posVar, existsVar := id+"CompositeKey", id+"Pos", id+"Exists"
		fmt.Fprintf(b, "%s%s, %s, err := sqlbind.Key(row, %q)\n%sif err != nil { return err }\n%sif %s {\n", prefix, keyVar, presentVar, key.DB, prefix, prefix, presentVar)
		fmt.Fprintf(b, "%s\t%s := %s + \"\\x00\" + %s\n%s\t%s, %s := %sIndexes[%s]\n%s\tif !%s {\n", prefix, compositeVar, parentKey, keyVar, prefix, posVar, existsVar, id, compositeVar, prefix, existsVar)
		fmt.Fprintf(b, "%s\t\tvar child %s\n", prefix, child.Name)
		emitSQLFill(b, child, types, "child", prefix+"\t\t")
		fmt.Fprintf(b, "%s\t\t%s.%s = append(%s.%s, child)\n%s\t\t%s = len(%s.%s)-1\n%s\t\t%sIndexes[%s] = %s\n%s\t}\n", prefix, target, f.Name, target, f.Name, prefix, posVar, target, f.Name, prefix, id, compositeVar, posVar, prefix)
		if err := emitSQLChildren(b, child, types, target+"."+f.Name+"["+posVar+"]", compositeVar, path+f.Name, prefix+"\t"); err != nil {
			return err
		}
		fmt.Fprintf(b, "%s}\n", prefix)
	}
	return nil
}

func sqlIdent(s string) string {
	var b strings.Builder
	for _, r := range s {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			b.WriteRune(r)
		}
	}
	return b.String()
}

func emitDecodeJSON(b *bytes.Buffer, t TypePlan, types map[string]TypePlan) {
	fmt.Fprintf(b, "func decode%sBytes(data []byte) (%s, error) {\n", t.Name, t.Name)
	fmt.Fprintf(b, "\treturn decode%sJSON(json.RawMessage(data))\n}\n\n", t.Name)

	fmt.Fprintf(b, "func decode%sJSON(raw json.RawMessage) (%s, error) {\n", t.Name, t.Name)
	fmt.Fprintf(b, "\tvar out %s\n", t.Name)
	if documentFieldCount(t) == 0 {
		// No JSON document fields (e.g. cookie/path-only models).
		b.WriteString("\t_ = raw\n")
		b.WriteString("\treturn out, nil\n}\n\n")
		return
	}
	b.WriteString("\tm, err := jsonbind.RawJSONMap(raw)\n")
	b.WriteString("\tif err != nil {\n\t\treturn out, err\n\t}\n")
	emitFillFromJSONMap(b, t, types, "m", "\t")
	b.WriteString("\treturn out, nil\n}\n\n")
}

func documentFieldCount(t TypePlan) int {
	n := 0
	for _, f := range t.Fields {
		if isDocumentField(f) {
			n++
		}
	}
	return n
}

func isDocumentField(f FieldPlan) bool {
	if f.Source == SourcePath || f.Source == SourceHeader || f.Source == SourceCookie || f.Source == SourceMethod || f.Source == SourceQuery {
		return false
	}
	if f.Kind == "file" {
		return false
	}
	return f.Source == SourceInput || f.Source == SourcePayload
}

// emitFillFromJSONMap assigns fields of t from map variable mapVar into out.
func emitFillFromJSONMap(b *bytes.Buffer, t TypePlan, types map[string]TypePlan, mapVar, prefix string) {
	for _, f := range t.Fields {
		if !isDocumentField(f) || f.IsRest() {
			continue
		}
		key := f.JSON
		if key == "" || key == "*" {
			key = f.Wire
		}
		fmt.Fprintf(b, "%sif raw, ok := %s[%q]; ok {\n", prefix, mapVar, key)
		emitAssignFromRaw(b, f, types, "raw", prefix+"\t", "out."+f.Name, true)
		fmt.Fprintf(b, "%s}\n", prefix)
	}
	// rest fields
	for _, f := range t.Fields {
		if !f.IsRest() {
			continue
		}
		exclude := bodyWireExclude(t)
		switch f.Kind {
		case KindRestAny:
			fmt.Fprintf(b, "%s{\n", prefix)
			fmt.Fprintf(b, "%s\trm, err := jsonbind.RestJSONAny(%s, []string{%s})\n", prefix, mapVar, quoteStringList(exclude))
			fmt.Fprintf(b, "%s\tif err != nil {\n%s\t\treturn out, err\n%s\t}\n", prefix, prefix, prefix)
			fmt.Fprintf(b, "%s\tout.%s = rm\n", prefix, f.Name)
			fmt.Fprintf(b, "%s}\n", prefix)
		case KindRestRaw:
			fmt.Fprintf(b, "%sout.%s = jsonbind.RestJSONRaw(%s, []string{%s})\n", prefix, f.Name, mapVar, quoteStringList(exclude))
		}
	}
}

func emitAssignFromRaw(b *bytes.Buffer, f FieldPlan, types map[string]TypePlan, rawVar, prefix, dest string, returnOut bool) {
	ret := "return out, "
	if !returnOut {
		ret = "return "
	}
	switch f.Kind {
	case "string":
		fmt.Fprintf(b, "%sv, err := jsonbind.DecodeJSONString(%s)\n", prefix, rawVar)
		fmt.Fprintf(b, "%sif err != nil {\n%s\t%sjsonbind.FieldError(%q, \"invalid string\", err)\n%s}\n", prefix, prefix, ret, f.Wire, prefix)
		fmt.Fprintf(b, "%s%s = v\n", prefix, dest)
	case "int":
		fmt.Fprintf(b, "%sv, err := jsonbind.DecodeJSONInt(%s)\n", prefix, rawVar)
		fmt.Fprintf(b, "%sif err != nil {\n%s\t%sjsonbind.FieldError(%q, \"invalid int\", err)\n%s}\n", prefix, prefix, ret, f.Wire, prefix)
		fmt.Fprintf(b, "%s%s = v\n", prefix, dest)
	case "int64":
		fmt.Fprintf(b, "%sv, err := jsonbind.DecodeJSONInt64(%s)\n", prefix, rawVar)
		fmt.Fprintf(b, "%sif err != nil {\n%s\t%sjsonbind.FieldError(%q, \"invalid int64\", err)\n%s}\n", prefix, prefix, ret, f.Wire, prefix)
		fmt.Fprintf(b, "%s%s = v\n", prefix, dest)
	case "bool":
		fmt.Fprintf(b, "%sv, err := jsonbind.DecodeJSONBool(%s)\n", prefix, rawVar)
		fmt.Fprintf(b, "%sif err != nil {\n%s\t%sjsonbind.FieldError(%q, \"invalid bool\", err)\n%s}\n", prefix, prefix, ret, f.Wire, prefix)
		fmt.Fprintf(b, "%s%s = v\n", prefix, dest)
	case "float64":
		fmt.Fprintf(b, "%sv, err := jsonbind.DecodeJSONFloat64(%s)\n", prefix, rawVar)
		fmt.Fprintf(b, "%sif err != nil {\n%s\t%sjsonbind.FieldError(%q, \"invalid float64\", err)\n%s}\n", prefix, prefix, ret, f.Wire, prefix)
		fmt.Fprintf(b, "%s%s = v\n", prefix, dest)
	case KindStruct:
		fmt.Fprintf(b, "%sv, err := decode%sJSON(%s)\n", prefix, f.TypeName, rawVar)
		fmt.Fprintf(b, "%sif err != nil {\n%s\t%serr\n%s}\n", prefix, prefix, ret, prefix)
		fmt.Fprintf(b, "%s%s = v\n", prefix, dest)
	case KindSlice:
		emitAssignSliceFromRaw(b, f, rawVar, prefix, dest, ret)
	case KindMap:
		emitAssignMapFromRaw(b, f, rawVar, prefix, dest, ret)
	case "file":
		// file cannot be decoded from JSON object fields
	}
}

func emitAssignSliceFromRaw(b *bytes.Buffer, f FieldPlan, rawVar, prefix, dest, ret string) {
	switch f.ElemKind {
	case "string":
		fmt.Fprintf(b, "%sv, err := jsonbind.DecodeJSONStringSlice(%s)\n", prefix, rawVar)
		fmt.Fprintf(b, "%sif err != nil {\n%s\t%serr\n%s}\n", prefix, prefix, ret, prefix)
		fmt.Fprintf(b, "%s%s = v\n", prefix, dest)
	case "int":
		fmt.Fprintf(b, "%sv, err := jsonbind.DecodeJSONIntSlice(%s)\n", prefix, rawVar)
		fmt.Fprintf(b, "%sif err != nil {\n%s\t%serr\n%s}\n", prefix, prefix, ret, prefix)
		fmt.Fprintf(b, "%s%s = v\n", prefix, dest)
	case "int64":
		fmt.Fprintf(b, "%sv, err := jsonbind.DecodeJSONInt64Slice(%s)\n", prefix, rawVar)
		fmt.Fprintf(b, "%sif err != nil {\n%s\t%serr\n%s}\n", prefix, prefix, ret, prefix)
		fmt.Fprintf(b, "%s%s = v\n", prefix, dest)
	case "bool":
		fmt.Fprintf(b, "%sv, err := jsonbind.DecodeJSONBoolSlice(%s)\n", prefix, rawVar)
		fmt.Fprintf(b, "%sif err != nil {\n%s\t%serr\n%s}\n", prefix, prefix, ret, prefix)
		fmt.Fprintf(b, "%s%s = v\n", prefix, dest)
	case "float64":
		fmt.Fprintf(b, "%sv, err := jsonbind.DecodeJSONFloat64Slice(%s)\n", prefix, rawVar)
		fmt.Fprintf(b, "%sif err != nil {\n%s\t%serr\n%s}\n", prefix, prefix, ret, prefix)
		fmt.Fprintf(b, "%s%s = v\n", prefix, dest)
	case KindStruct:
		fmt.Fprintf(b, "%sarr, err := jsonbind.RawJSONArray(%s)\n", prefix, rawVar)
		fmt.Fprintf(b, "%sif err != nil {\n%s\t%serr\n%s}\n", prefix, prefix, ret, prefix)
		fmt.Fprintf(b, "%sslice := make([]%s, 0, len(arr))\n", prefix, f.TypeName)
		fmt.Fprintf(b, "%sfor _, el := range arr {\n", prefix)
		fmt.Fprintf(b, "%s\titem, err := decode%sJSON(el)\n", prefix, f.TypeName)
		fmt.Fprintf(b, "%s\tif err != nil {\n%s\t\t%serr\n%s\t}\n", prefix, prefix, ret, prefix)
		fmt.Fprintf(b, "%s\tslice = append(slice, item)\n", prefix)
		fmt.Fprintf(b, "%s}\n", prefix)
		fmt.Fprintf(b, "%s%s = slice\n", prefix, dest)
	}
}

func emitAssignMapFromRaw(b *bytes.Buffer, f FieldPlan, rawVar, prefix, dest, ret string) {
	switch f.ElemKind {
	case "string":
		fmt.Fprintf(b, "%sv, err := jsonbind.DecodeJSONMapStringString(%s)\n", prefix, rawVar)
		fmt.Fprintf(b, "%sif err != nil {\n%s\t%serr\n%s}\n", prefix, prefix, ret, prefix)
		fmt.Fprintf(b, "%s%s = v\n", prefix, dest)
	case KindStruct:
		fmt.Fprintf(b, "%sobj, err := jsonbind.RawJSONMap(%s)\n", prefix, rawVar)
		fmt.Fprintf(b, "%sif err != nil {\n%s\t%serr\n%s}\n", prefix, prefix, ret, prefix)
		fmt.Fprintf(b, "%smout := make(map[string]%s, len(obj))\n", prefix, f.TypeName)
		fmt.Fprintf(b, "%sfor k, el := range obj {\n", prefix)
		fmt.Fprintf(b, "%s\titem, err := decode%sJSON(el)\n", prefix, f.TypeName)
		fmt.Fprintf(b, "%s\tif err != nil {\n%s\t\t%serr\n%s\t}\n", prefix, prefix, ret, prefix)
		fmt.Fprintf(b, "%s\tmout[k] = item\n", prefix)
		fmt.Fprintf(b, "%s}\n", prefix)
		fmt.Fprintf(b, "%s%s = mout\n", prefix, dest)
	default:
		// map[string]int etc. via encoding/json into temp — still not reflecting app structs
		fmt.Fprintf(b, "%svar mv %s\n", prefix, f.GoType())
		fmt.Fprintf(b, "%sif err := json.Unmarshal(%s, &mv); err != nil {\n", prefix, rawVar)
		fmt.Fprintf(b, "%s\t%sjsonbind.FieldError(%q, \"invalid map\", err)\n", prefix, ret, f.Wire)
		fmt.Fprintf(b, "%s}\n", prefix)
		fmt.Fprintf(b, "%s%s = mv\n", prefix, dest)
	}
}

func emitEncode(b *bytes.Buffer, t TypePlan, types map[string]TypePlan) {
	fmt.Fprintf(b, "func encode%sMap(v %s) map[string]any {\n", t.Name, t.Name)
	b.WriteString("\tbody := map[string]any{}\n")
	for _, f := range t.Fields {
		if f.IsRest() {
			fmt.Fprintf(b, "\tfor k, val := range v.%s {\n", f.Name)
			b.WriteString("\t\tbody[k] = val\n")
			b.WriteString("\t}\n")
			continue
		}
		key := f.JSON
		if key == "" {
			key = f.Wire
		}
		switch f.Kind {
		case KindStruct:
			fmt.Fprintf(b, "\tbody[%q] = encode%sMap(v.%s)\n", key, f.TypeName, f.Name)
		case KindSlice:
			if f.ElemKind == KindStruct {
				fmt.Fprintf(b, "\t{\n")
				fmt.Fprintf(b, "\t\tarr := make([]any, len(v.%s))\n", f.Name)
				fmt.Fprintf(b, "\t\tfor i := range v.%s {\n", f.Name)
				fmt.Fprintf(b, "\t\t\tarr[i] = encode%sMap(v.%s[i])\n", f.TypeName, f.Name)
				fmt.Fprintf(b, "\t\t}\n")
				fmt.Fprintf(b, "\t\tbody[%q] = arr\n", key)
				fmt.Fprintf(b, "\t}\n")
			} else {
				fmt.Fprintf(b, "\tbody[%q] = v.%s\n", key, f.Name)
			}
		case KindMap:
			if f.ElemKind == KindStruct {
				fmt.Fprintf(b, "\t{\n")
				fmt.Fprintf(b, "\t\tm := make(map[string]any, len(v.%s))\n", f.Name)
				fmt.Fprintf(b, "\t\tfor k, item := range v.%s {\n", f.Name)
				fmt.Fprintf(b, "\t\t\tm[k] = encode%sMap(item)\n", f.TypeName)
				fmt.Fprintf(b, "\t\t}\n")
				fmt.Fprintf(b, "\t\tbody[%q] = m\n", key)
				fmt.Fprintf(b, "\t}\n")
			} else {
				fmt.Fprintf(b, "\tbody[%q] = v.%s\n", key, f.Name)
			}
		case "file":
			fmt.Fprintf(b, "\tbody[%q] = v.%s\n", key, f.Name)
		default:
			fmt.Fprintf(b, "\tbody[%q] = v.%s\n", key, f.Name)
		}
	}
	b.WriteString("\treturn body\n}\n\n")

	fmt.Fprintf(b, "func encode%s(w io.Writer, v %s) error {\n", t.Name, t.Name)
	fmt.Fprintf(b, "\treturn json.NewEncoder(w).Encode(encode%sMap(v))\n}\n\n", t.Name)
	_ = types
}

func emitBinder(b *bytes.Buffer, t TypePlan, types map[string]TypePlan) {
	fmt.Fprintf(b, "func bind%s(r *http.Request) (%s, error) {\n", t.Name, t.Name)
	fmt.Fprintf(b, "\tvar out %s\n", t.Name)

	hasChecks := false
	for _, f := range t.Fields {
		if f.Check.NeedsPresence() {
			hasChecks = true
			fmt.Fprintf(b, "\tvar present%s bool\n", f.Name)
		}
	}

	needsBody := false
	needsFiles := false
	needsForm := false // formBody used for scalar/rest fields
	for _, f := range t.Fields {
		if f.Source == SourceInput || f.Source == SourcePayload {
			needsBody = true
			if f.Kind == "file" {
				needsFiles = true
			} else if f.IsRest() || !f.IsComposite() {
				needsForm = true
			}
		}
	}
	if needsBody {
		b.WriteString("\tvar jsonBody map[string]json.RawMessage\n")
		if needsForm || needsFiles {
			b.WriteString("\tvar formBody map[string]string\n")
		}
		if needsFiles {
			b.WriteString("\tvar fileBody map[string]httpbind.File\n")
		}
		b.WriteString("\tvar bodyRead bool\n")
		b.WriteString("\treadBody := func() error {\n")
		b.WriteString("\t\tif bodyRead {\n\t\t\treturn nil\n\t\t}\n")
		b.WriteString("\t\tbodyRead = true\n")
		b.WriteString("\t\tif httpbind.IsJSONRequest(r) {\n")
		b.WriteString("\t\t\tm, err := httpbind.ReadJSONMap(r)\n")
		b.WriteString("\t\t\tif err != nil {\n\t\t\t\treturn err\n\t\t\t}\n")
		b.WriteString("\t\t\tjsonBody = m\n")
		b.WriteString("\t\t\treturn nil\n")
		b.WriteString("\t\t}\n")
		if needsForm || needsFiles {
			b.WriteString("\t\tif httpbind.IsFormRequest(r) {\n")
			b.WriteString("\t\t\tm, err := httpbind.ParseFormMap(r)\n")
			b.WriteString("\t\t\tif err != nil {\n\t\t\t\treturn err\n\t\t\t}\n")
			b.WriteString("\t\t\tformBody = m\n")
			b.WriteString("\t\t\treturn nil\n")
			b.WriteString("\t\t}\n")
			b.WriteString("\t\tif httpbind.IsMultipartRequest(r) {\n")
			if needsFiles {
				b.WriteString("\t\t\tm, files, err := httpbind.ParseMultipartMap(r)\n")
				b.WriteString("\t\t\tif err != nil {\n\t\t\t\treturn err\n\t\t\t}\n")
				b.WriteString("\t\t\tformBody = m\n")
				b.WriteString("\t\t\tfileBody = files\n")
			} else {
				b.WriteString("\t\t\tm, _, err := httpbind.ParseMultipartMap(r)\n")
				b.WriteString("\t\t\tif err != nil {\n\t\t\t\treturn err\n\t\t\t}\n")
				b.WriteString("\t\t\tformBody = m\n")
			}
			b.WriteString("\t\t\treturn nil\n")
			b.WriteString("\t\t}\n")
		}
		b.WriteString("\t\treturn nil\n")
		b.WriteString("\t}\n")
	}

	for _, f := range t.Fields {
		if f.IsRest() {
			continue
		}
		emitFieldBind(b, f, types)
	}
	for _, f := range t.Fields {
		if f.IsRest() {
			emitRestField(b, t, f)
		}
	}

	if hasChecks {
		emitValidate(b, t)
		emitDefaults(b, t)
	}
	b.WriteString("\treturn out, nil\n}\n\n")
}

func bodyWireExclude(t TypePlan) []string {
	var out []string
	for _, f := range t.Fields {
		if f.IsRest() {
			continue
		}
		if f.Source == SourcePayload || f.Source == SourceInput {
			if f.Wire != "" && f.Wire != "*" {
				out = append(out, f.Wire)
			}
		}
	}
	return out
}

func emitRestField(b *bytes.Buffer, t TypePlan, f FieldPlan) {
	exclude := bodyWireExclude(t)
	b.WriteString("\tif err := readBody(); err != nil {\n\t\treturn out, err\n\t}\n")
	fmt.Fprintf(b, "\tif jsonBody != nil {\n")
	switch f.Kind {
	case KindRestAny:
		fmt.Fprintf(b, "\t\tm, err := jsonbind.RestJSONAny(jsonBody, []string{%s})\n", quoteStringList(exclude))
		b.WriteString("\t\tif err != nil {\n\t\t\treturn out, err\n\t\t}\n")
		fmt.Fprintf(b, "\t\tout.%s = m\n", f.Name)
	case KindRestRaw:
		fmt.Fprintf(b, "\t\tout.%s = jsonbind.RestJSONRaw(jsonBody, []string{%s})\n", f.Name, quoteStringList(exclude))
	}
	fmt.Fprintf(b, "\t} else if formBody != nil {\n")
	switch f.Kind {
	case KindRestAny:
		fmt.Fprintf(b, "\t\tout.%s = httpbind.RestFormAny(formBody, []string{%s})\n", f.Name, quoteStringList(exclude))
	case KindRestRaw:
		fmt.Fprintf(b, "\t\tout.%s = httpbind.RestFormRaw(formBody, []string{%s})\n", f.Name, quoteStringList(exclude))
	}
	fmt.Fprintf(b, "\t} else {\n")
	switch f.Kind {
	case KindRestAny:
		fmt.Fprintf(b, "\t\tout.%s = map[string]any{}\n", f.Name)
	case KindRestRaw:
		fmt.Fprintf(b, "\t\tout.%s = map[string]json.RawMessage{}\n", f.Name)
	}
	b.WriteString("\t}\n")
}

func quoteStringList(ss []string) string {
	if len(ss) == 0 {
		return ""
	}
	var b strings.Builder
	for i, s := range ss {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(strconv.Quote(s))
	}
	return b.String()
}

func emitFieldBind(b *bytes.Buffer, f FieldPlan, types map[string]TypePlan) {
	track := f.Check.NeedsPresence()
	switch f.Source {
	case SourcePath:
		if f.Kind == "string" {
			fmt.Fprintf(b, "\tout.%s = httpbind.PathValue(r, %q)\n", f.Name, f.Wire)
			if track {
				fmt.Fprintf(b, "\tif out.%s != \"\" {\n\t\tpresent%s = true\n\t}\n", f.Name, f.Name)
			}
		} else if !f.IsComposite() && f.Kind != "file" {
			fmt.Fprintf(b, "\tif pv := httpbind.PathValue(r, %q); pv != \"\" {\n", f.Wire)
			if track {
				fmt.Fprintf(b, "\t\tpresent%s = true\n", f.Name)
			}
			emitConvertFromStringIndented(b, f, "pv", "path", "\t\t")
			b.WriteString("\t}\n")
		}
	case SourceHeader:
		if f.Kind == "string" {
			fmt.Fprintf(b, "\tout.%s = httpbind.HeaderValue(r, %q)\n", f.Name, f.Wire)
			if track {
				fmt.Fprintf(b, "\tif out.%s != \"\" {\n\t\tpresent%s = true\n\t}\n", f.Name, f.Name)
			}
		} else if !f.IsComposite() && f.Kind != "file" {
			fmt.Fprintf(b, "\tif hv := httpbind.HeaderValue(r, %q); hv != \"\" {\n", f.Wire)
			if track {
				fmt.Fprintf(b, "\t\tpresent%s = true\n", f.Name)
			}
			emitConvertFromStringIndented(b, f, "hv", "header", "\t\t")
			b.WriteString("\t}\n")
		}
	case SourceCookie:
		if !f.IsComposite() {
			fmt.Fprintf(b, "\tif cv, ok := httpbind.CookieValue(r, %q); ok {\n", f.Wire)
			if track {
				fmt.Fprintf(b, "\t\tpresent%s = true\n", f.Name)
			}
			emitConvertFromStringIndented(b, f, "cv", "cookie", "\t\t")
			b.WriteString("\t}\n")
		}
	case SourceMethod:
		if f.Kind == "string" {
			fmt.Fprintf(b, "\tout.%s = r.Method\n", f.Name)
			if track {
				fmt.Fprintf(b, "\tpresent%s = true\n", f.Name)
			}
		}
	case SourceQuery:
		if !f.IsComposite() {
			fmt.Fprintf(b, "\tif qv, ok := httpbind.QueryValue(r, %q); ok {\n", f.Wire)
			if track {
				fmt.Fprintf(b, "\t\tpresent%s = true\n", f.Name)
			}
			emitConvertFromStringIndented(b, f, "qv", "query", "\t\t")
			b.WriteString("\t}\n")
		}
	case SourcePayload:
		emitPayloadField(b, f, types, "\t", track)
	case SourceInput:
		if f.IsComposite() {
			// Nested only from body for input-tagged composites.
			emitPayloadField(b, f, types, "\t", track)
			return
		}
		fmt.Fprintf(b, "\tif qv, ok := httpbind.QueryValue(r, %q); ok {\n", f.Wire)
		if track {
			fmt.Fprintf(b, "\t\tpresent%s = true\n", f.Name)
		}
		emitConvertFromStringIndented(b, f, "qv", "query", "\t\t")
		b.WriteString("\t} else {\n")
		emitPayloadField(b, f, types, "\t\t", track)
		b.WriteString("\t}\n")
	}
}

func emitPayloadField(b *bytes.Buffer, f FieldPlan, types map[string]TypePlan, prefix string, track bool) {
	fmt.Fprintf(b, "%sif err := readBody(); err != nil {\n%s\treturn out, err\n%s}\n", prefix, prefix, prefix)
	if f.Kind == "file" {
		fmt.Fprintf(b, "%sif fv, ok := fileBody[%q]; ok {\n", prefix, f.Wire)
		if track {
			fmt.Fprintf(b, "%s\tpresent%s = true\n", prefix, f.Name)
		}
		fmt.Fprintf(b, "%s\tout.%s = fv\n", prefix, f.Name)
		fmt.Fprintf(b, "%s} else if fileBody != nil {\n", prefix)
		fmt.Fprintf(b, "%s\treturn out, httpbind.BindError(%q, \"payload\", \"missing file\")\n", prefix, f.Wire)
		fmt.Fprintf(b, "%s}\n", prefix)
		return
	}
	// JSON path (including nested)
	fmt.Fprintf(b, "%sif raw, ok := jsonBody[%q]; ok {\n", prefix, f.Wire)
	if track {
		fmt.Fprintf(b, "%s\tpresent%s = true\n", prefix, f.Name)
	}
	emitAssignFromRaw(b, f, types, "raw", prefix+"\t", "out."+f.Name, true)
	if f.IsComposite() {
		fmt.Fprintf(b, "%s}\n", prefix)
		return
	}
	// form only for scalars
	fmt.Fprintf(b, "%s} else if formBody != nil {\n", prefix)
	fmt.Fprintf(b, "%s\tif fv, ok := formBody[%q]; ok {\n", prefix, f.Wire)
	if track {
		fmt.Fprintf(b, "%s\t\tpresent%s = true\n", prefix, f.Name)
	}
	emitConvertFromStringIndented(b, f, "fv", "payload", prefix+"\t\t")
	fmt.Fprintf(b, "%s\t}\n", prefix)
	fmt.Fprintf(b, "%s}\n", prefix)
}

func emitConvertFromStringIndented(b *bytes.Buffer, f FieldPlan, varName, location, prefix string) {
	switch f.Kind {
	case "int":
		fmt.Fprintf(b, "%sv, err := httpbind.ParseInt(%s)\n", prefix, varName)
		fmt.Fprintf(b, "%sif err != nil {\n%s\treturn out, httpbind.BindError(%q, %q, \"invalid int\")\n%s}\n", prefix, prefix, f.Wire, location, prefix)
		fmt.Fprintf(b, "%sout.%s = v\n", prefix, f.Name)
	case "int64":
		fmt.Fprintf(b, "%sv, err := httpbind.ParseInt64(%s)\n", prefix, varName)
		fmt.Fprintf(b, "%sif err != nil {\n%s\treturn out, httpbind.BindError(%q, %q, \"invalid int64\")\n%s}\n", prefix, prefix, f.Wire, location, prefix)
		fmt.Fprintf(b, "%sout.%s = v\n", prefix, f.Name)
	case "bool":
		fmt.Fprintf(b, "%sv, err := httpbind.ParseBool(%s)\n", prefix, varName)
		fmt.Fprintf(b, "%sif err != nil {\n%s\treturn out, httpbind.BindError(%q, %q, \"invalid bool\")\n%s}\n", prefix, prefix, f.Wire, location, prefix)
		fmt.Fprintf(b, "%sout.%s = v\n", prefix, f.Name)
	case "float64":
		fmt.Fprintf(b, "%sv, err := httpbind.ParseFloat64(%s)\n", prefix, varName)
		fmt.Fprintf(b, "%sif err != nil {\n%s\treturn out, httpbind.BindError(%q, %q, \"invalid float64\")\n%s}\n", prefix, prefix, f.Wire, location, prefix)
		fmt.Fprintf(b, "%sout.%s = v\n", prefix, f.Name)
	case "string":
		fmt.Fprintf(b, "%sout.%s = %s\n", prefix, f.Name, varName)
	}
}

func emitValidate(b *bytes.Buffer, t TypePlan) {
	b.WriteString("\tvar checkFields []httpbind.FieldError\n")
	for _, f := range t.Fields {
		if !f.Check.HasRules() {
			continue
		}
		loc := checkLocation(f.Source)
		c := f.Check
		if c.Required {
			switch f.Kind {
			case "string":
				fmt.Fprintf(b, "\tif !present%s || out.%s == \"\" {\n", f.Name, f.Name)
			case "file":
				fmt.Fprintf(b, "\tif !present%s || out.%s.Empty() {\n", f.Name, f.Name)
			default:
				fmt.Fprintf(b, "\tif !present%s {\n", f.Name)
			}
			fmt.Fprintf(b, "\t\tcheckFields = append(checkFields, httpbind.Field(%q, %q, \"required\"))\n", f.Wire, loc)
			b.WriteString("\t}\n")
		}

		hasValueConstraints := c.Min != nil || c.Max != nil ||
			c.MinLen != nil || c.MaxLen != nil || c.Len != nil ||
			len(c.Enum) > 0 || c.Email || c.UUID || c.Date || c.Time || c.DateTime || c.Pattern != ""
		if hasValueConstraints {
			fmt.Fprintf(b, "\tif present%s {\n", f.Name)
			if c.Min != nil {
				switch f.Kind {
				case "int":
					fmt.Fprintf(b, "\t\tif out.%s < %s {\n", f.Name, intLit(*c.Min))
				case "int64":
					fmt.Fprintf(b, "\t\tif out.%s < %s {\n", f.Name, int64Lit(*c.Min))
				case "float64":
					fmt.Fprintf(b, "\t\tif out.%s < %s {\n", f.Name, floatLit(*c.Min))
				}
				fmt.Fprintf(b, "\t\t\tcheckFields = append(checkFields, httpbind.Field(%q, %q, %q))\n", f.Wire, loc, fmt.Sprintf("must be >= %v", numMsg(*c.Min)))
				b.WriteString("\t\t}\n")
			}
			if c.Max != nil {
				switch f.Kind {
				case "int":
					fmt.Fprintf(b, "\t\tif out.%s > %s {\n", f.Name, intLit(*c.Max))
				case "int64":
					fmt.Fprintf(b, "\t\tif out.%s > %s {\n", f.Name, int64Lit(*c.Max))
				case "float64":
					fmt.Fprintf(b, "\t\tif out.%s > %s {\n", f.Name, floatLit(*c.Max))
				}
				fmt.Fprintf(b, "\t\t\tcheckFields = append(checkFields, httpbind.Field(%q, %q, %q))\n", f.Wire, loc, fmt.Sprintf("must be <= %v", numMsg(*c.Max)))
				b.WriteString("\t\t}\n")
			}
			if f.Kind == "string" {
				if c.MinLen != nil {
					fmt.Fprintf(b, "\t\tif len(out.%s) < %d {\n", f.Name, *c.MinLen)
					fmt.Fprintf(b, "\t\t\tcheckFields = append(checkFields, httpbind.Field(%q, %q, %q))\n", f.Wire, loc, fmt.Sprintf("length must be >= %d", *c.MinLen))
					b.WriteString("\t\t}\n")
				}
				if c.MaxLen != nil {
					fmt.Fprintf(b, "\t\tif len(out.%s) > %d {\n", f.Name, *c.MaxLen)
					fmt.Fprintf(b, "\t\t\tcheckFields = append(checkFields, httpbind.Field(%q, %q, %q))\n", f.Wire, loc, fmt.Sprintf("length must be <= %d", *c.MaxLen))
					b.WriteString("\t\t}\n")
				}
				if c.Len != nil {
					fmt.Fprintf(b, "\t\tif len(out.%s) != %d {\n", f.Name, *c.Len)
					fmt.Fprintf(b, "\t\t\tcheckFields = append(checkFields, httpbind.Field(%q, %q, %q))\n", f.Wire, loc, fmt.Sprintf("length must be %d", *c.Len))
					b.WriteString("\t\t}\n")
				}
			}
			if len(c.Enum) > 0 {
				b.WriteString("\t\t{\n")
				b.WriteString("\t\t\tenumOK := false\n")
				for _, v := range c.Enum {
					lit, _ := defaultGoLiteral(f.Kind, v)
					fmt.Fprintf(b, "\t\t\tif out.%s == %s {\n\t\t\t\tenumOK = true\n\t\t\t}\n", f.Name, lit)
				}
				b.WriteString("\t\t\tif !enumOK {\n")
				msg := "must be one of: " + joinEnumMsg(c.Enum)
				fmt.Fprintf(b, "\t\t\t\tcheckFields = append(checkFields, httpbind.Field(%q, %q, %q))\n", f.Wire, loc, msg)
				b.WriteString("\t\t\t}\n")
				b.WriteString("\t\t}\n")
			}
			if f.Kind == "string" && (c.Email || c.UUID || c.Date || c.Time || c.DateTime || c.Pattern != "") {
				fmt.Fprintf(b, "\t\tif out.%s != \"\" {\n", f.Name)
				if c.Email {
					fmt.Fprintf(b, "\t\t\tif !httpbind.CheckEmail(out.%s) {\n", f.Name)
					fmt.Fprintf(b, "\t\t\t\tcheckFields = append(checkFields, httpbind.Field(%q, %q, \"must be a valid email\"))\n", f.Wire, loc)
					b.WriteString("\t\t\t}\n")
				}
				if c.UUID {
					fmt.Fprintf(b, "\t\t\tif !httpbind.CheckUUID(out.%s) {\n", f.Name)
					fmt.Fprintf(b, "\t\t\t\tcheckFields = append(checkFields, httpbind.Field(%q, %q, \"must be a valid uuid\"))\n", f.Wire, loc)
					b.WriteString("\t\t\t}\n")
				}
				if c.Date {
					fmt.Fprintf(b, "\t\t\tif !httpbind.CheckDate(out.%s) {\n", f.Name)
					fmt.Fprintf(b, "\t\t\t\tcheckFields = append(checkFields, httpbind.Field(%q, %q, \"must be ISO date\"))\n", f.Wire, loc)
					b.WriteString("\t\t\t}\n")
				}
				if c.Time {
					fmt.Fprintf(b, "\t\t\tif !httpbind.CheckTime(out.%s) {\n", f.Name)
					fmt.Fprintf(b, "\t\t\t\tcheckFields = append(checkFields, httpbind.Field(%q, %q, \"must be ISO time\"))\n", f.Wire, loc)
					b.WriteString("\t\t\t}\n")
				}
				if c.DateTime {
					fmt.Fprintf(b, "\t\t\tif !httpbind.CheckDateTime(out.%s) {\n", f.Name)
					fmt.Fprintf(b, "\t\t\t\tcheckFields = append(checkFields, httpbind.Field(%q, %q, \"must be RFC3339 datetime\"))\n", f.Wire, loc)
					b.WriteString("\t\t\t}\n")
				}
				if c.Pattern != "" {
					fmt.Fprintf(b, "\t\t\tif !checkPattern%s%s.MatchString(out.%s) {\n", t.Name, f.Name, f.Name)
					fmt.Fprintf(b, "\t\t\t\tcheckFields = append(checkFields, httpbind.Field(%q, %q, \"must match pattern\"))\n", f.Wire, loc)
					b.WriteString("\t\t\t}\n")
				}
				b.WriteString("\t\t}\n")
			}
			b.WriteString("\t}\n")
		}
	}
	b.WriteString("\tif len(checkFields) > 0 {\n")
	b.WriteString("\t\treturn out, httpbind.Validation(checkFields...)\n")
	b.WriteString("\t}\n")
}

func emitDefaults(b *bytes.Buffer, t TypePlan) {
	for _, f := range t.Fields {
		if !f.Check.HasDefault {
			continue
		}
		lit, err := defaultGoLiteral(f.Kind, f.Check.Default)
		if err != nil {
			continue
		}
		fmt.Fprintf(b, "\tif !present%s {\n", f.Name)
		fmt.Fprintf(b, "\t\tout.%s = %s\n", f.Name, lit)
		b.WriteString("\t}\n")
	}
}

func joinEnumMsg(vals []string) string {
	return joinComma(vals)
}

func joinComma(vals []string) string {
	if len(vals) == 0 {
		return ""
	}
	out := vals[0]
	for i := 1; i < len(vals); i++ {
		out += ", " + vals[i]
	}
	return out
}

func intLit(f float64) string {
	return strconv.FormatInt(int64(f), 10)
}

func int64Lit(f float64) string {
	return fmt.Sprintf("int64(%d)", int64(f))
}

func floatLit(f float64) string {
	return strconv.FormatFloat(f, 'g', -1, 64)
}

func numMsg(f float64) any {
	if f == float64(int64(f)) {
		return int64(f)
	}
	return f
}

func emitWriter(b *bytes.Buffer, t TypePlan, types map[string]TypePlan) {
	fmt.Fprintf(b, "func write%s(w http.ResponseWriter, r *http.Request, v %s) error {\n", t.Name, t.Name)
	b.WriteString("\t_ = r\n")
	fmt.Fprintf(b, "\treturn httpbind.WriteJSON(w, http.StatusOK, encode%sMap(v))\n", t.Name)
	b.WriteString("}\n\n")
	_ = types
}
