package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"strconv"
	"strings"
)

// EmitFirestoreQueries generates one function per checked declaration.
func EmitFirestoreQueries(pkg string, plans []FirestoreQueryPlan) ([]byte, error) {
	if len(plans) == 0 {
		return nil, nil
	}
	var body bytes.Buffer
	e := &firestoreQueryEmitter{}
	for _, plan := range plans {
		if err := e.query(&body, plan); err != nil {
			return nil, err
		}
	}

	var out bytes.Buffer
	out.WriteString("// Code generated by tinybind; DO NOT EDIT.\n\n")
	fmt.Fprintf(&out, "package %s\n\n", pkg)
	writeFirestoreQueryImports(&out, body.Bytes())
	out.Write(body.Bytes())

	formatted, err := format.Source(out.Bytes())
	if err != nil {
		return out.Bytes(), fmt.Errorf("firestorebind: format generated query: %w\n%s", err, out.String())
	}
	return formatted, nil
}

var firestoreQueryImports = []struct {
	qualifier string
	path      string
	stdlib    bool
}{
	{qualifier: "context", path: "context", stdlib: true},
	{qualifier: "iter", path: "iter", stdlib: true},
	{qualifier: "time", path: "time", stdlib: true},
	{qualifier: "firestorebind", path: firestorebindImportPath},
	{qualifier: "datastore", path: datastoreImportPath},
}

func writeFirestoreQueryImports(out *bytes.Buffer, body []byte) {
	var stdlib, external []string
	for _, item := range firestoreQueryImports {
		if !usesQualifier(body, item.qualifier) {
			continue
		}
		if item.stdlib {
			stdlib = append(stdlib, item.path)
		} else {
			external = append(external, item.path)
		}
	}
	if len(stdlib)+len(external) == 0 {
		return
	}
	out.WriteString("import (\n")
	for _, path := range stdlib {
		fmt.Fprintf(out, "\t%q\n", path)
	}
	if len(stdlib) > 0 && len(external) > 0 {
		out.WriteString("\n")
	}
	for _, path := range external {
		fmt.Fprintf(out, "\t%q\n", path)
	}
	out.WriteString(")\n\n")
}

type firestoreQueryEmitter struct {
	temps int
}

func (e *firestoreQueryEmitter) temp(prefix string) string {
	e.temps++
	return fmt.Sprintf("%s%d", prefix, e.temps)
}

func (e *firestoreQueryEmitter) query(b *bytes.Buffer, plan FirestoreQueryPlan) error {
	decl := plan.Decl
	name := decl.Name
	base := lowerFirst(name)

	// The kind is a constant taken from the type rather than from the
	// declaration, so a declaration cannot disagree with the codec about what it
	// is querying. That is why there is no table clause here.
	fmt.Fprintf(b, "// %sKind is the kind %s runs against, which is %s's own.\n", base, name, plan.Entity.Name)
	fmt.Fprintf(b, "const %sKind = %s\n\n", base, strconv.Quote(plan.Entity.Kind))

	if decl.HasIndex {
		// The index is meant to be consumed by a deploy step, so it takes the
		// declaration's own visibility rather than the unexported spelling the
		// kind constant uses. An index a caller cannot reach describes nothing.
		indexName := base + "Index"
		if decl.Exported {
			indexName = name + "Index"
		}
		e.index(b, plan, base, name, indexName)
	}

	result, err := firestoreQueryResult(plan)
	if err != nil {
		return err
	}

	fmt.Fprintf(b, "// %s queries %s.\n", name, plan.Entity.Name)
	if decl.Shape == FirestoreMany {
		b.WriteString("//\n// One range can issue many requests; nothing here reports the boundary.\n")
	}
	if !decl.HasIndex && firestoreNeedsIndexHint(plan) {
		b.WriteString("//\n// This query combines filters and ordering in a shape that may require a\n")
		b.WriteString("// composite index. Nothing in the toolchain verifies that one exists, so a\n")
		b.WriteString("// missing index surfaces as FAILED_PRECONDITION on the first run.\n")
	}
	fmt.Fprintf(b, "func %s(ctx context.Context%s, opts ...datastore.ReadOption) %s {\n",
		name, firestoreQueryParams(decl), result)

	fmt.Fprintf(b, "\tq := datastore.NewQuery(%sKind)\n", base)
	for _, filter := range plan.Filters {
		if err := e.filter(b, filter); err != nil {
			return fmt.Errorf("firestorebind: statement %s: %w", name, err)
		}
	}
	if plan.Ancestor != "" {
		fmt.Fprintf(b, "\tq = q.Ancestor(%s)\n", plan.Ancestor)
	}
	for _, order := range plan.Orders {
		entry := "Order"
		if order.Order.Direction == FirestoreDescending {
			entry = "OrderDesc"
		}
		fmt.Fprintf(b, "\tq = q.%s(%s)\n", entry, strconv.Quote(order.Field.Property))
	}
	if bound, ok := firestoreBoundExpr(decl.Limit); ok {
		fmt.Fprintf(b, "\tq = q.Limit(%s)\n", bound)
	}
	if bound, ok := firestoreBoundExpr(decl.Offset); ok {
		fmt.Fprintf(b, "\tq = q.Offset(%s)\n", bound)
	}
	if decl.Shape == FirestoreKeys {
		b.WriteString("\tq = q.KeysOnly()\n")
	}

	switch decl.Shape {
	case FirestoreMany:
		fmt.Fprintf(b, "\treturn firestorebind.Query[%s](ctx, q, opts...)\n", plan.Entity.Name)
	case FirestoreBatch:
		fmt.Fprintf(b, "\treturn firestorebind.QueryPage[%s](ctx, q, opts...)\n", plan.Entity.Name)
	case FirestoreCount:
		b.WriteString("\treturn firestorebind.Count(ctx, q, opts...)\n")
	case FirestoreKeys:
		b.WriteString("\treturn firestorebind.QueryKeysPage(ctx, q, opts...)\n")
	}
	b.WriteString("}\n\n")
	return nil
}

// index emits the composite index the author declared, as a value a deploy step
// can marshal. Nothing derives it; see decision:firestore-no-schema-artifact.
func (e *firestoreQueryEmitter) index(b *bytes.Buffer, plan FirestoreQueryPlan, base, name, indexName string) {
	fmt.Fprintf(b, "// %s is the composite index %s declares it needs.\n", indexName, name)
	b.WriteString("//\n// It is a description, not a request: applying an index is an admin-API\n")
	b.WriteString("// operation. Feed it to datastore.MarshalIndexYAML and to whatever owns\n")
	b.WriteString("// index.yaml in this project.\n")
	fmt.Fprintf(b, "var %s = datastore.Index{\n", indexName)
	fmt.Fprintf(b, "\tKind: %sKind,\n", base)
	if plan.Ancestor != "" {
		b.WriteString("\tAncestor: true,\n")
	}
	b.WriteString("\tProperties: []datastore.IndexProperty{\n")
	for _, property := range plan.Decl.Index {
		direction := "datastore.Ascending"
		if property.Direction == FirestoreDescending {
			direction = "datastore.Descending"
		}
		fmt.Fprintf(b, "\t\t{Name: %s, Direction: %s},\n", strconv.Quote(property.Name), direction)
	}
	b.WriteString("\t},\n}\n\n")
}

// filter emits one property filter. The value goes through the same encoders the
// codec uses, so a filter and a stored property cannot disagree about how a
// value is written.
func (e *firestoreQueryEmitter) filter(b *bytes.Buffer, filter FirestoreQueryFilter) error {
	property := strconv.Quote(filter.Field.Property)
	op := firestoreOpConstant(filter.Predicate.Op)

	if filter.Predicate.Op.Multi() {
		members := e.temp("members")
		element := e.temp("member")
		fmt.Fprintf(b, "\t%s := make([]datastore.Value, 0, len(%s))\n", members, filter.Param.Name)
		fmt.Fprintf(b, "\tfor _, %s := range %s {\n", element, filter.Param.Name)
		expr, ok := firestoreScalarEncode(element, filter.Field.Type)
		if !ok {
			return fmt.Errorf("property %s cannot be a filter value", filter.Field.Property)
		}
		fmt.Fprintf(b, "\t\t%s = append(%s, %s)\n", members, members, expr)
		b.WriteString("\t}\n")
		fmt.Fprintf(b, "\tq = q.Filter(%s, %s, datastore.Array(%s...))\n", property, op, members)
		return nil
	}

	expr, ok := firestoreScalarEncode(filter.Param.Name, filter.Field.Type)
	if !ok {
		return fmt.Errorf("property %s cannot be a filter value", filter.Field.Property)
	}
	fmt.Fprintf(b, "\tq = q.Filter(%s, %s, %s)\n", property, op, expr)
	return nil
}

func firestoreOpConstant(op FirestoreOp) string {
	switch op {
	case FirestoreEqual:
		return "datastore.Equal"
	case FirestoreNotEqual:
		return "datastore.NotEqual"
	case FirestoreLess:
		return "datastore.LessThan"
	case FirestoreLessOrEqual:
		return "datastore.LessThanOrEqual"
	case FirestoreGreater:
		return "datastore.GreaterThan"
	case FirestoreGreaterOrEqual:
		return "datastore.GreaterThanEqual"
	case FirestoreIn:
		return "datastore.In"
	case FirestoreNotIn:
		return "datastore.NotIn"
	default:
		return "datastore.Equal"
	}
}

// firestoreBoundExpr writes a limit or offset as the int32 the driver takes.
func firestoreBoundExpr(bound FirestoreBound) (string, bool) {
	if !bound.Present {
		return "", false
	}
	if bound.Param != "" {
		return "int32(" + bound.Param + ")", true
	}
	return strconv.Itoa(bound.Literal), true
}

// firestoreQueryResult is the Go result type a declaration's shape selects.
func firestoreQueryResult(plan FirestoreQueryPlan) (string, error) {
	switch plan.Decl.Shape {
	case FirestoreBatch:
		return fmt.Sprintf("(firestorebind.Page[%s], error)", plan.Entity.Name), nil
	case FirestoreMany:
		return fmt.Sprintf("iter.Seq2[%s, error]", plan.Entity.Name), nil
	case FirestoreCount:
		return "(int64, error)", nil
	case FirestoreKeys:
		return "(firestorebind.KeyPage, error)", nil
	default:
		return "", fmt.Errorf("firestorebind: statement %s has no result shape", plan.Decl.Name)
	}
}

// firestoreQueryParams writes the declared parameters as a Go parameter list.
func firestoreQueryParams(decl FirestoreQueryDecl) string {
	if len(decl.Params) == 0 {
		return ""
	}
	typed := make([]string, 0, len(decl.Params))
	for _, param := range decl.Params {
		typed = append(typed, param.Name+" "+param.Type)
	}
	return ", " + strings.Join(typed, ", ")
}

// firestoreNeedsIndexHint reports the shapes that commonly require a composite
// index, for the godoc warning only.
//
// It is deliberately not a derivation: the real rule is subtle, and a generated
// diagnostic that named the wrong index would read as authoritative while
// leaving the query broken. This only says "may", and only where more than one
// property is involved.
func firestoreNeedsIndexHint(plan FirestoreQueryPlan) bool {
	if plan.Decl.Shape == FirestoreCount {
		// A count runs the aggregation query, and warning about ordering it
		// would be noise: the parser already rejects an order clause there.
		return false
	}
	properties := map[string]bool{}
	inequality := false
	for _, filter := range plan.Filters {
		properties[filter.Field.Property] = true
		if filter.Predicate.Op != FirestoreEqual {
			inequality = true
		}
	}
	for _, order := range plan.Orders {
		properties[order.Field.Property] = true
	}
	switch {
	case len(plan.Orders) > 1:
		return true
	case plan.Ancestor != "" && (len(plan.Orders) > 0 || len(plan.Filters) > 0):
		// An ancestor query that also sorts or filters needs an ancestor index,
		// which is a composite index by another name.
		return true
	default:
		return len(properties) > 1 && (inequality || len(plan.Orders) > 0)
	}
}
