package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"strconv"
)

// EmitFirestoreEntities generates the entity codec for every plan in the
// package.
func EmitFirestoreEntities(plan *FirestorePackagePlan) ([]byte, error) {
	return emitFirestoreSelected(plan, nil)
}

// emitFirestoreSelected emits the named subset of a package plan. A nil
// selection emits everything.
func emitFirestoreSelected(plan *FirestorePackagePlan, selected map[string]bool) ([]byte, error) {
	if plan == nil {
		return nil, fmt.Errorf("firestorebind: nil plan")
	}
	e := &firestoreEmitter{}
	for _, entity := range plan.Entities {
		if selected != nil && !selected[entity.Name] {
			continue
		}
		if err := e.entity(entity); err != nil {
			return nil, err
		}
	}
	if e.body.Len() == 0 {
		return nil, nil
	}

	var out bytes.Buffer
	out.WriteString("// Code generated by tinybind; DO NOT EDIT.\n\n")
	fmt.Fprintf(&out, "package %s\n\n", plan.Package)
	writeFirestoreImports(&out, e.body.Bytes())
	out.Write(e.body.Bytes())

	formatted, err := format.Source(out.Bytes())
	if err != nil {
		return out.Bytes(), fmt.Errorf("firestorebind: format generated code: %w\n%s", err, out.String())
	}
	return formatted, nil
}

// firestoreImports lists every package the entity emitter can reference, with
// the qualifier that proves the reference.
var firestoreImports = []struct {
	qualifier string
	path      string
	stdlib    bool
}{
	{qualifier: "strconv", path: "strconv", stdlib: true},
	{qualifier: "time", path: "time", stdlib: true},
	{qualifier: "firestorebind", path: firestorebindImportPath},
	{qualifier: "datastore", path: datastoreImportPath},
}

func writeFirestoreImports(out *bytes.Buffer, body []byte) {
	var stdlib, external []string
	for _, item := range firestoreImports {
		if !usesQualifier(body, item.qualifier) {
			continue
		}
		if item.stdlib {
			stdlib = append(stdlib, item.path)
		} else {
			external = append(external, item.path)
		}
	}
	if len(stdlib)+len(external) == 0 {
		return
	}
	out.WriteString("import (\n")
	for _, path := range stdlib {
		fmt.Fprintf(out, "\t%q\n", path)
	}
	if len(stdlib) > 0 && len(external) > 0 {
		out.WriteString("\n")
	}
	for _, path := range external {
		fmt.Fprintf(out, "\t%q\n", path)
	}
	out.WriteString(")\n\n")
}

type firestoreEmitter struct {
	body bytes.Buffer
	// temps numbers the locals a nested encode or decode needs, so two fields of
	// one method never collide.
	temps int
}

func (e *firestoreEmitter) temp(prefix string) string {
	e.temps++
	return fmt.Sprintf("%s%d", prefix, e.temps)
}

func (e *firestoreEmitter) entity(entity FirestoreEntityPlan) error {
	e.temps = 0
	receiver := "v"
	_, hasIdentity := entity.Identity()
	emitKey := entity.Usage&FirestoreKey != 0 && hasIdentity

	if entity.Usage&FirestoreEncode != 0 {
		fmt.Fprintf(&e.body, "var _ firestorebind.EntityEncoder = %s{}\n", entity.Name)
	}
	if entity.Usage&FirestoreDecode != 0 {
		fmt.Fprintf(&e.body, "var _ firestorebind.EntityDecoder = (*%s)(nil)\n", entity.Name)
	}
	if emitKey {
		fmt.Fprintf(&e.body, "var _ firestorebind.Keyer = %s{}\n", entity.Name)
	}
	if _, ok := entity.Version(); ok {
		fmt.Fprintf(&e.body, "var _ firestorebind.Versioner = %s{}\n", entity.Name)
	}
	if _, ok := entity.Expiry(); ok {
		fmt.Fprintf(&e.body, "var _ firestorebind.Expirer = %s{}\n", entity.Name)
	}
	fmt.Fprintf(&e.body, "var _ firestorebind.Kinder = %s{}\n\n", entity.Name)

	e.kind(entity, receiver)
	e.entityVersion(entity, receiver)
	e.expiryProperty(entity, receiver)
	if emitKey {
		if err := e.entityKey(entity, receiver); err != nil {
			return err
		}
	}
	if entity.Usage&FirestoreEncode != 0 {
		if err := e.encodeEntity(entity, receiver, emitKey); err != nil {
			return err
		}
	}
	if entity.Usage&FirestoreDecode != 0 {
		if err := e.decodeEntity(entity, receiver); err != nil {
			return err
		}
	}
	return nil
}

func (e *firestoreEmitter) kind(entity FirestoreEntityPlan, receiver string) {
	fmt.Fprintf(&e.body, "// Kind is the Datastore kind %s is stored under. A kind belongs to the type\n", entity.Name)
	e.body.WriteString("// rather than to the deployment, so nothing configures it.\n")
	fmt.Fprintf(&e.body, "func (%s %s) Kind() string { return %s }\n\n", receiver, entity.Name, strconv.Quote(entity.Kind))
}

// entityVersion emits the read-at version, which is what makes a later write
// conditional. It is emitted from the tag rather than from a discovered call:
// the runtime asks for it by interface, and an interface assertion is not a call
// the generator can find.
func (e *firestoreEmitter) entityVersion(entity FirestoreEntityPlan, receiver string) {
	version, ok := entity.Version()
	if !ok {
		return
	}
	fmt.Fprintf(&e.body, "// EntityVersion is the version %s was read at. A non-zero version makes a\n", entity.Name)
	e.body.WriteString("// later Store or Update conditional on the stored entity still being at it.\n")
	fmt.Fprintf(&e.body, "func (%s %s) EntityVersion() int64 { return int64(%s.%s) }\n\n", receiver, entity.Name, receiver, version.Name)
}

// expiryProperty emits the property a TTL policy is meant to expire this kind
// by. It writes nothing into the codec: the property is encoded as an ordinary
// timestamp, exactly as it would be without the tag. What this produces is one
// fact a deployment step can read, so the property name lives beside the field
// it describes rather than in a hand-kept list.
//
// Like the version accessor, it is emitted from the tag rather than from a
// discovered call, because the caller is a tool outside the package.
func (e *firestoreEmitter) expiryProperty(entity FirestoreEntityPlan, receiver string) {
	expiry, ok := entity.Expiry()
	if !ok {
		return
	}
	fmt.Fprintf(&e.body, "// ExpiryProperty is the property a TTL policy for kind %s should expire\n", entity.Kind)
	e.body.WriteString("// entities by. Nothing here applies one: Datastore mode has no expiry on the\n")
	e.body.WriteString("// wire, so a policy is applied out of band with gcloud over this property.\n")
	fmt.Fprintf(&e.body, "func (%s %s) ExpiryProperty() (string, bool) { return %s, true }\n\n",
		receiver, entity.Name, strconv.Quote(expiry.Property))
}

func (e *firestoreEmitter) entityKey(entity FirestoreEntityPlan, receiver string) error {
	identity, _ := entity.Identity()
	parent, hasParent := entity.Parent()

	fmt.Fprintf(&e.body, "// EntityKey returns the key of %s, including its ancestor path.\n", entity.Name)
	fmt.Fprintf(&e.body, "func (%s %s) EntityKey() datastore.Key {\n", receiver, entity.Name)

	var self string
	switch identity.Role {
	case "name":
		self = fmt.Sprintf("datastore.NameKey(%s.Kind(), string(%s.%s))", receiver, receiver, identity.Name)
	case "id":
		self = fmt.Sprintf("datastore.IDKey(%s.Kind(), int64(%s.%s))", receiver, receiver, identity.Name)
	default:
		return fmt.Errorf("%s: no identity field to build a key from", entity.Name)
	}

	if !hasParent {
		fmt.Fprintf(&e.body, "\treturn %s\n}\n\n", self)
		return nil
	}
	// A child key is the parent path with this entity's element appended, so the
	// ancestor is part of identity rather than a property beside it.
	var parentKey string
	switch parent.Type.Kind {
	case FirestoreKeyRef:
		parentKey = receiver + "." + parent.Name
	case FirestoreStruct:
		parentKey = receiver + "." + parent.Name + ".EntityKey()"
	default:
		return fmt.Errorf("%s.%s: parent is neither a datastore.Key nor a bound type", entity.Name, parent.Name)
	}
	element := e.temp("self")
	fmt.Fprintf(&e.body, "\t%s := %s\n", element, self)
	fmt.Fprintf(&e.body, "\tif len(%s.Path) == 0 {\n\t\treturn %s\n\t}\n", parentKey, element)
	fmt.Fprintf(&e.body, "\treturn %s.Child(%s.Path[len(%s.Path)-1])\n}\n\n", parentKey, element, element)
	return nil
}

func (e *firestoreEmitter) encodeEntity(entity FirestoreEntityPlan, receiver string, hasKey bool) error {
	properties := entity.Properties()
	fmt.Fprintf(&e.body, "// EncodeEntity converts %s into a Datastore entity.\n", entity.Name)
	e.body.WriteString("//\n")
	e.body.WriteString("// The key travels beside the properties rather than among them, so the\n")
	e.body.WriteString("// identity fields are absent from the property map and cannot drift from it.\n")
	fmt.Fprintf(&e.body, "func (%s %s) EncodeEntity() datastore.Entity {\n", receiver, entity.Name)
	fmt.Fprintf(&e.body, "\tproperties := make(map[string]datastore.Value, %d)\n", len(properties))
	for _, f := range properties {
		source := receiver + "." + f.Name
		target := fmt.Sprintf("properties[%s]", strconv.Quote(f.Property))
		indent := "\t"
		guard, guarded := firestoreEmptyGuard(f, source)
		if guarded {
			fmt.Fprintf(&e.body, "\tif %s {\n", guard)
			indent = "\t\t"
		}
		if err := e.encodeInto(target, source, f.Type, f.NoIndex, indent); err != nil {
			return fmt.Errorf("%s.%s: %w", entity.Name, f.Name, err)
		}
		if guarded {
			e.body.WriteString("\t}\n")
		}
	}
	if hasKey {
		fmt.Fprintf(&e.body, "\tkey := %s.EntityKey()\n", receiver)
		e.body.WriteString("\treturn datastore.Entity{Key: &key, Properties: properties}\n}\n\n")
	} else {
		// A nested entity carries no key, and a type with no identity has none
		// to carry; the caller supplies one.
		e.body.WriteString("\treturn datastore.Entity{Properties: properties}\n}\n\n")
	}
	return nil
}

// firestoreEmptyGuard returns the condition under which a property is written at
// all. omitempty asks for it; a zero datastore.Value gets it unasked, because a
// value with no member set is rejected by the codec and cannot be what the
// caller meant to store.
func firestoreEmptyGuard(f FirestoreFieldPlan, source string) (string, bool) {
	if f.Type.Kind == FirestoreRaw {
		return fmt.Sprintf("%s.Kind() != datastore.KindInvalid", source), true
	}
	if !f.OmitEmpty {
		return "", false
	}
	switch f.Type.Kind {
	case FirestoreString:
		return fmt.Sprintf("%s != \"\"", source), true
	case FirestoreInt, FirestoreUint, FirestoreDouble:
		return fmt.Sprintf("%s != 0", source), true
	case FirestoreBool:
		return fmt.Sprintf("bool(%s)", source), true
	case FirestoreBlob, FirestoreArray:
		return fmt.Sprintf("len(%s) != 0", source), true
	case FirestoreTime:
		return fmt.Sprintf("!%s.IsZero()", source), true
	case FirestorePointer:
		return fmt.Sprintf("%s != nil", source), true
	default:
		return "", false
	}
}

// encodeInto writes the statements that assign the value for source to target.
// target is any assignable expression, so one function serves fields and array
// elements alike.
func (e *firestoreEmitter) encodeInto(target, source string, t FirestoreType, noIndex bool, indent string) error {
	wrap := func(expr string) string {
		if noIndex {
			return fmt.Sprintf("datastore.Unindexed(%s)", expr)
		}
		return expr
	}
	if expr, ok := firestoreScalarEncode(source, t); ok {
		fmt.Fprintf(&e.body, "%s%s = %s\n", indent, target, wrap(expr))
		return nil
	}
	switch t.Kind {
	case FirestoreStruct:
		fmt.Fprintf(&e.body, "%s%s = %s\n", indent, target, wrap(fmt.Sprintf("datastore.Nested(%s.EncodeEntity())", source)))

	case FirestorePointer:
		fmt.Fprintf(&e.body, "%sif %s == nil {\n", indent, source)
		fmt.Fprintf(&e.body, "%s\t%s = %s\n", indent, target, wrap("datastore.Null()"))
		fmt.Fprintf(&e.body, "%s} else {\n", indent)
		if err := e.encodeInto(target, "(*"+source+")", *t.Elem, noIndex, indent+"\t"); err != nil {
			return err
		}
		fmt.Fprintf(&e.body, "%s}\n", indent)

	case FirestoreArray:
		name := e.temp("array")
		element := e.temp("element")
		fmt.Fprintf(&e.body, "%s%s := make([]datastore.Value, 0, len(%s))\n", indent, name, source)
		fmt.Fprintf(&e.body, "%sfor _, member := range %s {\n", indent, source)
		if err := e.encodeElement(element, "member", *t.Elem, indent+"\t"); err != nil {
			return err
		}
		fmt.Fprintf(&e.body, "%s\t%s = append(%s, %s)\n", indent, name, name, element)
		fmt.Fprintf(&e.body, "%s}\n", indent)
		// excludeFromIndexes on an array applies to its elements, so the wrap
		// goes on the array value as it does on a scalar.
		fmt.Fprintf(&e.body, "%s%s = %s\n", indent, target, wrap(fmt.Sprintf("datastore.Array(%s...)", name)))

	default:
		return fmt.Errorf("no encoder for property kind %s", t.Kind)
	}
	return nil
}

// encodeElement declares one array member's value. A scalar is one expression
// and needs no separate declaration; anything else is filled in by statements,
// so it is declared first.
func (e *firestoreEmitter) encodeElement(name, source string, t FirestoreType, indent string) error {
	if expr, ok := firestoreScalarEncode(source, t); ok {
		fmt.Fprintf(&e.body, "%s%s := %s\n", indent, name, expr)
		return nil
	}
	fmt.Fprintf(&e.body, "%svar %s datastore.Value\n", indent, name)
	return e.encodeInto(name, source, t, false, indent)
}

// firestoreScalarEncode returns the one-expression encoding of a scalar.
func firestoreScalarEncode(source string, t FirestoreType) (string, bool) {
	switch t.Kind {
	case FirestoreString:
		return fmt.Sprintf("datastore.String(string(%s))", source), true
	case FirestoreInt, FirestoreUint:
		return fmt.Sprintf("datastore.Int(%s)", source), true
	case FirestoreDouble:
		return fmt.Sprintf("datastore.Float(float64(%s))", source), true
	case FirestoreBool:
		return fmt.Sprintf("datastore.Bool(bool(%s))", source), true
	case FirestoreBlob:
		return fmt.Sprintf("datastore.Blob([]byte(%s))", source), true
	case FirestoreTime:
		return fmt.Sprintf("datastore.Time(%s)", source), true
	case FirestoreKeyRef:
		return fmt.Sprintf("datastore.KeyValue(%s)", source), true
	case FirestoreGeo:
		return fmt.Sprintf("datastore.GeoPoint(%s.Latitude, %s.Longitude)", source, source), true
	case FirestoreRaw:
		return source, true
	default:
		return "", false
	}
}
