package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"

	"github.com/shibukawa/tinybind-go/parser"
	"golang.org/x/tools/go/packages"
)

// Route registration for the derived backend.
//
// fasthttp has no router of its own, so the generated registration installs on
// one the application supplies. Which router that is stays configuration, for
// the same reason the import rewrites are: this module should not decide which
// third-party package an application depends on.
//
// The pattern syntax needs almost no translation. fasthttp/router spells a
// named parameter {name}, exactly as net/http's ServeMux does, and stores it
// with SetUserValue, which is where PathValue reads. Only the catch-all differs.

// RouterTarget names the router generated registration installs on.
type RouterTarget struct {
	// Import is the package supplying the router, and Qualifier the name the
	// generated file refers to it by.
	Import    string
	Qualifier string
	// Type is the parameter type of the generated registration function,
	// written verbatim so an interface needs no pointer.
	Type string
	// RegisterFunc is the name of the generated registration function.
	RegisterFunc string
	// CatchAllSuffix replaces the net/http "..." catch-all marker inside a
	// pattern segment. Empty rejects catch-all routes instead of guessing.
	CatchAllSuffix string
}

// DefaultRouterTarget targets the fasthttp/router fork that tinygodriver
// carries beside its fasthttp fork.
//
// It has to be that one rather than upstream: a handler taking the fork's
// RequestCtx is not a handler taking valyala/fasthttp's, so the upstream router
// will not accept generated code. An application on upstream fasthttp points
// Import at github.com/fasthttp/router instead; the two share an API and a
// pattern syntax, so nothing else in the target changes.
func DefaultRouterTarget() RouterTarget {
	return RouterTarget{
		Import:         "github.com/shibukawa/tinygodriver/fasthttprouter",
		Qualifier:      "router",
		Type:           "*router.Router",
		RegisterFunc:   "RegisterRoutes",
		CatchAllSuffix: ":*",
	}
}

func (t RouterTarget) normalized() (RouterTarget, error) {
	if t.Import == "" || t.Qualifier == "" || t.Type == "" {
		return t, fmt.Errorf("generator: router target needs an import, a qualifier and a type")
	}
	if t.RegisterFunc == "" {
		t.RegisterFunc = "RegisterRoutes"
	}
	return t, nil
}

// routePattern converts a discovered net/http pattern to the router's spelling.
// A catch-all is the only segment shape that moves.
func (t RouterTarget) routePattern(path string) (string, error) {
	if !strings.Contains(path, "...") {
		return path, nil
	}
	if t.CatchAllSuffix == "" {
		return "", fmt.Errorf("catch-all pattern %q has no equivalent on this router", path)
	}
	segments := strings.Split(path, "/")
	for i, segment := range segments {
		if !strings.HasPrefix(segment, "{") || !strings.HasSuffix(segment, "}") {
			continue
		}
		name := strings.TrimSuffix(strings.TrimPrefix(segment, "{"), "}")
		if !strings.HasSuffix(name, "...") {
			continue
		}
		segments[i] = "{" + strings.TrimSuffix(name, "...") + t.CatchAllSuffix + "}"
	}
	return strings.Join(segments, "/"), nil
}

// emitRouteRegistration writes the function that installs every discovered
// route on the caller's router. It is emitted into the backend's tagged file
// set, so the net/http build never sees it.
func emitRouteRegistration(pkg *packages.Package, routes []parser.Route, target RouterTarget, transform transportTarget) ([]byte, error) {
	target, err := target.normalized()
	if err != nil {
		return nil, err
	}
	registered := make([]parser.Route, 0, len(routes))
	for _, route := range routes {
		if route.Handler.Name == "" || route.Method == "" || route.Path == "" {
			// A handler the analysis could not name has no address to register.
			continue
		}
		registered = append(registered, route)
	}
	if len(registered) == 0 {
		return nil, nil
	}
	sort.SliceStable(registered, func(i, j int) bool {
		if registered[i].Path != registered[j].Path {
			return registered[i].Path < registered[j].Path
		}
		return registered[i].Method < registered[j].Method
	})

	var b bytes.Buffer
	b.WriteString("// Code generated by tinybind; DO NOT EDIT.\n\n")
	if transform.buildTag != "" {
		fmt.Fprintf(&b, "//go:build %s\n\n", transform.buildTag)
	}
	fmt.Fprintf(&b, "package %s\n\n", pkg.Name)
	fmt.Fprintf(&b, "import %s %s\n\n", target.Qualifier, strconv.Quote(target.Import))
	fmt.Fprintf(&b, "// %s installs every route this package declares.\n", target.RegisterFunc)
	fmt.Fprintf(&b, "//\n")
	fmt.Fprintf(&b, "// The patterns are the ones the net/http source registers, unchanged where\n")
	fmt.Fprintf(&b, "// the two routers spell a parameter the same way.\n")
	fmt.Fprintf(&b, "func %s(r %s) {\n", target.RegisterFunc, target.Type)
	for _, route := range registered {
		pattern, err := target.routePattern(route.Path)
		if err != nil {
			return nil, err
		}
		fmt.Fprintf(&b, "\tr.Handle(%s, %s, %s)\n",
			strconv.Quote(route.Method), strconv.Quote(pattern), route.Handler.Name)
	}
	b.WriteString("}\n")

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return b.Bytes(), fmt.Errorf("format generated route registration: %w\n%s", err, b.String())
	}
	return formatted, nil
}

// transportRoutesArtifacts installs the derived handlers on the caller's
// router. The authored net/http wiring lives in a file the build tag excludes,
// so a package generated through the artifact API without this one compiles
// and serves nothing.
func (g *Generator) transportRoutesArtifacts(load *packageLoad) ([]Artifact, error) {
	if g.Options.Transform == nil {
		return nil, nil
	}
	transform, err := g.transformOptions().normalized()
	if err != nil {
		return nil, err
	}
	pkg, err := load.get()
	if err != nil {
		return nil, err
	}
	normalized, err := g.Options.normalized()
	if err != nil {
		return nil, err
	}
	result, err := parser.ParseLoadedPackage(pkg, normalized.parserConfig)
	if err != nil {
		return nil, err
	}
	code, err := emitRouteRegistration(pkg, result.Routes, transform.Router, fasthttpTarget())
	if err != nil || code == nil {
		return nil, err
	}
	return []Artifact{{
		Kind:        ArtifactTransportRoutes,
		Destination: DestinationGoPackage,
		OutputBase:  transportRoutesArtifactBase,
		Extension:   ExtensionGo,
		PackageName: pkg.Name,
		Content:     code,
	}}, nil
}
