package routetree

import (
	"bytes"
	"embed"
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"
	"text/template"
)

// GeneratedHeader is the first line of every file this package emits.
const GeneratedHeader = "// Code generated by tinybind; DO NOT EDIT."

// Names of the symbols the default templates produce in a route package.
const (
	RouteParamsType = "RouteParams"
	DecodeRouteFunc = "DecodeRoute"
)

// Error codes the default decoder template reports.
const (
	CodeInvalidPath    = "invalid_path_parameter"
	CodeInvalidQuery   = "invalid_query_parameter"
	CodeMissingPath    = "missing_path_parameter"
	defaultErrorImport = "github.com/shibukawa/tinybind-go"
)

// TemplateDecoder is the name of the template that renders a route decoder.
// Pass it to [Emitter.Parse] to replace the emitted shape.
const TemplateDecoder = "decoder"

//go:embed templates/*.tmpl
var defaultTemplates embed.FS

// Symbols names the identities generated code calls. Repointing them is the
// cheap half of customization: a framework that only wants its own error
// constructor changes these and keeps every default template.
type Symbols struct {
	// HTTPImport and HTTPAlias name the package providing Request and
	// PathValue. The alias is what generated source writes.
	HTTPImport string
	HTTPAlias  string
	// MuxImport and MuxAlias name the package providing the router the registry
	// installs on. They are separate from the pair above because the same alias
	// would otherwise supply both the router and Request: a framework wanting
	// only its own router would drag the request package along with it and be
	// left replacing the whole registry template.
	MuxImport string
	MuxAlias  string
	// MuxType is the router type the generated registration function takes, and
	// MuxConstructor the call that builds one. Both are written verbatim, so a
	// framework whose router is an interface writes no pointer. An empty
	// MuxConstructor omits the constructor function, which is what a router
	// needing arguments generated code cannot supply wants.
	//
	// Generated code registers through HandleFunc alone, so a one-method
	// interface is enough to satisfy either.
	MuxType        string
	MuxConstructor string
	// ErrorImport and ErrorAlias name the package providing the constructors
	// below. An empty ErrorImport suppresses the import, which is what a
	// template that reports errors some other way wants.
	ErrorImport string
	ErrorAlias  string
	// BadRequest and Problem are selectors on ErrorAlias.
	BadRequest string
	Problem    string
	// StrconvImport is the package providing the scalar parsers. It is only
	// imported when a route actually declares a non-string input.
	StrconvImport string
	StrconvAlias  string
	// RuntimeImport and RuntimeAlias name the HTML rendering runtime the
	// composer calls.
	RuntimeImport string
	RuntimeAlias  string
}

// DefaultSymbols targets the httpbind runtime this module ships.
func DefaultSymbols() Symbols {
	return Symbols{
		HTTPImport:     "net/http",
		HTTPAlias:      "http",
		MuxImport:      "net/http",
		MuxAlias:       "http",
		MuxType:        "*http.ServeMux",
		MuxConstructor: "http.NewServeMux",

		ErrorImport:   defaultErrorImport,
		ErrorAlias:    "httpbind",
		BadRequest:    "BadRequest",
		Problem:       "Problem",
		StrconvImport: "strconv",
		StrconvAlias:  "strconv",
		RuntimeImport: defaultErrorImport + "/htmlbind",
		RuntimeAlias:  "htmlbind",
	}
}

// Emitter renders generated Go source. Its zero value is not usable; build one
// with [NewEmitter].
type Emitter struct {
	// Symbols are the identities the templates call.
	Symbols Symbols
	// ParamsType, DecodeFunc, and RenderFunc name the generated declarations, so
	// a framework can publish its own vocabulary without replacing a template.
	ParamsType   string
	DecodeFunc   string
	RenderFunc   string
	RegisterFunc string
	MuxFunc      string
	TableVar     string
	// RenderWriterType is the writer the generated composer takes. Empty uses
	// [DefaultRenderWriterType], which is what keeps a rung 3 handler free to
	// render into a buffer. It must be qualified by io, by Symbols.HTTPAlias, or
	// by Symbols.RuntimeAlias, because those are the packages the composer
	// imports.
	RenderWriterType string
	// RenderRequestParam adds a request parameter to the generated composer under
	// this name, so a "render" block override has the request in scope there as
	// well as in the registry handler. Empty declares none.
	//
	// It is off by default because the composer's contract is a writer: a handler
	// rendering into a buffer to choose its status has no response to hand over.
	RenderRequestParam string
	// ActionPrefix is the reserved path every server function endpoint hangs
	// below. Empty uses [DefaultActionPrefix]. A framework mounting under a
	// sub-path or owning its own URL namespace sets it, which is why it is not
	// the fixed value the endpoint hash is.
	ActionPrefix string
	// ActionTableVar names the generated list of endpoints. Every server
	// function is reachable whether or not a template references it, so the
	// list is what makes that surface inspectable.
	ActionTableVar string
	// ActionAttr is the attribute a lowered server-action writes in compiled
	// templates. Empty uses the htmlbind default.
	ActionAttr string

	tmpl *template.Template
}

// NewEmitter returns an emitter with the built-in templates and the httpbind
// symbols.
func NewEmitter() *Emitter {
	tmpl := template.Must(template.New("routetree").Funcs(templateFuncs()).ParseFS(defaultTemplates, "templates/*.tmpl"))
	// ParseFS names each template after its file, so alias every one to the
	// stable name callers override.
	for stable, file := range map[string]string{
		TemplateDecoder:  "decoder.go.tmpl",
		TemplateComposer: "composer.go.tmpl",
		TemplateRegistry: "registry.go.tmpl",
	} {
		tmpl = template.Must(tmpl.AddParseTree(stable, tmpl.Lookup(file).Tree))
	}
	return &Emitter{
		Symbols:          DefaultSymbols(),
		ParamsType:       RouteParamsType,
		DecodeFunc:       DecodeRouteFunc,
		RenderFunc:       RenderFunc,
		RenderWriterType: DefaultRenderWriterType,
		RegisterFunc:     RegisterFunc,
		MuxFunc:          MuxFunc,
		TableVar:         TableVar,
		ActionPrefix:     DefaultActionPrefix,
		ActionTableVar:   ActionTableVar,
		tmpl:             tmpl,
	}
}

// Parse replaces one named template. It returns an error when the text does not
// parse, leaving the emitter unchanged.
//
// The replacement is compiled into a copy of the template set, so a framework
// may override the whole file shape with [TemplateDecoder] or only one nested
// block such as "error", "convert", or [TemplateRender].
func (e *Emitter) Parse(name, text string) error {
	clone, err := e.tmpl.Clone()
	if err != nil {
		return err
	}
	if _, err := clone.New(name).Parse(text); err != nil {
		return fmt.Errorf("routetree: template %q: %w", name, err)
	}
	e.tmpl = clone
	return nil
}

// Clone returns an independent emitter, so one configured base can be
// specialized per generation run without sharing template state.
func (e *Emitter) Clone() (*Emitter, error) {
	tmpl, err := e.tmpl.Clone()
	if err != nil {
		return nil, err
	}
	out := *e
	out.tmpl = tmpl
	return &out, nil
}

// templateFuncs are the helpers the built-in templates use. They are available
// to an override too.
func templateFuncs() template.FuncMap {
	return template.FuncMap{
		"quote": strconv.Quote,
		// dict builds a map so a nested template can receive more than one
		// value, which Go templates otherwise cannot express.
		"dict": func(pairs ...any) (map[string]any, error) {
			if len(pairs)%2 != 0 {
				return nil, fmt.Errorf("dict: odd argument count %d", len(pairs))
			}
			out := make(map[string]any, len(pairs)/2)
			for i := 0; i < len(pairs); i += 2 {
				key, ok := pairs[i].(string)
				if !ok {
					return nil, fmt.Errorf("dict: key %d is %T, want string", i, pairs[i])
				}
				out[key] = pairs[i+1]
			}
			return out, nil
		},
	}
}

// Import is one import line of a generated file.
type Import struct {
	Path  string
	Alias string
	// Group starts a new import group before this line, which is how the
	// standard library and the runtime end up separated.
	Group bool
}

// DecoderField is one input of a generated decoder, already lowered to
// everything the template needs to write it out.
type DecoderField struct {
	// Go is the generated struct field name.
	Go string
	// Key is the path wildcard or query key it reads.
	Key string
	// Type is the declared Go type, which is a pointer when the input is
	// optional.
	Type string
	// Base is Type with the optional pointer removed, so it is the scalar the
	// parse call and the diagnostics name.
	Base string
	// Optional binds a pointer, left nil when the key is absent or its value is
	// empty. It is set for a query parameter only.
	Optional bool
	// IsQuery reads from the query string rather than the path.
	IsQuery bool
	// Required rejects an empty value. A catch-all is not required, because an
	// empty remainder is a legal match.
	Required bool
	// Parse is the call that converts raw into v, empty for a string.
	Parse string
	// Convert narrows the parse result, empty when the types already agree.
	Convert string
	// ErrCode and ErrMessage describe the failure of Parse.
	ErrCode    string
	ErrMessage string
	// MissingMessage describes an absent required path value.
	MissingMessage string
}

// DecoderModel is the data the decoder template renders.
type DecoderModel struct {
	Header      string
	Package     string
	Pattern     string
	Imports     []Import
	ParamsType  string
	DecodeFunc  string
	Fields      []DecoderField
	HasQuery    bool
	MissingCode string
	Symbols     Symbols
}

// EmitDecoder renders the typed route decoder for one route using the default
// emitter. See [Emitter.Decoder] to customize the output.
func EmitDecoder(route Route, inputs []Value) ([]byte, error) {
	return NewEmitter().Decoder(route, inputs)
}

// Decoder renders the typed route decoder for one route.
//
// inputs is the page's declared input list: the route's dynamic segments in
// order, followed by the query parameters. It is the component parameter list
// at RungTemplateOnly and the func Page parameter list at RungTypedPage. The
// caller has already checked the shape with [Validate]; Decoder assumes it.
func (e *Emitter) Decoder(route Route, inputs []Value) ([]byte, error) {
	model, err := e.decoderModel(route, inputs)
	if err != nil {
		return nil, err
	}
	var raw bytes.Buffer
	if err := e.tmpl.ExecuteTemplate(&raw, TemplateDecoder, model); err != nil {
		return nil, fmt.Errorf("routetree: rendering %s: %w", TemplateDecoder, err)
	}
	source, err := format.Source(raw.Bytes())
	if err != nil {
		return nil, fmt.Errorf("routetree: template %q produced unparsable Go for %s: %w\n%s",
			TemplateDecoder, route.Path, err, raw.String())
	}
	return source, nil
}

func (e *Emitter) decoderModel(route Route, inputs []Value) (DecoderModel, error) {
	if len(inputs) < len(route.Params) {
		return DecoderModel{}, &Error{
			Path: route.PageFile,
			Message: fmt.Sprintf("route %s binds %d path parameter(s) but only %d input(s) were declared",
				route.Path, len(route.Params), len(inputs)),
		}
	}

	fields := make([]DecoderField, 0, len(inputs))
	for i, input := range inputs {
		base, optional, _ := bindableType(input.Type)
		field := DecoderField{
			Go:       ExportedName(input.Name),
			Type:     input.Type,
			Base:     base,
			Optional: optional,
		}
		if i < len(route.Params) {
			segment := route.Params[i]
			if optional {
				return DecoderModel{}, &Error{
					Path:    route.PageFile,
					Message: optionalPathError(input.Name, input.Type, segment.Kind == CatchAllSegment),
				}
			}
			field.Key = segment.Name
			// A catch-all matches an empty remainder, so only a single-element
			// wildcard is required to be present.
			field.Required = segment.Kind != CatchAllSegment
			field.ErrCode = CodeInvalidPath
			field.ErrMessage = "path parameter " + field.Key + " is not a valid " + base
			field.MissingMessage = "missing path parameter " + field.Key
		} else {
			field.Key = input.Name
			field.IsQuery = true
			field.ErrCode = CodeInvalidQuery
			field.ErrMessage = "query parameter " + field.Key + " is not a valid " + base
		}
		if base != "string" {
			parse, ok := parseCall(e.Symbols.StrconvAlias, base)
			if !ok {
				return DecoderModel{}, &Error{
					Path: route.PageFile,
					Message: fmt.Sprintf("input %q has type %s, which no generated decoder can bind from a URL",
						input.Name, input.Type),
				}
			}
			field.Parse = parse
			field.Convert, _ = resultConversion(base)
		}
		fields = append(fields, field)
	}
	if err := checkFieldNames(route, fields); err != nil {
		return DecoderModel{}, err
	}

	model := DecoderModel{
		Header:      GeneratedHeader,
		Package:     route.Package,
		Pattern:     route.Pattern(),
		ParamsType:  e.ParamsType,
		DecodeFunc:  e.DecodeFunc,
		Fields:      fields,
		MissingCode: CodeMissingPath,
		Symbols:     e.Symbols,
	}
	for _, field := range fields {
		if field.IsQuery {
			model.HasQuery = true
			break
		}
	}
	model.Imports = e.decoderImports(fields)
	return model, nil
}

// decoderImports lists only what the emitted body actually references, so a
// route with no scalar inputs does not import strconv.
func (e *Emitter) decoderImports(fields []DecoderField) []Import {
	imports := []Import{{Path: e.Symbols.HTTPImport, Alias: aliasFor(e.Symbols.HTTPImport, e.Symbols.HTTPAlias)}}
	needsParse, needsError := false, false
	for _, field := range fields {
		if field.Parse != "" {
			needsParse = true
			needsError = true
		}
		if field.Required {
			needsError = true
		}
	}
	if needsParse && e.Symbols.StrconvImport != "" {
		imports = append(imports, Import{
			Path:  e.Symbols.StrconvImport,
			Alias: aliasFor(e.Symbols.StrconvImport, e.Symbols.StrconvAlias),
		})
	}
	if needsError && e.Symbols.ErrorImport != "" {
		imports = append(imports, Import{
			Path:  e.Symbols.ErrorImport,
			Alias: aliasFor(e.Symbols.ErrorImport, e.Symbols.ErrorAlias),
			// The runtime is not standard library, so it gets its own group.
			Group: true,
		})
	}
	return imports
}

// aliasFor omits an alias that matches the last path element, which is what a
// Go author would write.
func aliasFor(path, alias string) string {
	if alias == "" || alias == path[strings.LastIndex(path, "/")+1:] {
		return ""
	}
	return alias
}

// checkFieldNames rejects two inputs that would become one struct field, which
// go/format would otherwise report as a redeclaration far from its cause.
func checkFieldNames(route Route, fields []DecoderField) error {
	seen := make(map[string]string, len(fields))
	var collisions []string
	for _, f := range fields {
		if first, ok := seen[f.Go]; ok {
			collisions = append(collisions, fmt.Sprintf("%q and %q both become field %s", first, f.Key, f.Go))
			continue
		}
		seen[f.Go] = f.Key
	}
	if len(collisions) == 0 {
		return nil
	}
	sort.Strings(collisions)
	return &Error{
		Path:    route.PageFile,
		Message: fmt.Sprintf("route %s has colliding input names: %s", route.Path, strings.Join(collisions, "; ")),
	}
}

// parseCall returns the call that reads one scalar, and whether the type is
// supported at all.
func parseCall(alias, goType string) (string, bool) {
	switch goType {
	case "bool":
		return alias + ".ParseBool(raw)", true
	case "int":
		return alias + ".Atoi(raw)", true
	case "int8", "int16", "int32", "int64":
		return fmt.Sprintf("%s.ParseInt(raw, 10, %s)", alias, bitSize(goType)), true
	case "uint", "uint8", "uint16", "uint32", "uint64":
		return fmt.Sprintf("%s.ParseUint(raw, 10, %s)", alias, bitSize(goType)), true
	case "float32", "float64":
		return fmt.Sprintf("%s.ParseFloat(raw, %s)", alias, bitSize(goType)), true
	default:
		return "", false
	}
}

// resultConversion reports the narrowing conversion a parse result needs,
// because ParseInt returns int64 whatever bit size it was asked for.
func resultConversion(goType string) (string, bool) {
	switch goType {
	case "bool", "int", "int64", "uint64", "float64":
		return "", false
	default:
		return goType, true
	}
}

func bitSize(goType string) string {
	switch goType {
	case "int8", "uint8":
		return "8"
	case "int16", "uint16":
		return "16"
	case "int32", "uint32", "float32":
		return "32"
	case "uint":
		return "64"
	default:
		return "64"
	}
}

// commonInitialisms are rendered in full caps in a Go field name, matching the
// convention the standard library and every Go linter expect.
var commonInitialisms = map[string]bool{
	"ACL": true, "API": true, "ASCII": true, "CPU": true, "CSS": true, "DNS": true,
	"EOF": true, "GUID": true, "HTML": true, "HTTP": true, "HTTPS": true, "ID": true,
	"IP": true, "JSON": true, "LHS": true, "QPS": true, "RAM": true, "RHS": true,
	"RPC": true, "SLA": true, "SMTP": true, "SQL": true, "SSH": true, "TCP": true,
	"TLS": true, "TTL": true, "UDP": true, "UI": true, "UID": true, "UUID": true,
	"URI": true, "URL": true, "UTF8": true, "VM": true, "XML": true, "XMPP": true,
	"XSRF": true, "XSS": true,
}

// ExportedName converts a declared input name to its generated struct field
// name. It splits on underscores and case boundaries so id, user_id, and
// userID all reach the field a Go author would have written by hand.
func ExportedName(name string) string {
	var b strings.Builder
	for _, word := range splitWords(name) {
		upper := strings.ToUpper(word)
		if commonInitialisms[upper] {
			b.WriteString(upper)
			continue
		}
		b.WriteString(strings.ToUpper(word[:1]))
		if len(word) > 1 {
			b.WriteString(strings.ToLower(word[1:]))
		}
	}
	return b.String()
}

// splitWords breaks an identifier into words at underscores and at lower-to-
// upper case boundaries.
func splitWords(name string) []string {
	var words []string
	var current strings.Builder
	flush := func() {
		if current.Len() > 0 {
			words = append(words, current.String())
			current.Reset()
		}
	}
	runes := []rune(name)
	for i, r := range runes {
		if r == '_' || r == '-' {
			flush()
			continue
		}
		if i > 0 && isUpper(r) && !isUpper(runes[i-1]) {
			flush()
		}
		current.WriteRune(r)
	}
	flush()
	return words
}

func isUpper(r rune) bool { return r >= 'A' && r <= 'Z' }
