// Code generated by tinybind HTML templates; DO NOT EDIT.

package pages

import (
	"github.com/shibukawa/tinybind-go/htmlbind"
)

type LayoutParams struct {
	Children htmlbind.Fragment
}

var planLayoutOps = htmlbind.Builder[LayoutParams]{}

var planLayoutPlan = &htmlbind.Plan[LayoutParams]{
	Head: nil,
	Ops: []htmlbind.Op[LayoutParams]{
		planLayoutOps.Static(" <div id=\"shell\">"),
		planLayoutOps.Slot(func(p LayoutParams) htmlbind.Fragment { return p.Children },
			nil),
		planLayoutOps.Static("</div> "),
	},
}

// Layout binds Layout to its parameters, producing a renderable fragment.
func Layout(params LayoutParams) htmlbind.Fragment { return htmlbind.Bind(planLayoutPlan, params) }

// BindLayout binds Layout as a chain wrapper filling its unnamed slot.
func BindLayout(params LayoutParams) htmlbind.Wrapper {
	return htmlbind.BindWrapper(planLayoutPlan, params, func(target *LayoutParams, children htmlbind.Fragment) { target.Children = children })
}
