// Code generated by tinybind; DO NOT EDIT.

package pages

import (
	"net/http"

	httpbind "github.com/shibukawa/tinybind-go"
	"github.com/shibukawa/tinybind-go/htmlbind"
	"github.com/shibukawa/tinybind-go/internal/pagesfixture/pages/about"
	"github.com/shibukawa/tinybind-go/internal/pagesfixture/pages/users/id_"
)

// Register installs every discovered route on mux.
//
// Options are passed to the runtime on each render, so a caller supplies its
// per-request cache, timeout, and error hook here.
func Register(mux *http.ServeMux, options ...htmlbind.Option) {
	mux.HandleFunc("GET /{$}",
		func(w http.ResponseWriter, r *http.Request) {
			route, err := DecodeRoute(r)
			if err != nil {
				httpbind.WriteError(w, r, err)
				return
			}
			_ = route // a route with no dynamic segment and no query input reads nothing
			params := PageParams{}
			wrappers := []htmlbind.Wrapper{
				BindLayout(LayoutParams{}),
			}
			if err := htmlbind.RenderChain(w, wrappers, Page(params), options...); err != nil {
				httpbind.WriteError(w, r, err)
			}
		})
	mux.HandleFunc("GET /about",
		func(w http.ResponseWriter, r *http.Request) {
			route, err := about.DecodeRoute(r)
			if err != nil {
				httpbind.WriteError(w, r, err)
				return
			}
			_ = route // a route with no dynamic segment and no query input reads nothing
			params := about.PageParams{
				Topic: route.Topic,
			}
			wrappers := []htmlbind.Wrapper{
				BindLayout(LayoutParams{}),
			}
			if err := htmlbind.RenderChain(w, wrappers, about.Page(params), options...); err != nil {
				httpbind.WriteError(w, r, err)
			}
		})
	mux.HandleFunc("GET /users/{id}",
		func(w http.ResponseWriter, r *http.Request) {
			route, err := id_.DecodeRoute(r)
			if err != nil {
				httpbind.WriteError(w, r, err)
				return
			}
			_ = route // a route with no dynamic segment and no query input reads nothing
			pageName, err := id_.Load(route.ID)
			if err != nil {
				httpbind.WriteError(w, r, err)
				return
			}
			params := id_.PageParams{
				Name: pageName,
			}
			wrappers := []htmlbind.Wrapper{
				BindLayout(LayoutParams{}),
			}
			if err := htmlbind.RenderChain(w, wrappers, id_.Page(params), options...); err != nil {
				httpbind.WriteError(w, r, err)
			}
		})
}

// NewServeMux returns a ServeMux carrying every discovered route.
func NewServeMux(options ...htmlbind.Option) *http.ServeMux {
	mux := http.NewServeMux()
	Register(mux, options...)
	return mux
}

// Routes lists what the filesystem knows about each route, so a
// framework can build a sitemap or an inspector without a metadata format.
var Routes = []RouteInfo{
	{Pattern: "GET /{$}", Path: "/", Dir: "", Params: nil},
	{Pattern: "GET /about", Path: "/about", Dir: "about", Params: nil},
	{Pattern: "GET /users/{id}", Path: "/users/{id}", Dir: "users/id_", Params: []string{"id"}},
}

// RouteInfo is one entry of Routes.
type RouteInfo struct {
	// Pattern is the stdlib ServeMux pattern the route is registered under.
	Pattern string
	// Path is the pattern without its method.
	Path string
	// Dir is the route directory relative to the route root.
	Dir string
	// Params names the dynamic segments, in route order.
	Params []string
}
