// Code generated by tinybind; DO NOT EDIT.

package pages

import (
	"net/http"

	httpbind "github.com/shibukawa/tinybind-go"
	"github.com/shibukawa/tinybind-go/htmlbind"
	"github.com/shibukawa/tinybind-go/internal/pagesfixture/pages/about"
	"github.com/shibukawa/tinybind-go/internal/pagesfixture/pages/archive"
	"github.com/shibukawa/tinybind-go/internal/pagesfixture/pages/users/id_"
)

// Register installs every discovered route on mux.
//
// Options are passed to the runtime on each render, so a caller supplies its
// per-request cache, timeout, and error hook here.
func Register(mux *http.ServeMux, options ...htmlbind.Option) {
	mux.HandleFunc("GET /{$}",
		func(w http.ResponseWriter, r *http.Request) {
			route, err := DecodeRoute(r)
			if err != nil {
				httpbind.WriteError(w, r, err)
				return
			}
			_ = route // a route with no dynamic segment and no query input reads nothing
			params := PageParams{}
			wrappers := []htmlbind.Wrapper{
				BindLayout(LayoutParams{}),
			}
			if err := htmlbind.RenderChain(w, wrappers, Page(params), append(options[:len(options):len(options)], htmlbind.WithContext(r.Context()))...); err != nil {
				httpbind.WriteError(w, r, err)
			}
		})
	mux.HandleFunc("GET /about",
		func(w http.ResponseWriter, r *http.Request) {
			route, err := about.DecodeRoute(r)
			if err != nil {
				httpbind.WriteError(w, r, err)
				return
			}
			_ = route // a route with no dynamic segment and no query input reads nothing
			params := about.PageParams{
				Topic: route.Topic,
				Page:  route.Page,
			}
			wrappers := []htmlbind.Wrapper{
				BindLayout(LayoutParams{}),
			}
			if err := htmlbind.RenderChain(w, wrappers, about.Page(params), append(options[:len(options):len(options)], htmlbind.WithContext(r.Context()))...); err != nil {
				httpbind.WriteError(w, r, err)
			}
		})
	mux.HandleFunc("GET /archive",
		func(w http.ResponseWriter, r *http.Request) {
			route, err := archive.DecodeRoute(r)
			if err != nil {
				httpbind.WriteError(w, r, err)
				return
			}
			_ = route // a route with no dynamic segment and no query input reads nothing
			pageLatest, err := archive.Load(r.Context())
			if err != nil {
				httpbind.WriteError(w, r, err)
				return
			}
			params := archive.PageParams{
				Latest: pageLatest,
			}
			wrappers := []htmlbind.Wrapper{
				BindLayout(LayoutParams{}),
			}
			if err := htmlbind.RenderChain(w, wrappers, archive.Page(params), append(options[:len(options):len(options)], htmlbind.WithContext(r.Context()))...); err != nil {
				httpbind.WriteError(w, r, err)
			}
		})
	mux.HandleFunc("GET /users/{id}",
		func(w http.ResponseWriter, r *http.Request) {
			route, err := id_.DecodeRoute(r)
			if err != nil {
				httpbind.WriteError(w, r, err)
				return
			}
			_ = route // a route with no dynamic segment and no query input reads nothing
			pageName, err := id_.Load(route.ID)
			if err != nil {
				httpbind.WriteError(w, r, err)
				return
			}
			params := id_.PageParams{
				Name: pageName,
			}
			wrappers := []htmlbind.Wrapper{
				BindLayout(LayoutParams{}),
			}
			if err := htmlbind.RenderChain(w, wrappers, id_.Page(params), append(options[:len(options):len(options)], htmlbind.WithContext(r.Context()))...); err != nil {
				httpbind.WriteError(w, r, err)
			}
		})

	// Server function endpoints. Each handler owns its whole response, so
	// nothing is generated around it; registration is all there is.
	mux.HandleFunc("POST /_action/00369cf962b6/Rename", id_.Rename)
}

// NewServeMux returns a router carrying every discovered route.
func NewServeMux(options ...htmlbind.Option) *http.ServeMux {
	mux := http.NewServeMux()
	Register(mux, options...)
	return mux
}

// Routes lists what the filesystem knows about each route, so a
// framework can build a sitemap or an inspector without a metadata format.
var Routes = []RouteInfo{
	{Pattern: "GET /{$}", Path: "/", Dir: "", Params: nil},
	{Pattern: "GET /about", Path: "/about", Dir: "about", Params: nil},
	{Pattern: "GET /archive", Path: "/archive", Dir: "archive", Params: nil},
	{Pattern: "GET /users/{id}", Path: "/users/{id}", Dir: "users/id_", Params: []string{"id"}},
}

// RouteInfo is one entry of Routes.
type RouteInfo struct {
	// Pattern is the stdlib ServeMux pattern the route is registered under.
	Pattern string
	// Path is the pattern without its method.
	Path string
	// Dir is the route directory relative to the route root.
	Dir string
	// Params names the dynamic segments, in route order.
	Params []string
}

// Actions lists every server function endpoint. Every exported
// handler in a route package is reachable whether or not a template references
// it, so this is what makes that surface inspectable.
//
// An endpoint grants nothing: the path hides structure but is not a capability
// token, so each handler still authenticates and authorizes its own caller.
var Actions = []ActionInfo{
	{Pattern: "POST /_action/00369cf962b6/Rename", Path: "/_action/00369cf962b6/Rename", Dir: "users/id_", Handler: "Rename", Hash: "00369cf962b6"},
}

// ActionInfo is one entry of Actions.
type ActionInfo struct {
	// Pattern is the stdlib ServeMux pattern the endpoint is registered under.
	Pattern string
	// Path is the pattern without its method.
	Path string
	// Dir is the declaring package's directory relative to the route root.
	Dir string
	// Handler is the exported Go function name.
	Handler string
	// Hash is the stable half of the path.
	Hash string
}
