// Code generated by tinybind HTML templates; DO NOT EDIT.

package pages

import (
	"context"

	"github.com/shibukawa/tinybind-go/htmlbind"
	"github.com/shibukawa/tinybind-go/htmlbind/delta"
)

type Point struct {
	Label string
	Value int
}

type GaugeParams struct {
	Id string
}

type ChatParams struct {
	Room string
}

type DashboardParams struct {
	Id string
}

type MixedParams struct {
	Id string
}

type StaticParams struct {
	Id string
}

type planGaugeOpsAwait1 struct {
	Outer GaugeParams
	Point Point
}

var planGaugeOpsAwait1Ops = htmlbind.Builder[planGaugeOpsAwait1]{}

type planGaugeOpsAwait1Recover struct {
	Outer GaugeParams
	Err   htmlbind.AsyncError
}

var planGaugeOpsAwait1RecoverOps = htmlbind.Builder[planGaugeOpsAwait1Recover]{}

type planChatOpsAwait2 struct {
	Outer    ChatParams
	Messages []string
}

var planChatOpsAwait2Ops = htmlbind.Builder[planChatOpsAwait2]{}

type planChatOpsAwait2Recover struct {
	Outer ChatParams
	Err   htmlbind.AsyncError
}

var planChatOpsAwait2RecoverOps = htmlbind.Builder[planChatOpsAwait2Recover]{}

type planChatOpsAwait2OpsScope3 struct {
	Outer planChatOpsAwait2
	Item  string
	Index int
}

var planChatOpsAwait2OpsScope3Ops = htmlbind.Builder[planChatOpsAwait2OpsScope3]{}

type planDashboardOpsAwait4 struct {
	Outer    DashboardParams
	Point    Point
	Messages []string
}

var planDashboardOpsAwait4Ops = htmlbind.Builder[planDashboardOpsAwait4]{}

type planDashboardOpsAwait4Recover struct {
	Outer DashboardParams
	Err   htmlbind.AsyncError
}

var planDashboardOpsAwait4RecoverOps = htmlbind.Builder[planDashboardOpsAwait4Recover]{}

type planDashboardOpsAwait4OpsScope5 struct {
	Outer planDashboardOpsAwait4
	Item  string
	Index int
}

var planDashboardOpsAwait4OpsScope5Ops = htmlbind.Builder[planDashboardOpsAwait4OpsScope5]{}

type planMixedOpsAwait6 struct {
	Outer MixedParams
	Title string
	Point Point
}

var planMixedOpsAwait6Ops = htmlbind.Builder[planMixedOpsAwait6]{}

type planMixedOpsAwait6Recover struct {
	Outer MixedParams
	Err   htmlbind.AsyncError
}

var planMixedOpsAwait6RecoverOps = htmlbind.Builder[planMixedOpsAwait6Recover]{}

var planGaugeOps = htmlbind.Builder[GaugeParams]{}

// planGaugeInput canonically encodes the declared inputs of Gauge.
// Slot arguments are excluded: their content belongs to the child boundary,
// so a frame stays comparable when only its child changed.
func planGaugeInput(p GaugeParams) string {
	return delta.CanonJoin(
		delta.CanonString[string](p.Id),
	)
}

var planGaugeBoundary = &htmlbind.Boundary[GaugeParams]{
	ComponentID: "pages.input.Gauge",
	Attr:        "data-tb-id",
	Input:       planGaugeInput,
}

var planGaugePlan = &htmlbind.Plan[GaugeParams]{
	Head:          nil,
	Boundary:      planGaugeBoundary,
	HasAwaitBlock: true,
	HasLiveBlock:  true,
	Ops: []htmlbind.Op[GaugeParams]{
		planGaugeOps.Static(" <section"),
		planGaugeOps.BoundaryAttr(),
		planGaugeOps.Static("> "),
		htmlbind.Live(
			func(ctx context.Context, p GaugeParams) []htmlbind.LiveBinding[planGaugeOpsAwait1] {
				return []htmlbind.LiveBinding[planGaugeOpsAwait1]{
					func(deliver func(func(*planGaugeOpsAwait1), error) bool) error {
						for value, err := range WatchMetrics(ctx, p.Id) {
							if !deliver(func(scope *planGaugeOpsAwait1) { scope.Point = value }, err) {
								return nil
							}
						}
						return nil
					},
				}
			},
			func(p GaugeParams) planGaugeOpsAwait1 { return planGaugeOpsAwait1{Outer: p} },
			func(p GaugeParams, err htmlbind.AsyncError) planGaugeOpsAwait1Recover {
				return planGaugeOpsAwait1Recover{Outer: p, Err: err}
			},
			[]htmlbind.Op[planGaugeOpsAwait1]{
				planGaugeOpsAwait1Ops.Static(" <p class=\"value\">"),
				planGaugeOpsAwait1Ops.Text(func(p planGaugeOpsAwait1) string { return p.Point.Label }),
				planGaugeOpsAwait1Ops.Static(": "),
				planGaugeOpsAwait1Ops.Raw(func(p planGaugeOpsAwait1) string { return htmlbind.FormatInt(p.Point.Value) }),
				planGaugeOpsAwait1Ops.Static("</p> "),
			},
			[]htmlbind.Op[GaugeParams]{
				planGaugeOps.Static(" <p class=\"pending\">waiting…</p> "),
			},
			[]htmlbind.Op[planGaugeOpsAwait1Recover]{
				planGaugeOpsAwait1RecoverOps.Static(" <p class=\"failed\">"),
				planGaugeOpsAwait1RecoverOps.Text(func(p planGaugeOpsAwait1Recover) string { return p.Err.Code }),
				planGaugeOpsAwait1RecoverOps.Static("</p> "),
			}),
		planGaugeOps.Static(" </section> "),
	},
}

// Gauge binds Gauge to its parameters, producing a renderable fragment.
func Gauge(params GaugeParams) htmlbind.Fragment { return htmlbind.Bind(planGaugePlan, params) }

var planChatOps = htmlbind.Builder[ChatParams]{}

var planChatPlan = &htmlbind.Plan[ChatParams]{
	Head:          nil,
	HasAwaitBlock: true,
	HasLiveBlock:  true,
	Ops: []htmlbind.Op[ChatParams]{
		planChatOps.Static(" "),
		htmlbind.Live(
			func(ctx context.Context, p ChatParams) []htmlbind.LiveBinding[planChatOpsAwait2] {
				return []htmlbind.LiveBinding[planChatOpsAwait2]{
					func(deliver func(func(*planChatOpsAwait2), error) bool) error {
						for value, err := range WatchMessages(ctx, p.Room) {
							if !deliver(func(scope *planChatOpsAwait2) { scope.Messages = value }, err) {
								return nil
							}
						}
						return nil
					},
				}
			},
			func(p ChatParams) planChatOpsAwait2 { return planChatOpsAwait2{Outer: p} },
			func(p ChatParams, err htmlbind.AsyncError) planChatOpsAwait2Recover {
				return planChatOpsAwait2Recover{Outer: p, Err: err}
			},
			[]htmlbind.Op[planChatOpsAwait2]{
				planChatOpsAwait2Ops.Static(" <ul> "),
				htmlbind.For(
					func(p planChatOpsAwait2) []string { return p.Messages },
					func(p planChatOpsAwait2, item string, index int) planChatOpsAwait2OpsScope3 {
						return planChatOpsAwait2OpsScope3{Outer: p, Item: item, Index: index}
					},
					[]htmlbind.Op[planChatOpsAwait2OpsScope3]{
						planChatOpsAwait2OpsScope3Ops.Static(" <li>"),
						planChatOpsAwait2OpsScope3Ops.Text(func(p planChatOpsAwait2OpsScope3) string { return p.Item }),
						planChatOpsAwait2OpsScope3Ops.Static("</li> "),
					}),
				planChatOpsAwait2Ops.Static(" </ul> "),
			},
			[]htmlbind.Op[ChatParams]{
				planChatOps.Static(" <p>connecting…</p> "),
			},
			nil),
		planChatOps.Static(" "),
	},
}

// Chat binds Chat to its parameters, producing a renderable fragment.
func Chat(params ChatParams) htmlbind.Fragment { return htmlbind.Bind(planChatPlan, params) }

var planDashboardOps = htmlbind.Builder[DashboardParams]{}

var planDashboardPlan = &htmlbind.Plan[DashboardParams]{
	Head:          nil,
	HasAwaitBlock: true,
	HasLiveBlock:  true,
	Ops: []htmlbind.Op[DashboardParams]{
		planDashboardOps.Static(" "),
		htmlbind.Live(
			func(ctx context.Context, p DashboardParams) []htmlbind.LiveBinding[planDashboardOpsAwait4] {
				return []htmlbind.LiveBinding[planDashboardOpsAwait4]{
					func(deliver func(func(*planDashboardOpsAwait4), error) bool) error {
						for value, err := range WatchMetrics(ctx, p.Id) {
							if !deliver(func(scope *planDashboardOpsAwait4) { scope.Point = value }, err) {
								return nil
							}
						}
						return nil
					},
					func(deliver func(func(*planDashboardOpsAwait4), error) bool) error {
						for value, err := range WatchMessages(ctx, p.Id) {
							if !deliver(func(scope *planDashboardOpsAwait4) { scope.Messages = value }, err) {
								return nil
							}
						}
						return nil
					},
				}
			},
			func(p DashboardParams) planDashboardOpsAwait4 { return planDashboardOpsAwait4{Outer: p} },
			func(p DashboardParams, err htmlbind.AsyncError) planDashboardOpsAwait4Recover {
				return planDashboardOpsAwait4Recover{Outer: p, Err: err}
			},
			[]htmlbind.Op[planDashboardOpsAwait4]{
				planDashboardOpsAwait4Ops.Static(" <p class=\"value\">"),
				planDashboardOpsAwait4Ops.Text(func(p planDashboardOpsAwait4) string { return p.Point.Label }),
				planDashboardOpsAwait4Ops.Static(": "),
				planDashboardOpsAwait4Ops.Raw(func(p planDashboardOpsAwait4) string { return htmlbind.FormatInt(p.Point.Value) }),
				planDashboardOpsAwait4Ops.Static("</p> <ul> "),
				htmlbind.For(
					func(p planDashboardOpsAwait4) []string { return p.Messages },
					func(p planDashboardOpsAwait4, item string, index int) planDashboardOpsAwait4OpsScope5 {
						return planDashboardOpsAwait4OpsScope5{Outer: p, Item: item, Index: index}
					},
					[]htmlbind.Op[planDashboardOpsAwait4OpsScope5]{
						planDashboardOpsAwait4OpsScope5Ops.Static(" <li>"),
						planDashboardOpsAwait4OpsScope5Ops.Text(func(p planDashboardOpsAwait4OpsScope5) string { return p.Item }),
						planDashboardOpsAwait4OpsScope5Ops.Static("</li> "),
					}),
				planDashboardOpsAwait4Ops.Static(" </ul> "),
			},
			[]htmlbind.Op[DashboardParams]{
				planDashboardOps.Static(" <p class=\"pending\">waiting…</p> "),
			},
			[]htmlbind.Op[planDashboardOpsAwait4Recover]{
				planDashboardOpsAwait4RecoverOps.Static(" <p class=\"failed\">"),
				planDashboardOpsAwait4RecoverOps.Text(func(p planDashboardOpsAwait4Recover) string { return p.Err.Code }),
				planDashboardOpsAwait4RecoverOps.Static("</p> "),
			}),
		planDashboardOps.Static(" "),
	},
}

// Dashboard binds Dashboard to its parameters, producing a renderable fragment.
func Dashboard(params DashboardParams) htmlbind.Fragment {
	return htmlbind.Bind(planDashboardPlan, params)
}

var planMixedOps = htmlbind.Builder[MixedParams]{}

var planMixedPlan = &htmlbind.Plan[MixedParams]{
	Head:          nil,
	HasAwaitBlock: true,
	HasLiveBlock:  true,
	Ops: []htmlbind.Op[MixedParams]{
		planMixedOps.Static(" "),
		htmlbind.Live(
			func(ctx context.Context, p MixedParams) []htmlbind.LiveBinding[planMixedOpsAwait6] {
				return []htmlbind.LiveBinding[planMixedOpsAwait6]{
					func(deliver func(func(*planMixedOpsAwait6), error) bool) error {
						value, err := LoadTitle(p.Id)
						deliver(func(scope *planMixedOpsAwait6) { scope.Title = value }, err)
						return nil
					},
					func(deliver func(func(*planMixedOpsAwait6), error) bool) error {
						for value, err := range WatchMetrics(ctx, p.Id) {
							if !deliver(func(scope *planMixedOpsAwait6) { scope.Point = value }, err) {
								return nil
							}
						}
						return nil
					},
				}
			},
			func(p MixedParams) planMixedOpsAwait6 { return planMixedOpsAwait6{Outer: p} },
			func(p MixedParams, err htmlbind.AsyncError) planMixedOpsAwait6Recover {
				return planMixedOpsAwait6Recover{Outer: p, Err: err}
			},
			[]htmlbind.Op[planMixedOpsAwait6]{
				planMixedOpsAwait6Ops.Static(" <h1>"),
				planMixedOpsAwait6Ops.Text(func(p planMixedOpsAwait6) string { return p.Title }),
				planMixedOpsAwait6Ops.Static("</h1> <p class=\"value\">"),
				planMixedOpsAwait6Ops.Text(func(p planMixedOpsAwait6) string { return p.Point.Label }),
				planMixedOpsAwait6Ops.Static(": "),
				planMixedOpsAwait6Ops.Raw(func(p planMixedOpsAwait6) string { return htmlbind.FormatInt(p.Point.Value) }),
				planMixedOpsAwait6Ops.Static("</p> "),
			},
			[]htmlbind.Op[MixedParams]{
				planMixedOps.Static(" <p class=\"pending\">waiting…</p> "),
			},
			[]htmlbind.Op[planMixedOpsAwait6Recover]{
				planMixedOpsAwait6RecoverOps.Static(" <p class=\"failed\">"),
				planMixedOpsAwait6RecoverOps.Text(func(p planMixedOpsAwait6Recover) string { return p.Err.Code }),
				planMixedOpsAwait6RecoverOps.Static("</p> "),
			}),
		planMixedOps.Static(" "),
	},
}

// Mixed binds Mixed to its parameters, producing a renderable fragment.
func Mixed(params MixedParams) htmlbind.Fragment { return htmlbind.Bind(planMixedPlan, params) }

var planStaticOps = htmlbind.Builder[StaticParams]{}

// planStaticInput canonically encodes the declared inputs of Static.
// Slot arguments are excluded: their content belongs to the child boundary,
// so a frame stays comparable when only its child changed.
func planStaticInput(p StaticParams) string {
	return delta.CanonJoin(
		delta.CanonString[string](p.Id),
	)
}

var planStaticBoundary = &htmlbind.Boundary[StaticParams]{
	ComponentID: "pages.input.Static",
	Attr:        "data-tb-id",
	Input:       planStaticInput,
}

var planStaticPlan = &htmlbind.Plan[StaticParams]{
	Head:     nil,
	Boundary: planStaticBoundary,
	Ops: []htmlbind.Op[StaticParams]{
		planStaticOps.Static(" <p"),
		planStaticOps.BoundaryAttr(),
		planStaticOps.Static(">"),
		planStaticOps.Text(func(p StaticParams) string { return p.Id }),
		planStaticOps.Static("</p> "),
	},
}

// Static binds Static to its parameters, producing a renderable fragment.
func Static(params StaticParams) htmlbind.Fragment { return htmlbind.Bind(planStaticPlan, params) }
