// Code generated by tinybind; DO NOT EDIT.
// tinybind:generated v1 inputs=sha256:b0079d8f562a65864107168d7fa0153d92a02175700faa94df514d8042c0c5f8 self=sha256:b9b2ee78281f27d4c8497a1cf8daad5eaafcbb547553582e24a0938080305636 outputs=tinybind_gen.go,tinybind_openapi_gen.go

package checkfixture

import (
	"io"
	"net/http"
	"regexp"

	"github.com/shibukawa/tinybind-go"
	"github.com/shibukawa/tinybind-go/jsonbind"
)

var checkPatternCheckRequestCode = regexp.MustCompile("^[A-Z]{3}$")

func init() {
	httpbind.RegisterBind[CheckRequest](bindCheckRequest)
	httpbind.RegisterWrite[CheckRequest](writeCheckRequest)
	jsonbind.RegisterDecode[CheckRequest](decodeCheckRequestBytes)
	jsonbind.RegisterEncode[CheckRequest](encodeCheckRequest)
	httpbind.RegisterBind[CheckResponse](bindCheckResponse)
	httpbind.RegisterWrite[CheckResponse](writeCheckResponse)
	jsonbind.RegisterDecode[CheckResponse](decodeCheckResponseBytes)
	jsonbind.RegisterEncode[CheckResponse](encodeCheckResponse)
	httpbind.RegisterBind[OpenAPICheckRequest](bindOpenAPICheckRequest)
	httpbind.RegisterWrite[OpenAPICheckRequest](writeOpenAPICheckRequest)
	jsonbind.RegisterDecode[OpenAPICheckRequest](decodeOpenAPICheckRequestBytes)
	jsonbind.RegisterEncode[OpenAPICheckRequest](encodeOpenAPICheckRequest)
	httpbind.RegisterBind[OpenAPICheckResponse](bindOpenAPICheckResponse)
	httpbind.RegisterWrite[OpenAPICheckResponse](writeOpenAPICheckResponse)
	jsonbind.RegisterDecode[OpenAPICheckResponse](decodeOpenAPICheckResponseBytes)
	jsonbind.RegisterEncode[OpenAPICheckResponse](encodeOpenAPICheckResponse)
}

func decodeCheckRequestBytes(data []byte) (CheckRequest, error) {
	if jsonbind.IsBlank(data) {
		var out CheckRequest
		return out, nil
	}
	p := jsonbind.NewParser(data)
	out, err := decodeCheckRequestJSON(p)
	if err != nil {
		return out, err
	}
	if err := p.End(); err != nil {
		return out, err
	}
	return out, nil
}

func decodeCheckRequestJSON(p *jsonbind.Parser) (CheckRequest, error) {
	var out CheckRequest
	null, err := p.ObjectStart()
	if err != nil || null {
		return out, err
	}
	for n := 0; ; n++ {
		key, ok, err := p.ObjectKey(n)
		if err != nil {
			return out, err
		}
		if !ok {
			return out, nil
		}
		switch string(key) {
		default:
			if err := p.SkipValue(); err != nil {
				return out, err
			}
		}
	}
}

func appendCheckRequestJSON(dst []byte, v CheckRequest) []byte {
	dst = append(dst, '{')
	dst = append(dst, "\"name\":"...)
	dst = jsonbind.AppendString(dst, v.Name)
	dst = append(dst, ",\"email\":"...)
	dst = jsonbind.AppendString(dst, v.Email)
	dst = append(dst, ",\"age\":"...)
	dst = jsonbind.AppendInt(dst, int64(v.Age))
	dst = append(dst, ",\"sort\":"...)
	dst = jsonbind.AppendString(dst, v.Sort)
	dst = append(dst, ",\"code\":"...)
	dst = jsonbind.AppendString(dst, v.Code)
	dst = append(dst, ",\"id\":"...)
	dst = jsonbind.AppendString(dst, v.ID)
	dst = append(dst, ",\"born\":"...)
	dst = jsonbind.AppendString(dst, v.Born)
	dst = append(dst, ",\"at\":"...)
	dst = jsonbind.AppendString(dst, v.At)
	dst = append(dst, ",\"when\":"...)
	dst = jsonbind.AppendString(dst, v.When)
	dst = append(dst, ",\"page\":"...)
	dst = jsonbind.AppendInt(dst, int64(v.Page))
	dst = append(dst, ",\"optional\":"...)
	dst = jsonbind.AppendString(dst, v.Optional)
	return append(dst, '}')
}

func encodeCheckRequest(w io.Writer, v CheckRequest) error {
	buf := jsonbind.GetBuffer()
	*buf = appendCheckRequestJSON((*buf)[:0], v)
	*buf = append(*buf, '\n')
	_, err := w.Write(*buf)
	jsonbind.PutBuffer(buf)
	return err
}

func bindCheckRequest(r *http.Request) (CheckRequest, error) {
	var out CheckRequest
	var presentName bool
	var presentEmail bool
	var presentAge bool
	var presentSort bool
	var presentCode bool
	var presentID bool
	var presentBorn bool
	var presentAt bool
	var presentWhen bool
	var presentPage bool
	var presentOptional bool
	queryVals := httpbind.Queries(r)
	if qv, ok := httpbind.QueryLookup(queryVals, "name"); ok {
		presentName = true
		out.Name = qv
	}
	if qv, ok := httpbind.QueryLookup(queryVals, "email"); ok {
		presentEmail = true
		out.Email = qv
	}
	if qv, ok := httpbind.QueryLookup(queryVals, "age"); ok {
		presentAge = true
		v, err := httpbind.ParseInt(qv)
		if err != nil {
			return out, httpbind.BindError("age", "query", "invalid int")
		}
		out.Age = v
	}
	if qv, ok := httpbind.QueryLookup(queryVals, "sort"); ok {
		presentSort = true
		out.Sort = qv
	}
	if qv, ok := httpbind.QueryLookup(queryVals, "code"); ok {
		presentCode = true
		out.Code = qv
	}
	if qv, ok := httpbind.QueryLookup(queryVals, "id"); ok {
		presentID = true
		out.ID = qv
	}
	if qv, ok := httpbind.QueryLookup(queryVals, "born"); ok {
		presentBorn = true
		out.Born = qv
	}
	if qv, ok := httpbind.QueryLookup(queryVals, "at"); ok {
		presentAt = true
		out.At = qv
	}
	if qv, ok := httpbind.QueryLookup(queryVals, "when"); ok {
		presentWhen = true
		out.When = qv
	}
	if qv, ok := httpbind.QueryLookup(queryVals, "page"); ok {
		presentPage = true
		v, err := httpbind.ParseInt(qv)
		if err != nil {
			return out, httpbind.BindError("page", "query", "invalid int")
		}
		out.Page = v
	}
	if qv, ok := httpbind.QueryLookup(queryVals, "optional"); ok {
		presentOptional = true
		out.Optional = qv
	}
	var checkFields []httpbind.FieldError
	if !presentName || out.Name == "" {
		checkFields = append(checkFields, httpbind.Field("name", "query", "required"))
	}
	if presentName {
		if len(out.Name) < 1 {
			checkFields = append(checkFields, httpbind.Field("name", "query", "length must be >= 1"))
		}
		if len(out.Name) > 64 {
			checkFields = append(checkFields, httpbind.Field("name", "query", "length must be <= 64"))
		}
	}
	if !presentEmail || out.Email == "" {
		checkFields = append(checkFields, httpbind.Field("email", "query", "required"))
	}
	if presentEmail {
		if len(out.Email) > 254 {
			checkFields = append(checkFields, httpbind.Field("email", "query", "length must be <= 254"))
		}
		if out.Email != "" {
			if !httpbind.CheckEmail(out.Email) {
				checkFields = append(checkFields, httpbind.Field("email", "query", "must be a valid email"))
			}
		}
	}
	if presentAge {
		if out.Age < 0 {
			checkFields = append(checkFields, httpbind.Field("age", "query", "must be >= 0"))
		}
		if out.Age > 150 {
			checkFields = append(checkFields, httpbind.Field("age", "query", "must be <= 150"))
		}
	}
	if presentSort {
		{
			enumOK := false
			if out.Sort == "asc" {
				enumOK = true
			}
			if out.Sort == "desc" {
				enumOK = true
			}
			if !enumOK {
				checkFields = append(checkFields, httpbind.Field("sort", "query", "must be one of: asc, desc"))
			}
		}
	}
	if presentCode {
		if out.Code != "" {
			if !checkPatternCheckRequestCode.MatchString(out.Code) {
				checkFields = append(checkFields, httpbind.Field("code", "query", "must match pattern"))
			}
		}
	}
	if presentID {
		if out.ID != "" {
			if !httpbind.CheckUUID(out.ID) {
				checkFields = append(checkFields, httpbind.Field("id", "query", "must be a valid uuid"))
			}
		}
	}
	if presentBorn {
		if out.Born != "" {
			if !httpbind.CheckDate(out.Born) {
				checkFields = append(checkFields, httpbind.Field("born", "query", "must be ISO date"))
			}
		}
	}
	if presentAt {
		if out.At != "" {
			if !httpbind.CheckTime(out.At) {
				checkFields = append(checkFields, httpbind.Field("at", "query", "must be ISO time"))
			}
		}
	}
	if presentWhen {
		if out.When != "" {
			if !httpbind.CheckDateTime(out.When) {
				checkFields = append(checkFields, httpbind.Field("when", "query", "must be RFC3339 datetime"))
			}
		}
	}
	if presentPage {
		if out.Page < 1 {
			checkFields = append(checkFields, httpbind.Field("page", "query", "must be >= 1"))
		}
	}
	if presentOptional {
		if out.Optional != "" {
			if !httpbind.CheckEmail(out.Optional) {
				checkFields = append(checkFields, httpbind.Field("optional", "query", "must be a valid email"))
			}
		}
	}
	if len(checkFields) > 0 {
		return out, httpbind.Validation(checkFields...)
	}
	if !presentPage {
		out.Page = -1
	}
	return out, nil
}

func writeCheckRequest(w http.ResponseWriter, r *http.Request, v CheckRequest) error {
	_ = r
	buf := jsonbind.GetBuffer()
	*buf = appendCheckRequestJSON((*buf)[:0], v)
	err := httpbind.WriteJSONBytes(w, http.StatusOK, *buf)
	jsonbind.PutBuffer(buf)
	return err
}

func decodeCheckResponseBytes(data []byte) (CheckResponse, error) {
	if jsonbind.IsBlank(data) {
		var out CheckResponse
		return out, nil
	}
	p := jsonbind.NewParser(data)
	out, err := decodeCheckResponseJSON(p)
	if err != nil {
		return out, err
	}
	if err := p.End(); err != nil {
		return out, err
	}
	return out, nil
}

func decodeCheckResponseJSON(p *jsonbind.Parser) (CheckResponse, error) {
	var out CheckResponse
	null, err := p.ObjectStart()
	if err != nil || null {
		return out, err
	}
	for n := 0; ; n++ {
		key, ok, err := p.ObjectKey(n)
		if err != nil {
			return out, err
		}
		if !ok {
			return out, nil
		}
		switch string(key) {
		case "ok":
			v, err := p.Bool()
			if err != nil {
				return out, jsonbind.FieldError("ok", "invalid bool", err)
			}
			out.OK = v
		default:
			if err := p.SkipValue(); err != nil {
				return out, err
			}
		}
	}
}

func appendCheckResponseJSON(dst []byte, v CheckResponse) []byte {
	dst = append(dst, '{')
	dst = append(dst, "\"ok\":"...)
	dst = jsonbind.AppendBool(dst, v.OK)
	return append(dst, '}')
}

func encodeCheckResponse(w io.Writer, v CheckResponse) error {
	buf := jsonbind.GetBuffer()
	*buf = appendCheckResponseJSON((*buf)[:0], v)
	*buf = append(*buf, '\n')
	_, err := w.Write(*buf)
	jsonbind.PutBuffer(buf)
	return err
}

func bindCheckResponse(r *http.Request) (CheckResponse, error) {
	var out CheckResponse
	queryVals := httpbind.Queries(r)
	var jsonBody *jsonbind.Object
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		var err error
		jsonBody, formBody, _, err = httpbind.ReadBody(r, true, false)
		return err
	}
	if qv, ok := httpbind.QueryLookup(queryVals, "oK"); ok {
		v, err := httpbind.ParseBool(qv)
		if err != nil {
			return out, httpbind.BindError("oK", "query", "invalid bool")
		}
		out.OK = v
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody.Get("oK"); ok {
			v, err := jsonbind.DecodeJSONBool(raw)
			if err != nil {
				return out, jsonbind.FieldError("oK", "invalid bool", err)
			}
			out.OK = v
		} else if formBody != nil {
			if fv, ok := formBody["oK"]; ok {
				v, err := httpbind.ParseBool(fv)
				if err != nil {
					return out, httpbind.BindError("oK", "payload", "invalid bool")
				}
				out.OK = v
			}
		}
	}
	return out, nil
}

func writeCheckResponse(w http.ResponseWriter, r *http.Request, v CheckResponse) error {
	_ = r
	buf := jsonbind.GetBuffer()
	*buf = appendCheckResponseJSON((*buf)[:0], v)
	err := httpbind.WriteJSONBytes(w, http.StatusOK, *buf)
	jsonbind.PutBuffer(buf)
	return err
}

func decodeOpenAPICheckRequestBytes(data []byte) (OpenAPICheckRequest, error) {
	if jsonbind.IsBlank(data) {
		var out OpenAPICheckRequest
		return out, nil
	}
	p := jsonbind.NewParser(data)
	out, err := decodeOpenAPICheckRequestJSON(p)
	if err != nil {
		return out, err
	}
	if err := p.End(); err != nil {
		return out, err
	}
	return out, nil
}

func decodeOpenAPICheckRequestJSON(p *jsonbind.Parser) (OpenAPICheckRequest, error) {
	var out OpenAPICheckRequest
	null, err := p.ObjectStart()
	if err != nil || null {
		return out, err
	}
	for n := 0; ; n++ {
		key, ok, err := p.ObjectKey(n)
		if err != nil {
			return out, err
		}
		if !ok {
			return out, nil
		}
		switch string(key) {
		case "name":
			v, err := p.String()
			if err != nil {
				return out, jsonbind.FieldError("name", "invalid string", err)
			}
			out.Name = v
		case "age":
			v, err := p.Int()
			if err != nil {
				return out, jsonbind.FieldError("age", "invalid int", err)
			}
			out.Age = v
		case "email":
			v, err := p.String()
			if err != nil {
				return out, jsonbind.FieldError("email", "invalid string", err)
			}
			out.Email = v
		default:
			if err := p.SkipValue(); err != nil {
				return out, err
			}
		}
	}
}

func appendOpenAPICheckRequestJSON(dst []byte, v OpenAPICheckRequest) []byte {
	dst = append(dst, '{')
	dst = append(dst, "\"name\":"...)
	dst = jsonbind.AppendString(dst, v.Name)
	dst = append(dst, ",\"age\":"...)
	dst = jsonbind.AppendInt(dst, int64(v.Age))
	dst = append(dst, ",\"sort\":"...)
	dst = jsonbind.AppendString(dst, v.Sort)
	dst = append(dst, ",\"email\":"...)
	dst = jsonbind.AppendString(dst, v.Email)
	return append(dst, '}')
}

func encodeOpenAPICheckRequest(w io.Writer, v OpenAPICheckRequest) error {
	buf := jsonbind.GetBuffer()
	*buf = appendOpenAPICheckRequestJSON((*buf)[:0], v)
	*buf = append(*buf, '\n')
	_, err := w.Write(*buf)
	jsonbind.PutBuffer(buf)
	return err
}

func bindOpenAPICheckRequest(r *http.Request) (OpenAPICheckRequest, error) {
	var out OpenAPICheckRequest
	var presentName bool
	var presentAge bool
	var presentSort bool
	var presentEmail bool
	queryVals := httpbind.Queries(r)
	var jsonBody *jsonbind.Object
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		var err error
		jsonBody, formBody, _, err = httpbind.ReadBody(r, true, false)
		return err
	}
	if err := readBody(); err != nil {
		return out, err
	}
	if raw, ok := jsonBody.Get("name"); ok {
		presentName = true
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("name", "invalid string", err)
		}
		out.Name = v
	} else if formBody != nil {
		if fv, ok := formBody["name"]; ok {
			presentName = true
			out.Name = fv
		}
	}
	if err := readBody(); err != nil {
		return out, err
	}
	if raw, ok := jsonBody.Get("age"); ok {
		presentAge = true
		v, err := jsonbind.DecodeJSONInt(raw)
		if err != nil {
			return out, jsonbind.FieldError("age", "invalid int", err)
		}
		out.Age = v
	} else if formBody != nil {
		if fv, ok := formBody["age"]; ok {
			presentAge = true
			v, err := httpbind.ParseInt(fv)
			if err != nil {
				return out, httpbind.BindError("age", "payload", "invalid int")
			}
			out.Age = v
		}
	}
	if qv, ok := httpbind.QueryLookup(queryVals, "sort"); ok {
		presentSort = true
		out.Sort = qv
	}
	if err := readBody(); err != nil {
		return out, err
	}
	if raw, ok := jsonBody.Get("email"); ok {
		presentEmail = true
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("email", "invalid string", err)
		}
		out.Email = v
	} else if formBody != nil {
		if fv, ok := formBody["email"]; ok {
			presentEmail = true
			out.Email = fv
		}
	}
	var checkFields []httpbind.FieldError
	if !presentName || out.Name == "" {
		checkFields = append(checkFields, httpbind.Field("name", "payload", "required"))
	}
	if presentName {
		if len(out.Name) < 1 {
			checkFields = append(checkFields, httpbind.Field("name", "payload", "length must be >= 1"))
		}
	}
	if presentAge {
		if out.Age < 1 {
			checkFields = append(checkFields, httpbind.Field("age", "payload", "must be >= 1"))
		}
		if out.Age > 120 {
			checkFields = append(checkFields, httpbind.Field("age", "payload", "must be <= 120"))
		}
	}
	if presentSort {
		{
			enumOK := false
			if out.Sort == "asc" {
				enumOK = true
			}
			if out.Sort == "desc" {
				enumOK = true
			}
			if !enumOK {
				checkFields = append(checkFields, httpbind.Field("sort", "query", "must be one of: asc, desc"))
			}
		}
	}
	if presentEmail {
		if out.Email != "" {
			if !httpbind.CheckEmail(out.Email) {
				checkFields = append(checkFields, httpbind.Field("email", "payload", "must be a valid email"))
			}
		}
	}
	if len(checkFields) > 0 {
		return out, httpbind.Validation(checkFields...)
	}
	if !presentSort {
		out.Sort = "asc"
	}
	return out, nil
}

func writeOpenAPICheckRequest(w http.ResponseWriter, r *http.Request, v OpenAPICheckRequest) error {
	_ = r
	buf := jsonbind.GetBuffer()
	*buf = appendOpenAPICheckRequestJSON((*buf)[:0], v)
	err := httpbind.WriteJSONBytes(w, http.StatusOK, *buf)
	jsonbind.PutBuffer(buf)
	return err
}

func decodeOpenAPICheckResponseBytes(data []byte) (OpenAPICheckResponse, error) {
	if jsonbind.IsBlank(data) {
		var out OpenAPICheckResponse
		return out, nil
	}
	p := jsonbind.NewParser(data)
	out, err := decodeOpenAPICheckResponseJSON(p)
	if err != nil {
		return out, err
	}
	if err := p.End(); err != nil {
		return out, err
	}
	return out, nil
}

func decodeOpenAPICheckResponseJSON(p *jsonbind.Parser) (OpenAPICheckResponse, error) {
	var out OpenAPICheckResponse
	null, err := p.ObjectStart()
	if err != nil || null {
		return out, err
	}
	for n := 0; ; n++ {
		key, ok, err := p.ObjectKey(n)
		if err != nil {
			return out, err
		}
		if !ok {
			return out, nil
		}
		switch string(key) {
		case "ok":
			v, err := p.Bool()
			if err != nil {
				return out, jsonbind.FieldError("ok", "invalid bool", err)
			}
			out.OK = v
		default:
			if err := p.SkipValue(); err != nil {
				return out, err
			}
		}
	}
}

func appendOpenAPICheckResponseJSON(dst []byte, v OpenAPICheckResponse) []byte {
	dst = append(dst, '{')
	dst = append(dst, "\"ok\":"...)
	dst = jsonbind.AppendBool(dst, v.OK)
	return append(dst, '}')
}

func encodeOpenAPICheckResponse(w io.Writer, v OpenAPICheckResponse) error {
	buf := jsonbind.GetBuffer()
	*buf = appendOpenAPICheckResponseJSON((*buf)[:0], v)
	*buf = append(*buf, '\n')
	_, err := w.Write(*buf)
	jsonbind.PutBuffer(buf)
	return err
}

func bindOpenAPICheckResponse(r *http.Request) (OpenAPICheckResponse, error) {
	var out OpenAPICheckResponse
	queryVals := httpbind.Queries(r)
	var jsonBody *jsonbind.Object
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		var err error
		jsonBody, formBody, _, err = httpbind.ReadBody(r, true, false)
		return err
	}
	if qv, ok := httpbind.QueryLookup(queryVals, "oK"); ok {
		v, err := httpbind.ParseBool(qv)
		if err != nil {
			return out, httpbind.BindError("oK", "query", "invalid bool")
		}
		out.OK = v
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody.Get("oK"); ok {
			v, err := jsonbind.DecodeJSONBool(raw)
			if err != nil {
				return out, jsonbind.FieldError("oK", "invalid bool", err)
			}
			out.OK = v
		} else if formBody != nil {
			if fv, ok := formBody["oK"]; ok {
				v, err := httpbind.ParseBool(fv)
				if err != nil {
					return out, httpbind.BindError("oK", "payload", "invalid bool")
				}
				out.OK = v
			}
		}
	}
	return out, nil
}

func writeOpenAPICheckResponse(w http.ResponseWriter, r *http.Request, v OpenAPICheckResponse) error {
	_ = r
	buf := jsonbind.GetBuffer()
	*buf = appendOpenAPICheckResponseJSON((*buf)[:0], v)
	err := httpbind.WriteJSONBytes(w, http.StatusOK, *buf)
	jsonbind.PutBuffer(buf)
	return err
}
