// Code generated by tinybind; DO NOT EDIT.
// tinybind:generated v1 inputs=sha256:27056eba705fe860e7225b7bab3d1c1e0c297f985d93dfebfc87288460ce54c5 self=sha256:5207011f7cbf5341a10b414a8bf379a2c0cbe8de32ef310ddf66a0923d863533 outputs=tinybind_gen.go

package tinycheck

import (
	"io"
	"net/http"

	"github.com/shibukawa/tinybind-go"
	"github.com/shibukawa/tinybind-go/jsonbind"
)

func init() {
	httpbind.RegisterBind[CreateUserRequest](bindCreateUserRequest)
	httpbind.RegisterWrite[CreateUserRequest](writeCreateUserRequest)
	jsonbind.RegisterDecode[CreateUserRequest](decodeCreateUserRequestBytes)
	jsonbind.RegisterEncode[CreateUserRequest](encodeCreateUserRequest)
	httpbind.RegisterBind[CreateUserResponse](bindCreateUserResponse)
	httpbind.RegisterWrite[CreateUserResponse](writeCreateUserResponse)
	jsonbind.RegisterDecode[CreateUserResponse](decodeCreateUserResponseBytes)
	jsonbind.RegisterEncode[CreateUserResponse](encodeCreateUserResponse)
}

func decodeCreateUserRequestBytes(data []byte) (CreateUserRequest, error) {
	if jsonbind.IsBlank(data) {
		var out CreateUserRequest
		return out, nil
	}
	p := jsonbind.NewParser(data)
	out, err := decodeCreateUserRequestJSON(p)
	if err != nil {
		return out, err
	}
	if err := p.End(); err != nil {
		return out, err
	}
	return out, nil
}

func decodeCreateUserRequestJSON(p *jsonbind.Parser) (CreateUserRequest, error) {
	var out CreateUserRequest
	null, err := p.ObjectStart()
	if err != nil || null {
		return out, err
	}
	for n := 0; ; n++ {
		key, ok, err := p.ObjectKey(n)
		if err != nil {
			return out, err
		}
		if !ok {
			return out, nil
		}
		switch string(key) {
		case "name":
			v, err := p.String()
			if err != nil {
				return out, jsonbind.FieldError("name", "invalid string", err)
			}
			out.Name = v
		case "email":
			v, err := p.String()
			if err != nil {
				return out, jsonbind.FieldError("email", "invalid string", err)
			}
			out.Email = v
		default:
			if err := p.SkipValue(); err != nil {
				return out, err
			}
		}
	}
}

func appendCreateUserRequestJSON(dst []byte, v CreateUserRequest) []byte {
	dst = append(dst, '{')
	dst = append(dst, "\"name\":"...)
	dst = jsonbind.AppendString(dst, v.Name)
	dst = append(dst, ",\"email\":"...)
	dst = jsonbind.AppendString(dst, v.Email)
	dst = append(dst, ",\"org_id\":"...)
	dst = jsonbind.AppendString(dst, v.OrgID)
	dst = append(dst, ",\"Authorization\":"...)
	dst = jsonbind.AppendString(dst, v.Token)
	return append(dst, '}')
}

func encodeCreateUserRequest(w io.Writer, v CreateUserRequest) error {
	buf := jsonbind.GetBuffer()
	*buf = appendCreateUserRequestJSON((*buf)[:0], v)
	*buf = append(*buf, '\n')
	_, err := w.Write(*buf)
	jsonbind.PutBuffer(buf)
	return err
}

func bindCreateUserRequest(r *http.Request) (CreateUserRequest, error) {
	var out CreateUserRequest
	queryVals := httpbind.Queries(r)
	var jsonBody *jsonbind.Object
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		var err error
		jsonBody, formBody, _, err = httpbind.ReadBody(r, true, false)
		return err
	}
	if qv, ok := httpbind.QueryLookup(queryVals, "name"); ok {
		out.Name = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody.Get("name"); ok {
			v, err := jsonbind.DecodeJSONString(raw)
			if err != nil {
				return out, jsonbind.FieldError("name", "invalid string", err)
			}
			out.Name = v
		} else if formBody != nil {
			if fv, ok := formBody["name"]; ok {
				out.Name = fv
			}
		}
	}
	if qv, ok := httpbind.QueryLookup(queryVals, "email"); ok {
		out.Email = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody.Get("email"); ok {
			v, err := jsonbind.DecodeJSONString(raw)
			if err != nil {
				return out, jsonbind.FieldError("email", "invalid string", err)
			}
			out.Email = v
		} else if formBody != nil {
			if fv, ok := formBody["email"]; ok {
				out.Email = fv
			}
		}
	}
	out.OrgID = httpbind.PathValue(r, "org_id")
	out.Token = httpbind.HeaderValue(r, "Authorization")
	return out, nil
}

func writeCreateUserRequest(w http.ResponseWriter, r *http.Request, v CreateUserRequest) error {
	_ = r
	buf := jsonbind.GetBuffer()
	*buf = appendCreateUserRequestJSON((*buf)[:0], v)
	err := httpbind.WriteJSONBytes(w, http.StatusOK, *buf)
	jsonbind.PutBuffer(buf)
	return err
}

func decodeCreateUserResponseBytes(data []byte) (CreateUserResponse, error) {
	if jsonbind.IsBlank(data) {
		var out CreateUserResponse
		return out, nil
	}
	p := jsonbind.NewParser(data)
	out, err := decodeCreateUserResponseJSON(p)
	if err != nil {
		return out, err
	}
	if err := p.End(); err != nil {
		return out, err
	}
	return out, nil
}

func decodeCreateUserResponseJSON(p *jsonbind.Parser) (CreateUserResponse, error) {
	var out CreateUserResponse
	null, err := p.ObjectStart()
	if err != nil || null {
		return out, err
	}
	for n := 0; ; n++ {
		key, ok, err := p.ObjectKey(n)
		if err != nil {
			return out, err
		}
		if !ok {
			return out, nil
		}
		switch string(key) {
		case "id":
			v, err := p.String()
			if err != nil {
				return out, jsonbind.FieldError("id", "invalid string", err)
			}
			out.ID = v
		case "name":
			v, err := p.String()
			if err != nil {
				return out, jsonbind.FieldError("name", "invalid string", err)
			}
			out.Name = v
		case "email":
			v, err := p.String()
			if err != nil {
				return out, jsonbind.FieldError("email", "invalid string", err)
			}
			out.Email = v
		default:
			if err := p.SkipValue(); err != nil {
				return out, err
			}
		}
	}
}

func appendCreateUserResponseJSON(dst []byte, v CreateUserResponse) []byte {
	dst = append(dst, '{')
	dst = append(dst, "\"id\":"...)
	dst = jsonbind.AppendString(dst, v.ID)
	dst = append(dst, ",\"name\":"...)
	dst = jsonbind.AppendString(dst, v.Name)
	dst = append(dst, ",\"email\":"...)
	dst = jsonbind.AppendString(dst, v.Email)
	return append(dst, '}')
}

func encodeCreateUserResponse(w io.Writer, v CreateUserResponse) error {
	buf := jsonbind.GetBuffer()
	*buf = appendCreateUserResponseJSON((*buf)[:0], v)
	*buf = append(*buf, '\n')
	_, err := w.Write(*buf)
	jsonbind.PutBuffer(buf)
	return err
}

func bindCreateUserResponse(r *http.Request) (CreateUserResponse, error) {
	var out CreateUserResponse
	queryVals := httpbind.Queries(r)
	var jsonBody *jsonbind.Object
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		var err error
		jsonBody, formBody, _, err = httpbind.ReadBody(r, true, false)
		return err
	}
	if qv, ok := httpbind.QueryLookup(queryVals, "iD"); ok {
		out.ID = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody.Get("iD"); ok {
			v, err := jsonbind.DecodeJSONString(raw)
			if err != nil {
				return out, jsonbind.FieldError("iD", "invalid string", err)
			}
			out.ID = v
		} else if formBody != nil {
			if fv, ok := formBody["iD"]; ok {
				out.ID = fv
			}
		}
	}
	if qv, ok := httpbind.QueryLookup(queryVals, "name"); ok {
		out.Name = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody.Get("name"); ok {
			v, err := jsonbind.DecodeJSONString(raw)
			if err != nil {
				return out, jsonbind.FieldError("name", "invalid string", err)
			}
			out.Name = v
		} else if formBody != nil {
			if fv, ok := formBody["name"]; ok {
				out.Name = fv
			}
		}
	}
	if qv, ok := httpbind.QueryLookup(queryVals, "email"); ok {
		out.Email = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody.Get("email"); ok {
			v, err := jsonbind.DecodeJSONString(raw)
			if err != nil {
				return out, jsonbind.FieldError("email", "invalid string", err)
			}
			out.Email = v
		} else if formBody != nil {
			if fv, ok := formBody["email"]; ok {
				out.Email = fv
			}
		}
	}
	return out, nil
}

func writeCreateUserResponse(w http.ResponseWriter, r *http.Request, v CreateUserResponse) error {
	_ = r
	buf := jsonbind.GetBuffer()
	*buf = appendCreateUserResponseJSON((*buf)[:0], v)
	err := httpbind.WriteJSONBytes(w, http.StatusOK, *buf)
	jsonbind.PutBuffer(buf)
	return err
}
