// Code generated by tinybind HTML templates; DO NOT EDIT.

package archive

import (
	"context"

	"github.com/shibukawa/tinybind-go/htmlbind"
)

type PageParams struct {
	Latest string
}

var planPageOps = htmlbind.Builder[PageParams]{}

var planPagePlan = &htmlbind.Plan[PageParams]{
	Head: nil,
	Ops: []htmlbind.Op[PageParams]{
		planPageOps.Static(" <h1>archive for "),
		planPageOps.TextCtx(func(ctx context.Context, p PageParams) string { return CurrentReader(ctx) }),
		planPageOps.Static("</h1> <p>latest: "),
		planPageOps.Text(func(p PageParams) string { return p.Latest }),
		planPageOps.Static("</p> "),
	},
}

// Page binds Page to its parameters, producing a renderable fragment.
func Page(params PageParams) htmlbind.Fragment { return htmlbind.Bind(planPagePlan, params) }
