// Code generated by tinybind; DO NOT EDIT.

package archive

import "net/http"

// RouteParams holds the URL inputs of GET /archive.
type RouteParams struct {
}

// DecodeRoute reads the path and query values of GET /archive.
// An unparsable value produces an error rather than a zero value.
func DecodeRoute(r *http.Request) (RouteParams, error) {
	var out RouteParams
	return out, nil
}
