// Code generated by tinybind; DO NOT EDIT.

package id_

import (
	"github.com/shibukawa/tinygodriver/fasthttp"
	"strconv"

	httpbind "github.com/shibukawa/tinybind-go/fasthttpbind"
)

// RouteParams holds the URL inputs of GET /users/{id}.
type RouteParams struct {
	ID   string
	Page *int
}

// DecodeRoute reads the path and query values of GET /users/{id}.
// An unparsable value produces an error rather than a zero value.
func DecodeRoute(ctx *fasthttp.RequestCtx) (RouteParams, error) {
	var out RouteParams
	query := httpbind.Queries(ctx)
	rawID := httpbind.PathValue(ctx, "id")
	if rawID == "" {
		return out, httpbind.BadRequest(httpbind.Problem{Code: "missing_path_parameter", Message: "missing path parameter id"})
	}
	out.ID = rawID
	if raw, _ := httpbind.QueryLookup(query, "page"); raw != "" {
		v, err := strconv.Atoi(raw)
		if err != nil {
			return out, httpbind.BadRequest(httpbind.Problem{Code: "invalid_query_parameter", Message: "query parameter page is not a valid int"}, err)
		}
		value := v
		out.Page = &value
	}
	return out, nil
}
