// Code generated by tinybind HTML templates; DO NOT EDIT.

package pages

import (
	"context"

	"github.com/shibukawa/tinybind-go/htmlbind"
)

type User struct {
	Name  string
	Admin bool
}

type renderBadgeParams struct {
	User User
	Tone string
}

type ProfileParams struct {
	Id string
}

type PageParams struct {
	Id string
}

type ShellParams struct {
	Children htmlbind.Fragment
}

type SilentParams struct {
	Id string
}

func _tinybindKeyUser(value User) string {
	return htmlbind.KeyString[string](value.Name) + htmlbind.KeyBool(value.Admin)
}

type planProfileOpsAwait1 struct {
	Outer ProfileParams
	User  User
	Tags  []string
}

var planProfileOpsAwait1Ops = htmlbind.Builder[planProfileOpsAwait1]{}

type planProfileOpsAwait1Recover struct {
	Outer ProfileParams
	Err   htmlbind.AsyncError
}

var planProfileOpsAwait1RecoverOps = htmlbind.Builder[planProfileOpsAwait1Recover]{}

type planProfileOpsAwait1OpsScope2 struct {
	Outer planProfileOpsAwait1
	Item  string
	Index int
}

var planProfileOpsAwait1OpsScope2Ops = htmlbind.Builder[planProfileOpsAwait1OpsScope2]{}

type planSilentOpsAwait3 struct {
	Outer SilentParams
	User  User
}

var planSilentOpsAwait3Ops = htmlbind.Builder[planSilentOpsAwait3]{}

type planSilentOpsAwait3Recover struct {
	Outer SilentParams
	Err   htmlbind.AsyncError
}

var planSilentOpsAwait3RecoverOps = htmlbind.Builder[planSilentOpsAwait3Recover]{}

var planBadgeOps = htmlbind.Builder[renderBadgeParams]{}

var planBadgeCache = htmlbind.CachePolicy[renderBadgeParams]{
	ID:  "pages/input.txt:Badge:4b86c256396c2d7a",
	TTL: 300000000000, // 5m0s
	Key: func(p renderBadgeParams) string { return _tinybindKeyUser(p.User) + htmlbind.KeyString[string](p.Tone) },
}

var planBadgePlan = &htmlbind.Plan[renderBadgeParams]{
	Head:  nil,
	Cache: &planBadgeCache,
	Ops: []htmlbind.Op[renderBadgeParams]{
		planBadgeOps.Static(" <span"),
		planBadgeOps.Attr("class", func(p renderBadgeParams) (string, bool) { return "badge " + htmlbind.Escape(p.Tone), true }),
		planBadgeOps.Static(">"),
		planBadgeOps.Text(func(p renderBadgeParams) string { return p.User.Name }),
		planBadgeOps.Static("</span> "),
	},
}

// renderBadge binds Badge to its parameters, producing a renderable fragment.
func renderBadge(params renderBadgeParams) htmlbind.Fragment {
	return htmlbind.Bind(planBadgePlan, params)
}

var planProfileOps = htmlbind.Builder[ProfileParams]{}

// planProfileInput canonically encodes the declared inputs of Profile.
// Slot arguments are excluded: their content belongs to the child boundary,
// so a frame stays comparable when only its child changed.
func planProfileInput(p ProfileParams) string {
	return htmlbind.CanonJoin(
		htmlbind.CanonString[string](p.Id),
	)
}

var planProfileBoundary = &htmlbind.Boundary[ProfileParams]{
	ComponentID: "pages.input.Profile",
	Attr:        "data-tb-id",
	Input:       planProfileInput,
}

var planProfilePlan = &htmlbind.Plan[ProfileParams]{
	Head:          nil,
	Boundary:      planProfileBoundary,
	HasAwaitBlock: true,
	Ops: []htmlbind.Op[ProfileParams]{
		planProfileOps.Static(" <section"),
		planProfileOps.BoundaryAttr(),
		planProfileOps.Static("> "),
		htmlbind.Await(
			func(ctx context.Context, p ProfileParams) (planProfileOpsAwait1, error) {
				scope := planProfileOpsAwait1{Outer: p}
				if err := htmlbind.Concurrent(ctx,
					func() error { value, err := LoadUser(p.Id); scope.User = value; return err },
					func() error { value, err := LoadTags(p.Id); scope.Tags = value; return err },
				); err != nil {
					var zero planProfileOpsAwait1
					return zero, err
				}
				return scope, nil
			},
			func(p ProfileParams, err htmlbind.AsyncError) planProfileOpsAwait1Recover {
				return planProfileOpsAwait1Recover{Outer: p, Err: err}
			},
			[]htmlbind.Op[planProfileOpsAwait1]{
				planProfileOpsAwait1Ops.Static(" "),
				planProfileOpsAwait1Ops.Component(func(p planProfileOpsAwait1) htmlbind.Fragment {
					return renderBadge(renderBadgeParams{User: p.User, Tone: "solid"})
				}),
				planProfileOpsAwait1Ops.Static(" <ul> "),
				htmlbind.For(
					func(p planProfileOpsAwait1) []string { return p.Tags },
					func(p planProfileOpsAwait1, item string, index int) planProfileOpsAwait1OpsScope2 {
						return planProfileOpsAwait1OpsScope2{Outer: p, Item: item, Index: index}
					},
					[]htmlbind.Op[planProfileOpsAwait1OpsScope2]{
						planProfileOpsAwait1OpsScope2Ops.Static(" <li>"),
						planProfileOpsAwait1OpsScope2Ops.Text(func(p planProfileOpsAwait1OpsScope2) string { return p.Item }),
						planProfileOpsAwait1OpsScope2Ops.Static("</li> "),
					}),
				planProfileOpsAwait1Ops.Static(" </ul> "),
			},
			[]htmlbind.Op[ProfileParams]{
				planProfileOps.Static(" <p class=\"pending\">loading…</p> "),
			},
			[]htmlbind.Op[planProfileOpsAwait1Recover]{
				planProfileOpsAwait1RecoverOps.Static(" <p class=\"failed\">"),
				planProfileOpsAwait1RecoverOps.Text(func(p planProfileOpsAwait1Recover) string { return p.Err.Code }),
				planProfileOpsAwait1RecoverOps.Static(": "),
				planProfileOpsAwait1RecoverOps.Text(func(p planProfileOpsAwait1Recover) string { return p.Err.Message }),
				planProfileOpsAwait1RecoverOps.Static("</p> "),
			}),
		planProfileOps.Static(" </section> "),
	},
}

// Profile binds Profile to its parameters, producing a renderable fragment.
func Profile(params ProfileParams) htmlbind.Fragment { return htmlbind.Bind(planProfilePlan, params) }

var planPageOps = htmlbind.Builder[PageParams]{}

// planPageInput canonically encodes the declared inputs of Page.
// Slot arguments are excluded: their content belongs to the child boundary,
// so a frame stays comparable when only its child changed.
func planPageInput(p PageParams) string {
	return htmlbind.CanonJoin(
		htmlbind.CanonString[string](p.Id),
	)
}

var planPageBoundary = &htmlbind.Boundary[PageParams]{
	ComponentID: "pages.input.Page",
	Attr:        "data-tb-id",
	Input:       planPageInput,
}

var planPagePlan = &htmlbind.Plan[PageParams]{
	Head:          nil,
	Boundary:      planPageBoundary,
	HasAwaitBlock: true,
	Ops: []htmlbind.Op[PageParams]{
		planPageOps.Static(" <main"),
		planPageOps.BoundaryAttr(),
		planPageOps.Static(">"),
		planPageOps.Component(func(p PageParams) htmlbind.Fragment { return Profile(ProfileParams{Id: p.Id}) }),
		planPageOps.Static("</main> "),
	},
}

// Page binds Page to its parameters, producing a renderable fragment.
func Page(params PageParams) htmlbind.Fragment { return htmlbind.Bind(planPagePlan, params) }

var planShellOps = htmlbind.Builder[ShellParams]{}

// planShellInput canonically encodes the declared inputs of Shell.
// Slot arguments are excluded: their content belongs to the child boundary,
// so a frame stays comparable when only its child changed.
func planShellInput(p ShellParams) string {
	return htmlbind.CanonJoin()
}

var planShellBoundary = &htmlbind.Boundary[ShellParams]{
	ComponentID: "pages.input.Shell",
	Attr:        "data-tb-id",
	Input:       planShellInput,
}

var planShellPlan = &htmlbind.Plan[ShellParams]{
	Head:     nil,
	Boundary: planShellBoundary,
	Slots: func(p ShellParams) []htmlbind.Fragment {
		return []htmlbind.Fragment{p.Children}
	},
	Ops: []htmlbind.Op[ShellParams]{
		planShellOps.Static(" <div"),
		planShellOps.BoundaryAttr(),
		planShellOps.Static(" class=\"shell\">"),
		planShellOps.Slot(func(p ShellParams) htmlbind.Fragment { return p.Children }, nil),
		planShellOps.Static("</div> "),
	},
}

// Shell binds Shell to its parameters, producing a renderable fragment.
func Shell(params ShellParams) htmlbind.Fragment { return htmlbind.Bind(planShellPlan, params) }

// BindShell binds Shell as a chain wrapper filling its unnamed slot.
func BindShell(params ShellParams) htmlbind.Wrapper {
	return htmlbind.BindWrapper(planShellPlan, params, func(target *ShellParams, children htmlbind.Fragment) { target.Children = children })
}

var planSilentOps = htmlbind.Builder[SilentParams]{}

var planSilentPlan = &htmlbind.Plan[SilentParams]{
	Head:          nil,
	HasAwaitBlock: true,
	Ops: []htmlbind.Op[SilentParams]{
		planSilentOps.Static(" "),
		htmlbind.Await(
			func(ctx context.Context, p SilentParams) (planSilentOpsAwait3, error) {
				scope := planSilentOpsAwait3{Outer: p}
				if err := htmlbind.Concurrent(ctx,
					func() error { value, err := LoadUser(p.Id); scope.User = value; return err },
				); err != nil {
					var zero planSilentOpsAwait3
					return zero, err
				}
				return scope, nil
			},
			func(p SilentParams, err htmlbind.AsyncError) planSilentOpsAwait3Recover {
				return planSilentOpsAwait3Recover{Outer: p, Err: err}
			},
			[]htmlbind.Op[planSilentOpsAwait3]{
				planSilentOpsAwait3Ops.Static(" <p>"),
				planSilentOpsAwait3Ops.Text(func(p planSilentOpsAwait3) string { return p.User.Name }),
				planSilentOpsAwait3Ops.Static("</p> "),
			},
			[]htmlbind.Op[SilentParams]{
				planSilentOps.Static(" <p>waiting</p> "),
			},
			nil),
		planSilentOps.Static(" "),
	},
}

// Silent binds Silent to its parameters, producing a renderable fragment.
func Silent(params SilentParams) htmlbind.Fragment { return htmlbind.Bind(planSilentPlan, params) }
