// Code generated by configbind/codegen; DO NOT EDIT.

package configmoduleb

import (
	"fmt"

	"github.com/shibukawa/tinybind-go/cliparser"
	"github.com/shibukawa/tinybind-go/configbind"
)

func init() {
	registerConfigBinding0()
}

func registerConfigBinding0() {
	configbind.RegisterBinding[Config]("application", "github.com/shibukawa/tinybind-go/testdata/configmoduleb.Config", configbind.Meta{
		TypeName: "github.com/shibukawa/tinybind-go/testdata/configmoduleb.Config",
		KnownKeys: []string{
			"application.endpoint",
		},
		Defaults: map[string]string{
			"application.endpoint": "application",
		},
		FlagMetas: []cliparser.FieldMeta{
			{Prefix: "application", Key: "endpoint", Help: "application endpoint"},
		},
		Apply: applyConfigBinding0,
	})
	configbind.RegisterScaffold(configbind.ScaffoldFragment{ID: "github.com/shibukawa/tinybind-go/testdata/configmoduleb.Config@application", Prefix: "application", Fields: []configbind.ScaffoldField{
		{Key: "endpoint", Kind: configbind.ScaffoldString, Default: "application", Help: "application endpoint"},
	}})
}

func applyConfigBinding0(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*Config)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply Config: bad destination")
	}
	if v, ok := o.GetString("application.endpoint"); ok {
		p.Endpoint = v
	} else {
		p.Endpoint = "application"
	}
	return nil
}
