// Code generated by tinybind HTML templates; DO NOT EDIT.

package pages

import (
	"context"

	"github.com/shibukawa/tinybind-go/htmlbind"
)

type Order struct {
	Id    string
	Total int
}

type Customer struct {
	Name   string
	Orders htmlbind.Pending[[]Order]
}

type Row struct {
	Label string
	Count htmlbind.Pending[int]
}

type LayoutParams struct {
	Customer Customer
	Children htmlbind.Fragment
}

type ProfileParams struct {
	Customer Customer
	Headline htmlbind.Pending[*string]
}

type RowsParams struct {
	Rows []Row
}

func _tinybindCanonCustomer(value Customer) string {
	return htmlbind.CanonRecord(htmlbind.CanonJoin(
		htmlbind.CanonString[string](value.Name),
	))
}

func _tinybindCanonOrder(value Order) string {
	return htmlbind.CanonRecord(htmlbind.CanonJoin(
		htmlbind.CanonString[string](value.Id),
		htmlbind.CanonInt(value.Total),
	))
}

func _tinybindCanonRow(value Row) string {
	return htmlbind.CanonRecord(htmlbind.CanonJoin(
		htmlbind.CanonString[string](value.Label),
	))
}

type planLayoutOpsAwait1 struct {
	Outer  LayoutParams
	Orders []Order
}

var planLayoutOpsAwait1Ops = htmlbind.Builder[planLayoutOpsAwait1]{}

type planLayoutOpsAwait1Recover struct {
	Outer LayoutParams
	Err   htmlbind.AsyncError
}

var planLayoutOpsAwait1RecoverOps = htmlbind.Builder[planLayoutOpsAwait1Recover]{}

type planLayoutOpsAwait1OpsScope2 struct {
	Outer planLayoutOpsAwait1
	Item  Order
	Index int
}

var planLayoutOpsAwait1OpsScope2Ops = htmlbind.Builder[planLayoutOpsAwait1OpsScope2]{}

type planProfileOpsAwait3 struct {
	Outer  ProfileParams
	Orders []Order
	Badge  string
}

var planProfileOpsAwait3Ops = htmlbind.Builder[planProfileOpsAwait3]{}

type planProfileOpsAwait3Recover struct {
	Outer ProfileParams
	Err   htmlbind.AsyncError
}

var planProfileOpsAwait3RecoverOps = htmlbind.Builder[planProfileOpsAwait3Recover]{}

type planProfileOpsAwait3OpsScope4 struct {
	Outer planProfileOpsAwait3
	Item  Order
	Index int
}

var planProfileOpsAwait3OpsScope4Ops = htmlbind.Builder[planProfileOpsAwait3OpsScope4]{}

type planProfileOpsAwait5 struct {
	Outer ProfileParams
	Note  *string
}

var planProfileOpsAwait5Ops = htmlbind.Builder[planProfileOpsAwait5]{}

type planProfileOpsAwait5Recover struct {
	Outer ProfileParams
	Err   htmlbind.AsyncError
}

var planProfileOpsAwait5RecoverOps = htmlbind.Builder[planProfileOpsAwait5Recover]{}

type planRowsOpsScope6 struct {
	Outer RowsParams
	Item  Row
	Index int
}

var planRowsOpsScope6Ops = htmlbind.Builder[planRowsOpsScope6]{}

type planRowsOpsScope6OpsAwait7 struct {
	Outer planRowsOpsScope6
	Count int
}

var planRowsOpsScope6OpsAwait7Ops = htmlbind.Builder[planRowsOpsScope6OpsAwait7]{}

type planRowsOpsScope6OpsAwait7Recover struct {
	Outer planRowsOpsScope6
	Err   htmlbind.AsyncError
}

var planRowsOpsScope6OpsAwait7RecoverOps = htmlbind.Builder[planRowsOpsScope6OpsAwait7Recover]{}

var planLayoutOps = htmlbind.Builder[LayoutParams]{}

var planLayoutPlan = &htmlbind.Plan[LayoutParams]{
	Head:          nil,
	HasAwaitBlock: true,
	Slots: func(p LayoutParams) []htmlbind.Fragment {
		return []htmlbind.Fragment{p.Children}
	},
	Check: func(p LayoutParams) error {
		if !p.Customer.Orders.IsSet() {
			return htmlbind.ErrUnsetPending("customer.orders")
		}
		return nil
	},
	Ops: []htmlbind.Op[LayoutParams]{
		planLayoutOps.Static(" <header> "),
		htmlbind.Await(
			func(ctx context.Context, p LayoutParams) (planLayoutOpsAwait1, error) {
				scope := planLayoutOpsAwait1{Outer: p}
				if err := htmlbind.Concurrent(ctx,
					func() error { value, err := p.Customer.Orders.Wait(ctx); scope.Orders = value; return err },
				); err != nil {
					var zero planLayoutOpsAwait1
					return zero, err
				}
				return scope, nil
			},
			func(p LayoutParams, err htmlbind.AsyncError) planLayoutOpsAwait1Recover {
				return planLayoutOpsAwait1Recover{Outer: p, Err: err}
			},
			[]htmlbind.Op[planLayoutOpsAwait1]{
				planLayoutOpsAwait1Ops.Static(" <span class=\"count\">"),
				htmlbind.For(
					func(p planLayoutOpsAwait1) []Order { return p.Orders },
					func(p planLayoutOpsAwait1, item Order, index int) planLayoutOpsAwait1OpsScope2 {
						return planLayoutOpsAwait1OpsScope2{Outer: p, Item: item, Index: index}
					},
					[]htmlbind.Op[planLayoutOpsAwait1OpsScope2]{
						planLayoutOpsAwait1OpsScope2Ops.Static("<i>"),
						planLayoutOpsAwait1OpsScope2Ops.Text(func(p planLayoutOpsAwait1OpsScope2) string { return p.Item.Id }),
						planLayoutOpsAwait1OpsScope2Ops.Static("</i>"),
					}),
				planLayoutOpsAwait1Ops.Static("</span> "),
			},
			[]htmlbind.Op[LayoutParams]{
				planLayoutOps.Static(" <span class=\"count-pending\"></span> "),
			},
			nil),
		planLayoutOps.Static(" </header> <main>"),
		planLayoutOps.Slot(func(p LayoutParams) htmlbind.Fragment { return p.Children }, nil),
		planLayoutOps.Static("</main> "),
	},
}

// Layout binds Layout to its parameters, producing a renderable fragment.
func Layout(params LayoutParams) htmlbind.Fragment { return htmlbind.Bind(planLayoutPlan, params) }

// BindLayout binds Layout as a chain wrapper filling its unnamed slot.
func BindLayout(params LayoutParams) htmlbind.Wrapper {
	return htmlbind.BindWrapper(planLayoutPlan, params, func(target *LayoutParams, children htmlbind.Fragment) { target.Children = children })
}

var planProfileOps = htmlbind.Builder[ProfileParams]{}

// planProfileInput canonically encodes the declared inputs of Profile.
// Slot arguments are excluded: their content belongs to the child boundary,
// so a frame stays comparable when only its child changed.
func planProfileInput(p ProfileParams) string {
	return htmlbind.CanonJoin(
		_tinybindCanonCustomer(p.Customer),
	)
}

var planProfileBoundary = &htmlbind.Boundary[ProfileParams]{
	ComponentID: "pages.input.Profile",
	Attr:        "data-tb-id",
	Input:       planProfileInput,
}

var planProfilePlan = &htmlbind.Plan[ProfileParams]{
	Head:          nil,
	Boundary:      planProfileBoundary,
	HasAwaitBlock: true,
	Check: func(p ProfileParams) error {
		if !p.Customer.Orders.IsSet() {
			return htmlbind.ErrUnsetPending("customer.orders")
		}
		return nil
	},
	Ops: []htmlbind.Op[ProfileParams]{
		planProfileOps.Static(" <section"),
		planProfileOps.BoundaryAttr(),
		planProfileOps.Static("> <h1>"),
		planProfileOps.Text(func(p ProfileParams) string { return p.Customer.Name }),
		planProfileOps.Static("</h1> "),
		htmlbind.Await(
			func(ctx context.Context, p ProfileParams) (planProfileOpsAwait3, error) {
				scope := planProfileOpsAwait3{Outer: p}
				if err := htmlbind.Concurrent(ctx,
					func() error { value, err := p.Customer.Orders.Wait(ctx); scope.Orders = value; return err },
					func() error { value, err := LoadBadge(p.Customer.Name); scope.Badge = value; return err },
				); err != nil {
					var zero planProfileOpsAwait3
					return zero, err
				}
				return scope, nil
			},
			func(p ProfileParams, err htmlbind.AsyncError) planProfileOpsAwait3Recover {
				return planProfileOpsAwait3Recover{Outer: p, Err: err}
			},
			[]htmlbind.Op[planProfileOpsAwait3]{
				planProfileOpsAwait3Ops.Static(" <p class=\"badge\">"),
				planProfileOpsAwait3Ops.Text(func(p planProfileOpsAwait3) string { return p.Badge }),
				planProfileOpsAwait3Ops.Static("</p> <ul>"),
				htmlbind.For(
					func(p planProfileOpsAwait3) []Order { return p.Orders },
					func(p planProfileOpsAwait3, item Order, index int) planProfileOpsAwait3OpsScope4 {
						return planProfileOpsAwait3OpsScope4{Outer: p, Item: item, Index: index}
					},
					[]htmlbind.Op[planProfileOpsAwait3OpsScope4]{
						planProfileOpsAwait3OpsScope4Ops.Static("<li>"),
						planProfileOpsAwait3OpsScope4Ops.Text(func(p planProfileOpsAwait3OpsScope4) string { return p.Item.Id }),
						planProfileOpsAwait3OpsScope4Ops.Static(": "),
						planProfileOpsAwait3OpsScope4Ops.Text(func(p planProfileOpsAwait3OpsScope4) string { return htmlbind.FormatInt(p.Item.Total) }),
						planProfileOpsAwait3OpsScope4Ops.Static("</li>"),
					}),
				planProfileOpsAwait3Ops.Static("</ul> "),
			},
			[]htmlbind.Op[ProfileParams]{
				planProfileOps.Static(" <p class=\"pending\">loading "),
				planProfileOps.Text(func(p ProfileParams) string { return p.Customer.Name }),
				planProfileOps.Static("…</p> "),
			},
			[]htmlbind.Op[planProfileOpsAwait3Recover]{
				planProfileOpsAwait3RecoverOps.Static(" <p class=\"failed\">"),
				planProfileOpsAwait3RecoverOps.Text(func(p planProfileOpsAwait3Recover) string { return p.Err.Code }),
				planProfileOpsAwait3RecoverOps.Static("</p> "),
			}),
		planProfileOps.Static(" "),
		htmlbind.Await(
			func(ctx context.Context, p ProfileParams) (planProfileOpsAwait5, error) {
				scope := planProfileOpsAwait5{Outer: p}
				if err := htmlbind.Concurrent(ctx,
					func() error { value, err := p.Headline.Wait(ctx); scope.Note = value; return err },
				); err != nil {
					var zero planProfileOpsAwait5
					return zero, err
				}
				return scope, nil
			},
			func(p ProfileParams, err htmlbind.AsyncError) planProfileOpsAwait5Recover {
				return planProfileOpsAwait5Recover{Outer: p, Err: err}
			},
			[]htmlbind.Op[planProfileOpsAwait5]{
				planProfileOpsAwait5Ops.Static(" <p class=\"note\""),
				planProfileOpsAwait5Ops.Attr("title", func(p planProfileOpsAwait5) (string, bool) {
					if p.Note == nil {
						return "", false
					}
					return htmlbind.Escape(*(p.Note)), true
				}),
				planProfileOpsAwait5Ops.Static(">note</p> "),
			},
			[]htmlbind.Op[ProfileParams]{
				planProfileOps.Static(" <p class=\"note-pending\"></p> "),
			},
			nil),
		planProfileOps.Static(" </section> "),
	},
}

// Profile binds Profile to its parameters, producing a renderable fragment.
func Profile(params ProfileParams) htmlbind.Fragment { return htmlbind.Bind(planProfilePlan, params) }

var planRowsOps = htmlbind.Builder[RowsParams]{}

// planRowsInput canonically encodes the declared inputs of Rows.
// Slot arguments are excluded: their content belongs to the child boundary,
// so a frame stays comparable when only its child changed.
func planRowsInput(p RowsParams) string {
	return htmlbind.CanonJoin(
		htmlbind.CanonArray(p.Rows, _tinybindCanonRow),
	)
}

var planRowsBoundary = &htmlbind.Boundary[RowsParams]{
	ComponentID: "pages.input.Rows",
	Attr:        "data-tb-id",
	Input:       planRowsInput,
}

var planRowsPlan = &htmlbind.Plan[RowsParams]{
	Head:          nil,
	Boundary:      planRowsBoundary,
	HasAwaitBlock: true,
	Ops: []htmlbind.Op[RowsParams]{
		planRowsOps.Static(" <ul"),
		planRowsOps.BoundaryAttr(),
		planRowsOps.Static("> "),
		htmlbind.For(
			func(p RowsParams) []Row { return p.Rows },
			func(p RowsParams, item Row, index int) planRowsOpsScope6 {
				return planRowsOpsScope6{Outer: p, Item: item, Index: index}
			},
			[]htmlbind.Op[planRowsOpsScope6]{
				planRowsOpsScope6Ops.Static(" "),
				htmlbind.Require(func(p planRowsOpsScope6) error {
					if !p.Item.Count.IsSet() {
						return htmlbind.ErrUnsetPending("row.count")
					}
					return nil
				}),
				htmlbind.Await(
					func(ctx context.Context, p planRowsOpsScope6) (planRowsOpsScope6OpsAwait7, error) {
						scope := planRowsOpsScope6OpsAwait7{Outer: p}
						if err := htmlbind.Concurrent(ctx,
							func() error { value, err := p.Item.Count.Wait(ctx); scope.Count = value; return err },
						); err != nil {
							var zero planRowsOpsScope6OpsAwait7
							return zero, err
						}
						return scope, nil
					},
					func(p planRowsOpsScope6, err htmlbind.AsyncError) planRowsOpsScope6OpsAwait7Recover {
						return planRowsOpsScope6OpsAwait7Recover{Outer: p, Err: err}
					},
					[]htmlbind.Op[planRowsOpsScope6OpsAwait7]{
						planRowsOpsScope6OpsAwait7Ops.Static(" <li>"),
						planRowsOpsScope6OpsAwait7Ops.Text(func(p planRowsOpsScope6OpsAwait7) string { return p.Outer.Item.Label }),
						planRowsOpsScope6OpsAwait7Ops.Static(": "),
						planRowsOpsScope6OpsAwait7Ops.Text(func(p planRowsOpsScope6OpsAwait7) string { return htmlbind.FormatInt(p.Count) }),
						planRowsOpsScope6OpsAwait7Ops.Static("</li> "),
					},
					[]htmlbind.Op[planRowsOpsScope6]{
						planRowsOpsScope6Ops.Static(" <li>"),
						planRowsOpsScope6Ops.Text(func(p planRowsOpsScope6) string { return p.Item.Label }),
						planRowsOpsScope6Ops.Static(": pending</li> "),
					},
					nil),
				planRowsOpsScope6Ops.Static(" "),
			}),
		planRowsOps.Static(" </ul> "),
	},
}

// Rows binds Rows to its parameters, producing a renderable fragment.
func Rows(params RowsParams) htmlbind.Fragment { return htmlbind.Bind(planRowsPlan, params) }
