// Code generated by tinybind HTML templates; DO NOT EDIT.

package pages

import (
	"html"
	"io"
	"net/url"
	"strconv"
	"strings"
)

type HTML func(io.Writer) error
type TrustedHTML string
type TrustedCSS string
type TrustedJavaScript string
type ScriptJSON string

func _tinybindWrite(w io.Writer, value string) error { _, err := io.WriteString(w, value); return err }
func _tinybindEscape(value string) string            { return html.EscapeString(value) }
func _tinybindBool(value bool) string                { return strconv.FormatBool(value) }
func _tinybindInt(value int) string                  { return strconv.Itoa(value) }
func _tinybindFloat(value float64) string            { return strconv.FormatFloat(value, 'g', -1, 64) }

func _tinybindJSONQuote(value string) string {
	const hex = "0123456789abcdef"
	var out strings.Builder
	out.WriteByte('"')
	for _, r := range value {
		switch r {
		case '"':
			out.WriteString("\\\"")
		case '\\':
			out.WriteString("\\\\")
		case '\b':
			out.WriteString("\\b")
		case '\f':
			out.WriteString("\\f")
		case '\n':
			out.WriteString("\\n")
		case '\r':
			out.WriteString("\\r")
		case '\t':
			out.WriteString("\\t")
		case '<':
			out.WriteString("\\u003c")
		case '>':
			out.WriteString("\\u003e")
		case '&':
			out.WriteString("\\u0026")
		case '\u2028':
			out.WriteString("\\u2028")
		case '\u2029':
			out.WriteString("\\u2029")
		default:
			if r < 0x20 {
				out.WriteString("\\u00")
				out.WriteByte(hex[byte(r)>>4])
				out.WriteByte(hex[byte(r)&15])
			} else {
				out.WriteRune(r)
			}
		}
	}
	out.WriteByte('"')
	return out.String()
}

type User struct {
	Name       string
	Active     bool
	Nickname   *string
	ProfileURL url.URL
	Tags       []string
}

type ProfileParams struct {
	User User
}

func Profile(w io.Writer, _tinybindParams ProfileParams) error {
	user := _tinybindParams.User
	_ = user
	if err := _tinybindWrite(w, "\n<article"); err != nil {
		return err
	}
	if !(user.Active) {
		if err := _tinybindWrite(w, " hidden"); err != nil {
			return err
		}
	}
	if user.Nickname != nil {
		if err := _tinybindWrite(w, " title=\""); err != nil {
			return err
		}
		if err := _tinybindWrite(w, _tinybindEscape(*(user.Nickname))); err != nil {
			return err
		}
		if err := _tinybindWrite(w, "\""); err != nil {
			return err
		}
	}
	if err := _tinybindWrite(w, ">\n  <a href=\""); err != nil {
		return err
	}
	if err := _tinybindWrite(w, _tinybindEscape(user.ProfileURL.String())); err != nil {
		return err
	}
	if err := _tinybindWrite(w, "\">"); err != nil {
		return err
	}
	if err := _tinybindWrite(w, _tinybindEscape(user.Name)); err != nil {
		return err
	}
	if err := _tinybindWrite(w, "</a>\n  "); err != nil {
		return err
	}
	if user.Active {
		if err := _tinybindWrite(w, "\n    <ul>"); err != nil {
			return err
		}
		for index, tag := range user.Tags {
			if err := _tinybindWrite(w, "<li data-index=\""); err != nil {
				return err
			}
			if err := _tinybindWrite(w, _tinybindEscape(_tinybindInt(index))); err != nil {
				return err
			}
			if err := _tinybindWrite(w, "\">"); err != nil {
				return err
			}
			if err := _tinybindWrite(w, _tinybindEscape(tag)); err != nil {
				return err
			}
			if err := _tinybindWrite(w, "</li>"); err != nil {
				return err
			}
		}
		if err := _tinybindWrite(w, "</ul>\n  "); err != nil {
			return err
		}
	} else {
		if err := _tinybindWrite(w, "\n    <p>inactive</p>\n  "); err != nil {
			return err
		}
	}
	if err := _tinybindWrite(w, "\n</article>\n"); err != nil {
		return err
	}
	return nil
}
