// Code generated by tinybind; DO NOT EDIT.

package id_

import (
	"net/http"

	httpbind "github.com/shibukawa/tinybind-go"
)

// RouteParams holds the URL inputs of GET /records/{id}.
type RouteParams struct {
	ID string
}

// DecodeRoute reads the path and query values of GET /records/{id}.
// An unparsable value produces an error rather than a zero value.
func DecodeRoute(r *http.Request) (RouteParams, error) {
	var out RouteParams
	rawID := httpbind.PathValue(r, "id")
	if rawID == "" {
		return out, httpbind.BadRequest(httpbind.Problem{Code: "missing_path_parameter", Message: "missing path parameter id"})
	}
	out.ID = rawID
	return out, nil
}
