// Code generated by tinybind; DO NOT EDIT.

package dynamofixture

import (
	"context"
	"iter"

	"github.com/shibukawa/tinybind-go/dynamobind"
	"github.com/shibukawa/tinygodriver/nosql/dynamodb"
)

// readingsSinceTable is the table ReadingsSince declares.
const readingsSinceTable = "readings"

// readingsSinceKeyCondition is the key condition of ReadingsSince.
const readingsSinceKeyCondition = "#k0 = :v0 AND #k1 > :v1"

var readingsSinceAttributeNames = map[string]string{
	"#k0": "sensor",
	"#k1": "at",
}

// ReadingsSince queries Reading in readings.
func ReadingsSince(ctx context.Context, sensor Sensor, from int64, opts ...dynamodb.QueryOption) iter.Seq2[Reading, error] {
	values := map[string]dynamodb.AttributeValue{
		":v0": dynamodb.S(string(sensor)),
		":v1": dynamodb.N(from),
	}
	opts = append(opts,
		dynamodb.WithExpressionNames(readingsSinceAttributeNames),
		dynamodb.WithExpressionValues(values),
	)
	return dynamobind.Query[Reading](ctx, readingsSinceTable, readingsSinceKeyCondition, opts...)
}

// readingsBetweenTable is the table ReadingsBetween declares.
const readingsBetweenTable = "readings"

// readingsBetweenKeyCondition is the key condition of ReadingsBetween.
const readingsBetweenKeyCondition = "#k0 = :v0 AND #k1 BETWEEN :v1 AND :v2"

var readingsBetweenAttributeNames = map[string]string{
	"#k0": "sensor",
	"#k1": "at",
}

// ReadingsBetween queries Reading in readings.
func ReadingsBetween(ctx context.Context, sensor Sensor, low int64, high int64, opts ...dynamodb.QueryOption) (dynamobind.Page[Reading], error) {
	values := map[string]dynamodb.AttributeValue{
		":v0": dynamodb.S(string(sensor)),
		":v1": dynamodb.N(low),
		":v2": dynamodb.N(high),
	}
	opts = append(opts,
		dynamodb.WithExpressionNames(readingsBetweenAttributeNames),
		dynamodb.WithExpressionValues(values),
	)
	return dynamobind.QueryPage[Reading](ctx, readingsBetweenTable, readingsBetweenKeyCondition, opts...)
}

// readingsForSensorTable is the table ReadingsForSensor declares.
const readingsForSensorTable = "readings"

// readingsForSensorKeyCondition is the key condition of ReadingsForSensor.
const readingsForSensorKeyCondition = "#k0 = :v0"

var readingsForSensorAttributeNames = map[string]string{
	"#k0": "sensor",
}

// ReadingsForSensor queries Reading in readings.
func ReadingsForSensor(ctx context.Context, sensor Sensor, opts ...dynamodb.QueryOption) iter.Seq2[Reading, error] {
	values := map[string]dynamodb.AttributeValue{
		":v0": dynamodb.S(string(sensor)),
	}
	opts = append(opts,
		dynamodb.WithExpressionNames(readingsForSensorAttributeNames),
		dynamodb.WithExpressionValues(values),
	)
	return dynamobind.Query[Reading](ctx, readingsForSensorTable, readingsForSensorKeyCondition, opts...)
}
