// Code generated by tinybind; DO NOT EDIT.

package dynamofixture

import (
	"strconv"
	"time"

	"github.com/shibukawa/tinybind-go/dynamobind"
	"github.com/shibukawa/tinygodriver/nosql/dynamodb"
)

var _ dynamobind.ItemEncoder = Reading{}
var _ dynamobind.ItemDecoder = (*Reading)(nil)
var _ dynamobind.Keyer = Reading{}

// EncodeItem converts Reading into a DynamoDB item.
func (v Reading) EncodeItem() dynamodb.Item {
	item := make(dynamodb.Item, 18)
	item["sensor"] = dynamodb.S(string(v.Sensor))
	item["at"] = dynamodb.N(v.At)
	item["note"] = dynamodb.S(string(v.Note))
	item["scale"] = dynamodb.N(v.Scale)
	item["count"] = dynamodb.N(v.Count)
	item["active"] = dynamodb.Bool(bool(v.Active))
	item["blob"] = dynamodb.B([]byte(v.Blob))
	item["taken"] = dynamodb.S(v.Taken.UTC().Format(time.RFC3339Nano))
	item["seen"] = dynamodb.N(v.Seen.Unix())
	if len(v.Tags) != 0 {
		set1 := make([]string, 0, len(v.Tags))
		for _, member := range v.Tags {
			set1 = append(set1, string(member))
		}
		item["tags"] = dynamodb.SS(set1...)
	}
	if len(v.Counts) != 0 {
		set2 := make([]string, 0, len(v.Counts))
		for _, member := range v.Counts {
			set2 = append(set2, strconv.FormatInt(int64(member), 10))
		}
		item["counts"] = dynamodb.NS(set2...)
	}
	if len(v.Chunks) != 0 {
		set3 := make([][]byte, 0, len(v.Chunks))
		for _, member := range v.Chunks {
			set3 = append(set3, []byte(member))
		}
		item["chunks"] = dynamodb.BS(set3...)
	}
	list4 := make([]dynamodb.AttributeValue, 0, len(v.Words))
	for _, member := range v.Words {
		element5 := dynamodb.S(string(member))
		list4 = append(list4, element5)
	}
	item["words"] = dynamodb.List(list4...)
	entries6 := make(map[string]dynamodb.AttributeValue, len(v.Scores))
	for key, member := range v.Scores {
		element7 := dynamodb.N(member)
		entries6[string(key)] = element7
	}
	item["scores"] = dynamodb.Map(entries6)
	if len(v.Sites) != 0 {
		entries8 := make(map[string]dynamodb.AttributeValue, len(v.Sites))
		for key, member := range v.Sites {
			element9 := dynamodb.S(string(member))
			entries8[string(key)] = element9
		}
		item["sites"] = dynamodb.Map(entries8)
	}
	item["site"] = dynamodb.Map(v.Site.EncodeItem())
	if v.Backup == nil {
		item["backup"] = dynamodb.Null()
	} else {
		item["backup"] = dynamodb.Map((*v.Backup).EncodeItem())
	}
	if v.Exact.Kind() != dynamodb.KindNone {
		item["exact"] = v.Exact
	}
	return item
}

// DecodeItem fills Reading from a DynamoDB item. An attribute the item does
// not carry leaves its field untouched.
func (v *Reading) DecodeItem(item dynamodb.Item) error {
	if attr10, ok := item["sensor"]; ok {
		text11, ok := attr10.AsString()
		if !ok {
			return dynamobind.TypeError("sensor", "S", attr10)
		}
		v.Sensor = Sensor(text11)
	}
	if attr12, ok := item["at"]; ok {
		text13, ok := attr12.AsNumber()
		if !ok {
			return dynamobind.TypeError("at", "N", attr12)
		}
		number14, err := strconv.ParseInt(text13, 10, 64)
		if err != nil {
			return dynamobind.ValueError("at", "number is not a signed integer", err)
		}
		v.At = int64(number14)
	}
	if attr15, ok := item["note"]; ok {
		text16, ok := attr15.AsString()
		if !ok {
			return dynamobind.TypeError("note", "S", attr15)
		}
		v.Note = string(text16)
	}
	if attr17, ok := item["scale"]; ok {
		text18, ok := attr17.AsNumber()
		if !ok {
			return dynamobind.TypeError("scale", "N", attr17)
		}
		number19, err := strconv.ParseFloat(text18, 32)
		if err != nil {
			return dynamobind.ValueError("scale", "number is not a float", err)
		}
		v.Scale = float32(number19)
	}
	if attr20, ok := item["count"]; ok {
		text21, ok := attr20.AsNumber()
		if !ok {
			return dynamobind.TypeError("count", "N", attr20)
		}
		number22, err := strconv.ParseUint(text21, 10, 16)
		if err != nil {
			return dynamobind.ValueError("count", "number is not a unsigned integer", err)
		}
		v.Count = uint16(number22)
	}
	if attr23, ok := item["active"]; ok {
		flag24, ok := attr23.AsBool()
		if !ok {
			return dynamobind.TypeError("active", "BOOL", attr23)
		}
		v.Active = bool(flag24)
	}
	if attr25, ok := item["blob"]; ok {
		binary26, ok := attr25.AsBytes()
		if !ok {
			return dynamobind.TypeError("blob", "B", attr25)
		}
		v.Blob = []byte(binary26)
	}
	if attr27, ok := item["taken"]; ok {
		text28, ok := attr27.AsString()
		if !ok {
			return dynamobind.TypeError("taken", "S", attr27)
		}
		when29, err := time.Parse(time.RFC3339Nano, text28)
		if err != nil {
			return dynamobind.ValueError("taken", "time is not RFC 3339", err)
		}
		v.Taken = when29
	}
	if attr30, ok := item["seen"]; ok {
		text31, ok := attr30.AsNumber()
		if !ok {
			return dynamobind.TypeError("seen", "N", attr30)
		}
		seconds32, err := strconv.ParseInt(text31, 10, 64)
		if err != nil {
			return dynamobind.ValueError("seen", "unix time is not an int64", err)
		}
		v.Seen = time.Unix(seconds32, 0).UTC()
	}
	if attr33, ok := item["tags"]; ok {
		if attr33.Kind() != dynamodb.KindStringSet {
			return dynamobind.TypeError("tags", "SS", attr33)
		}
		members34 := make([]string, 0, len(attr33.SS))
		for _, member := range attr33.SS {
			members34 = append(members34, string(member))
		}
		v.Tags = members34
	}
	if attr35, ok := item["counts"]; ok {
		if attr35.Kind() != dynamodb.KindNumberSet {
			return dynamobind.TypeError("counts", "NS", attr35)
		}
		members36 := make([]int, 0, len(attr35.NS))
		for _, member := range attr35.NS {
			number37, err := strconv.ParseInt(member, 10, 0)
			if err != nil {
				return dynamobind.ValueError("counts", "number is not a signed integer", err)
			}
			members36 = append(members36, int(number37))
		}
		v.Counts = members36
	}
	if attr38, ok := item["chunks"]; ok {
		if attr38.Kind() != dynamodb.KindBinarySet {
			return dynamobind.TypeError("chunks", "BS", attr38)
		}
		members39 := make([][]byte, 0, len(attr38.BS))
		for _, member := range attr38.BS {
			members39 = append(members39, []byte(member))
		}
		v.Chunks = members39
	}
	if attr40, ok := item["words"]; ok {
		list41, ok := attr40.AsList()
		if !ok {
			return dynamobind.TypeError("words", "L", attr40)
		}
		members42 := make([]Sensor, 0, len(list41))
		for _, member := range list41 {
			var value43 Sensor
			text44, ok := member.AsString()
			if !ok {
				return dynamobind.TypeError("words", "S", member)
			}
			value43 = Sensor(text44)
			members42 = append(members42, value43)
		}
		v.Words = members42
	}
	if attr45, ok := item["scores"]; ok {
		entries46, ok := attr45.AsMap()
		if !ok {
			return dynamobind.TypeError("scores", "M", attr45)
		}
		members47 := make(map[string]int32, len(entries46))
		for key, member := range entries46 {
			var value48 int32
			text49, ok := member.AsNumber()
			if !ok {
				return dynamobind.TypeError("scores", "N", member)
			}
			number50, err := strconv.ParseInt(text49, 10, 32)
			if err != nil {
				return dynamobind.ValueError("scores", "number is not a signed integer", err)
			}
			value48 = int32(number50)
			members47[string(key)] = value48
		}
		v.Scores = members47
	}
	if attr51, ok := item["sites"]; ok {
		entries52, ok := attr51.AsMap()
		if !ok {
			return dynamobind.TypeError("sites", "M", attr51)
		}
		members53 := make(map[string]string, len(entries52))
		for key, member := range entries52 {
			var value54 string
			text55, ok := member.AsString()
			if !ok {
				return dynamobind.TypeError("sites", "S", member)
			}
			value54 = string(text55)
			members53[string(key)] = value54
		}
		v.Sites = members53
	}
	if attr56, ok := item["site"]; ok {
		entries57, ok := attr56.AsMap()
		if !ok {
			return dynamobind.TypeError("site", "M", attr56)
		}
		if err := v.Site.DecodeItem(entries57); err != nil {
			return err
		}
	}
	if attr58, ok := item["backup"]; ok {
		if attr58.IsNull() {
			v.Backup = nil
		} else {
			var value59 Site
			entries60, ok := attr58.AsMap()
			if !ok {
				return dynamobind.TypeError("backup", "M", attr58)
			}
			if err := value59.DecodeItem(entries60); err != nil {
				return err
			}
			v.Backup = &value59
		}
	}
	if attr61, ok := item["exact"]; ok {
		v.Exact = attr61
	}
	return nil
}

// ItemKey returns the primary key of Reading.
func (v Reading) ItemKey() dynamodb.Key {
	return dynamodb.Key{
		"sensor": dynamodb.S(string(v.Sensor)),
		"at":     dynamodb.N(v.At),
	}
}

// ReadingTable describes the table Reading is stored in. The key names come from
// the same tags as the codec, so they cannot drift apart.
func ReadingTable(name string) dynamodb.TableDefinition {
	return dynamodb.TableDefinition{
		Name:         name,
		PartitionKey: dynamodb.KeyAttribute{Name: "sensor", Type: dynamodb.TypeString},
		SortKey:      &dynamodb.KeyAttribute{Name: "at", Type: dynamodb.TypeNumber},
	}
}

var _ dynamobind.ItemEncoder = Site{}
var _ dynamobind.ItemDecoder = (*Site)(nil)

// EncodeItem converts Site into a DynamoDB item.
func (v Site) EncodeItem() dynamodb.Item {
	item := make(dynamodb.Item, 2)
	item["city"] = dynamodb.S(string(v.City))
	if v.Zip != "" {
		item["zip"] = dynamodb.S(string(v.Zip))
	}
	return item
}

// DecodeItem fills Site from a DynamoDB item. An attribute the item does
// not carry leaves its field untouched.
func (v *Site) DecodeItem(item dynamodb.Item) error {
	if attr1, ok := item["city"]; ok {
		text2, ok := attr1.AsString()
		if !ok {
			return dynamobind.TypeError("city", "S", attr1)
		}
		v.City = string(text2)
	}
	if attr3, ok := item["zip"]; ok {
		text4, ok := attr3.AsString()
		if !ok {
			return dynamobind.TypeError("zip", "S", attr3)
		}
		v.Zip = string(text4)
	}
	return nil
}
