// Code generated by httpbinder; DO NOT EDIT.

package openapifixture

import (
	"encoding/json"
	"net/http"

	"github.com/shibukawa/httpbind-go"
)

type jsonRaw = json.RawMessage

func init() {
	httpbinder.RegisterBind[CreateUserRequest](bindCreateUserRequest)
	httpbinder.RegisterWrite[CreateUserRequest](writeCreateUserRequest)
	httpbinder.RegisterBind[CreateUserResponse](bindCreateUserResponse)
	httpbinder.RegisterWrite[CreateUserResponse](writeCreateUserResponse)
	httpbinder.RegisterBind[SearchRequest](bindSearchRequest)
	httpbinder.RegisterWrite[SearchRequest](writeSearchRequest)
	httpbinder.RegisterBind[SearchResponse](bindSearchResponse)
	httpbinder.RegisterWrite[SearchResponse](writeSearchResponse)
}

func bindCreateUserRequest(r *http.Request) (CreateUserRequest, error) {
	var out CreateUserRequest
	var jsonBody map[string]jsonRaw
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbinder.IsJSONRequest(r) {
			m, err := httpbinder.ReadJSONMap(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbinder.IsFormRequest(r) {
			m, err := httpbinder.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbinder.IsMultipartRequest(r) {
			m, _, err := httpbinder.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		return nil
	}
	if qv, ok := httpbinder.QueryValue(r, "name"); ok {
		out.Name = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["name"]; ok {
			v, err := httpbinder.DecodeJSONString(raw)
			if err != nil {
				return out, httpbinder.BindError("name", "payload", "invalid string")
			}
			out.Name = v
		} else if formBody != nil {
			if fv, ok := formBody["name"]; ok {
				out.Name = fv
			}
		}
	}
	if qv, ok := httpbinder.QueryValue(r, "email"); ok {
		out.Email = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["email"]; ok {
			v, err := httpbinder.DecodeJSONString(raw)
			if err != nil {
				return out, httpbinder.BindError("email", "payload", "invalid string")
			}
			out.Email = v
		} else if formBody != nil {
			if fv, ok := formBody["email"]; ok {
				out.Email = fv
			}
		}
	}
	out.OrgID = httpbinder.PathValue(r, "org_id")
	out.Token = httpbinder.HeaderValue(r, "Authorization")
	return out, nil
}

func writeCreateUserRequest(w http.ResponseWriter, r *http.Request, v CreateUserRequest) error {
	_ = r
	body := map[string]any{
		"name":          v.Name,
		"email":         v.Email,
		"org_id":        v.OrgID,
		"Authorization": v.Token,
	}
	return httpbinder.WriteJSON(w, http.StatusOK, body)
}

func bindCreateUserResponse(r *http.Request) (CreateUserResponse, error) {
	var out CreateUserResponse
	var jsonBody map[string]jsonRaw
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbinder.IsJSONRequest(r) {
			m, err := httpbinder.ReadJSONMap(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbinder.IsFormRequest(r) {
			m, err := httpbinder.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbinder.IsMultipartRequest(r) {
			m, _, err := httpbinder.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		return nil
	}
	if qv, ok := httpbinder.QueryValue(r, "iD"); ok {
		out.ID = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["iD"]; ok {
			v, err := httpbinder.DecodeJSONString(raw)
			if err != nil {
				return out, httpbinder.BindError("iD", "payload", "invalid string")
			}
			out.ID = v
		} else if formBody != nil {
			if fv, ok := formBody["iD"]; ok {
				out.ID = fv
			}
		}
	}
	if qv, ok := httpbinder.QueryValue(r, "name"); ok {
		out.Name = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["name"]; ok {
			v, err := httpbinder.DecodeJSONString(raw)
			if err != nil {
				return out, httpbinder.BindError("name", "payload", "invalid string")
			}
			out.Name = v
		} else if formBody != nil {
			if fv, ok := formBody["name"]; ok {
				out.Name = fv
			}
		}
	}
	if qv, ok := httpbinder.QueryValue(r, "email"); ok {
		out.Email = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["email"]; ok {
			v, err := httpbinder.DecodeJSONString(raw)
			if err != nil {
				return out, httpbinder.BindError("email", "payload", "invalid string")
			}
			out.Email = v
		} else if formBody != nil {
			if fv, ok := formBody["email"]; ok {
				out.Email = fv
			}
		}
	}
	return out, nil
}

func writeCreateUserResponse(w http.ResponseWriter, r *http.Request, v CreateUserResponse) error {
	_ = r
	body := map[string]any{
		"id":    v.ID,
		"name":  v.Name,
		"email": v.Email,
	}
	return httpbinder.WriteJSON(w, http.StatusOK, body)
}

func bindSearchRequest(r *http.Request) (SearchRequest, error) {
	var out SearchRequest
	var jsonBody map[string]jsonRaw
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbinder.IsJSONRequest(r) {
			m, err := httpbinder.ReadJSONMap(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbinder.IsFormRequest(r) {
			m, err := httpbinder.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbinder.IsMultipartRequest(r) {
			m, _, err := httpbinder.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		return nil
	}
	if qv, ok := httpbinder.QueryValue(r, "keyword"); ok {
		out.Keyword = qv
	}
	if qv, ok := httpbinder.QueryValue(r, "page"); ok {
		v, err := httpbinder.ParseInt(qv)
		if err != nil {
			return out, httpbinder.BindError("page", "query", "invalid int")
		}
		out.Page = v
	}
	if err := readBody(); err != nil {
		return out, err
	}
	if raw, ok := jsonBody["filter"]; ok {
		v, err := httpbinder.DecodeJSONString(raw)
		if err != nil {
			return out, httpbinder.BindError("filter", "payload", "invalid string")
		}
		out.Filter = v
	} else if formBody != nil {
		if fv, ok := formBody["filter"]; ok {
			out.Filter = fv
		}
	}
	return out, nil
}

func writeSearchRequest(w http.ResponseWriter, r *http.Request, v SearchRequest) error {
	_ = r
	body := map[string]any{
		"keyword": v.Keyword,
		"page":    v.Page,
		"filter":  v.Filter,
	}
	return httpbinder.WriteJSON(w, http.StatusOK, body)
}

func bindSearchResponse(r *http.Request) (SearchResponse, error) {
	var out SearchResponse
	var jsonBody map[string]jsonRaw
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbinder.IsJSONRequest(r) {
			m, err := httpbinder.ReadJSONMap(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbinder.IsFormRequest(r) {
			m, err := httpbinder.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbinder.IsMultipartRequest(r) {
			m, _, err := httpbinder.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		return nil
	}
	if qv, ok := httpbinder.QueryValue(r, "keyword"); ok {
		out.Keyword = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["keyword"]; ok {
			v, err := httpbinder.DecodeJSONString(raw)
			if err != nil {
				return out, httpbinder.BindError("keyword", "payload", "invalid string")
			}
			out.Keyword = v
		} else if formBody != nil {
			if fv, ok := formBody["keyword"]; ok {
				out.Keyword = fv
			}
		}
	}
	if qv, ok := httpbinder.QueryValue(r, "page"); ok {
		v, err := httpbinder.ParseInt(qv)
		if err != nil {
			return out, httpbinder.BindError("page", "query", "invalid int")
		}
		out.Page = v
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["page"]; ok {
			v, err := httpbinder.DecodeJSONInt(raw)
			if err != nil {
				return out, httpbinder.BindError("page", "payload", "invalid int")
			}
			out.Page = v
		} else if formBody != nil {
			if fv, ok := formBody["page"]; ok {
				v, err := httpbinder.ParseInt(fv)
				if err != nil {
					return out, httpbinder.BindError("page", "payload", "invalid int")
				}
				out.Page = v
			}
		}
	}
	if qv, ok := httpbinder.QueryValue(r, "filter"); ok {
		out.Filter = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["filter"]; ok {
			v, err := httpbinder.DecodeJSONString(raw)
			if err != nil {
				return out, httpbinder.BindError("filter", "payload", "invalid string")
			}
			out.Filter = v
		} else if formBody != nil {
			if fv, ok := formBody["filter"]; ok {
				out.Filter = fv
			}
		}
	}
	return out, nil
}

func writeSearchResponse(w http.ResponseWriter, r *http.Request, v SearchResponse) error {
	_ = r
	body := map[string]any{
		"keyword": v.Keyword,
		"page":    v.Page,
		"filter":  v.Filter,
	}
	return httpbinder.WriteJSON(w, http.StatusOK, body)
}
