// Code generated by tinybind; DO NOT EDIT.
// tinybind:generated v1 inputs=sha256:1904db67bdcab70e0dd6a2b2519da17b096020ce666a537b96b2dfa11b244c53 self=sha256:5d9c1ece93a09f8479a4cb19fd476fd49b897e36e6cbcbe04ac630a09f156321 outputs=tinybind_gen.go

package openapifixture

import (
	"io"
	"net/http"

	"github.com/shibukawa/tinybind-go"
	"github.com/shibukawa/tinybind-go/jsonbind"
)

func init() {
	httpbind.RegisterBind[CreateUserRequest](bindCreateUserRequest)
	httpbind.RegisterWrite[CreateUserRequest](writeCreateUserRequest)
	jsonbind.RegisterDecode[CreateUserRequest](decodeCreateUserRequestBytes)
	jsonbind.RegisterEncode[CreateUserRequest](encodeCreateUserRequest)
	httpbind.RegisterBind[CreateUserResponse](bindCreateUserResponse)
	httpbind.RegisterWrite[CreateUserResponse](writeCreateUserResponse)
	jsonbind.RegisterDecode[CreateUserResponse](decodeCreateUserResponseBytes)
	jsonbind.RegisterEncode[CreateUserResponse](encodeCreateUserResponse)
	httpbind.RegisterBind[SearchRequest](bindSearchRequest)
	httpbind.RegisterWrite[SearchRequest](writeSearchRequest)
	jsonbind.RegisterDecode[SearchRequest](decodeSearchRequestBytes)
	jsonbind.RegisterEncode[SearchRequest](encodeSearchRequest)
	httpbind.RegisterBind[SearchResponse](bindSearchResponse)
	httpbind.RegisterWrite[SearchResponse](writeSearchResponse)
	jsonbind.RegisterDecode[SearchResponse](decodeSearchResponseBytes)
	jsonbind.RegisterEncode[SearchResponse](encodeSearchResponse)
}

func decodeCreateUserRequestBytes(data []byte) (CreateUserRequest, error) {
	if jsonbind.IsBlank(data) {
		var out CreateUserRequest
		return out, nil
	}
	p := jsonbind.NewParser(data)
	out, err := decodeCreateUserRequestJSON(p)
	if err != nil {
		return out, err
	}
	if err := p.End(); err != nil {
		return out, err
	}
	return out, nil
}

func decodeCreateUserRequestJSON(p *jsonbind.Parser) (CreateUserRequest, error) {
	var out CreateUserRequest
	null, err := p.ObjectStart()
	if err != nil || null {
		return out, err
	}
	for n := 0; ; n++ {
		key, ok, err := p.ObjectKey(n)
		if err != nil {
			return out, err
		}
		if !ok {
			return out, nil
		}
		switch string(key) {
		case "name":
			v, err := p.String()
			if err != nil {
				return out, jsonbind.FieldError("name", "invalid string", err)
			}
			out.Name = v
		case "email":
			v, err := p.String()
			if err != nil {
				return out, jsonbind.FieldError("email", "invalid string", err)
			}
			out.Email = v
		default:
			if err := p.SkipValue(); err != nil {
				return out, err
			}
		}
	}
}

func appendCreateUserRequestJSON(dst []byte, v CreateUserRequest) []byte {
	dst = append(dst, '{')
	dst = append(dst, "\"name\":"...)
	dst = jsonbind.AppendString(dst, v.Name)
	dst = append(dst, ",\"email\":"...)
	dst = jsonbind.AppendString(dst, v.Email)
	dst = append(dst, ",\"org_id\":"...)
	dst = jsonbind.AppendString(dst, v.OrgID)
	dst = append(dst, ",\"Authorization\":"...)
	dst = jsonbind.AppendString(dst, v.Token)
	return append(dst, '}')
}

func encodeCreateUserRequest(w io.Writer, v CreateUserRequest) error {
	buf := jsonbind.GetBuffer()
	*buf = appendCreateUserRequestJSON((*buf)[:0], v)
	*buf = append(*buf, '\n')
	_, err := w.Write(*buf)
	jsonbind.PutBuffer(buf)
	return err
}

func bindCreateUserRequest(r *http.Request) (CreateUserRequest, error) {
	var out CreateUserRequest
	var jsonBody *jsonbind.Object
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbind.IsJSONRequest(r) {
			m, err := httpbind.ReadJSONObject(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbind.IsFormRequest(r) {
			m, err := httpbind.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbind.IsMultipartRequest(r) {
			m, _, err := httpbind.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		return nil
	}
	if qv, ok := httpbind.QueryValue(r, "name"); ok {
		out.Name = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody.Get("name"); ok {
			v, err := jsonbind.DecodeJSONString(raw)
			if err != nil {
				return out, jsonbind.FieldError("name", "invalid string", err)
			}
			out.Name = v
		} else if formBody != nil {
			if fv, ok := formBody["name"]; ok {
				out.Name = fv
			}
		}
	}
	if qv, ok := httpbind.QueryValue(r, "email"); ok {
		out.Email = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody.Get("email"); ok {
			v, err := jsonbind.DecodeJSONString(raw)
			if err != nil {
				return out, jsonbind.FieldError("email", "invalid string", err)
			}
			out.Email = v
		} else if formBody != nil {
			if fv, ok := formBody["email"]; ok {
				out.Email = fv
			}
		}
	}
	out.OrgID = httpbind.PathValue(r, "org_id")
	out.Token = httpbind.HeaderValue(r, "Authorization")
	return out, nil
}

func writeCreateUserRequest(w http.ResponseWriter, r *http.Request, v CreateUserRequest) error {
	_ = r
	buf := jsonbind.GetBuffer()
	*buf = appendCreateUserRequestJSON((*buf)[:0], v)
	err := httpbind.WriteJSONBytes(w, http.StatusOK, *buf)
	jsonbind.PutBuffer(buf)
	return err
}

func decodeCreateUserResponseBytes(data []byte) (CreateUserResponse, error) {
	if jsonbind.IsBlank(data) {
		var out CreateUserResponse
		return out, nil
	}
	p := jsonbind.NewParser(data)
	out, err := decodeCreateUserResponseJSON(p)
	if err != nil {
		return out, err
	}
	if err := p.End(); err != nil {
		return out, err
	}
	return out, nil
}

func decodeCreateUserResponseJSON(p *jsonbind.Parser) (CreateUserResponse, error) {
	var out CreateUserResponse
	null, err := p.ObjectStart()
	if err != nil || null {
		return out, err
	}
	for n := 0; ; n++ {
		key, ok, err := p.ObjectKey(n)
		if err != nil {
			return out, err
		}
		if !ok {
			return out, nil
		}
		switch string(key) {
		case "id":
			v, err := p.String()
			if err != nil {
				return out, jsonbind.FieldError("iD", "invalid string", err)
			}
			out.ID = v
		case "name":
			v, err := p.String()
			if err != nil {
				return out, jsonbind.FieldError("name", "invalid string", err)
			}
			out.Name = v
		case "email":
			v, err := p.String()
			if err != nil {
				return out, jsonbind.FieldError("email", "invalid string", err)
			}
			out.Email = v
		default:
			if err := p.SkipValue(); err != nil {
				return out, err
			}
		}
	}
}

func appendCreateUserResponseJSON(dst []byte, v CreateUserResponse) []byte {
	dst = append(dst, '{')
	dst = append(dst, "\"id\":"...)
	dst = jsonbind.AppendString(dst, v.ID)
	dst = append(dst, ",\"name\":"...)
	dst = jsonbind.AppendString(dst, v.Name)
	dst = append(dst, ",\"email\":"...)
	dst = jsonbind.AppendString(dst, v.Email)
	return append(dst, '}')
}

func encodeCreateUserResponse(w io.Writer, v CreateUserResponse) error {
	buf := jsonbind.GetBuffer()
	*buf = appendCreateUserResponseJSON((*buf)[:0], v)
	*buf = append(*buf, '\n')
	_, err := w.Write(*buf)
	jsonbind.PutBuffer(buf)
	return err
}

func bindCreateUserResponse(r *http.Request) (CreateUserResponse, error) {
	var out CreateUserResponse
	var jsonBody *jsonbind.Object
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbind.IsJSONRequest(r) {
			m, err := httpbind.ReadJSONObject(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbind.IsFormRequest(r) {
			m, err := httpbind.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbind.IsMultipartRequest(r) {
			m, _, err := httpbind.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		return nil
	}
	if qv, ok := httpbind.QueryValue(r, "iD"); ok {
		out.ID = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody.Get("iD"); ok {
			v, err := jsonbind.DecodeJSONString(raw)
			if err != nil {
				return out, jsonbind.FieldError("iD", "invalid string", err)
			}
			out.ID = v
		} else if formBody != nil {
			if fv, ok := formBody["iD"]; ok {
				out.ID = fv
			}
		}
	}
	if qv, ok := httpbind.QueryValue(r, "name"); ok {
		out.Name = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody.Get("name"); ok {
			v, err := jsonbind.DecodeJSONString(raw)
			if err != nil {
				return out, jsonbind.FieldError("name", "invalid string", err)
			}
			out.Name = v
		} else if formBody != nil {
			if fv, ok := formBody["name"]; ok {
				out.Name = fv
			}
		}
	}
	if qv, ok := httpbind.QueryValue(r, "email"); ok {
		out.Email = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody.Get("email"); ok {
			v, err := jsonbind.DecodeJSONString(raw)
			if err != nil {
				return out, jsonbind.FieldError("email", "invalid string", err)
			}
			out.Email = v
		} else if formBody != nil {
			if fv, ok := formBody["email"]; ok {
				out.Email = fv
			}
		}
	}
	return out, nil
}

func writeCreateUserResponse(w http.ResponseWriter, r *http.Request, v CreateUserResponse) error {
	_ = r
	buf := jsonbind.GetBuffer()
	*buf = appendCreateUserResponseJSON((*buf)[:0], v)
	err := httpbind.WriteJSONBytes(w, http.StatusOK, *buf)
	jsonbind.PutBuffer(buf)
	return err
}

func decodeSearchRequestBytes(data []byte) (SearchRequest, error) {
	if jsonbind.IsBlank(data) {
		var out SearchRequest
		return out, nil
	}
	p := jsonbind.NewParser(data)
	out, err := decodeSearchRequestJSON(p)
	if err != nil {
		return out, err
	}
	if err := p.End(); err != nil {
		return out, err
	}
	return out, nil
}

func decodeSearchRequestJSON(p *jsonbind.Parser) (SearchRequest, error) {
	var out SearchRequest
	null, err := p.ObjectStart()
	if err != nil || null {
		return out, err
	}
	for n := 0; ; n++ {
		key, ok, err := p.ObjectKey(n)
		if err != nil {
			return out, err
		}
		if !ok {
			return out, nil
		}
		switch string(key) {
		case "filter":
			v, err := p.String()
			if err != nil {
				return out, jsonbind.FieldError("filter", "invalid string", err)
			}
			out.Filter = v
		default:
			if err := p.SkipValue(); err != nil {
				return out, err
			}
		}
	}
}

func appendSearchRequestJSON(dst []byte, v SearchRequest) []byte {
	dst = append(dst, '{')
	dst = append(dst, "\"keyword\":"...)
	dst = jsonbind.AppendString(dst, v.Keyword)
	dst = append(dst, ",\"page\":"...)
	dst = jsonbind.AppendInt(dst, int64(v.Page))
	dst = append(dst, ",\"filter\":"...)
	dst = jsonbind.AppendString(dst, v.Filter)
	return append(dst, '}')
}

func encodeSearchRequest(w io.Writer, v SearchRequest) error {
	buf := jsonbind.GetBuffer()
	*buf = appendSearchRequestJSON((*buf)[:0], v)
	*buf = append(*buf, '\n')
	_, err := w.Write(*buf)
	jsonbind.PutBuffer(buf)
	return err
}

func bindSearchRequest(r *http.Request) (SearchRequest, error) {
	var out SearchRequest
	var jsonBody *jsonbind.Object
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbind.IsJSONRequest(r) {
			m, err := httpbind.ReadJSONObject(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbind.IsFormRequest(r) {
			m, err := httpbind.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbind.IsMultipartRequest(r) {
			m, _, err := httpbind.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		return nil
	}
	if qv, ok := httpbind.QueryValue(r, "keyword"); ok {
		out.Keyword = qv
	}
	if qv, ok := httpbind.QueryValue(r, "page"); ok {
		v, err := httpbind.ParseInt(qv)
		if err != nil {
			return out, httpbind.BindError("page", "query", "invalid int")
		}
		out.Page = v
	}
	if err := readBody(); err != nil {
		return out, err
	}
	if raw, ok := jsonBody.Get("filter"); ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("filter", "invalid string", err)
		}
		out.Filter = v
	} else if formBody != nil {
		if fv, ok := formBody["filter"]; ok {
			out.Filter = fv
		}
	}
	return out, nil
}

func writeSearchRequest(w http.ResponseWriter, r *http.Request, v SearchRequest) error {
	_ = r
	buf := jsonbind.GetBuffer()
	*buf = appendSearchRequestJSON((*buf)[:0], v)
	err := httpbind.WriteJSONBytes(w, http.StatusOK, *buf)
	jsonbind.PutBuffer(buf)
	return err
}

func decodeSearchResponseBytes(data []byte) (SearchResponse, error) {
	if jsonbind.IsBlank(data) {
		var out SearchResponse
		return out, nil
	}
	p := jsonbind.NewParser(data)
	out, err := decodeSearchResponseJSON(p)
	if err != nil {
		return out, err
	}
	if err := p.End(); err != nil {
		return out, err
	}
	return out, nil
}

func decodeSearchResponseJSON(p *jsonbind.Parser) (SearchResponse, error) {
	var out SearchResponse
	null, err := p.ObjectStart()
	if err != nil || null {
		return out, err
	}
	for n := 0; ; n++ {
		key, ok, err := p.ObjectKey(n)
		if err != nil {
			return out, err
		}
		if !ok {
			return out, nil
		}
		switch string(key) {
		case "keyword":
			v, err := p.String()
			if err != nil {
				return out, jsonbind.FieldError("keyword", "invalid string", err)
			}
			out.Keyword = v
		case "page":
			v, err := p.Int()
			if err != nil {
				return out, jsonbind.FieldError("page", "invalid int", err)
			}
			out.Page = v
		case "filter":
			v, err := p.String()
			if err != nil {
				return out, jsonbind.FieldError("filter", "invalid string", err)
			}
			out.Filter = v
		default:
			if err := p.SkipValue(); err != nil {
				return out, err
			}
		}
	}
}

func appendSearchResponseJSON(dst []byte, v SearchResponse) []byte {
	dst = append(dst, '{')
	dst = append(dst, "\"keyword\":"...)
	dst = jsonbind.AppendString(dst, v.Keyword)
	dst = append(dst, ",\"page\":"...)
	dst = jsonbind.AppendInt(dst, int64(v.Page))
	dst = append(dst, ",\"filter\":"...)
	dst = jsonbind.AppendString(dst, v.Filter)
	return append(dst, '}')
}

func encodeSearchResponse(w io.Writer, v SearchResponse) error {
	buf := jsonbind.GetBuffer()
	*buf = appendSearchResponseJSON((*buf)[:0], v)
	*buf = append(*buf, '\n')
	_, err := w.Write(*buf)
	jsonbind.PutBuffer(buf)
	return err
}

func bindSearchResponse(r *http.Request) (SearchResponse, error) {
	var out SearchResponse
	var jsonBody *jsonbind.Object
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbind.IsJSONRequest(r) {
			m, err := httpbind.ReadJSONObject(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbind.IsFormRequest(r) {
			m, err := httpbind.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbind.IsMultipartRequest(r) {
			m, _, err := httpbind.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		return nil
	}
	if qv, ok := httpbind.QueryValue(r, "keyword"); ok {
		out.Keyword = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody.Get("keyword"); ok {
			v, err := jsonbind.DecodeJSONString(raw)
			if err != nil {
				return out, jsonbind.FieldError("keyword", "invalid string", err)
			}
			out.Keyword = v
		} else if formBody != nil {
			if fv, ok := formBody["keyword"]; ok {
				out.Keyword = fv
			}
		}
	}
	if qv, ok := httpbind.QueryValue(r, "page"); ok {
		v, err := httpbind.ParseInt(qv)
		if err != nil {
			return out, httpbind.BindError("page", "query", "invalid int")
		}
		out.Page = v
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody.Get("page"); ok {
			v, err := jsonbind.DecodeJSONInt(raw)
			if err != nil {
				return out, jsonbind.FieldError("page", "invalid int", err)
			}
			out.Page = v
		} else if formBody != nil {
			if fv, ok := formBody["page"]; ok {
				v, err := httpbind.ParseInt(fv)
				if err != nil {
					return out, httpbind.BindError("page", "payload", "invalid int")
				}
				out.Page = v
			}
		}
	}
	if qv, ok := httpbind.QueryValue(r, "filter"); ok {
		out.Filter = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody.Get("filter"); ok {
			v, err := jsonbind.DecodeJSONString(raw)
			if err != nil {
				return out, jsonbind.FieldError("filter", "invalid string", err)
			}
			out.Filter = v
		} else if formBody != nil {
			if fv, ok := formBody["filter"]; ok {
				out.Filter = fv
			}
		}
	}
	return out, nil
}

func writeSearchResponse(w http.ResponseWriter, r *http.Request, v SearchResponse) error {
	_ = r
	buf := jsonbind.GetBuffer()
	*buf = appendSearchResponseJSON((*buf)[:0], v)
	err := httpbind.WriteJSONBytes(w, http.StatusOK, *buf)
	jsonbind.PutBuffer(buf)
	return err
}
