// Code generated by tinybind; DO NOT EDIT.
// tinybind:generated v1 inputs=sha256:933d57ba9318293bad93f8b7562165d04e94002e63d2e1dd07e0a2c2e846bbe7 self=sha256:0507d358d6b8e1c7618327bdc50eb9629012b1e0121c438a8dae1529a09be512 outputs=tinybind_gen.go,tinybind_openapi_gen.go

package openapifixture

import (
	"io"
	"net/http"

	"github.com/shibukawa/tinybind-go"
	"github.com/shibukawa/tinybind-go/jsonbind"
)

func init() {
	httpbind.RegisterBind[CreateUserRequest](bindCreateUserRequest)
	httpbind.RegisterWrite[CreateUserRequest](writeCreateUserRequest)
	jsonbind.RegisterDecode[CreateUserRequest](decodeCreateUserRequestBytes)
	jsonbind.RegisterEncode[CreateUserRequest](encodeCreateUserRequest)
	jsonbind.RegisterAppend[CreateUserRequest](appendCreateUserRequestJSON)
	httpbind.RegisterBind[CreateUserResponse](bindCreateUserResponse)
	httpbind.RegisterWrite[CreateUserResponse](writeCreateUserResponse)
	jsonbind.RegisterDecode[CreateUserResponse](decodeCreateUserResponseBytes)
	jsonbind.RegisterEncode[CreateUserResponse](encodeCreateUserResponse)
	jsonbind.RegisterAppend[CreateUserResponse](appendCreateUserResponseJSON)
	httpbind.RegisterBind[SearchRequest](bindSearchRequest)
	httpbind.RegisterWrite[SearchRequest](writeSearchRequest)
	jsonbind.RegisterDecode[SearchRequest](decodeSearchRequestBytes)
	jsonbind.RegisterEncode[SearchRequest](encodeSearchRequest)
	jsonbind.RegisterAppend[SearchRequest](appendSearchRequestJSON)
	httpbind.RegisterBind[SearchResponse](bindSearchResponse)
	httpbind.RegisterWrite[SearchResponse](writeSearchResponse)
	jsonbind.RegisterDecode[SearchResponse](decodeSearchResponseBytes)
	jsonbind.RegisterEncode[SearchResponse](encodeSearchResponse)
	jsonbind.RegisterAppend[SearchResponse](appendSearchResponseJSON)
}

func decodeCreateUserRequestBytes(data []byte) (CreateUserRequest, error) {
	if jsonbind.IsBlank(data) {
		var out CreateUserRequest
		return out, nil
	}
	var p jsonbind.Parser
	p.Reset(data)
	out, err := decodeCreateUserRequestJSON(&p)
	if err != nil {
		return out, err
	}
	if err := p.End(); err != nil {
		return out, err
	}
	return out, nil
}

func decodeCreateUserRequestJSON(p *jsonbind.Parser) (CreateUserRequest, error) {
	var out CreateUserRequest
	null, err := p.ObjectStart()
	if err != nil || null {
		return out, err
	}
	for n := 0; ; n++ {
		key, ok, err := p.ObjectKey(n)
		if err != nil {
			return out, err
		}
		if !ok {
			return out, nil
		}
		switch string(key) {
		case "name":
			v, err := p.String()
			if err != nil {
				return out, jsonbind.FieldError("name", "invalid string", err)
			}
			out.Name = v
		case "email":
			v, err := p.String()
			if err != nil {
				return out, jsonbind.FieldError("email", "invalid string", err)
			}
			out.Email = v
		default:
			if err := p.SkipValue(); err != nil {
				return out, err
			}
		}
	}
}

func appendCreateUserRequestJSON(dst []byte, v CreateUserRequest) []byte {
	dst = append(dst, '{')
	dst = append(dst, "\"name\":"...)
	dst = jsonbind.AppendString(dst, v.Name)
	dst = append(dst, ",\"email\":"...)
	dst = jsonbind.AppendString(dst, v.Email)
	dst = append(dst, ",\"org_id\":"...)
	dst = jsonbind.AppendString(dst, v.OrgID)
	dst = append(dst, ",\"Authorization\":"...)
	dst = jsonbind.AppendString(dst, v.Token)
	return append(dst, '}')
}

func encodeCreateUserRequest(w io.Writer, v CreateUserRequest) error {
	buf := jsonbind.GetBuffer()
	*buf = appendCreateUserRequestJSON((*buf)[:0], v)
	*buf = append(*buf, '\n')
	_, err := w.Write(*buf)
	jsonbind.PutBuffer(buf)
	return err
}

func bindCreateUserRequest(r *http.Request) (CreateUserRequest, error) {
	var out CreateUserRequest
	queryVals := httpbind.Queries(r)
	needName := true
	needEmail := true
	if qv, ok := httpbind.QueryLookup(queryVals, "name"); ok {
		needName = false
		out.Name = qv
	}
	if qv, ok := httpbind.QueryLookup(queryVals, "email"); ok {
		needEmail = false
		out.Email = qv
	}
	out.OrgID = httpbind.PathValue(r, "org_id")
	out.Token = httpbind.HeaderValue(r, "Authorization")
	if needName || needEmail {
		if httpbind.IsJSONRequest(r) {
			data, err := httpbind.ReadJSONBody(r)
			if err != nil {
				return out, err
			}
			if !jsonbind.IsBlank(data) {
				var bodyParser jsonbind.Parser
				bodyParser.Reset(data)
				p := &bodyParser
				null, err := p.ObjectStart()
				if err != nil {
					return out, httpbind.JSONBodyError(err)
				}
				if null {
					return out, httpbind.JSONBodyNotObject()
				}
				for n := 0; ; n++ {
					key, ok, err := p.ObjectKey(n)
					if err != nil {
						return out, httpbind.JSONBodyError(err)
					}
					if !ok {
						break
					}
					switch string(key) {
					case "name":
						if !needName {
							if err := p.SkipValue(); err != nil {
								return out, httpbind.JSONBodyError(err)
							}
							continue
						}
						v, err := p.String()
						if err != nil {
							return out, jsonbind.FieldError("name", "invalid string", err)
						}
						out.Name = v
					case "email":
						if !needEmail {
							if err := p.SkipValue(); err != nil {
								return out, httpbind.JSONBodyError(err)
							}
							continue
						}
						v, err := p.String()
						if err != nil {
							return out, jsonbind.FieldError("email", "invalid string", err)
						}
						out.Email = v
					default:
						if err := p.SkipValue(); err != nil {
							return out, httpbind.JSONBodyError(err)
						}
					}
				}
				if err := p.End(); err != nil {
					return out, httpbind.JSONBodyError(err)
				}
			}
		} else {
			formBody, _, err := httpbind.ReadFormBody(r, true, false)
			if err != nil {
				return out, err
			}
			if needName && formBody != nil {
				if fv, ok := formBody["name"]; ok {
					out.Name = fv
				}
			}
			if needEmail && formBody != nil {
				if fv, ok := formBody["email"]; ok {
					out.Email = fv
				}
			}
		}
	}
	return out, nil
}

func writeCreateUserRequest(w http.ResponseWriter, r *http.Request, v CreateUserRequest) error {
	_ = r
	buf := jsonbind.GetBuffer()
	*buf = appendCreateUserRequestJSON((*buf)[:0], v)
	err := httpbind.WriteJSONBytes(w, http.StatusOK, *buf)
	jsonbind.PutBuffer(buf)
	return err
}

func decodeCreateUserResponseBytes(data []byte) (CreateUserResponse, error) {
	if jsonbind.IsBlank(data) {
		var out CreateUserResponse
		return out, nil
	}
	var p jsonbind.Parser
	p.Reset(data)
	out, err := decodeCreateUserResponseJSON(&p)
	if err != nil {
		return out, err
	}
	if err := p.End(); err != nil {
		return out, err
	}
	return out, nil
}

func decodeCreateUserResponseJSON(p *jsonbind.Parser) (CreateUserResponse, error) {
	var out CreateUserResponse
	null, err := p.ObjectStart()
	if err != nil || null {
		return out, err
	}
	for n := 0; ; n++ {
		key, ok, err := p.ObjectKey(n)
		if err != nil {
			return out, err
		}
		if !ok {
			return out, nil
		}
		switch string(key) {
		case "id":
			v, err := p.String()
			if err != nil {
				return out, jsonbind.FieldError("id", "invalid string", err)
			}
			out.ID = v
		case "name":
			v, err := p.String()
			if err != nil {
				return out, jsonbind.FieldError("name", "invalid string", err)
			}
			out.Name = v
		case "email":
			v, err := p.String()
			if err != nil {
				return out, jsonbind.FieldError("email", "invalid string", err)
			}
			out.Email = v
		default:
			if err := p.SkipValue(); err != nil {
				return out, err
			}
		}
	}
}

func appendCreateUserResponseJSON(dst []byte, v CreateUserResponse) []byte {
	dst = append(dst, '{')
	dst = append(dst, "\"id\":"...)
	dst = jsonbind.AppendString(dst, v.ID)
	dst = append(dst, ",\"name\":"...)
	dst = jsonbind.AppendString(dst, v.Name)
	dst = append(dst, ",\"email\":"...)
	dst = jsonbind.AppendString(dst, v.Email)
	return append(dst, '}')
}

func encodeCreateUserResponse(w io.Writer, v CreateUserResponse) error {
	buf := jsonbind.GetBuffer()
	*buf = appendCreateUserResponseJSON((*buf)[:0], v)
	*buf = append(*buf, '\n')
	_, err := w.Write(*buf)
	jsonbind.PutBuffer(buf)
	return err
}

func bindCreateUserResponse(r *http.Request) (CreateUserResponse, error) {
	var out CreateUserResponse
	queryVals := httpbind.Queries(r)
	needID := true
	needName := true
	needEmail := true
	if qv, ok := httpbind.QueryLookup(queryVals, "iD"); ok {
		needID = false
		out.ID = qv
	}
	if qv, ok := httpbind.QueryLookup(queryVals, "name"); ok {
		needName = false
		out.Name = qv
	}
	if qv, ok := httpbind.QueryLookup(queryVals, "email"); ok {
		needEmail = false
		out.Email = qv
	}
	if needID || needName || needEmail {
		if httpbind.IsJSONRequest(r) {
			data, err := httpbind.ReadJSONBody(r)
			if err != nil {
				return out, err
			}
			if !jsonbind.IsBlank(data) {
				var bodyParser jsonbind.Parser
				bodyParser.Reset(data)
				p := &bodyParser
				null, err := p.ObjectStart()
				if err != nil {
					return out, httpbind.JSONBodyError(err)
				}
				if null {
					return out, httpbind.JSONBodyNotObject()
				}
				for n := 0; ; n++ {
					key, ok, err := p.ObjectKey(n)
					if err != nil {
						return out, httpbind.JSONBodyError(err)
					}
					if !ok {
						break
					}
					switch string(key) {
					case "iD":
						if !needID {
							if err := p.SkipValue(); err != nil {
								return out, httpbind.JSONBodyError(err)
							}
							continue
						}
						v, err := p.String()
						if err != nil {
							return out, jsonbind.FieldError("iD", "invalid string", err)
						}
						out.ID = v
					case "name":
						if !needName {
							if err := p.SkipValue(); err != nil {
								return out, httpbind.JSONBodyError(err)
							}
							continue
						}
						v, err := p.String()
						if err != nil {
							return out, jsonbind.FieldError("name", "invalid string", err)
						}
						out.Name = v
					case "email":
						if !needEmail {
							if err := p.SkipValue(); err != nil {
								return out, httpbind.JSONBodyError(err)
							}
							continue
						}
						v, err := p.String()
						if err != nil {
							return out, jsonbind.FieldError("email", "invalid string", err)
						}
						out.Email = v
					default:
						if err := p.SkipValue(); err != nil {
							return out, httpbind.JSONBodyError(err)
						}
					}
				}
				if err := p.End(); err != nil {
					return out, httpbind.JSONBodyError(err)
				}
			}
		} else {
			formBody, _, err := httpbind.ReadFormBody(r, true, false)
			if err != nil {
				return out, err
			}
			if needID && formBody != nil {
				if fv, ok := formBody["iD"]; ok {
					out.ID = fv
				}
			}
			if needName && formBody != nil {
				if fv, ok := formBody["name"]; ok {
					out.Name = fv
				}
			}
			if needEmail && formBody != nil {
				if fv, ok := formBody["email"]; ok {
					out.Email = fv
				}
			}
		}
	}
	return out, nil
}

func writeCreateUserResponse(w http.ResponseWriter, r *http.Request, v CreateUserResponse) error {
	_ = r
	buf := jsonbind.GetBuffer()
	*buf = appendCreateUserResponseJSON((*buf)[:0], v)
	err := httpbind.WriteJSONBytes(w, http.StatusOK, *buf)
	jsonbind.PutBuffer(buf)
	return err
}

func decodeSearchRequestBytes(data []byte) (SearchRequest, error) {
	if jsonbind.IsBlank(data) {
		var out SearchRequest
		return out, nil
	}
	var p jsonbind.Parser
	p.Reset(data)
	out, err := decodeSearchRequestJSON(&p)
	if err != nil {
		return out, err
	}
	if err := p.End(); err != nil {
		return out, err
	}
	return out, nil
}

func decodeSearchRequestJSON(p *jsonbind.Parser) (SearchRequest, error) {
	var out SearchRequest
	null, err := p.ObjectStart()
	if err != nil || null {
		return out, err
	}
	for n := 0; ; n++ {
		key, ok, err := p.ObjectKey(n)
		if err != nil {
			return out, err
		}
		if !ok {
			return out, nil
		}
		switch string(key) {
		case "filter":
			v, err := p.String()
			if err != nil {
				return out, jsonbind.FieldError("filter", "invalid string", err)
			}
			out.Filter = v
		default:
			if err := p.SkipValue(); err != nil {
				return out, err
			}
		}
	}
}

func appendSearchRequestJSON(dst []byte, v SearchRequest) []byte {
	dst = append(dst, '{')
	dst = append(dst, "\"keyword\":"...)
	dst = jsonbind.AppendString(dst, v.Keyword)
	dst = append(dst, ",\"page\":"...)
	dst = jsonbind.AppendInt(dst, int64(v.Page))
	dst = append(dst, ",\"filter\":"...)
	dst = jsonbind.AppendString(dst, v.Filter)
	return append(dst, '}')
}

func encodeSearchRequest(w io.Writer, v SearchRequest) error {
	buf := jsonbind.GetBuffer()
	*buf = appendSearchRequestJSON((*buf)[:0], v)
	*buf = append(*buf, '\n')
	_, err := w.Write(*buf)
	jsonbind.PutBuffer(buf)
	return err
}

func bindSearchRequest(r *http.Request) (SearchRequest, error) {
	var out SearchRequest
	queryVals := httpbind.Queries(r)
	if qv, ok := httpbind.QueryLookup(queryVals, "keyword"); ok {
		out.Keyword = qv
	}
	if qv, ok := httpbind.QueryLookup(queryVals, "page"); ok {
		v, err := httpbind.ParseInt(qv)
		if err != nil {
			return out, httpbind.BindError("page", "query", "invalid int")
		}
		out.Page = v
	}
	if httpbind.IsJSONRequest(r) {
		data, err := httpbind.ReadJSONBody(r)
		if err != nil {
			return out, err
		}
		if !jsonbind.IsBlank(data) {
			var bodyParser jsonbind.Parser
			bodyParser.Reset(data)
			p := &bodyParser
			null, err := p.ObjectStart()
			if err != nil {
				return out, httpbind.JSONBodyError(err)
			}
			if null {
				return out, httpbind.JSONBodyNotObject()
			}
			for n := 0; ; n++ {
				key, ok, err := p.ObjectKey(n)
				if err != nil {
					return out, httpbind.JSONBodyError(err)
				}
				if !ok {
					break
				}
				switch string(key) {
				case "filter":
					v, err := p.String()
					if err != nil {
						return out, jsonbind.FieldError("filter", "invalid string", err)
					}
					out.Filter = v
				default:
					if err := p.SkipValue(); err != nil {
						return out, httpbind.JSONBodyError(err)
					}
				}
			}
			if err := p.End(); err != nil {
				return out, httpbind.JSONBodyError(err)
			}
		}
	} else {
		formBody, _, err := httpbind.ReadFormBody(r, true, false)
		if err != nil {
			return out, err
		}
		if formBody != nil {
			if fv, ok := formBody["filter"]; ok {
				out.Filter = fv
			}
		}
	}
	return out, nil
}

func writeSearchRequest(w http.ResponseWriter, r *http.Request, v SearchRequest) error {
	_ = r
	buf := jsonbind.GetBuffer()
	*buf = appendSearchRequestJSON((*buf)[:0], v)
	err := httpbind.WriteJSONBytes(w, http.StatusOK, *buf)
	jsonbind.PutBuffer(buf)
	return err
}

func decodeSearchResponseBytes(data []byte) (SearchResponse, error) {
	if jsonbind.IsBlank(data) {
		var out SearchResponse
		return out, nil
	}
	var p jsonbind.Parser
	p.Reset(data)
	out, err := decodeSearchResponseJSON(&p)
	if err != nil {
		return out, err
	}
	if err := p.End(); err != nil {
		return out, err
	}
	return out, nil
}

func decodeSearchResponseJSON(p *jsonbind.Parser) (SearchResponse, error) {
	var out SearchResponse
	null, err := p.ObjectStart()
	if err != nil || null {
		return out, err
	}
	for n := 0; ; n++ {
		key, ok, err := p.ObjectKey(n)
		if err != nil {
			return out, err
		}
		if !ok {
			return out, nil
		}
		switch string(key) {
		case "keyword":
			v, err := p.String()
			if err != nil {
				return out, jsonbind.FieldError("keyword", "invalid string", err)
			}
			out.Keyword = v
		case "page":
			v, err := p.Int()
			if err != nil {
				return out, jsonbind.FieldError("page", "invalid int", err)
			}
			out.Page = v
		case "filter":
			v, err := p.String()
			if err != nil {
				return out, jsonbind.FieldError("filter", "invalid string", err)
			}
			out.Filter = v
		default:
			if err := p.SkipValue(); err != nil {
				return out, err
			}
		}
	}
}

func appendSearchResponseJSON(dst []byte, v SearchResponse) []byte {
	dst = append(dst, '{')
	dst = append(dst, "\"keyword\":"...)
	dst = jsonbind.AppendString(dst, v.Keyword)
	dst = append(dst, ",\"page\":"...)
	dst = jsonbind.AppendInt(dst, int64(v.Page))
	dst = append(dst, ",\"filter\":"...)
	dst = jsonbind.AppendString(dst, v.Filter)
	return append(dst, '}')
}

func encodeSearchResponse(w io.Writer, v SearchResponse) error {
	buf := jsonbind.GetBuffer()
	*buf = appendSearchResponseJSON((*buf)[:0], v)
	*buf = append(*buf, '\n')
	_, err := w.Write(*buf)
	jsonbind.PutBuffer(buf)
	return err
}

func bindSearchResponse(r *http.Request) (SearchResponse, error) {
	var out SearchResponse
	queryVals := httpbind.Queries(r)
	needKeyword := true
	needPage := true
	needFilter := true
	if qv, ok := httpbind.QueryLookup(queryVals, "keyword"); ok {
		needKeyword = false
		out.Keyword = qv
	}
	if qv, ok := httpbind.QueryLookup(queryVals, "page"); ok {
		needPage = false
		v, err := httpbind.ParseInt(qv)
		if err != nil {
			return out, httpbind.BindError("page", "query", "invalid int")
		}
		out.Page = v
	}
	if qv, ok := httpbind.QueryLookup(queryVals, "filter"); ok {
		needFilter = false
		out.Filter = qv
	}
	if needKeyword || needPage || needFilter {
		if httpbind.IsJSONRequest(r) {
			data, err := httpbind.ReadJSONBody(r)
			if err != nil {
				return out, err
			}
			if !jsonbind.IsBlank(data) {
				var bodyParser jsonbind.Parser
				bodyParser.Reset(data)
				p := &bodyParser
				null, err := p.ObjectStart()
				if err != nil {
					return out, httpbind.JSONBodyError(err)
				}
				if null {
					return out, httpbind.JSONBodyNotObject()
				}
				for n := 0; ; n++ {
					key, ok, err := p.ObjectKey(n)
					if err != nil {
						return out, httpbind.JSONBodyError(err)
					}
					if !ok {
						break
					}
					switch string(key) {
					case "keyword":
						if !needKeyword {
							if err := p.SkipValue(); err != nil {
								return out, httpbind.JSONBodyError(err)
							}
							continue
						}
						v, err := p.String()
						if err != nil {
							return out, jsonbind.FieldError("keyword", "invalid string", err)
						}
						out.Keyword = v
					case "page":
						if !needPage {
							if err := p.SkipValue(); err != nil {
								return out, httpbind.JSONBodyError(err)
							}
							continue
						}
						v, err := p.Int()
						if err != nil {
							return out, jsonbind.FieldError("page", "invalid int", err)
						}
						out.Page = v
					case "filter":
						if !needFilter {
							if err := p.SkipValue(); err != nil {
								return out, httpbind.JSONBodyError(err)
							}
							continue
						}
						v, err := p.String()
						if err != nil {
							return out, jsonbind.FieldError("filter", "invalid string", err)
						}
						out.Filter = v
					default:
						if err := p.SkipValue(); err != nil {
							return out, httpbind.JSONBodyError(err)
						}
					}
				}
				if err := p.End(); err != nil {
					return out, httpbind.JSONBodyError(err)
				}
			}
		} else {
			formBody, _, err := httpbind.ReadFormBody(r, true, false)
			if err != nil {
				return out, err
			}
			if needKeyword && formBody != nil {
				if fv, ok := formBody["keyword"]; ok {
					out.Keyword = fv
				}
			}
			if needPage && formBody != nil {
				if fv, ok := formBody["page"]; ok {
					v, err := httpbind.ParseInt(fv)
					if err != nil {
						return out, httpbind.BindError("page", "payload", "invalid int")
					}
					out.Page = v
				}
			}
			if needFilter && formBody != nil {
				if fv, ok := formBody["filter"]; ok {
					out.Filter = fv
				}
			}
		}
	}
	return out, nil
}

func writeSearchResponse(w http.ResponseWriter, r *http.Request, v SearchResponse) error {
	_ = r
	buf := jsonbind.GetBuffer()
	*buf = appendSearchResponseJSON((*buf)[:0], v)
	err := httpbind.WriteJSONBytes(w, http.StatusOK, *buf)
	jsonbind.PutBuffer(buf)
	return err
}
