// Code generated by tinybind HTML templates; DO NOT EDIT.

package pages

import (
	"github.com/shibukawa/tinybind-go/htmlbind"
)

type BadgeParams struct {
	Label string
}

type NoteParams struct {
	Text string
}

type PanelParams struct {
	Label string
	Text  string
}

type DocumentParams struct {
	Label    string
	Text     string
	Children htmlbind.Fragment
}

var planBadgeOps = htmlbind.Builder[BadgeParams]{}

// planBadgeInput canonically encodes the declared inputs of Badge.
// Slot arguments are excluded: their content belongs to the child boundary,
// so a frame stays comparable when only its child changed.
func planBadgeInput(p BadgeParams) string {
	return htmlbind.CanonJoin(
		htmlbind.CanonString[string](p.Label),
	)
}

var planBadgeBoundary = &htmlbind.Boundary[BadgeParams]{
	ComponentID: "pages.input.Badge",
	Attr:        "data-tb-id",
	Input:       planBadgeInput,
}

var planBadgePlan = &htmlbind.Plan[BadgeParams]{
	Head:        []string{"<link rel=\"stylesheet\" href=\"/shared.css\">", "<link rel=\"stylesheet\" href=\"/public/generated/input.style.c028744bd69d.css\">"},
	HeadSources: []string{"Badge (headcontrib/input.txt:5:1)", "Badge (headcontrib/input.txt:6:1)"},
	Boundary:    planBadgeBoundary,
	Ops: []htmlbind.Op[BadgeParams]{
		planBadgeOps.Static("<span"),
		planBadgeOps.BoundaryAttr(),
		planBadgeOps.Static(" class=\"badge_kr30dc\">"),
		planBadgeOps.Text(func(p BadgeParams) string { return p.Label }),
		planBadgeOps.Static("</span> "),
	},
}

// Badge binds Badge to its parameters, producing a renderable fragment.
func Badge(params BadgeParams) htmlbind.Fragment { return htmlbind.Bind(planBadgePlan, params) }

var planNoteOps = htmlbind.Builder[NoteParams]{}

// planNoteInput canonically encodes the declared inputs of Note.
// Slot arguments are excluded: their content belongs to the child boundary,
// so a frame stays comparable when only its child changed.
func planNoteInput(p NoteParams) string {
	return htmlbind.CanonJoin(
		htmlbind.CanonString[string](p.Text),
	)
}

var planNoteBoundary = &htmlbind.Boundary[NoteParams]{
	ComponentID: "pages.input.Note",
	Attr:        "data-tb-id",
	Input:       planNoteInput,
}

var planNotePlan = &htmlbind.Plan[NoteParams]{
	Head:        []string{"<link rel=\"stylesheet\" href=\"/shared.css\">", "<link rel=\"stylesheet\" href=\"/public/generated/input.style.c028744bd69d.css\">"},
	HeadSources: []string{"Note (headcontrib/input.txt:13:1)", "Note (headcontrib/input.txt:14:1)"},
	Boundary:    planNoteBoundary,
	Ops: []htmlbind.Op[NoteParams]{
		planNoteOps.Static("<p"),
		planNoteOps.BoundaryAttr(),
		planNoteOps.Static(" class=\"note_x86lcf\">"),
		planNoteOps.Text(func(p NoteParams) string { return p.Text }),
		planNoteOps.Static("</p> "),
	},
}

// Note binds Note to its parameters, producing a renderable fragment.
func Note(params NoteParams) htmlbind.Fragment { return htmlbind.Bind(planNotePlan, params) }

var planPanelOps = htmlbind.Builder[PanelParams]{}

// planPanelInput canonically encodes the declared inputs of Panel.
// Slot arguments are excluded: their content belongs to the child boundary,
// so a frame stays comparable when only its child changed.
func planPanelInput(p PanelParams) string {
	return htmlbind.CanonJoin(
		htmlbind.CanonString[string](p.Label),
		htmlbind.CanonString[string](p.Text),
	)
}

var planPanelBoundary = &htmlbind.Boundary[PanelParams]{
	ComponentID: "pages.input.Panel",
	Attr:        "data-tb-id",
	Input:       planPanelInput,
}

var planPanelPlan = &htmlbind.Plan[PanelParams]{
	Head:        []string{"<link rel=\"stylesheet\" href=\"/shared.css\">", "<link rel=\"stylesheet\" href=\"/public/generated/input.style.c028744bd69d.css\">"},
	HeadSources: []string{"Badge (headcontrib/input.txt:5:1)", "Badge (headcontrib/input.txt:6:1)"},
	Boundary:    planPanelBoundary,
	Ops: []htmlbind.Op[PanelParams]{
		planPanelOps.Static(" <div"),
		planPanelOps.BoundaryAttr(),
		planPanelOps.Static(">"),
		planPanelOps.Component(func(p PanelParams) htmlbind.Fragment { return Badge(BadgeParams{Label: p.Label}) }),
		planPanelOps.Component(func(p PanelParams) htmlbind.Fragment { return Note(NoteParams{Text: p.Text}) }),
		planPanelOps.Static("</div> "),
	},
}

// Panel binds Panel to its parameters, producing a renderable fragment.
func Panel(params PanelParams) htmlbind.Fragment { return htmlbind.Bind(planPanelPlan, params) }

var planDocumentOps = htmlbind.Builder[DocumentParams]{}

var planDocumentPlan = &htmlbind.Plan[DocumentParams]{
	Head: nil,
	Ops: []htmlbind.Op[DocumentParams]{
		planDocumentOps.Static("<!DOCTYPE html><html><head><title>t</title>"),
		planDocumentOps.MergedHead(),
		planDocumentOps.Static("</head><body>"),
		planDocumentOps.Slot(func(p DocumentParams) htmlbind.Fragment { return p.Children },
			nil),
		planDocumentOps.Static("</body></html>"),
	},
}

// Document binds Document to its parameters, producing a renderable fragment.
func Document(params DocumentParams) htmlbind.Fragment {
	return htmlbind.Bind(planDocumentPlan, params)
}

// BindDocument binds Document as a chain wrapper filling its unnamed slot.
func BindDocument(params DocumentParams) htmlbind.Wrapper {
	return htmlbind.BindWrapper(planDocumentPlan, params, func(target *DocumentParams, children htmlbind.Fragment) { target.Children = children })
}
