// Code generated by tinybind HTML templates; DO NOT EDIT.

package id_

import (
	"github.com/shibukawa/tinybind-go/htmlbind"
)

type PageParams struct {
	Name string
}

var planPageOps = htmlbind.Builder[PageParams]{}

var planPagePlan = &htmlbind.Plan[PageParams]{
	Head: nil,
	Ops: []htmlbind.Op[PageParams]{
		planPageOps.Static(" <h1>user "),
		planPageOps.Text(func(p PageParams) string { return p.Name }),
		planPageOps.Static("</h1> <button data-tb-action=\"/_action/00369cf962b6/Rename\" data-target=\"#name\">rename</button> <form data-tb-action=\"/_action/d71506d06c1e/Retire\" method=\"post\"><input type=\"hidden\" name=\"_action\" value=\"d71506d06c1e/Retire\" />"),
		planPageOps.CSRFField("_csrf"),
		planPageOps.Static(" <input name=\"reason\" /> <button type=\"submit\">retire</button> </form> "),
	},
}

// Page binds Page to its parameters, producing a renderable fragment.
func Page(params PageParams) htmlbind.Fragment { return htmlbind.Bind(planPagePlan, params) }
