// Code generated by tinybind; DO NOT EDIT.

package id_

import (
	"encoding/json"
	"net/http"

	"github.com/shibukawa/tinybind-go"
	"github.com/shibukawa/tinybind-go/jsonbind"
)

func init() {
	httpbind.RegisterBind[RenameRequest](bindRenameRequest)
}

func decodeRenameRequestBytes(data []byte) (RenameRequest, error) {
	return decodeRenameRequestJSON(json.RawMessage(data))
}

func decodeRenameRequestJSON(raw json.RawMessage) (RenameRequest, error) {
	var out RenameRequest
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["name"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("name", "invalid string", err)
		}
		out.Name = v
	}
	return out, nil
}

func bindRenameRequest(r *http.Request) (RenameRequest, error) {
	var out RenameRequest
	var presentName bool
	var jsonBody map[string]json.RawMessage
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbind.IsJSONRequest(r) {
			m, err := httpbind.ReadJSONMap(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbind.IsFormRequest(r) {
			m, err := httpbind.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbind.IsMultipartRequest(r) {
			m, _, err := httpbind.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		return nil
	}
	if qv, ok := httpbind.QueryValue(r, "name"); ok {
		presentName = true
		out.Name = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["name"]; ok {
			presentName = true
			v, err := jsonbind.DecodeJSONString(raw)
			if err != nil {
				return out, jsonbind.FieldError("name", "invalid string", err)
			}
			out.Name = v
		} else if formBody != nil {
			if fv, ok := formBody["name"]; ok {
				presentName = true
				out.Name = fv
			}
		}
	}
	var checkFields []httpbind.FieldError
	if !presentName || out.Name == "" {
		checkFields = append(checkFields, httpbind.Field("name", "input", "required"))
	}
	if len(checkFields) > 0 {
		return out, httpbind.Validation(checkFields...)
	}
	return out, nil
}
