// Code generated by tinybind; DO NOT EDIT.

package id_

import (
	"net/http"

	"github.com/shibukawa/tinybind-go"
	"github.com/shibukawa/tinybind-go/jsonbind"
)

func init() {
	httpbind.RegisterBind[RenameRequest](bindRenameRequest)
}

func decodeRenameRequestBytes(data []byte) (RenameRequest, error) {
	if jsonbind.IsBlank(data) {
		var out RenameRequest
		return out, nil
	}
	p := jsonbind.NewParser(data)
	out, err := decodeRenameRequestJSON(p)
	if err != nil {
		return out, err
	}
	if err := p.End(); err != nil {
		return out, err
	}
	return out, nil
}

func decodeRenameRequestJSON(p *jsonbind.Parser) (RenameRequest, error) {
	var out RenameRequest
	null, err := p.ObjectStart()
	if err != nil || null {
		return out, err
	}
	for n := 0; ; n++ {
		key, ok, err := p.ObjectKey(n)
		if err != nil {
			return out, err
		}
		if !ok {
			return out, nil
		}
		switch string(key) {
		case "name":
			v, err := p.String()
			if err != nil {
				return out, jsonbind.FieldError("name", "invalid string", err)
			}
			out.Name = v
		default:
			if err := p.SkipValue(); err != nil {
				return out, err
			}
		}
	}
}

func bindRenameRequest(r *http.Request) (RenameRequest, error) {
	var out RenameRequest
	var presentName bool
	queryVals := httpbind.Queries(r)
	var jsonBody *jsonbind.Object
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		var err error
		jsonBody, formBody, _, err = httpbind.ReadBody(r, true, false)
		return err
	}
	if qv, ok := httpbind.QueryLookup(queryVals, "name"); ok {
		presentName = true
		out.Name = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody.Get("name"); ok {
			presentName = true
			v, err := jsonbind.DecodeJSONString(raw)
			if err != nil {
				return out, jsonbind.FieldError("name", "invalid string", err)
			}
			out.Name = v
		} else if formBody != nil {
			if fv, ok := formBody["name"]; ok {
				presentName = true
				out.Name = fv
			}
		}
	}
	var checkFields []httpbind.FieldError
	if !presentName || out.Name == "" {
		checkFields = append(checkFields, httpbind.Field("name", "input", "required"))
	}
	if len(checkFields) > 0 {
		return out, httpbind.Validation(checkFields...)
	}
	return out, nil
}
