// Code generated by tinybind; DO NOT EDIT.
// tinybind:generated v1 inputs=sha256:d1969396e4b917277381d4d98a2d6258e82292293e165a23d2708a44b7d43ae1 self=sha256:a9c7eb8ff35c9f78f7b9043845653b4fc4436c808c7f7f00fc81dcec2a842622 outputs=tinybind_gen.go,tinybind_openapi_gen.go

package main

import (
	"io"
	"net/http"

	"github.com/shibukawa/tinybind-go"
	"github.com/shibukawa/tinybind-go/jsonbind"
)

func init() {
	jsonbind.RegisterDecode[ClientMsg](decodeClientMsgBytes)
	jsonbind.RegisterEncode[ServerMsg](encodeServerMsg)
	jsonbind.RegisterAppend[ServerMsg](appendServerMsgJSON)
	httpbind.RegisterWrite[HealthResponse](writeHealthResponse)
}

func decodeClientMsgBytes(data []byte) (ClientMsg, error) {
	if jsonbind.IsBlank(data) {
		var out ClientMsg
		return out, nil
	}
	var p jsonbind.Parser
	p.Reset(data)
	out, err := decodeClientMsgJSON(&p)
	if err != nil {
		return out, err
	}
	if err := p.End(); err != nil {
		return out, err
	}
	return out, nil
}

func decodeClientMsgJSON(p *jsonbind.Parser) (ClientMsg, error) {
	var out ClientMsg
	null, err := p.ObjectStart()
	if err != nil || null {
		return out, err
	}
	for n := 0; ; n++ {
		key, ok, err := p.ObjectKey(n)
		if err != nil {
			return out, err
		}
		if !ok {
			return out, nil
		}
		switch string(key) {
		case "type":
			v, err := p.String()
			if err != nil {
				return out, jsonbind.FieldError("type", "invalid string", err)
			}
			out.Type = v
		case "name":
			v, err := p.String()
			if err != nil {
				return out, jsonbind.FieldError("name", "invalid string", err)
			}
			out.Name = v
		case "text":
			v, err := p.String()
			if err != nil {
				return out, jsonbind.FieldError("text", "invalid string", err)
			}
			out.Text = v
		default:
			if err := p.SkipValue(); err != nil {
				return out, err
			}
		}
	}
}

func appendServerMsgJSON(dst []byte, v ServerMsg) []byte {
	dst = append(dst, '{')
	dst = append(dst, "\"type\":"...)
	dst = jsonbind.AppendString(dst, v.Type)
	if v.From != "" {
		dst = append(dst, ",\"from\":"...)
		dst = jsonbind.AppendString(dst, v.From)
	}
	if v.Text != "" {
		dst = append(dst, ",\"text\":"...)
		dst = jsonbind.AppendString(dst, v.Text)
	}
	if v.Code != "" {
		dst = append(dst, ",\"code\":"...)
		dst = jsonbind.AppendString(dst, v.Code)
	}
	dst = append(dst, ",\"live\":"...)
	dst = jsonbind.AppendInt(dst, int64(v.Live))
	return append(dst, '}')
}

func encodeServerMsg(w io.Writer, v ServerMsg) error {
	buf := jsonbind.GetBuffer()
	*buf = appendServerMsgJSON((*buf)[:0], v)
	*buf = append(*buf, '\n')
	_, err := w.Write(*buf)
	jsonbind.PutBuffer(buf)
	return err
}

func appendHealthResponseJSON(dst []byte, v HealthResponse) []byte {
	dst = append(dst, '{')
	dst = append(dst, "\"status\":"...)
	dst = jsonbind.AppendString(dst, v.Status)
	dst = append(dst, ",\"live\":"...)
	dst = jsonbind.AppendInt(dst, int64(v.Live))
	return append(dst, '}')
}

func encodeHealthResponse(w io.Writer, v HealthResponse) error {
	buf := jsonbind.GetBuffer()
	*buf = appendHealthResponseJSON((*buf)[:0], v)
	*buf = append(*buf, '\n')
	_, err := w.Write(*buf)
	jsonbind.PutBuffer(buf)
	return err
}

func writeHealthResponse(w http.ResponseWriter, r *http.Request, v HealthResponse) error {
	_ = r
	buf := jsonbind.GetBuffer()
	*buf = appendHealthResponseJSON((*buf)[:0], v)
	err := httpbind.WriteJSONBytes(w, http.StatusOK, *buf)
	jsonbind.PutBuffer(buf)
	return err
}
