// tinybind:generated v1 inputs=sha256:d461eb18ba2aa637b655af2a205bab6410c38d7c2fa53ceaf68cd3bfce2dda38 self=sha256:654e22705bbfc6bb86ee3af41a21efc74dc55716e0e1f4082a3dd31b5649ce76 outputs=tinybind_gen.go,tinybind_openapi_gen.go
//go:build !tinybind_no_openapi

// Code generated by tinybind; DO NOT EDIT.

package main

import "github.com/shibukawa/tinybind-go"

func init() {
	httpbind.RegisterOpenAPIFragmentString("github.com/shibukawa/tinybind-go/examples/websocket", openapiFragmentJSON)
}

const openapiFragmentJSON = "{\"components\":{\"schemas\":{\"HealthResponse\":{\"description\":\"HealthResponse is an ordinary REST response, here to show the socket living\\non the same port and the same mux as everything else.\",\"properties\":{\"live\":{\"type\":\"integer\"},\"status\":{\"type\":\"string\"}},\"type\":\"object\"},\"ProblemDetails\":{\"properties\":{\"code\":{\"type\":\"string\"},\"detail\":{\"type\":\"string\"},\"errors\":{\"items\":{\"properties\":{\"field\":{\"type\":\"string\"},\"location\":{\"type\":\"string\"},\"message\":{\"type\":\"string\"}},\"type\":\"object\"},\"type\":\"array\"},\"status\":{\"type\":\"integer\"},\"title\":{\"type\":\"string\"},\"type\":{\"type\":\"string\"}},\"type\":\"object\"}}},\"paths\":{\"/\":{\"get\":{\"operationId\":\"indexHandler\",\"responses\":{\"200\":{\"description\":\"OK\"}}}},\"/healthz\":{\"get\":{\"operationId\":\"healthHandler\",\"responses\":{\"200\":{\"content\":{\"application/json\":{\"schema\":{\"$ref\":\"#/components/schemas/HealthResponse\"}}},\"description\":\"OK\"}},\"summary\":\"healthHandler is an ordinary REST route, sharing the port with the socket.\"}},\"/ws\":{\"get\":{\"description\":\"Neither type argument is spelled at the call: generation recovers ClientMsg\\nand ServerMsg from the closure parameter and emits a decoder for the first\\nand an encoder for the second.\",\"operationId\":\"chatHandler\",\"responses\":{\"200\":{\"description\":\"OK\"}},\"summary\":\"chatHandler upgrades to a WebSocket and runs the room protocol.\"}}}}"
