// Package codegen emits reflection-free configbind apply, flag, and env key tables.
package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"strconv"
	"strings"

	"github.com/shibukawa/tinybind-go/cliparser"
	"github.com/shibukawa/tinybind-go/minitoml/codegen"
)

// Spec is a Bind-style struct and prefix discovered in one Go package.
type Spec struct {
	PackagePath string
	TypeName    string
	Prefix      string
	Fields      []Field
}

// Field and FieldKind re-export for callers.
type (
	Field     = codegen.Field
	FieldKind = codegen.FieldKind
)

const (
	FieldString      = codegen.FieldString
	FieldBool        = codegen.FieldBool
	FieldInt         = codegen.FieldInt
	FieldStringSlice = codegen.FieldStringSlice
	FieldStruct      = codegen.FieldStruct
)

// Generate emits package source that registers Meta and Apply for each Spec.
func Generate(packageName string, specs []Spec) ([]byte, error) {
	if packageName == "" {
		return nil, fmt.Errorf("configbind/codegen: package name required")
	}
	if len(specs) == 0 {
		return nil, fmt.Errorf("configbind/codegen: no specs")
	}
	var b bytes.Buffer
	b.WriteString("// Code generated by configbind/codegen; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", packageName)
	b.WriteString("import (\n")
	b.WriteString("\t\"fmt\"\n")
	if specsNeedStrconv(specs) {
		b.WriteString("\t\"strconv\"\n")
	}
	b.WriteString("\n")
	b.WriteString("\t\"github.com/shibukawa/tinybind-go/cliparser\"\n")
	b.WriteString("\t\"github.com/shibukawa/tinybind-go/configbind\"\n")
	b.WriteString(")\n\n")

	b.WriteString("func init() {\n")
	for i, s := range specs {
		fmt.Fprintf(&b, "\tregister%sBinding%d()\n", s.TypeName, i)
	}
	b.WriteString("}\n\n")

	for i, s := range specs {
		if s.PackagePath == "" {
			s.PackagePath = packageName
		}
		if err := emitType(&b, s, fmt.Sprintf("register%sBinding%d", s.TypeName, i)); err != nil {
			return nil, err
		}
	}

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return b.Bytes(), fmt.Errorf("configbind/codegen: format: %w\n%s", err, b.String())
	}
	return formatted, nil
}

func specsNeedStrconv(specs []Spec) bool {
	var fieldsNeedStrconv func([]Field) bool
	fieldsNeedStrconv = func(fields []Field) bool {
		for _, field := range fields {
			if field.Kind == FieldBool || field.Kind == FieldInt ||
				(field.Kind == FieldStruct && fieldsNeedStrconv(field.Nested)) {
				return true
			}
		}
		return false
	}
	for _, spec := range specs {
		if fieldsNeedStrconv(spec.Fields) {
			return true
		}
	}
	return false
}

func emitType(b *bytes.Buffer, s Spec, registerName string) error {
	if s.TypeName == "" || s.Prefix == "" {
		return fmt.Errorf("configbind/codegen: TypeName and Prefix required")
	}
	keys := collectKeys(s.Prefix, s.Fields)
	defaults := collectDefaults(s.Prefix, s.Fields)
	flagMetas := collectFlagMetas(s.Prefix, s.Fields)
	if _, err := cliparser.BuildDefs(flagMetas); err != nil {
		return fmt.Errorf("configbind/codegen: %s: %w", s.TypeName, err)
	}

	typeIdentity := s.PackagePath + "." + s.TypeName
	fragmentID := typeIdentity + "@" + s.Prefix
	applyName := "apply" + strings.TrimPrefix(registerName, "register")
	fmt.Fprintf(b, "func %s() {\n", registerName)
	b.WriteString("\tconfigbind.RegisterBinding[")
	b.WriteString(s.TypeName)
	b.WriteString("](")
	fmt.Fprintf(b, "%s, %s, configbind.Meta{\n", strconv.Quote(s.Prefix), strconv.Quote(typeIdentity))
	fmt.Fprintf(b, "\t\tTypeName: %s,\n", strconv.Quote(typeIdentity))
	b.WriteString("\t\tKnownKeys: []string{\n")
	for _, k := range keys {
		fmt.Fprintf(b, "\t\t\t%s,\n", strconv.Quote(k))
	}
	b.WriteString("\t\t},\n")
	if len(defaults) > 0 {
		b.WriteString("\t\tDefaults: map[string]string{\n")
		// stable order
		for _, k := range keys {
			if v, ok := defaults[k]; ok {
				fmt.Fprintf(b, "\t\t\t%s: %s,\n", strconv.Quote(k), strconv.Quote(v))
			}
		}
		b.WriteString("\t\t},\n")
	}
	b.WriteString("\t\tFlagMetas: []cliparser.FieldMeta{\n")
	for _, m := range flagMetas {
		fmt.Fprintf(b, "\t\t\t{Prefix: %s, Key: %s", strconv.Quote(m.Prefix), strconv.Quote(m.Key))
		if m.Opt != "" {
			fmt.Fprintf(b, ", Opt: %s", strconv.Quote(m.Opt))
		}
		if m.Env != "" {
			fmt.Fprintf(b, ", Env: %s", strconv.Quote(m.Env))
		}
		if m.Help != "" {
			fmt.Fprintf(b, ", Help: %s", strconv.Quote(m.Help))
		}
		switch m.Kind {
		case cliparser.KindBool:
			b.WriteString(", Kind: cliparser.KindBool")
		case cliparser.KindArray:
			b.WriteString(", Kind: cliparser.KindArray")
		}
		b.WriteString("},\n")
	}
	b.WriteString("\t\t},\n")
	fmt.Fprintf(b, "\t\tApply: %s,\n", applyName)
	b.WriteString("\t})\n")
	fmt.Fprintf(b, "\tconfigbind.RegisterScaffold(configbind.ScaffoldFragment{ID: %s, Prefix: %s, Fields: []configbind.ScaffoldField{\n", strconv.Quote(fragmentID), strconv.Quote(s.Prefix))
	for _, scaffoldField := range flattenScaffoldFields("", s.Fields) {
		f := scaffoldField.Field
		fmt.Fprintf(b, "\t\t{Key: %s, Kind: %s", strconv.Quote(scaffoldField.Key), scaffoldKindName(f.Kind))
		if f.Default != "" {
			fmt.Fprintf(b, ", Default: %s", strconv.Quote(f.Default))
		}
		if f.Opt != "" {
			fmt.Fprintf(b, ", Opt: %s", strconv.Quote(f.Opt))
		}
		if f.Env != "" {
			fmt.Fprintf(b, ", Env: %s", strconv.Quote(f.Env))
		}
		if f.Help != "" {
			fmt.Fprintf(b, ", Help: %s", strconv.Quote(f.Help))
		}
		b.WriteString("},\n")
	}
	b.WriteString("\t}})\n")
	b.WriteString("}\n\n")

	// Apply function
	fmt.Fprintf(b, "func %s(dst any, o *configbind.Overlay) error {\n", applyName)
	fmt.Fprintf(b, "\tp, ok := dst.(*%s)\n", s.TypeName)
	b.WriteString("\tif !ok || p == nil {\n")
	fmt.Fprintf(b, "\t\treturn fmt.Errorf(\"configbind: apply %s: bad destination\")\n", s.TypeName)
	b.WriteString("\t}\n")
	if err := emitApplyFields(b, "p", s.Prefix, s.Fields); err != nil {
		return err
	}
	b.WriteString("\treturn nil\n")
	b.WriteString("}\n\n")
	return nil
}

type scaffoldCodegenField struct {
	Key   string
	Field Field
}

func flattenScaffoldFields(prefix string, fields []Field) []scaffoldCodegenField {
	var result []scaffoldCodegenField
	for _, field := range fields {
		key := joinKey(prefix, field.Key)
		if field.Kind == FieldStruct {
			result = append(result, flattenScaffoldFields(key, field.Nested)...)
			continue
		}
		result = append(result, scaffoldCodegenField{Key: key, Field: field})
	}
	return result
}

func scaffoldKindName(kind FieldKind) string {
	switch kind {
	case FieldString:
		return "configbind.ScaffoldString"
	case FieldBool:
		return "configbind.ScaffoldBool"
	case FieldInt:
		return "configbind.ScaffoldInt"
	case FieldStringSlice:
		return "configbind.ScaffoldStringSlice"
	default:
		return "configbind.ScaffoldString"
	}
}

func emitApplyFields(b *bytes.Buffer, recv, prefix string, fields []Field) error {
	for _, f := range fields {
		full := joinKey(prefix, f.Key)
		access := recv + "." + f.GoName
		switch f.Kind {
		case FieldString:
			fmt.Fprintf(b, "\tif v, ok := o.GetString(%q); ok {\n", full)
			fmt.Fprintf(b, "\t\t%s = v\n", access)
			if f.Default != "" {
				b.WriteString("\t} else {\n")
				fmt.Fprintf(b, "\t\t%s = %s\n", access, strconv.Quote(f.Default))
				b.WriteString("\t}\n")
			} else {
				b.WriteString("\t}\n")
			}
		case FieldBool:
			fmt.Fprintf(b, "\tif v, ok := o.GetString(%q); ok {\n", full)
			b.WriteString("\t\tbb, err := strconv.ParseBool(v)\n")
			b.WriteString("\t\tif err != nil {\n")
			fmt.Fprintf(b, "\t\t\treturn fmt.Errorf(\"configbind: %s: %%w\", err)\n", full)
			b.WriteString("\t\t}\n")
			fmt.Fprintf(b, "\t\t%s = bb\n", access)
			if f.Default != "" {
				value, err := strconv.ParseBool(f.Default)
				if err != nil {
					return fmt.Errorf("invalid bool default %q for %s", f.Default, f.GoName)
				}
				b.WriteString("\t} else {\n")
				fmt.Fprintf(b, "\t\t%s = %v\n", access, value)
				b.WriteString("\t}\n")
			} else {
				b.WriteString("\t}\n")
			}
		case FieldInt:
			fmt.Fprintf(b, "\tif v, ok := o.GetString(%q); ok {\n", full)
			b.WriteString("\t\tn, err := strconv.ParseInt(v, 10, 64)\n")
			b.WriteString("\t\tif err != nil {\n")
			fmt.Fprintf(b, "\t\t\treturn fmt.Errorf(\"configbind: %s: %%w\", err)\n", full)
			b.WriteString("\t\t}\n")
			fmt.Fprintf(b, "\t\t%s = int(n)\n", access)
			if f.Default != "" {
				value, err := strconv.ParseInt(f.Default, 10, 64)
				if err != nil {
					return fmt.Errorf("invalid int default %q for %s", f.Default, f.GoName)
				}
				b.WriteString("\t} else {\n")
				fmt.Fprintf(b, "\t\t%s = %s\n", access, strconv.FormatInt(value, 10))
				b.WriteString("\t}\n")
			} else {
				b.WriteString("\t}\n")
			}
		case FieldStringSlice:
			fmt.Fprintf(b, "\tif v, ok := o.GetMulti(%q); ok {\n", full)
			fmt.Fprintf(b, "\t\t%s = v\n", access)
			b.WriteString("\t}\n")
		case FieldStruct:
			if err := emitApplyFields(b, access, full, f.Nested); err != nil {
				return err
			}
		default:
			return fmt.Errorf("unsupported field kind for %s", f.GoName)
		}
	}
	return nil
}

func collectKeys(prefix string, fields []Field) []string {
	var keys []string
	var walk func(string, []Field)
	walk = func(p string, fs []Field) {
		for _, f := range fs {
			full := joinKey(p, f.Key)
			if f.Kind == FieldStruct {
				walk(full, f.Nested)
				continue
			}
			keys = append(keys, full)
		}
	}
	walk(prefix, fields)
	return keys
}

func collectDefaults(prefix string, fields []Field) map[string]string {
	out := map[string]string{}
	var walk func(string, []Field)
	walk = func(p string, fs []Field) {
		for _, f := range fs {
			full := joinKey(p, f.Key)
			if f.Kind == FieldStruct {
				walk(full, f.Nested)
				continue
			}
			if f.Default != "" {
				out[full] = f.Default
			}
		}
	}
	walk(prefix, fields)
	return out
}

func collectFlagMetas(prefix string, fields []Field) []cliparser.FieldMeta {
	var out []cliparser.FieldMeta
	var walk func(string, []Field)
	walk = func(p string, fs []Field) {
		for _, f := range fs {
			full := joinKey(p, f.Key)
			// relative key under original prefix for cliparser FieldMeta
			rel := strings.TrimPrefix(full, prefix+".")
			if full == prefix {
				rel = ""
			}
			if f.Kind == FieldStruct {
				walk(full, f.Nested)
				continue
			}
			// FieldMeta uses Prefix + Key where Key is relative path under prefix
			key := strings.TrimPrefix(full, prefix+".")
			m := cliparser.FieldMeta{
				Prefix: prefix,
				Key:    key,
				Opt:    f.Opt,
				Env:    f.Env,
				Help:   f.Help,
			}
			switch f.Kind {
			case FieldBool:
				m.Kind = cliparser.KindBool
			case FieldStringSlice:
				m.Kind = cliparser.KindArray
			default:
				m.Kind = cliparser.KindString
			}
			_ = rel
			out = append(out, m)
		}
	}
	walk(prefix, fields)
	return out
}

func joinKey(prefix, key string) string {
	if prefix == "" {
		return key
	}
	if key == "" {
		return prefix
	}
	return prefix + "." + key
}
