// Code generated by tinybind HTML templates; DO NOT EDIT.

package pages

import (
	"github.com/shibukawa/tinybind-go/htmlbind"
)

type renderPanelParams struct {
	Title    string
	Header   htmlbind.Fragment
	Children htmlbind.Fragment
	Footer   htmlbind.Fragment
}

type PageParams struct {
	Caption string
}

var planPageOpsFill1Plan = &htmlbind.Plan[PageParams]{Ops: []htmlbind.Op[PageParams]{
	planPageOps.Static("<em>Guide</em>"),
}}

var planPageOpsFill2Plan = &htmlbind.Plan[PageParams]{Ops: []htmlbind.Op[PageParams]{
	planPageOps.Static("<p>body text</p> "),
}}

var planPanelOps = htmlbind.Builder[renderPanelParams]{}

var planPanelPlan = &htmlbind.Plan[renderPanelParams]{
	Head: nil,
	Slots: func(p renderPanelParams) []htmlbind.Fragment {
		return []htmlbind.Fragment{p.Header, p.Children, p.Footer}
	},
	Ops: []htmlbind.Op[renderPanelParams]{
		planPanelOps.Static(" <section class=\"panel\"> <div class=\"head\">"),
		planPanelOps.Slot(func(p renderPanelParams) htmlbind.Fragment { return p.Header },
			[]htmlbind.Op[renderPanelParams]{
				planPanelOps.Static("<b>"),
				planPanelOps.Text(func(p renderPanelParams) string { return p.Title }),
				planPanelOps.Static("</b>"),
			}),
		planPanelOps.Static("</div> <div class=\"body\">"),
		planPanelOps.Slot(func(p renderPanelParams) htmlbind.Fragment { return p.Children },
			nil),
		planPanelOps.Static("</div> "),
		planPanelOps.Slot(func(p renderPanelParams) htmlbind.Fragment { return p.Footer },
			nil),
		planPanelOps.Static(" </section> "),
	},
}

// renderPanel binds Panel to its parameters, producing a renderable fragment.
func renderPanel(params renderPanelParams) htmlbind.Fragment {
	return htmlbind.Bind(planPanelPlan, params)
}

var planPageOps = htmlbind.Builder[PageParams]{}

var planPagePlan = &htmlbind.Plan[PageParams]{
	Head: nil,
	Ops: []htmlbind.Op[PageParams]{
		planPageOps.Static(" "),
		planPageOps.Component(func(p PageParams) htmlbind.Fragment {
			return renderPanel(renderPanelParams{Title: p.Caption, Header: htmlbind.Bind(planPageOpsFill1Plan, p), Children: htmlbind.Bind(planPageOpsFill2Plan, p)})
		}),
		planPageOps.Static(" "),
	},
}

// Page binds Page to its parameters, producing a renderable fragment.
func Page(params PageParams) htmlbind.Fragment { return htmlbind.Bind(planPagePlan, params) }
