// Code generated by tinybind HTML templates; DO NOT EDIT.

package pages

import (
	"github.com/shibukawa/tinybind-go/htmlbind"
)

type HelloParams struct{}

var planHelloOps = htmlbind.Builder[HelloParams]{}

// planHelloInput canonically encodes the declared inputs of Hello.
// Slot arguments are excluded: their content belongs to the child boundary,
// so a frame stays comparable when only its child changed.
func planHelloInput(p HelloParams) string {
	return htmlbind.CanonJoin()
}

var planHelloBoundary = &htmlbind.Boundary[HelloParams]{
	ComponentID: "pages.input.Hello",
	Attr:        "data-tb-id",
	Input:       planHelloInput,
}

var planHelloPlan = &htmlbind.Plan[HelloParams]{
	Head:     nil,
	Boundary: planHelloBoundary,
	Ops: []htmlbind.Op[HelloParams]{
		planHelloOps.Static("<!DOCTYPE html><h1"),
		planHelloOps.BoundaryAttr(),
		planHelloOps.Static(">Hello &amp; welcome</h1>"),
	},
}

// Hello binds Hello to its parameters, producing a renderable fragment.
func Hello(params HelloParams) htmlbind.Fragment { return htmlbind.Bind(planHelloPlan, params) }
