// Code generated by tinybind HTML templates; DO NOT EDIT.

package pages

import (
	"github.com/shibukawa/tinybind-go/htmlbind"
)

type HelloParams struct{}

var planHelloOps = htmlbind.Builder[HelloParams]{}

var planHelloPlan = &htmlbind.Plan[HelloParams]{
	Head: nil,
	Ops: []htmlbind.Op[HelloParams]{
		planHelloOps.Static("<!DOCTYPE html><h1>Hello &amp; welcome</h1>"),
	},
}

// Hello binds Hello to its parameters, producing a renderable fragment.
func Hello(params HelloParams) htmlbind.Fragment { return htmlbind.Bind(planHelloPlan, params) }
