// Code generated by configbind/codegen; DO NOT EDIT.

package main

import (
	"fmt"
	"strconv"

	"github.com/shibukawa/tinybind-go/cliparser"
	"github.com/shibukawa/tinybind-go/configbind"
)

func init() {
	registerServerConfigDefinition0()
}

func registerServerConfigDefinition0() {
	configbind.Register[ServerConfig](configbind.Definition{
		TypeName: "github.com/shibukawa/tinybind-go/examples/demo.ServerConfig",
		Prefix:   "server",
		Doc:      "ServerConfig is process config loaded via configbind (TOML / env / CLI). With opt:\"port,p\", the environment variable is PORT (CLI long name based)",
		KnownKeys: []string{
			"server.port",
		},
		Defaults: map[string]string{
			"server.port": "8080",
		},
		FlagMetas: []cliparser.FieldMeta{
			{Prefix: "server", Key: "port", Opt: "port,p", Help: "HTTP listen port"},
		},
		Apply: applyServerConfigDefinition0,
		Scaffold: []configbind.ScaffoldField{
			{Key: "port", Kind: configbind.ScaffoldInt, Default: "8080", Opt: "port,p", Help: "HTTP listen port"},
		},
	})
}

func applyServerConfigDefinition0(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*ServerConfig)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply ServerConfig: bad destination")
	}
	if v, ok := o.GetString("server.port"); ok {
		n, err := strconv.ParseInt(v, 10, 64)
		if err != nil {
			return fmt.Errorf("configbind: server.port: %w", err)
		}
		p.Port = int(n)
	} else {
		p.Port = 8080
	}
	return nil
}
