// Code generated by tinybind; DO NOT EDIT.
// tinybind:generated v1 inputs=sha256:c1bf09099851ebc84f660f6bbc15128ca2e836ae7135beb50e9c74177558fdb7 self=sha256:14240288644e626e08626dd77708b07d287d53ac4e60a2d6004f7ced64f314fb outputs=tinybind_templates_gen.go,tinybind_gen.go,configbind_gen.go,tinybind_openapi_gen.go

package main

import (
	"io"
	"net/http"

	"github.com/shibukawa/tinybind-go"
	"github.com/shibukawa/tinybind-go/jsonbind"
)

func init() {
	httpbind.RegisterBind[CreateUserRequest](bindCreateUserRequest)
	httpbind.RegisterWrite[CreateUserResponse](writeCreateUserResponse)
	httpbind.RegisterBind[SearchRequest](bindSearchRequest)
	httpbind.RegisterWrite[SearchResponse](writeSearchResponse)
	httpbind.RegisterBind[EchoRequest](bindEchoRequest)
	httpbind.RegisterWrite[EchoResponse](writeEchoResponse)
	httpbind.RegisterBind[SessionRequest](bindSessionRequest)
	httpbind.RegisterWrite[SessionResponse](writeSessionResponse)
	httpbind.RegisterBind[UserGetRequest](bindUserGetRequest)
	httpbind.RegisterWrite[UserGetResponse](writeUserGetResponse)
	httpbind.RegisterBind[ChatRequest](bindChatRequest)
	httpbind.RegisterWrite[ChatEvent](writeChatEvent)
	jsonbind.RegisterEncode[ChatEvent](encodeChatEvent)
	jsonbind.RegisterAppend[ChatEvent](appendChatEventJSON)
	httpbind.RegisterWrite[HealthResponse](writeHealthResponse)
}

func decodeCreateUserRequestBytes(data []byte) (CreateUserRequest, error) {
	if jsonbind.IsBlank(data) {
		var out CreateUserRequest
		return out, nil
	}
	var p jsonbind.Parser
	p.Reset(data)
	out, err := decodeCreateUserRequestJSON(&p)
	if err != nil {
		return out, err
	}
	if err := p.End(); err != nil {
		return out, err
	}
	return out, nil
}

func decodeCreateUserRequestJSON(p *jsonbind.Parser) (CreateUserRequest, error) {
	var out CreateUserRequest
	null, err := p.ObjectStart()
	if err != nil || null {
		return out, err
	}
	for n := 0; ; n++ {
		key, ok, err := p.ObjectKey(n)
		if err != nil {
			return out, err
		}
		if !ok {
			return out, nil
		}
		switch string(key) {
		case "name":
			v, err := p.String()
			if err != nil {
				return out, jsonbind.FieldError("name", "invalid string", err)
			}
			out.Name = v
		case "email":
			v, err := p.String()
			if err != nil {
				return out, jsonbind.FieldError("email", "invalid string", err)
			}
			out.Email = v
		default:
			if err := p.SkipValue(); err != nil {
				return out, err
			}
		}
	}
}

func bindCreateUserRequest(r *http.Request) (CreateUserRequest, error) {
	var out CreateUserRequest
	var presentName bool
	var presentEmail bool
	queryVals := httpbind.Queries(r)
	needName := true
	needEmail := true
	if qv, ok := httpbind.QueryLookup(queryVals, "name"); ok {
		needName = false
		presentName = true
		out.Name = qv
	}
	if qv, ok := httpbind.QueryLookup(queryVals, "email"); ok {
		needEmail = false
		presentEmail = true
		out.Email = qv
	}
	out.OrgID = httpbind.PathValue(r, "org_id")
	out.Token = httpbind.HeaderValue(r, "Authorization")
	if needName || needEmail {
		if httpbind.IsJSONRequest(r) {
			data, err := httpbind.ReadJSONBody(r)
			if err != nil {
				return out, err
			}
			if !jsonbind.IsBlank(data) {
				var bodyParser jsonbind.Parser
				bodyParser.Reset(data)
				p := &bodyParser
				null, err := p.ObjectStart()
				if err != nil {
					return out, httpbind.JSONBodyError(err)
				}
				if null {
					return out, httpbind.JSONBodyNotObject()
				}
				for n := 0; ; n++ {
					key, ok, err := p.ObjectKey(n)
					if err != nil {
						return out, httpbind.JSONBodyError(err)
					}
					if !ok {
						break
					}
					switch string(key) {
					case "name":
						if !needName {
							if err := p.SkipValue(); err != nil {
								return out, httpbind.JSONBodyError(err)
							}
							continue
						}
						presentName = true
						v, err := p.String()
						if err != nil {
							return out, jsonbind.FieldError("name", "invalid string", err)
						}
						out.Name = v
					case "email":
						if !needEmail {
							if err := p.SkipValue(); err != nil {
								return out, httpbind.JSONBodyError(err)
							}
							continue
						}
						presentEmail = true
						v, err := p.String()
						if err != nil {
							return out, jsonbind.FieldError("email", "invalid string", err)
						}
						out.Email = v
					default:
						if err := p.SkipValue(); err != nil {
							return out, httpbind.JSONBodyError(err)
						}
					}
				}
				if err := p.End(); err != nil {
					return out, httpbind.JSONBodyError(err)
				}
			}
		} else {
			formBody, _, err := httpbind.ReadFormBody(r, true, false)
			if err != nil {
				return out, err
			}
			if needName && formBody != nil {
				if fv, ok := formBody["name"]; ok {
					presentName = true
					out.Name = fv
				}
			}
			if needEmail && formBody != nil {
				if fv, ok := formBody["email"]; ok {
					presentEmail = true
					out.Email = fv
				}
			}
		}
	}
	var checkFields []httpbind.FieldError
	if !presentName || out.Name == "" {
		checkFields = append(checkFields, httpbind.Field("name", "input", "required"))
	}
	if presentName {
		if len(out.Name) < 1 {
			checkFields = append(checkFields, httpbind.Field("name", "input", "length must be >= 1"))
		}
		if len(out.Name) > 64 {
			checkFields = append(checkFields, httpbind.Field("name", "input", "length must be <= 64"))
		}
	}
	if !presentEmail || out.Email == "" {
		checkFields = append(checkFields, httpbind.Field("email", "input", "required"))
	}
	if presentEmail {
		if len(out.Email) > 254 {
			checkFields = append(checkFields, httpbind.Field("email", "input", "length must be <= 254"))
		}
		if out.Email != "" {
			if !httpbind.CheckEmail(out.Email) {
				checkFields = append(checkFields, httpbind.Field("email", "input", "must be a valid email"))
			}
		}
	}
	if len(checkFields) > 0 {
		return out, httpbind.Validation(checkFields...)
	}
	return out, nil
}

func appendCreateUserResponseJSON(dst []byte, v CreateUserResponse) []byte {
	dst = append(dst, '{')
	dst = append(dst, "\"id\":"...)
	dst = jsonbind.AppendString(dst, v.ID)
	dst = append(dst, ",\"name\":"...)
	dst = jsonbind.AppendString(dst, v.Name)
	dst = append(dst, ",\"email\":"...)
	dst = jsonbind.AppendString(dst, v.Email)
	dst = append(dst, ",\"org_id\":"...)
	dst = jsonbind.AppendString(dst, v.OrgID)
	return append(dst, '}')
}

func encodeCreateUserResponse(w io.Writer, v CreateUserResponse) error {
	buf := jsonbind.GetBuffer()
	*buf = appendCreateUserResponseJSON((*buf)[:0], v)
	*buf = append(*buf, '\n')
	_, err := w.Write(*buf)
	jsonbind.PutBuffer(buf)
	return err
}

func writeCreateUserResponse(w http.ResponseWriter, r *http.Request, v CreateUserResponse) error {
	_ = r
	buf := jsonbind.GetBuffer()
	*buf = appendCreateUserResponseJSON((*buf)[:0], v)
	err := httpbind.WriteJSONBytes(w, http.StatusOK, *buf)
	jsonbind.PutBuffer(buf)
	return err
}

func decodeSearchRequestBytes(data []byte) (SearchRequest, error) {
	if jsonbind.IsBlank(data) {
		var out SearchRequest
		return out, nil
	}
	var p jsonbind.Parser
	p.Reset(data)
	out, err := decodeSearchRequestJSON(&p)
	if err != nil {
		return out, err
	}
	if err := p.End(); err != nil {
		return out, err
	}
	return out, nil
}

func decodeSearchRequestJSON(p *jsonbind.Parser) (SearchRequest, error) {
	var out SearchRequest
	null, err := p.ObjectStart()
	if err != nil || null {
		return out, err
	}
	for n := 0; ; n++ {
		key, ok, err := p.ObjectKey(n)
		if err != nil {
			return out, err
		}
		if !ok {
			return out, nil
		}
		switch string(key) {
		case "filter":
			v, err := p.String()
			if err != nil {
				return out, jsonbind.FieldError("filter", "invalid string", err)
			}
			out.Filter = v
		default:
			if err := p.SkipValue(); err != nil {
				return out, err
			}
		}
	}
}

func bindSearchRequest(r *http.Request) (SearchRequest, error) {
	var out SearchRequest
	var presentKeyword bool
	var presentPage bool
	queryVals := httpbind.Queries(r)
	if qv, ok := httpbind.QueryLookup(queryVals, "keyword"); ok {
		presentKeyword = true
		out.Keyword = qv
	}
	if qv, ok := httpbind.QueryLookup(queryVals, "page"); ok {
		presentPage = true
		v, err := httpbind.ParseInt(qv)
		if err != nil {
			return out, httpbind.BindError("page", "query", "invalid int")
		}
		out.Page = v
	}
	if httpbind.IsJSONRequest(r) {
		data, err := httpbind.ReadJSONBody(r)
		if err != nil {
			return out, err
		}
		if !jsonbind.IsBlank(data) {
			var bodyParser jsonbind.Parser
			bodyParser.Reset(data)
			p := &bodyParser
			null, err := p.ObjectStart()
			if err != nil {
				return out, httpbind.JSONBodyError(err)
			}
			if null {
				return out, httpbind.JSONBodyNotObject()
			}
			for n := 0; ; n++ {
				key, ok, err := p.ObjectKey(n)
				if err != nil {
					return out, httpbind.JSONBodyError(err)
				}
				if !ok {
					break
				}
				switch string(key) {
				case "filter":
					v, err := p.String()
					if err != nil {
						return out, jsonbind.FieldError("filter", "invalid string", err)
					}
					out.Filter = v
				default:
					if err := p.SkipValue(); err != nil {
						return out, httpbind.JSONBodyError(err)
					}
				}
			}
			if err := p.End(); err != nil {
				return out, httpbind.JSONBodyError(err)
			}
		}
	} else {
		formBody, _, err := httpbind.ReadFormBody(r, true, false)
		if err != nil {
			return out, err
		}
		if formBody != nil {
			if fv, ok := formBody["filter"]; ok {
				out.Filter = fv
			}
		}
	}
	var checkFields []httpbind.FieldError
	if !presentKeyword || out.Keyword == "" {
		checkFields = append(checkFields, httpbind.Field("keyword", "query", "required"))
	}
	if presentPage {
		if out.Page < 1 {
			checkFields = append(checkFields, httpbind.Field("page", "query", "must be >= 1"))
		}
	}
	if len(checkFields) > 0 {
		return out, httpbind.Validation(checkFields...)
	}
	if !presentPage {
		out.Page = 1
	}
	return out, nil
}

func appendSearchResponseJSON(dst []byte, v SearchResponse) []byte {
	dst = append(dst, '{')
	dst = append(dst, "\"keyword\":"...)
	dst = jsonbind.AppendString(dst, v.Keyword)
	dst = append(dst, ",\"page\":"...)
	dst = jsonbind.AppendInt(dst, int64(v.Page))
	dst = append(dst, ",\"filter\":"...)
	dst = jsonbind.AppendString(dst, v.Filter)
	dst = append(dst, ",\"hits\":"...)
	dst = jsonbind.AppendInt(dst, int64(v.Hits))
	return append(dst, '}')
}

func encodeSearchResponse(w io.Writer, v SearchResponse) error {
	buf := jsonbind.GetBuffer()
	*buf = appendSearchResponseJSON((*buf)[:0], v)
	*buf = append(*buf, '\n')
	_, err := w.Write(*buf)
	jsonbind.PutBuffer(buf)
	return err
}

func writeSearchResponse(w http.ResponseWriter, r *http.Request, v SearchResponse) error {
	_ = r
	buf := jsonbind.GetBuffer()
	*buf = appendSearchResponseJSON((*buf)[:0], v)
	err := httpbind.WriteJSONBytes(w, http.StatusOK, *buf)
	jsonbind.PutBuffer(buf)
	return err
}

func decodeEchoRequestBytes(data []byte) (EchoRequest, error) {
	if jsonbind.IsBlank(data) {
		var out EchoRequest
		return out, nil
	}
	var p jsonbind.Parser
	p.Reset(data)
	out, err := decodeEchoRequestJSON(&p)
	if err != nil {
		return out, err
	}
	if err := p.End(); err != nil {
		return out, err
	}
	return out, nil
}

func decodeEchoRequestJSON(p *jsonbind.Parser) (EchoRequest, error) {
	var out EchoRequest
	null, err := p.ObjectStart()
	if err != nil || null {
		return out, err
	}
	for n := 0; ; n++ {
		key, ok, err := p.ObjectKey(n)
		if err != nil {
			return out, err
		}
		if !ok {
			return out, nil
		}
		switch string(key) {
		case "message":
			v, err := p.String()
			if err != nil {
				return out, jsonbind.FieldError("message", "invalid string", err)
			}
			out.Message = v
		default:
			if err := p.SkipValue(); err != nil {
				return out, err
			}
		}
	}
}

func bindEchoRequest(r *http.Request) (EchoRequest, error) {
	var out EchoRequest
	var presentMessage bool
	queryVals := httpbind.Queries(r)
	needMessage := true
	if qv, ok := httpbind.QueryLookup(queryVals, "message"); ok {
		needMessage = false
		presentMessage = true
		out.Message = qv
	}
	if qv, ok := httpbind.QueryLookup(queryVals, "n"); ok {
		v, err := httpbind.ParseInt(qv)
		if err != nil {
			return out, httpbind.BindError("n", "query", "invalid int")
		}
		out.N = v
	}
	if needMessage {
		if httpbind.IsJSONRequest(r) {
			data, err := httpbind.ReadJSONBody(r)
			if err != nil {
				return out, err
			}
			if !jsonbind.IsBlank(data) {
				var bodyParser jsonbind.Parser
				bodyParser.Reset(data)
				p := &bodyParser
				null, err := p.ObjectStart()
				if err != nil {
					return out, httpbind.JSONBodyError(err)
				}
				if null {
					return out, httpbind.JSONBodyNotObject()
				}
				for n := 0; ; n++ {
					key, ok, err := p.ObjectKey(n)
					if err != nil {
						return out, httpbind.JSONBodyError(err)
					}
					if !ok {
						break
					}
					switch string(key) {
					case "message":
						if !needMessage {
							if err := p.SkipValue(); err != nil {
								return out, httpbind.JSONBodyError(err)
							}
							continue
						}
						presentMessage = true
						v, err := p.String()
						if err != nil {
							return out, jsonbind.FieldError("message", "invalid string", err)
						}
						out.Message = v
					default:
						if err := p.SkipValue(); err != nil {
							return out, httpbind.JSONBodyError(err)
						}
					}
				}
				if err := p.End(); err != nil {
					return out, httpbind.JSONBodyError(err)
				}
			}
		} else {
			formBody, _, err := httpbind.ReadFormBody(r, true, false)
			if err != nil {
				return out, err
			}
			if needMessage && formBody != nil {
				if fv, ok := formBody["message"]; ok {
					presentMessage = true
					out.Message = fv
				}
			}
		}
	}
	var checkFields []httpbind.FieldError
	if !presentMessage || out.Message == "" {
		checkFields = append(checkFields, httpbind.Field("message", "input", "required"))
	}
	if len(checkFields) > 0 {
		return out, httpbind.Validation(checkFields...)
	}
	return out, nil
}

func appendEchoResponseJSON(dst []byte, v EchoResponse) []byte {
	dst = append(dst, '{')
	dst = append(dst, "\"message\":"...)
	dst = jsonbind.AppendString(dst, v.Message)
	dst = append(dst, ",\"n\":"...)
	dst = jsonbind.AppendInt(dst, int64(v.N))
	return append(dst, '}')
}

func encodeEchoResponse(w io.Writer, v EchoResponse) error {
	buf := jsonbind.GetBuffer()
	*buf = appendEchoResponseJSON((*buf)[:0], v)
	*buf = append(*buf, '\n')
	_, err := w.Write(*buf)
	jsonbind.PutBuffer(buf)
	return err
}

func writeEchoResponse(w http.ResponseWriter, r *http.Request, v EchoResponse) error {
	_ = r
	buf := jsonbind.GetBuffer()
	*buf = appendEchoResponseJSON((*buf)[:0], v)
	err := httpbind.WriteJSONBytes(w, http.StatusOK, *buf)
	jsonbind.PutBuffer(buf)
	return err
}

func decodeSessionRequestBytes(data []byte) (SessionRequest, error) {
	if jsonbind.IsBlank(data) {
		var out SessionRequest
		return out, nil
	}
	var p jsonbind.Parser
	p.Reset(data)
	out, err := decodeSessionRequestJSON(&p)
	if err != nil {
		return out, err
	}
	if err := p.End(); err != nil {
		return out, err
	}
	return out, nil
}

func decodeSessionRequestJSON(p *jsonbind.Parser) (SessionRequest, error) {
	var out SessionRequest
	null, err := p.ObjectStart()
	if err != nil || null {
		return out, err
	}
	for n := 0; ; n++ {
		key, ok, err := p.ObjectKey(n)
		if err != nil {
			return out, err
		}
		if !ok {
			return out, nil
		}
		switch string(key) {
		default:
			if err := p.SkipValue(); err != nil {
				return out, err
			}
		}
	}
}

func bindSessionRequest(r *http.Request) (SessionRequest, error) {
	var out SessionRequest
	if cv, ok := httpbind.CookieValue(r, "session"); ok {
		out.Session = cv
	}
	return out, nil
}

func appendSessionResponseJSON(dst []byte, v SessionResponse) []byte {
	dst = append(dst, '{')
	dst = append(dst, "\"session\":"...)
	dst = jsonbind.AppendString(dst, v.Session)
	dst = append(dst, ",\"ok\":"...)
	dst = jsonbind.AppendBool(dst, v.OK)
	return append(dst, '}')
}

func encodeSessionResponse(w io.Writer, v SessionResponse) error {
	buf := jsonbind.GetBuffer()
	*buf = appendSessionResponseJSON((*buf)[:0], v)
	*buf = append(*buf, '\n')
	_, err := w.Write(*buf)
	jsonbind.PutBuffer(buf)
	return err
}

func writeSessionResponse(w http.ResponseWriter, r *http.Request, v SessionResponse) error {
	_ = r
	buf := jsonbind.GetBuffer()
	*buf = appendSessionResponseJSON((*buf)[:0], v)
	err := httpbind.WriteJSONBytes(w, http.StatusOK, *buf)
	jsonbind.PutBuffer(buf)
	return err
}

func decodeUserGetRequestBytes(data []byte) (UserGetRequest, error) {
	if jsonbind.IsBlank(data) {
		var out UserGetRequest
		return out, nil
	}
	var p jsonbind.Parser
	p.Reset(data)
	out, err := decodeUserGetRequestJSON(&p)
	if err != nil {
		return out, err
	}
	if err := p.End(); err != nil {
		return out, err
	}
	return out, nil
}

func decodeUserGetRequestJSON(p *jsonbind.Parser) (UserGetRequest, error) {
	var out UserGetRequest
	null, err := p.ObjectStart()
	if err != nil || null {
		return out, err
	}
	for n := 0; ; n++ {
		key, ok, err := p.ObjectKey(n)
		if err != nil {
			return out, err
		}
		if !ok {
			return out, nil
		}
		switch string(key) {
		default:
			if err := p.SkipValue(); err != nil {
				return out, err
			}
		}
	}
}

func bindUserGetRequest(r *http.Request) (UserGetRequest, error) {
	var out UserGetRequest
	out.ID = httpbind.PathValue(r, "id")
	return out, nil
}

func appendUserGetResponseJSON(dst []byte, v UserGetResponse) []byte {
	dst = append(dst, '{')
	dst = append(dst, "\"id\":"...)
	dst = jsonbind.AppendString(dst, v.ID)
	dst = append(dst, ",\"name\":"...)
	dst = jsonbind.AppendString(dst, v.Name)
	return append(dst, '}')
}

func encodeUserGetResponse(w io.Writer, v UserGetResponse) error {
	buf := jsonbind.GetBuffer()
	*buf = appendUserGetResponseJSON((*buf)[:0], v)
	*buf = append(*buf, '\n')
	_, err := w.Write(*buf)
	jsonbind.PutBuffer(buf)
	return err
}

func writeUserGetResponse(w http.ResponseWriter, r *http.Request, v UserGetResponse) error {
	_ = r
	buf := jsonbind.GetBuffer()
	*buf = appendUserGetResponseJSON((*buf)[:0], v)
	err := httpbind.WriteJSONBytes(w, http.StatusOK, *buf)
	jsonbind.PutBuffer(buf)
	return err
}

func decodeChatRequestBytes(data []byte) (ChatRequest, error) {
	if jsonbind.IsBlank(data) {
		var out ChatRequest
		return out, nil
	}
	var p jsonbind.Parser
	p.Reset(data)
	out, err := decodeChatRequestJSON(&p)
	if err != nil {
		return out, err
	}
	if err := p.End(); err != nil {
		return out, err
	}
	return out, nil
}

func decodeChatRequestJSON(p *jsonbind.Parser) (ChatRequest, error) {
	var out ChatRequest
	null, err := p.ObjectStart()
	if err != nil || null {
		return out, err
	}
	for n := 0; ; n++ {
		key, ok, err := p.ObjectKey(n)
		if err != nil {
			return out, err
		}
		if !ok {
			return out, nil
		}
		switch string(key) {
		case "message":
			v, err := p.String()
			if err != nil {
				return out, jsonbind.FieldError("message", "invalid string", err)
			}
			out.Message = v
		default:
			if err := p.SkipValue(); err != nil {
				return out, err
			}
		}
	}
}

func bindChatRequest(r *http.Request) (ChatRequest, error) {
	var out ChatRequest
	queryVals := httpbind.Queries(r)
	needMessage := true
	if qv, ok := httpbind.QueryLookup(queryVals, "message"); ok {
		needMessage = false
		out.Message = qv
	}
	if needMessage {
		if httpbind.IsJSONRequest(r) {
			data, err := httpbind.ReadJSONBody(r)
			if err != nil {
				return out, err
			}
			if !jsonbind.IsBlank(data) {
				var bodyParser jsonbind.Parser
				bodyParser.Reset(data)
				p := &bodyParser
				null, err := p.ObjectStart()
				if err != nil {
					return out, httpbind.JSONBodyError(err)
				}
				if null {
					return out, httpbind.JSONBodyNotObject()
				}
				for n := 0; ; n++ {
					key, ok, err := p.ObjectKey(n)
					if err != nil {
						return out, httpbind.JSONBodyError(err)
					}
					if !ok {
						break
					}
					switch string(key) {
					case "message":
						if !needMessage {
							if err := p.SkipValue(); err != nil {
								return out, httpbind.JSONBodyError(err)
							}
							continue
						}
						v, err := p.String()
						if err != nil {
							return out, jsonbind.FieldError("message", "invalid string", err)
						}
						out.Message = v
					default:
						if err := p.SkipValue(); err != nil {
							return out, httpbind.JSONBodyError(err)
						}
					}
				}
				if err := p.End(); err != nil {
					return out, httpbind.JSONBodyError(err)
				}
			}
		} else {
			formBody, _, err := httpbind.ReadFormBody(r, true, false)
			if err != nil {
				return out, err
			}
			if needMessage && formBody != nil {
				if fv, ok := formBody["message"]; ok {
					out.Message = fv
				}
			}
		}
	}
	return out, nil
}

func appendChatEventJSON(dst []byte, v ChatEvent) []byte {
	dst = append(dst, '{')
	dst = append(dst, "\"type\":"...)
	dst = jsonbind.AppendString(dst, v.Type)
	if v.Delta != "" {
		dst = append(dst, ",\"delta\":"...)
		dst = jsonbind.AppendString(dst, v.Delta)
	}
	return append(dst, '}')
}

func encodeChatEvent(w io.Writer, v ChatEvent) error {
	buf := jsonbind.GetBuffer()
	*buf = appendChatEventJSON((*buf)[:0], v)
	*buf = append(*buf, '\n')
	_, err := w.Write(*buf)
	jsonbind.PutBuffer(buf)
	return err
}

func writeChatEvent(w http.ResponseWriter, r *http.Request, v ChatEvent) error {
	_ = r
	buf := jsonbind.GetBuffer()
	*buf = appendChatEventJSON((*buf)[:0], v)
	err := httpbind.WriteJSONBytes(w, http.StatusOK, *buf)
	jsonbind.PutBuffer(buf)
	return err
}

func appendHealthResponseJSON(dst []byte, v HealthResponse) []byte {
	dst = append(dst, '{')
	dst = append(dst, "\"status\":"...)
	dst = jsonbind.AppendString(dst, v.Status)
	return append(dst, '}')
}

func encodeHealthResponse(w io.Writer, v HealthResponse) error {
	buf := jsonbind.GetBuffer()
	*buf = appendHealthResponseJSON((*buf)[:0], v)
	*buf = append(*buf, '\n')
	_, err := w.Write(*buf)
	jsonbind.PutBuffer(buf)
	return err
}

func writeHealthResponse(w http.ResponseWriter, r *http.Request, v HealthResponse) error {
	_ = r
	buf := jsonbind.GetBuffer()
	*buf = appendHealthResponseJSON((*buf)[:0], v)
	err := httpbind.WriteJSONBytes(w, http.StatusOK, *buf)
	jsonbind.PutBuffer(buf)
	return err
}
