// Code generated by tinybind; DO NOT EDIT.

package main

import (
	"encoding/json"
	"io"
	"net/http"

	"github.com/shibukawa/tinybind-go"
	"github.com/shibukawa/tinybind-go/jsonbind"
)

type jsonRaw = json.RawMessage

func init() {
	httpbind.RegisterBind[CreateUserRequest](bindCreateUserRequest)
	httpbind.RegisterWrite[CreateUserResponse](writeCreateUserResponse)
	httpbind.RegisterBind[SearchRequest](bindSearchRequest)
	httpbind.RegisterWrite[SearchResponse](writeSearchResponse)
	httpbind.RegisterBind[EchoRequest](bindEchoRequest)
	httpbind.RegisterWrite[EchoResponse](writeEchoResponse)
	httpbind.RegisterBind[SessionRequest](bindSessionRequest)
	httpbind.RegisterWrite[SessionResponse](writeSessionResponse)
	httpbind.RegisterBind[UserGetRequest](bindUserGetRequest)
	httpbind.RegisterWrite[UserGetResponse](writeUserGetResponse)
	httpbind.RegisterBind[ChatRequest](bindChatRequest)
	jsonbind.RegisterEncode[ChatEvent](encodeChatEvent)
	httpbind.RegisterWrite[HealthResponse](writeHealthResponse)
}

func decodeCreateUserRequestBytes(data []byte) (CreateUserRequest, error) {
	return decodeCreateUserRequestJSON(json.RawMessage(data))
}

func decodeCreateUserRequestJSON(raw json.RawMessage) (CreateUserRequest, error) {
	var out CreateUserRequest
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["name"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("name", "invalid string", err)
		}
		out.Name = v
	}
	if raw, ok := m["email"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("email", "invalid string", err)
		}
		out.Email = v
	}
	return out, nil
}

func bindCreateUserRequest(r *http.Request) (CreateUserRequest, error) {
	var out CreateUserRequest
	var presentName bool
	var presentEmail bool
	var jsonBody map[string]jsonRaw
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbind.IsJSONRequest(r) {
			m, err := httpbind.ReadJSONMap(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbind.IsFormRequest(r) {
			m, err := httpbind.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbind.IsMultipartRequest(r) {
			m, _, err := httpbind.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		return nil
	}
	if qv, ok := httpbind.QueryValue(r, "name"); ok {
		presentName = true
		out.Name = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["name"]; ok {
			presentName = true
			v, err := jsonbind.DecodeJSONString(raw)
			if err != nil {
				return out, jsonbind.FieldError("name", "invalid string", err)
			}
			out.Name = v
		} else if formBody != nil {
			if fv, ok := formBody["name"]; ok {
				presentName = true
				out.Name = fv
			}
		}
	}
	if qv, ok := httpbind.QueryValue(r, "email"); ok {
		presentEmail = true
		out.Email = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["email"]; ok {
			presentEmail = true
			v, err := jsonbind.DecodeJSONString(raw)
			if err != nil {
				return out, jsonbind.FieldError("email", "invalid string", err)
			}
			out.Email = v
		} else if formBody != nil {
			if fv, ok := formBody["email"]; ok {
				presentEmail = true
				out.Email = fv
			}
		}
	}
	out.OrgID = httpbind.PathValue(r, "org_id")
	out.Token = httpbind.HeaderValue(r, "Authorization")
	var checkFields []httpbind.FieldError
	if !presentName || out.Name == "" {
		checkFields = append(checkFields, httpbind.Field("name", "input", "required"))
	}
	if presentName {
		if len(out.Name) < 1 {
			checkFields = append(checkFields, httpbind.Field("name", "input", "length must be >= 1"))
		}
		if len(out.Name) > 64 {
			checkFields = append(checkFields, httpbind.Field("name", "input", "length must be <= 64"))
		}
	}
	if !presentEmail || out.Email == "" {
		checkFields = append(checkFields, httpbind.Field("email", "input", "required"))
	}
	if presentEmail {
		if len(out.Email) > 254 {
			checkFields = append(checkFields, httpbind.Field("email", "input", "length must be <= 254"))
		}
		if out.Email != "" {
			if !httpbind.CheckEmail(out.Email) {
				checkFields = append(checkFields, httpbind.Field("email", "input", "must be a valid email"))
			}
		}
	}
	if len(checkFields) > 0 {
		return out, httpbind.Validation(checkFields...)
	}
	return out, nil
}

func encodeCreateUserResponseMap(v CreateUserResponse) map[string]any {
	body := map[string]any{}
	body["id"] = v.ID
	body["name"] = v.Name
	body["email"] = v.Email
	body["org_id"] = v.OrgID
	return body
}

func encodeCreateUserResponse(w io.Writer, v CreateUserResponse) error {
	return json.NewEncoder(w).Encode(encodeCreateUserResponseMap(v))
}

func writeCreateUserResponse(w http.ResponseWriter, r *http.Request, v CreateUserResponse) error {
	_ = r
	return httpbind.WriteJSON(w, http.StatusOK, encodeCreateUserResponseMap(v))
}

func decodeSearchRequestBytes(data []byte) (SearchRequest, error) {
	return decodeSearchRequestJSON(json.RawMessage(data))
}

func decodeSearchRequestJSON(raw json.RawMessage) (SearchRequest, error) {
	var out SearchRequest
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["filter"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("filter", "invalid string", err)
		}
		out.Filter = v
	}
	return out, nil
}

func bindSearchRequest(r *http.Request) (SearchRequest, error) {
	var out SearchRequest
	var presentKeyword bool
	var presentPage bool
	var jsonBody map[string]jsonRaw
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbind.IsJSONRequest(r) {
			m, err := httpbind.ReadJSONMap(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbind.IsFormRequest(r) {
			m, err := httpbind.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbind.IsMultipartRequest(r) {
			m, _, err := httpbind.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		return nil
	}
	if qv, ok := httpbind.QueryValue(r, "keyword"); ok {
		presentKeyword = true
		out.Keyword = qv
	}
	if qv, ok := httpbind.QueryValue(r, "page"); ok {
		presentPage = true
		v, err := httpbind.ParseInt(qv)
		if err != nil {
			return out, httpbind.BindError("page", "query", "invalid int")
		}
		out.Page = v
	}
	if err := readBody(); err != nil {
		return out, err
	}
	if raw, ok := jsonBody["filter"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("filter", "invalid string", err)
		}
		out.Filter = v
	} else if formBody != nil {
		if fv, ok := formBody["filter"]; ok {
			out.Filter = fv
		}
	}
	var checkFields []httpbind.FieldError
	if !presentKeyword || out.Keyword == "" {
		checkFields = append(checkFields, httpbind.Field("keyword", "query", "required"))
	}
	if presentPage {
		if out.Page < 1 {
			checkFields = append(checkFields, httpbind.Field("page", "query", "must be >= 1"))
		}
	}
	if len(checkFields) > 0 {
		return out, httpbind.Validation(checkFields...)
	}
	if !presentPage {
		out.Page = 1
	}
	return out, nil
}

func encodeSearchResponseMap(v SearchResponse) map[string]any {
	body := map[string]any{}
	body["keyword"] = v.Keyword
	body["page"] = v.Page
	body["filter"] = v.Filter
	body["hits"] = v.Hits
	return body
}

func encodeSearchResponse(w io.Writer, v SearchResponse) error {
	return json.NewEncoder(w).Encode(encodeSearchResponseMap(v))
}

func writeSearchResponse(w http.ResponseWriter, r *http.Request, v SearchResponse) error {
	_ = r
	return httpbind.WriteJSON(w, http.StatusOK, encodeSearchResponseMap(v))
}

func decodeEchoRequestBytes(data []byte) (EchoRequest, error) {
	return decodeEchoRequestJSON(json.RawMessage(data))
}

func decodeEchoRequestJSON(raw json.RawMessage) (EchoRequest, error) {
	var out EchoRequest
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["message"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("message", "invalid string", err)
		}
		out.Message = v
	}
	return out, nil
}

func bindEchoRequest(r *http.Request) (EchoRequest, error) {
	var out EchoRequest
	var presentMessage bool
	var jsonBody map[string]jsonRaw
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbind.IsJSONRequest(r) {
			m, err := httpbind.ReadJSONMap(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbind.IsFormRequest(r) {
			m, err := httpbind.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbind.IsMultipartRequest(r) {
			m, _, err := httpbind.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		return nil
	}
	if qv, ok := httpbind.QueryValue(r, "message"); ok {
		presentMessage = true
		out.Message = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["message"]; ok {
			presentMessage = true
			v, err := jsonbind.DecodeJSONString(raw)
			if err != nil {
				return out, jsonbind.FieldError("message", "invalid string", err)
			}
			out.Message = v
		} else if formBody != nil {
			if fv, ok := formBody["message"]; ok {
				presentMessage = true
				out.Message = fv
			}
		}
	}
	if qv, ok := httpbind.QueryValue(r, "n"); ok {
		v, err := httpbind.ParseInt(qv)
		if err != nil {
			return out, httpbind.BindError("n", "query", "invalid int")
		}
		out.N = v
	}
	var checkFields []httpbind.FieldError
	if !presentMessage || out.Message == "" {
		checkFields = append(checkFields, httpbind.Field("message", "input", "required"))
	}
	if len(checkFields) > 0 {
		return out, httpbind.Validation(checkFields...)
	}
	return out, nil
}

func encodeEchoResponseMap(v EchoResponse) map[string]any {
	body := map[string]any{}
	body["message"] = v.Message
	body["n"] = v.N
	return body
}

func encodeEchoResponse(w io.Writer, v EchoResponse) error {
	return json.NewEncoder(w).Encode(encodeEchoResponseMap(v))
}

func writeEchoResponse(w http.ResponseWriter, r *http.Request, v EchoResponse) error {
	_ = r
	return httpbind.WriteJSON(w, http.StatusOK, encodeEchoResponseMap(v))
}

func decodeSessionRequestBytes(data []byte) (SessionRequest, error) {
	return decodeSessionRequestJSON(json.RawMessage(data))
}

func decodeSessionRequestJSON(raw json.RawMessage) (SessionRequest, error) {
	var out SessionRequest
	_ = raw
	return out, nil
}

func bindSessionRequest(r *http.Request) (SessionRequest, error) {
	var out SessionRequest
	if cv, ok := httpbind.CookieValue(r, "session"); ok {
		out.Session = cv
	}
	return out, nil
}

func encodeSessionResponseMap(v SessionResponse) map[string]any {
	body := map[string]any{}
	body["session"] = v.Session
	body["ok"] = v.OK
	return body
}

func encodeSessionResponse(w io.Writer, v SessionResponse) error {
	return json.NewEncoder(w).Encode(encodeSessionResponseMap(v))
}

func writeSessionResponse(w http.ResponseWriter, r *http.Request, v SessionResponse) error {
	_ = r
	return httpbind.WriteJSON(w, http.StatusOK, encodeSessionResponseMap(v))
}

func decodeUserGetRequestBytes(data []byte) (UserGetRequest, error) {
	return decodeUserGetRequestJSON(json.RawMessage(data))
}

func decodeUserGetRequestJSON(raw json.RawMessage) (UserGetRequest, error) {
	var out UserGetRequest
	_ = raw
	return out, nil
}

func bindUserGetRequest(r *http.Request) (UserGetRequest, error) {
	var out UserGetRequest
	out.ID = httpbind.PathValue(r, "id")
	return out, nil
}

func encodeUserGetResponseMap(v UserGetResponse) map[string]any {
	body := map[string]any{}
	body["id"] = v.ID
	body["name"] = v.Name
	return body
}

func encodeUserGetResponse(w io.Writer, v UserGetResponse) error {
	return json.NewEncoder(w).Encode(encodeUserGetResponseMap(v))
}

func writeUserGetResponse(w http.ResponseWriter, r *http.Request, v UserGetResponse) error {
	_ = r
	return httpbind.WriteJSON(w, http.StatusOK, encodeUserGetResponseMap(v))
}

func decodeChatRequestBytes(data []byte) (ChatRequest, error) {
	return decodeChatRequestJSON(json.RawMessage(data))
}

func decodeChatRequestJSON(raw json.RawMessage) (ChatRequest, error) {
	var out ChatRequest
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["message"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("message", "invalid string", err)
		}
		out.Message = v
	}
	return out, nil
}

func bindChatRequest(r *http.Request) (ChatRequest, error) {
	var out ChatRequest
	var jsonBody map[string]jsonRaw
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbind.IsJSONRequest(r) {
			m, err := httpbind.ReadJSONMap(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbind.IsFormRequest(r) {
			m, err := httpbind.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbind.IsMultipartRequest(r) {
			m, _, err := httpbind.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		return nil
	}
	if qv, ok := httpbind.QueryValue(r, "message"); ok {
		out.Message = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["message"]; ok {
			v, err := jsonbind.DecodeJSONString(raw)
			if err != nil {
				return out, jsonbind.FieldError("message", "invalid string", err)
			}
			out.Message = v
		} else if formBody != nil {
			if fv, ok := formBody["message"]; ok {
				out.Message = fv
			}
		}
	}
	return out, nil
}

func encodeChatEventMap(v ChatEvent) map[string]any {
	body := map[string]any{}
	body["type"] = v.Type
	body["delta"] = v.Delta
	return body
}

func encodeChatEvent(w io.Writer, v ChatEvent) error {
	return json.NewEncoder(w).Encode(encodeChatEventMap(v))
}

func encodeHealthResponseMap(v HealthResponse) map[string]any {
	body := map[string]any{}
	body["status"] = v.Status
	return body
}

func encodeHealthResponse(w io.Writer, v HealthResponse) error {
	return json.NewEncoder(w).Encode(encodeHealthResponseMap(v))
}

func writeHealthResponse(w http.ResponseWriter, r *http.Request, v HealthResponse) error {
	_ = r
	return httpbind.WriteJSON(w, http.StatusOK, encodeHealthResponseMap(v))
}
