// Code generated by tinybind HTML templates; DO NOT EDIT.

package pages

import (
	"strings"

	"github.com/shibukawa/tinybind-go/htmlbind"
)

type Payload struct {
	Message string
	Count   int
	Enabled bool
}

type DocumentParams struct {
	Markup     string
	Css        string
	Javascript string
	Payload    Payload
}

func _tinybindJSONPayload(value Payload) string {
	var out strings.Builder
	out.WriteByte('{')
	out.WriteString("\"message\":")
	out.WriteString(htmlbind.JSONString[string](value.Message))
	out.WriteByte(',')
	out.WriteString("\"count\":")
	out.WriteString(htmlbind.JSONInt(value.Count))
	out.WriteByte(',')
	out.WriteString("\"enabled\":")
	out.WriteString(htmlbind.JSONBool(value.Enabled))
	out.WriteByte('}')
	return out.String()
}

var planDocumentOps = htmlbind.Builder[DocumentParams]{}

var planDocumentPlan = &htmlbind.Plan[DocumentParams]{
	Head: nil,
	Ops: []htmlbind.Op[DocumentParams]{
		planDocumentOps.Static(" "),
		planDocumentOps.Raw(func(p DocumentParams) string { return string(p.Markup) }),
		planDocumentOps.Static(" <style>"),
		planDocumentOps.Raw(func(p DocumentParams) string { return string(p.Css) }),
		planDocumentOps.Static("</style> <script>"),
		planDocumentOps.Raw(func(p DocumentParams) string { return string(p.Javascript) }),
		planDocumentOps.Static("</script> <script>window.payload = "),
		planDocumentOps.Raw(func(p DocumentParams) string { return _tinybindJSONPayload(p.Payload) }),
		planDocumentOps.Static(";</script> "),
	},
}

// Document binds Document to its parameters, producing a renderable fragment.
func Document(params DocumentParams) htmlbind.Fragment {
	return htmlbind.Bind(planDocumentPlan, params)
}
