// Code generated by configbind/codegen; DO NOT EDIT.
// tinybind:generated v1 inputs=sha256:5bbb4123146c49340744263db3bd93c44911cc97936f4efc88210ef0f784cce1 self=sha256:dc163add9e5f60f3a645b3f10b5670413f47c91956e1b7fd457cc9cf0a152279 outputs=tinybind_gen.go,configbind_gen.go,tinybind_openapi_gen.go

package configbindfixture

import (
	"fmt"
	"strconv"
	"time"

	"github.com/shibukawa/tinybind-go/cliparser"
	"github.com/shibukawa/tinybind-go/configbind"
)

func init() {
	registerWebServerConfigDefinition0()
	registerMigrateOptionsDefinition1()
}

func registerWebServerConfigDefinition0() {
	configbind.Register[WebServerConfig](configbind.Definition{
		TypeName: "github.com/shibukawa/tinybind-go/internal/configbindfixture.WebServerConfig",
		Prefix:   "webserver",
		Doc:      "WebServerConfig is a Bind-style config used by generator and load tests",
		KnownKeys: []string{
			"webserver.port",
			"webserver.host",
			"webserver.read_timeout",
			"webserver.cors_origins",
			"webserver.max_request_body",
			"webserver.admin_token",
			"webserver.tracing",
			"webserver.tracing_url",
			"webserver.tls.enabled",
			"webserver.tls.cert_path",
			"webserver.routes",
		},
		Defaults: map[string]string{
			"webserver.port":         "8080",
			"webserver.host":         "localhost",
			"webserver.read_timeout": "5s",
			"webserver.admin_token":  "seed-token",
			"webserver.tls.enabled":  "false",
		},
		DependsOn: map[string][]string{
			"webserver.tracing_url":   {"webserver.tracing"},
			"webserver.tls.cert_path": {"webserver.tls.enabled"},
		},
		Falsy: map[string]string{
			"webserver.tracing": "off",
		},
		Secrets: map[string]string{
			"webserver.admin_token":  "hide",
			"webserver.routes.owner": "mask",
		},
		FlagMetas: []cliparser.FieldMeta{
			{Prefix: "webserver", Key: "port", Opt: "port,p", Help: "HTTP listen port"},
			{Prefix: "webserver", Key: "host", Help: "listen host"},
			{Prefix: "webserver", Key: "read_timeout", Help: "request read timeout"},
			{Prefix: "webserver", Key: "cors_origins", Help: "CORS origins", Kind: cliparser.KindArray},
			{Prefix: "webserver", Key: "max_request_body", Help: "maximum request body in bytes"},
			{Prefix: "webserver", Key: "admin_token", Help: "admin API token"},
			{Prefix: "webserver", Key: "tracing", Help: "tracing exporter"},
			{Prefix: "webserver", Key: "tracing_url", Help: "tracing collector URL"},
			{Prefix: "webserver", Key: "tls.enabled", Help: "enable TLS", Kind: cliparser.KindBool},
			{Prefix: "webserver", Key: "tls.cert_path", Env: "TLS_CERT_FILE", Help: "TLS certificate path"},
		},
		Apply: applyWebServerConfigDefinition0,
		Scaffold: []configbind.ScaffoldField{
			{Key: "port", Kind: configbind.ScaffoldInt, Default: "8080", Opt: "port,p", Help: "HTTP listen port"},
			{Key: "host", Kind: configbind.ScaffoldString, Default: "localhost", Help: "listen host"},
			{Key: "read_timeout", Kind: configbind.ScaffoldDuration, Default: "5s", Help: "request read timeout"},
			{Key: "cors_origins", Kind: configbind.ScaffoldStringSlice, Help: "CORS origins"},
			{Key: "max_request_body", Kind: configbind.ScaffoldInt, Help: "maximum request body in bytes"},
			{Key: "admin_token", Kind: configbind.ScaffoldString, Default: "seed-token", Help: "admin API token"},
			{Key: "tracing", Kind: configbind.ScaffoldString, Help: "tracing exporter"},
			{Key: "tracing_url", Kind: configbind.ScaffoldString, Help: "tracing collector URL"},
			{Key: "tls.enabled", Kind: configbind.ScaffoldBool, Default: "false", Help: "enable TLS"},
			{Key: "tls.cert_path", Kind: configbind.ScaffoldString, Env: "TLS_CERT_FILE", Help: "TLS certificate path"},
			{Key: "routes", Kind: configbind.ScaffoldTableArray, Help: "static routes, one [[webserver.routes]] table each", Nested: []configbind.ScaffoldField{
				{Key: "path", Kind: configbind.ScaffoldString, Help: "URL path prefix"},
				{Key: "dir", Kind: configbind.ScaffoldString, Help: "directory served under the path"},
				{Key: "owner", Kind: configbind.ScaffoldString, Help: "team that owns this route"},
				{Key: "listing", Kind: configbind.ScaffoldBool, Default: "false", Help: "allow directory listing"},
				{Key: "max_age", Kind: configbind.ScaffoldDuration, Default: "1h", Help: "cache max age for this route"},
			}},
		},
	})
}

func applyWebServerConfigDefinition0(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*WebServerConfig)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply WebServerConfig: bad destination")
	}
	if v, ok := o.GetString("webserver.port"); ok {
		n, err := strconv.ParseInt(v, 10, 0)
		if err != nil {
			return fmt.Errorf("configbind: webserver.port: %w", err)
		}
		p.Port = int(n)
	} else {
		p.Port = 8080
	}
	if v, ok := o.GetString("webserver.host"); ok {
		p.Host = v
	} else {
		p.Host = "localhost"
	}
	if v, ok := o.GetString("webserver.read_timeout"); ok {
		d, err := time.ParseDuration(v)
		if err != nil {
			return fmt.Errorf("configbind: webserver.read_timeout: %w", err)
		}
		p.ReadTimeout = d
	} else {
		p.ReadTimeout = 5000000000 // 5s
	}
	if v, ok := o.GetMulti("webserver.cors_origins"); ok {
		p.CorsOrigins = v
	}
	if v, ok := o.GetString("webserver.max_request_body"); ok {
		n, err := strconv.ParseInt(v, 10, 64)
		if err != nil {
			return fmt.Errorf("configbind: webserver.max_request_body: %w", err)
		}
		p.MaxRequestBody = int64(n)
	}
	if v, ok := o.GetString("webserver.admin_token"); ok {
		p.AdminToken = v
	} else {
		p.AdminToken = "seed-token"
	}
	if v, ok := o.GetString("webserver.tracing"); ok {
		p.Tracing = v
	}
	if v, ok := o.GetString("webserver.tracing_url"); ok {
		p.TracingURL = v
	}
	if v, ok := o.GetString("webserver.tls.enabled"); ok {
		bb, err := strconv.ParseBool(v)
		if err != nil {
			return fmt.Errorf("configbind: webserver.tls.enabled: %w", err)
		}
		p.TLS.Enabled = bb
	} else {
		p.TLS.Enabled = false
	}
	if v, ok := o.GetString("webserver.tls.cert_path"); ok {
		p.TLS.CertPath = v
	}
	if ta1, ok := o.Get("webserver.routes"); ok {
		if !ta1.IsTables {
			return fmt.Errorf("configbind: webserver.routes: expected an array of tables ([[webserver.routes]])")
		}
		p.Routes = make([]RouteConfig, len(ta1.Tables))
		for i1 := range ta1.Tables {
			if v, ok := ta1.Tables[i1].GetString("path"); ok {
				p.Routes[i1].Path = v
			}
			if v, ok := ta1.Tables[i1].GetString("dir"); ok {
				p.Routes[i1].Dir = v
			}
			if v, ok := ta1.Tables[i1].GetString("owner"); ok {
				p.Routes[i1].Owner = v
			}
			if v, ok := ta1.Tables[i1].GetString("listing"); ok {
				bb, err := strconv.ParseBool(v)
				if err != nil {
					return fmt.Errorf("configbind: webserver.routes[%d].listing: %w", i1, err)
				}
				p.Routes[i1].Listing = bb
			} else {
				p.Routes[i1].Listing = false
			}
			if v, ok := ta1.Tables[i1].GetString("max_age"); ok {
				d, err := time.ParseDuration(v)
				if err != nil {
					return fmt.Errorf("configbind: webserver.routes[%d].max_age: %w", i1, err)
				}
				p.Routes[i1].MaxAge = d
			} else {
				p.Routes[i1].MaxAge = 3600000000000 // 1h0m0s
			}
		}
	}
	return nil
}

func registerMigrateOptionsDefinition1() {
	configbind.RegisterSubCommand[MigrateOptions](configbind.SubCommandDefinition{
		TypeName: "github.com/shibukawa/tinybind-go/internal/configbindfixture.MigrateOptions",
		Name:     "migrate",
		Help:     "run database migrations",
		Defaults: map[string]string{
			"dry_run": "false",
		},
		FlagMetas: []cliparser.FieldMeta{
			{Key: "dry_run", Env: "-", Help: "print changes without applying", Kind: cliparser.KindBool},
		},
		Positionals: []configbind.Positional{
			{ConfigKey: "path", Name: "path", Role: configbind.PositionalRequired, Help: "migration path"},
			{ConfigKey: "label", Name: "label", Role: configbind.PositionalOptional, Help: "migration label"},
			{ConfigKey: "extra", Name: "extra", Role: configbind.PositionalRest, Help: "additional migration inputs"},
		},
		Apply: applyMigrateOptionsDefinition1,
	})
}

func applyMigrateOptionsDefinition1(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*MigrateOptions)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply MigrateOptions: bad destination")
	}
	if v, ok := o.GetString("path"); ok {
		p.Path = v
	}
	if v, ok := o.GetString("label"); ok {
		p.Label = v
	}
	if v, ok := o.GetString("dry_run"); ok {
		bb, err := strconv.ParseBool(v)
		if err != nil {
			return fmt.Errorf("configbind: dry_run: %w", err)
		}
		p.DryRun = bb
	} else {
		p.DryRun = false
	}
	if v, ok := o.GetMulti("extra"); ok {
		p.Extra = v
	}
	return nil
}
