// tinybind:generated v1 inputs=sha256:110ec32d1a06fa696cbb13384222497944fb5b5adc8f7c390d52e0eb1ab77f08 self=sha256:1f22332084b7d08b7c790f877ce6873b6e64494bedfb72b440670711fcb0a5ec outputs=tinybind_gen.go,configbind_gen.go,tinybind_openapi_gen.go
//go:build !tinybind_no_openapi

// Code generated by tinybind; DO NOT EDIT.

package configbindfixture

import "github.com/shibukawa/tinybind-go"

func init() {
	httpbind.RegisterOpenAPIFragmentString("github.com/shibukawa/tinybind-go/internal/configbindfixture", openapiFragmentJSON)
}

const openapiFragmentJSON = "{\"components\":{\"schemas\":{\"ProblemDetails\":{\"properties\":{\"code\":{\"type\":\"string\"},\"detail\":{\"type\":\"string\"},\"errors\":{\"items\":{\"properties\":{\"field\":{\"type\":\"string\"},\"location\":{\"type\":\"string\"},\"message\":{\"type\":\"string\"}},\"type\":\"object\"},\"type\":\"array\"},\"status\":{\"type\":\"integer\"},\"title\":{\"type\":\"string\"},\"type\":{\"type\":\"string\"}},\"type\":\"object\"}}},\"paths\":{}}"
