// Code generated by tinybind; DO NOT EDIT.
// tinybind:generated v1 inputs=sha256:e8bed18a786edebfcdb1fa0df389c48efe4d3223d272705213fc5b8c45f39806 self=sha256:fbe290a8aab04a018f1bc3f53e46ef39e8e669684366dd8197493832fb703001 outputs=tinybind_gen.go,configbind_gen.go,tinybind_openapi_gen.go

package configbindfixture
