// Code generated by tinybind; DO NOT EDIT.
// tinybind:generated v1 inputs=sha256:ed74d7c96f94e9b4b26487cd2f077fb384b9d3dab2598624d3144eb59f4756c6 self=sha256:fbe290a8aab04a018f1bc3f53e46ef39e8e669684366dd8197493832fb703001 outputs=tinybind_gen.go,configbind_gen.go,tinybind_openapi_gen.go

package configbindfixture
