// Code generated by tinybind; DO NOT EDIT.
// tinybind:generated v1 inputs=sha256:110ec32d1a06fa696cbb13384222497944fb5b5adc8f7c390d52e0eb1ab77f08 self=sha256:fbe290a8aab04a018f1bc3f53e46ef39e8e669684366dd8197493832fb703001 outputs=tinybind_gen.go,configbind_gen.go,tinybind_openapi_gen.go

package configbindfixture
