// Code generated by tinybind; DO NOT EDIT.

package configbindfixture

import "github.com/shibukawa/tinybind-go"

func init() {
	httpbind.RegisterOpenAPIFragment("github.com/shibukawa/tinybind-go/internal/configbindfixture", []byte(openapiFragmentJSON))
}

const openapiFragmentJSON = "{\n  \"components\": {\n    \"schemas\": {\n      \"ProblemDetails\": {\n        \"properties\": {\n          \"code\": {\n            \"type\": \"string\"\n          },\n          \"detail\": {\n            \"type\": \"string\"\n          },\n          \"errors\": {\n            \"items\": {\n              \"properties\": {\n                \"field\": {\n                  \"type\": \"string\"\n                },\n                \"location\": {\n                  \"type\": \"string\"\n                },\n                \"message\": {\n                  \"type\": \"string\"\n                }\n              },\n              \"type\": \"object\"\n            },\n            \"type\": \"array\"\n          },\n          \"status\": {\n            \"type\": \"integer\"\n          },\n          \"title\": {\n            \"type\": \"string\"\n          },\n          \"type\": {\n            \"type\": \"string\"\n          }\n        },\n        \"type\": \"object\"\n      }\n    }\n  },\n  \"paths\": {}\n}"
