// Code generated by tinybind; DO NOT EDIT.
// tinybind:generated v1 inputs=sha256:07ad29e37da9b9952408f227921324029b410a0b3cc82cb06acfe9fe7d304ac8 self=sha256:df6d9d3d7dfba13ac46204e0183f5663e923ae499887d18ec94c0c103279ca64 outputs=tinybind_gen.go,configbind_gen.go,tinybind_openapi_gen.go

package configbindfixture

import "github.com/shibukawa/tinybind-go"

func init() {
	httpbind.RegisterOpenAPIFragment("github.com/shibukawa/tinybind-go/internal/configbindfixture", []byte(openapiFragmentJSON))
}

const openapiFragmentJSON = "{\n  \"components\": {\n    \"schemas\": {\n      \"ProblemDetails\": {\n        \"properties\": {\n          \"code\": {\n            \"type\": \"string\"\n          },\n          \"detail\": {\n            \"type\": \"string\"\n          },\n          \"errors\": {\n            \"items\": {\n              \"properties\": {\n                \"field\": {\n                  \"type\": \"string\"\n                },\n                \"location\": {\n                  \"type\": \"string\"\n                },\n                \"message\": {\n                  \"type\": \"string\"\n                }\n              },\n              \"type\": \"object\"\n            },\n            \"type\": \"array\"\n          },\n          \"status\": {\n            \"type\": \"integer\"\n          },\n          \"title\": {\n            \"type\": \"string\"\n          },\n          \"type\": {\n            \"type\": \"string\"\n          }\n        },\n        \"type\": \"object\"\n      }\n    }\n  },\n  \"paths\": {}\n}"
