// Code generated by tinybind HTML templates; DO NOT EDIT.

package pages

import (
	"github.com/shibukawa/tinybind-go/htmlbind"
)

type Tone string

const (
	TonePrimary   Tone = "Primary"
	ToneSecondary Tone = "Secondary"
)

type LabelParams struct {
	Value string
	Tone  Tone
}

var planLabelOps = htmlbind.Builder[LabelParams]{}

var planLabelPlan = &htmlbind.Plan[LabelParams]{
	Head: nil,
	Ops: []htmlbind.Op[LabelParams]{
		planLabelOps.Static(" <span>"),
		planLabelOps.Text(func(p LabelParams) string { return Decorate(p.Value, p.Tone) }),
		planLabelOps.Static("</span> "),
	},
}

// Label binds Label to its parameters, producing a renderable fragment.
func Label(params LabelParams) htmlbind.Fragment { return htmlbind.Bind(planLabelPlan, params) }
