// Code generated by tinybind; DO NOT EDIT.
// tinybind:generated v1 inputs=sha256:f58197758a206ea0fe6f2d22637a7f65c98226cb5563eaf116501cbed4033838 self=sha256:3acf907c851b573f7c525e3e248ed2377ec080dfa83179bc7cf990761e56505d outputs=tinybind_gen.go,firestorebind_gen.go,tinybind_openapi_gen.go

package firestorefixture

import (
	"strconv"

	"github.com/shibukawa/tinybind-go/firestorebind"
	"github.com/shibukawa/tinygodriver/nosql/datastore"
)

var _ firestorebind.EntityEncoder = Reading{}
var _ firestorebind.EntityDecoder = (*Reading)(nil)
var _ firestorebind.Keyer = Reading{}
var _ firestorebind.Versioner = Reading{}
var _ firestorebind.Kinder = Reading{}

// Kind is the Datastore kind Reading is stored under. A kind belongs to the type
// rather than to the deployment, so nothing configures it.
func (v Reading) Kind() string { return "Reading" }

// EntityVersion is the version Reading was read at. A non-zero version makes a
// later Store or Update conditional on the stored entity still being at it.
func (v Reading) EntityVersion() int64 { return int64(v.Ver) }

// EntityKey returns the key of Reading, including its ancestor path.
func (v Reading) EntityKey() datastore.Key {
	self1 := datastore.NameKey(v.Kind(), string(v.ID))
	if len(v.Parent.Path) == 0 {
		return self1
	}
	return v.Parent.Child(self1.Path[len(self1.Path)-1])
}

// EncodeEntity converts Reading into a Datastore entity.
//
// The key travels beside the properties rather than among them, so the
// identity fields are absent from the property map and cannot drift from it.
func (v Reading) EncodeEntity() datastore.Entity {
	properties := make(map[string]datastore.Value, 15)
	properties["note"] = datastore.String(string(v.Note))
	properties["at"] = datastore.Time(v.At)
	properties["scale"] = datastore.Float(float64(v.Scale))
	properties["small"] = datastore.Float(float64(v.Small))
	properties["count"] = datastore.Int(v.Count)
	properties["tiny"] = datastore.Int(v.Tiny)
	properties["active"] = datastore.Bool(bool(v.Active))
	properties["blob"] = datastore.Blob([]byte(v.Blob))
	properties["ref"] = datastore.KeyValue(v.Ref)
	properties["where"] = datastore.GeoPoint(v.Where.Latitude, v.Where.Longitude)
	if len(v.Tags) != 0 {
		array2 := make([]datastore.Value, 0, len(v.Tags))
		for _, member := range v.Tags {
			element3 := datastore.String(string(member))
			array2 = append(array2, element3)
		}
		properties["tags"] = datastore.Array(array2...)
	}
	properties["site"] = datastore.Nested(v.Nested.EncodeEntity())
	if v.Extra == nil {
		properties["extra"] = datastore.Null()
	} else {
		properties["extra"] = datastore.String(string((*v.Extra)))
	}
	properties["body"] = datastore.Unindexed(datastore.String(string(v.Body)))
	if v.Raw.Kind() != datastore.KindInvalid {
		properties["raw"] = v.Raw
	}
	key := v.EntityKey()
	return datastore.Entity{Key: &key, Properties: properties}
}

// DecodeEntity fills Reading from a Datastore entity. A property the entity does
// not carry leaves its field untouched, since Datastore is schemaless and an
// older writer is normal rather than exceptional.
func (v *Reading) DecodeEntity(e datastore.Entity) error {
	if value4, ok := e.Properties["note"]; ok {
		text5, ok := value4.AsString()
		if !ok {
			return firestorebind.TypeError("note", "string", value4)
		}
		v.Note = string(text5)
	}
	if value6, ok := e.Properties["at"]; ok {
		when7, ok := value6.AsTime()
		if !ok {
			return firestorebind.TypeError("at", "timestamp", value6)
		}
		v.At = when7
	}
	if value8, ok := e.Properties["scale"]; ok {
		number9, ok := value8.AsFloat()
		if !ok {
			return firestorebind.TypeError("scale", "double", value8)
		}
		v.Scale = float64(number9)
	}
	if value10, ok := e.Properties["small"]; ok {
		number11, ok := value10.AsFloat()
		if !ok {
			return firestorebind.TypeError("small", "double", value10)
		}
		v.Small = float32(number11)
	}
	if value12, ok := e.Properties["count"]; ok {
		text13, ok := value12.AsNumber()
		if !ok {
			return firestorebind.TypeError("count", "integer", value12)
		}
		number14, err := strconv.ParseInt(text13, 10, 64)
		if err != nil {
			return firestorebind.ValueError("count", "integer is not a signed integer", err)
		}
		v.Count = int64(number14)
	}
	if value15, ok := e.Properties["tiny"]; ok {
		text16, ok := value15.AsNumber()
		if !ok {
			return firestorebind.TypeError("tiny", "integer", value15)
		}
		number17, err := strconv.ParseUint(text16, 10, 16)
		if err != nil {
			return firestorebind.ValueError("tiny", "integer is not a unsigned integer", err)
		}
		v.Tiny = uint16(number17)
	}
	if value18, ok := e.Properties["active"]; ok {
		flag19, ok := value18.AsBool()
		if !ok {
			return firestorebind.TypeError("active", "boolean", value18)
		}
		v.Active = bool(flag19)
	}
	if value20, ok := e.Properties["blob"]; ok {
		blob21, ok := value20.AsBytes()
		if !ok {
			return firestorebind.TypeError("blob", "blob", value20)
		}
		v.Blob = []byte(blob21)
	}
	if value22, ok := e.Properties["ref"]; ok {
		key23, ok := value22.AsKey()
		if !ok {
			return firestorebind.TypeError("ref", "key", value22)
		}
		v.Ref = key23
	}
	if value24, ok := e.Properties["where"]; ok {
		point25, ok := value24.AsGeoPoint()
		if !ok {
			return firestorebind.TypeError("where", "geoPoint", value24)
		}
		v.Where = point25
	}
	if value26, ok := e.Properties["tags"]; ok {
		members27, ok := value26.AsArray()
		if !ok {
			return firestorebind.TypeError("tags", "array", value26)
		}
		decoded28 := make([]string, 0, len(members27))
		for _, member := range members27 {
			var value29 string
			text30, ok := member.AsString()
			if !ok {
				return firestorebind.TypeError("tags", "string", member)
			}
			value29 = string(text30)
			decoded28 = append(decoded28, value29)
		}
		v.Tags = decoded28
	}
	if value31, ok := e.Properties["site"]; ok {
		nested32, ok := value31.AsEntity()
		if !ok {
			return firestorebind.TypeError("site", "entity", value31)
		}
		if err := v.Nested.DecodeEntity(nested32); err != nil {
			return err
		}
	}
	if value33, ok := e.Properties["extra"]; ok {
		if value33.IsNull() {
			v.Extra = nil
		} else {
			var value34 string
			text35, ok := value33.AsString()
			if !ok {
				return firestorebind.TypeError("extra", "string", value33)
			}
			value34 = string(text35)
			v.Extra = &value34
		}
	}
	if value36, ok := e.Properties["body"]; ok {
		text37, ok := value36.AsString()
		if !ok {
			return firestorebind.TypeError("body", "string", value36)
		}
		v.Body = string(text37)
	}
	if value38, ok := e.Properties["raw"]; ok {
		v.Raw = value38
	}
	if e.Key != nil && len(e.Key.Path) > 0 {
		leaf := e.Key.Path[len(e.Key.Path)-1]
		v.ID = SensorID(leaf.Name)
		if len(e.Key.Path) > 1 {
			v.Parent = datastore.Key{Namespace: e.Key.Namespace, Path: e.Key.Path[:len(e.Key.Path)-1]}
		}
	}
	v.Ver = int64(e.Version)
	return nil
}

var _ firestorebind.EntityEncoder = Site{}
var _ firestorebind.EntityDecoder = (*Site)(nil)
var _ firestorebind.Kinder = Site{}

// Kind is the Datastore kind Site is stored under. A kind belongs to the type
// rather than to the deployment, so nothing configures it.
func (v Site) Kind() string { return "Site" }

// EncodeEntity converts Site into a Datastore entity.
//
// The key travels beside the properties rather than among them, so the
// identity fields are absent from the property map and cannot drift from it.
func (v Site) EncodeEntity() datastore.Entity {
	properties := make(map[string]datastore.Value, 2)
	properties["city"] = datastore.String(string(v.City))
	if v.Zip != "" {
		properties["zip"] = datastore.String(string(v.Zip))
	}
	return datastore.Entity{Properties: properties}
}

// DecodeEntity fills Site from a Datastore entity. A property the entity does
// not carry leaves its field untouched, since Datastore is schemaless and an
// older writer is normal rather than exceptional.
func (v *Site) DecodeEntity(e datastore.Entity) error {
	if value1, ok := e.Properties["city"]; ok {
		text2, ok := value1.AsString()
		if !ok {
			return firestorebind.TypeError("city", "string", value1)
		}
		v.City = string(text2)
	}
	if value3, ok := e.Properties["zip"]; ok {
		text4, ok := value3.AsString()
		if !ok {
			return firestorebind.TypeError("zip", "string", value3)
		}
		v.Zip = string(text4)
	}
	return nil
}

var _ firestorebind.EntityEncoder = Task{}
var _ firestorebind.EntityDecoder = (*Task)(nil)
var _ firestorebind.Keyer = Task{}
var _ firestorebind.Kinder = Task{}

// Kind is the Datastore kind Task is stored under. A kind belongs to the type
// rather than to the deployment, so nothing configures it.
func (v Task) Kind() string { return "Task" }

// EntityKey returns the key of Task, including its ancestor path.
func (v Task) EntityKey() datastore.Key {
	return datastore.IDKey(v.Kind(), int64(v.Number))
}

// EncodeEntity converts Task into a Datastore entity.
//
// The key travels beside the properties rather than among them, so the
// identity fields are absent from the property map and cannot drift from it.
func (v Task) EncodeEntity() datastore.Entity {
	properties := make(map[string]datastore.Value, 1)
	properties["title"] = datastore.String(string(v.Title))
	key := v.EntityKey()
	return datastore.Entity{Key: &key, Properties: properties}
}

// DecodeEntity fills Task from a Datastore entity. A property the entity does
// not carry leaves its field untouched, since Datastore is schemaless and an
// older writer is normal rather than exceptional.
func (v *Task) DecodeEntity(e datastore.Entity) error {
	if value1, ok := e.Properties["title"]; ok {
		text2, ok := value1.AsString()
		if !ok {
			return firestorebind.TypeError("title", "string", value1)
		}
		v.Title = string(text2)
	}
	if e.Key != nil && len(e.Key.Path) > 0 {
		leaf := e.Key.Path[len(e.Key.Path)-1]
		v.Number = int64(leaf.ID)
	}
	return nil
}
