// Code generated by tinybind; DO NOT EDIT.
// tinybind:generated v1 inputs=sha256:aa98a36e512122fae05f74ed1ae9604f058257d8c05bc4c16088f3f478efb309 self=sha256:fe7ca2cdf0814494fce845f074a2305afb4de5ae98e4121efe902e83110956bb outputs=tinybind_gen.go,firestorebind_gen.go,firestorequery_gen.go,tinybind_openapi_gen.go

package firestorefixture

import "github.com/shibukawa/tinybind-go"

func init() {
	httpbind.RegisterOpenAPIFragment("github.com/shibukawa/tinybind-go/internal/firestorefixture", []byte(openapiFragmentJSON))
}

const openapiFragmentJSON = "{\n  \"components\": {\n    \"schemas\": {\n      \"ProblemDetails\": {\n        \"properties\": {\n          \"code\": {\n            \"type\": \"string\"\n          },\n          \"detail\": {\n            \"type\": \"string\"\n          },\n          \"errors\": {\n            \"items\": {\n              \"properties\": {\n                \"field\": {\n                  \"type\": \"string\"\n                },\n                \"location\": {\n                  \"type\": \"string\"\n                },\n                \"message\": {\n                  \"type\": \"string\"\n                }\n              },\n              \"type\": \"object\"\n            },\n            \"type\": \"array\"\n          },\n          \"status\": {\n            \"type\": \"integer\"\n          },\n          \"title\": {\n            \"type\": \"string\"\n          },\n          \"type\": {\n            \"type\": \"string\"\n          }\n        },\n        \"type\": \"object\"\n      }\n    }\n  },\n  \"paths\": {}\n}"
