// Code generated by tinybind; DO NOT EDIT.
// tinybind:generated v1 inputs=sha256:6db4cf33383d572f1633a23ab9d816a8f38eadbddd8d077106405eff14cf8f16 self=sha256:05dc26f28f05e30d7c7ab58825e6dc43d4fca2410d8fe1c31bf85b92f1a731a1 outputs=tinybind_gen.go,firestorebind_gen.go,firestorequery_gen.go,tinybind_openapi_gen.go

package firestorefixture
