package htmlbind

import (
	"bytes"
	"fmt"
	"go/format"
	"path"
	"sort"
	"strconv"
	"strings"
	"unicode"

	"github.com/shibukawa/tinybind-go/templates/internal/syntax"
)

// GenerateOptions controls the generated Go file.
type GenerateOptions struct {
	// Package overrides the template package/module declaration.
	Package string
}

// Generate parses, validates, and compiles an HTML template module to Go.
func Generate(filename string, source []byte, options GenerateOptions) ([]byte, error) {
	module, err := Parse(filename, source)
	if err != nil {
		return nil, err
	}
	compiler := newCompiler(filename, string(source), module)
	if err := compiler.analyze(); err != nil {
		return nil, err
	}
	generated, err := compiler.emit(options)
	if err != nil {
		return nil, err
	}
	formatted, err := format.Source(generated)
	if err != nil {
		return generated, fmt.Errorf("format generated HTML code: %w\n%s", err, generated)
	}
	return formatted, nil
}

type goEmitter struct {
	c       *compiler
	b       bytes.Buffer
	indent  int
	pending strings.Builder
	temp    int
}

func (c *compiler) emit(options GenerateOptions) ([]byte, error) {
	e := &goEmitter{c: c}
	pkg := options.Package
	if pkg == "" && c.module.Package != nil {
		pkg = c.module.Package.Name
		if index := strings.LastIndex(pkg, "."); index >= 0 {
			pkg = pkg[index+1:]
		}
	}
	if pkg == "" {
		pkg = "templates"
	}
	pkg = goIdentifier(pkg)
	e.b.WriteString("// Code generated by tinybind HTML templates; DO NOT EDIT.\n\n")
	fmt.Fprintf(&e.b, "package %s\n\n", pkg)
	e.emitImports()
	e.emitRuntimeHelpers()
	e.emitDeclaredTypes()
	if err := e.emitComponentParams(); err != nil {
		return nil, err
	}
	e.emitJSONHelpers()
	for _, declaration := range c.module.Declarations {
		component, ok := declaration.(*TemplateDecl)
		if !ok {
			continue
		}
		if err := e.emitComponent(component); err != nil {
			return nil, err
		}
	}
	return e.b.Bytes(), nil
}

func (e *goEmitter) emitImports() {
	e.b.WriteString("import (\n\t\"html\"\n\t\"io\"\n\t\"strconv\"\n\t\"strings\"\n")
	if e.c.usesKind(kindDateTime) || e.c.usesKind(kindDate) || e.c.usesKind(kindTime) {
		e.b.WriteString("\t\"time\"\n")
	}
	if e.c.usesKind(kindURL) {
		e.b.WriteString("\t\"net/url\"\n")
	}
	for _, imported := range e.c.module.Imports {
		alias := imported.Alias
		if alias == "" {
			alias = path.Base(imported.Path)
		}
		if e.c.usesQualified(alias) {
			fmt.Fprintf(&e.b, "\t%s %s\n", alias, strconv.Quote(imported.Path))
		}
	}
	e.b.WriteString(")\n\n")
}

func (e *goEmitter) emitRuntimeHelpers() {
	e.b.WriteString("type HTML func(io.Writer) error\n")
	e.b.WriteString("type TrustedHTML string\ntype TrustedCSS string\ntype TrustedJavaScript string\ntype ScriptJSON string\n\n")
	e.b.WriteString("func _tinybindWrite(w io.Writer, value string) error { _, err := io.WriteString(w, value); return err }\n")
	e.b.WriteString("func _tinybindEscape(value string) string { return html.EscapeString(value) }\n")
	e.b.WriteString("func _tinybindBool(value bool) string { return strconv.FormatBool(value) }\n")
	e.b.WriteString("func _tinybindInt(value int) string { return strconv.Itoa(value) }\n")
	e.b.WriteString("func _tinybindFloat(value float64) string { return strconv.FormatFloat(value, 'g', -1, 64) }\n\n")
	e.b.WriteString(`func _tinybindJSONQuote(value string) string {
	const hex = "0123456789abcdef"
	var out strings.Builder
	out.WriteByte('"')
	for _, r := range value {
		switch r {
		case '"': out.WriteString("\\\"")
		case '\\': out.WriteString("\\\\")
		case '\b': out.WriteString("\\b")
		case '\f': out.WriteString("\\f")
		case '\n': out.WriteString("\\n")
		case '\r': out.WriteString("\\r")
		case '\t': out.WriteString("\\t")
		case '<': out.WriteString("\\u003c")
		case '>': out.WriteString("\\u003e")
		case '&': out.WriteString("\\u0026")
		case '\u2028': out.WriteString("\\u2028")
		case '\u2029': out.WriteString("\\u2029")
		default:
			if r < 0x20 { out.WriteString("\\u00"); out.WriteByte(hex[byte(r)>>4]); out.WriteByte(hex[byte(r)&15]) } else { out.WriteRune(r) }
		}
	}
	out.WriteByte('"')
	return out.String()
}

`)
}

func (e *goEmitter) emitDeclaredTypes() {
	for _, declaration := range e.c.module.Declarations {
		switch declaration := declaration.(type) {
		case *TypeDecl:
			fmt.Fprintf(&e.b, "type %s struct {\n", declaration.Name)
			for _, field := range declaration.Fields {
				t, _ := e.c.resolveType(field.Type)
				fmt.Fprintf(&e.b, "\t%s %s\n", goPublicName(field.Name), goType(t))
			}
			e.b.WriteString("}\n\n")
		case *EnumDecl:
			fmt.Fprintf(&e.b, "type %s string\n\nconst (\n", declaration.Name)
			for _, member := range declaration.Members {
				fmt.Fprintf(&e.b, "\t%s%s %s = %q\n", declaration.Name, member.Name, declaration.Name, member.Name)
			}
			e.b.WriteString(")\n\n")
		}
	}
}

// emitComponentParams declares one {Component}Params struct per component so
// every component keeps the same two-argument shape for zero, one, and many
// parameters.
func (e *goEmitter) emitComponentParams() error {
	for _, declaration := range e.c.module.Declarations {
		component, ok := declaration.(*TemplateDecl)
		if !ok {
			continue
		}
		name := e.c.paramsGoName(component.Name)
		if e.c.nameExists(name) {
			return e.c.error(component.Pos, "generated parameter type conflicts with declaration "+name)
		}
		if len(component.Parameters) == 0 {
			fmt.Fprintf(&e.b, "type %s struct{}\n\n", name)
			continue
		}
		fmt.Fprintf(&e.b, "type %s struct {\n", name)
		for _, parameter := range component.Parameters {
			t, _ := e.c.resolveType(parameter.Type)
			fmt.Fprintf(&e.b, "\t%s %s\n", goPublicName(parameter.Name), goType(t))
		}
		e.b.WriteString("}\n\n")
	}
	return nil
}

// emitComponent emits the HTTP-independent component form. The generated
// function owns escaping and writing only; content negotiation, compression,
// response commit, and error responses belong to the caller.
func (e *goEmitter) emitComponent(component *TemplateDecl) error {
	name := e.c.componentGoName(component.Name)
	fmt.Fprintf(&e.b, "func %s(w io.Writer, %s %s) error {\n", name, paramsIdent, e.c.paramsGoName(component.Name))
	e.indent = 1
	for _, parameter := range component.Parameters {
		local := goLocalName(parameter.Name)
		e.line(local + " := " + paramsIdent + "." + goPublicName(parameter.Name))
		e.line("_ = " + local)
	}
	body := component.Body.([]Node)
	if err := e.emitNodes(body, e.c.components[component.Name].params); err != nil {
		return err
	}
	e.flushStatic()
	e.line("return nil")
	e.b.WriteString("}\n\n")
	return nil
}

// paramsIdent names the generated parameter struct argument. It is reserved so
// a template parameter cannot shadow it.
const paramsIdent = "_tinybindParams"

func (e *goEmitter) emitNodes(nodes []Node, scope map[string]valueType) error {
	for _, node := range nodes {
		switch node := node.(type) {
		case *TextNode:
			e.static(node.Text)
		case *CommentNode:
			e.static("<!--" + node.Text + "-->")
		case *DoctypeNode:
			e.static("<!" + node.Text + ">")
		case *syntax.ExpressionNode:
			e.flushStatic()
			if err := e.emitExpressionWrite(node.Expression, node.Context, scope); err != nil {
				return err
			}
		case *syntax.IfNode:
			e.flushStatic()
			condition, err := e.expr(node.Condition, scope)
			if err != nil {
				return err
			}
			e.line("if " + condition + " {")
			e.indent++
			if err := e.emitNodes(node.Then, copyScope(scope)); err != nil {
				return err
			}
			e.flushStatic()
			e.indent--
			if len(node.Else) > 0 {
				e.line("} else {")
				e.indent++
				if err := e.emitNodes(node.Else, copyScope(scope)); err != nil {
					return err
				}
				e.flushStatic()
				e.indent--
				e.line("}")
			} else {
				e.line("}")
			}
		case *syntax.ForNode:
			e.flushStatic()
			iterable, err := e.expr(node.Iterable, scope)
			if err != nil {
				return err
			}
			index := "_"
			if node.Index != "" {
				index = node.Index
			}
			e.line(fmt.Sprintf("for %s, %s := range %s {", goLocalName(index), goLocalName(node.Variable), iterable))
			e.indent++
			inner := copyScope(scope)
			t := e.c.exprTypes[node.Iterable]
			inner[node.Variable] = *t.elem
			if node.Index != "" {
				inner[node.Index] = valueType{kind: kindInt}
			}
			if err := e.emitNodes(node.Body, inner); err != nil {
				return err
			}
			e.flushStatic()
			e.indent--
			e.line("}")
		case *ElementNode:
			if err := e.emitElement(node, scope); err != nil {
				return err
			}
		case *ComponentNode:
			if err := e.emitComponentCall(node, scope); err != nil {
				return err
			}
		default:
			return fmt.Errorf("unsupported HTML node %T", node)
		}
	}
	return nil
}

func (e *goEmitter) emitElement(node *ElementNode, scope map[string]valueType) error {
	e.static("<" + node.Name)
	for _, attribute := range node.Attributes {
		if attribute.Boolean {
			e.static(" " + attribute.Name)
			continue
		}
		if len(attribute.Value) == 1 && attribute.Value[0].Expression != nil {
			part := attribute.Value[0]
			t := e.c.exprTypes[part.Expression]
			code, err := e.expr(part.Expression, scope)
			if err != nil {
				return err
			}
			if t.optional {
				e.flushStatic()
				e.line("if " + code + " != nil {")
				e.indent++
				if t.required().kind == kindBool {
					e.line("if *(" + code + ") { if err := _tinybindWrite(w, " + strconv.Quote(" "+attribute.Name) + "); err != nil { return err } }")
				} else {
					e.writeStaticNow(" " + attribute.Name + "=\"")
					e.writeValue("*("+code+")", t.required(), true)
					e.writeStaticNow("\"")
				}
				e.indent--
				e.line("}")
				continue
			}
			if t.kind == kindBool {
				e.flushStatic()
				e.line("if " + code + " { if err := _tinybindWrite(w, " + strconv.Quote(" "+attribute.Name) + "); err != nil { return err } }")
				continue
			}
		}
		e.static(" " + attribute.Name + "=\"")
		for _, part := range attribute.Value {
			if part.Expression == nil {
				e.static(part.Text)
				continue
			}
			e.flushStatic()
			code, err := e.expr(part.Expression, scope)
			if err != nil {
				return err
			}
			e.writeValue(code, e.c.exprTypes[part.Expression], true)
		}
		e.static("\"")
	}
	if node.SelfClosing {
		e.static(" />")
		return nil
	}
	e.static(">")
	if err := e.emitNodes(node.Children, scope); err != nil {
		return err
	}
	if !voidElements[node.Name] {
		e.static("</" + node.Name + ">")
	}
	return nil
}

func (e *goEmitter) emitComponentCall(node *ComponentNode, scope map[string]valueType) error {
	e.flushStatic()
	component := e.c.components[node.Name]
	values := map[string]string{}
	for _, argument := range node.Arguments {
		code, err := e.attributeCode(argument, scope)
		if err != nil {
			return err
		}
		values[argument.Name] = code
	}
	name := e.c.componentGoName(node.Name)
	params := e.c.paramsGoName(node.Name)
	if len(node.Children) == 0 {
		fields := make([]string, 0, len(component.order))
		for _, parameter := range component.order {
			fields = append(fields, goPublicName(parameter.Name)+": "+values[parameter.Name])
		}
		e.line("if err := " + name + "(w, " + params + "{" + strings.Join(fields, ", ") + "}); err != nil { return err }")
		return nil
	}
	e.line("if err := " + name + "(w, " + params + "{")
	e.indent++
	for _, parameter := range component.order {
		if parameter.Name != "children" {
			e.line(goPublicName(parameter.Name) + ": " + values[parameter.Name] + ",")
			continue
		}
		e.line(goPublicName(parameter.Name) + ": func(w io.Writer) error {")
		e.indent++
		if err := e.emitNodes(node.Children, scope); err != nil {
			return err
		}
		e.flushStatic()
		e.line("return nil")
		e.indent--
		e.line("},")
	}
	e.indent--
	e.line("}); err != nil { return err }")
	return nil
}

func (e *goEmitter) attributeCode(attribute Attribute, scope map[string]valueType) (string, error) {
	if attribute.Boolean {
		return "true", nil
	}
	if len(attribute.Value) == 1 && attribute.Value[0].Expression != nil {
		return e.expr(attribute.Value[0].Expression, scope)
	}
	var parts []string
	for _, part := range attribute.Value {
		if part.Expression == nil {
			parts = append(parts, strconv.Quote(part.Text))
		} else {
			code, err := e.expr(part.Expression, scope)
			if err != nil {
				return "", err
			}
			parts = append(parts, code)
		}
	}
	if len(parts) == 0 {
		return `""`, nil
	}
	return strings.Join(parts, " + "), nil
}

func (e *goEmitter) emitExpressionWrite(expr Expr, context string, scope map[string]valueType) error {
	t := e.c.exprTypes[expr]
	code, err := e.expr(expr, scope)
	if err != nil {
		return err
	}
	if t.optional {
		e.line("if " + code + " != nil {")
		e.indent++
		e.writeValue("*("+code+")", t.required(), context == "html:child" || context == "html:attribute")
		e.indent--
		e.line("}")
		return nil
	}
	if t.kind == kindHTML {
		e.line("if err := " + code + "(w); err != nil { return err }")
		return nil
	}
	if context == "html:script" && t.kind == kindScriptJSON {
		call := expr.(*CallExpr)
		argument := call.Arguments[0]
		argCode, err := e.expr(argument, scope)
		if err != nil {
			return err
		}
		e.writeCall("_tinybindJSON" + jsonTypeKey(e.c.exprTypes[argument]) + "(" + argCode + ")")
		return nil
	}
	raw := t.kind == kindTrustedHTML || t.kind == kindTrustedCSS || t.kind == kindTrustedJS
	e.writeValue(code, t, !raw)
	return nil
}

func (e *goEmitter) writeValue(code string, t valueType, escaped bool) {
	stringCode := valueString(code, t)
	if escaped {
		stringCode = "_tinybindEscape(" + stringCode + ")"
	}
	e.writeCall(stringCode)
}

func (e *goEmitter) writeCall(value string) {
	e.line("if err := _tinybindWrite(w, " + value + "); err != nil { return err }")
}
func (e *goEmitter) writeStaticNow(value string) { e.writeCall(strconv.Quote(value)) }
func (e *goEmitter) static(value string)         { e.pending.WriteString(value) }
func (e *goEmitter) flushStatic() {
	if e.pending.Len() == 0 {
		return
	}
	value := e.pending.String()
	e.pending.Reset()
	e.writeStaticNow(value)
}
func (e *goEmitter) line(value string) {
	e.b.WriteString(strings.Repeat("\t", e.indent))
	e.b.WriteString(value)
	e.b.WriteByte('\n')
}

func (e *goEmitter) expr(expr Expr, scope map[string]valueType) (string, error) {
	switch expr := expr.(type) {
	case *IdentifierExpr:
		if t, ok := e.c.enumMembers[expr.Name]; ok {
			return t.name + expr.Name, nil
		}
		return goLocalName(expr.Name), nil
	case *LiteralExpr:
		switch expr.ValueKind {
		case "string":
			return strconv.Quote(expr.Value.(string)), nil
		case "bool":
			return strconv.FormatBool(expr.Value.(bool)), nil
		case "number":
			return expr.Value.(string), nil
		case "null":
			return "nil", nil
		}
	case *MemberExpr:
		object, err := e.expr(expr.Object, scope)
		if err != nil {
			return "", err
		}
		return object + "." + goPublicName(expr.Member), nil
	case *IndexExpr:
		object, err := e.expr(expr.Object, scope)
		if err != nil {
			return "", err
		}
		index, err := e.expr(expr.Index, scope)
		if err != nil {
			return "", err
		}
		return object + "[" + index + "]", nil
	case *CallExpr:
		callee := expr.Callee.(*IdentifierExpr)
		var args []string
		for _, argument := range expr.Arguments {
			code, err := e.expr(argument, scope)
			if err != nil {
				return "", err
			}
			args = append(args, code)
		}
		if _, intrinsic := intrinsicResult(callee.Name); intrinsic {
			return args[0], nil
		}
		return callee.Name + "(" + strings.Join(args, ", ") + ")", nil
	case *UnaryExpr:
		operand, err := e.expr(expr.Operand, scope)
		if err != nil {
			return "", err
		}
		operator := expr.Operator
		if operator == "not" {
			operator = "!"
		}
		return operator + "(" + operand + ")", nil
	case *BinaryExpr:
		left, err := e.expr(expr.Left, scope)
		if err != nil {
			return "", err
		}
		right, err := e.expr(expr.Right, scope)
		if err != nil {
			return "", err
		}
		operator := expr.Operator
		if operator == "and" {
			operator = "&&"
		} else if operator == "or" {
			operator = "||"
		}
		return "(" + left + " " + operator + " " + right + ")", nil
	case *ConditionalExpr:
		condition, err := e.expr(expr.Condition, scope)
		if err != nil {
			return "", err
		}
		thenCode, err := e.expr(expr.Then, scope)
		if err != nil {
			return "", err
		}
		elseCode, err := e.expr(expr.Else, scope)
		if err != nil {
			return "", err
		}
		t := e.c.exprTypes[expr]
		return "(func() " + goType(t) + " { if " + condition + " { return " + thenCode + " }; return " + elseCode + " })()", nil
	}
	return "", fmt.Errorf("unsupported expression %T", expr)
}

func valueString(code string, t valueType) string {
	switch t.kind {
	case kindString, kindDecimal, kindTrustedHTML, kindTrustedCSS, kindTrustedJS, kindScriptJSON:
		return code
	case kindEnum:
		return "string(" + code + ")"
	case kindBool:
		return "_tinybindBool(" + code + ")"
	case kindInt:
		return "_tinybindInt(" + code + ")"
	case kindFloat:
		return "_tinybindFloat(" + code + ")"
	case kindBytes:
		return "string(" + code + ")"
	case kindURL:
		return code + ".String()"
	case kindDateTime, kindDate, kindTime:
		return code + ".Format(time.RFC3339)"
	}
	return code
}

func goType(t valueType) string {
	var base string
	switch t.kind {
	case kindString, kindDecimal:
		base = "string"
	case kindBool:
		base = "bool"
	case kindInt:
		base = "int"
	case kindFloat:
		base = "float64"
	case kindBytes:
		base = "[]byte"
	case kindDateTime, kindDate, kindTime:
		base = "time.Time"
	case kindURL:
		base = "url.URL"
	case kindRecord, kindEnum:
		base = t.name
	case kindHTML:
		base = "HTML"
	case kindTrustedHTML:
		base = "TrustedHTML"
	case kindTrustedCSS:
		base = "TrustedCSS"
	case kindTrustedJS:
		base = "TrustedJavaScript"
	case kindScriptJSON:
		base = "ScriptJSON"
	case kindArray:
		if t.elem != nil {
			base = "[]" + goType(*t.elem)
		}
	}
	if t.optional {
		return "*" + base
	}
	return base
}

func (c *compiler) componentGoName(name string) string {
	if c.components[name].decl.Exported {
		return name
	}
	return "render" + name
}

// paramsGoName is the generated parameter struct name for a component. It
// follows the component's own exportedness so unexported components keep an
// unexported parameter type.
func (c *compiler) paramsGoName(name string) string { return c.componentGoName(name) + "Params" }
func goIdentifier(value string) string {
	var out strings.Builder
	for i, r := range value {
		if unicode.IsLetter(r) || r == '_' || (i > 0 && unicode.IsDigit(r)) {
			out.WriteRune(r)
		} else {
			out.WriteRune('_')
		}
	}
	if out.Len() == 0 {
		return "templates"
	}
	return goLocalName(out.String())
}

func goLocalName(name string) string {
	if goKeywords[name] {
		return "_" + name
	}
	return name
}

var goKeywords = map[string]bool{
	"break": true, "default": true, "func": true, "interface": true, "select": true,
	"case": true, "defer": true, "go": true, "map": true, "struct": true,
	"chan": true, "else": true, "goto": true, "package": true, "switch": true,
	"const": true, "fallthrough": true, "if": true, "range": true, "type": true,
	"continue": true, "for": true, "import": true, "return": true, "var": true,
}

func (c *compiler) usesKind(kind valueKind) bool {
	for _, declaration := range c.module.Declarations {
		switch declaration := declaration.(type) {
		case *TypeDecl:
			for _, f := range declaration.Fields {
				t, _ := c.resolveType(f.Type)
				if containsKind(t, kind) {
					return true
				}
			}
		case *ExternalDecl:
			for _, p := range declaration.Parameters {
				t, _ := c.resolveType(p.Type)
				if containsKind(t, kind) {
					return true
				}
			}
			t, _ := c.resolveType(declaration.Result)
			if containsKind(t, kind) {
				return true
			}
		case *TemplateDecl:
			for _, p := range declaration.Parameters {
				t, _ := c.resolveType(p.Type)
				if containsKind(t, kind) {
					return true
				}
			}
		}
	}
	return false
}
func containsKind(t valueType, kind valueKind) bool {
	if t.kind == kind {
		return true
	}
	return t.elem != nil && containsKind(*t.elem, kind)
}
func (c *compiler) usesQualified(alias string) bool {
	prefix := alias + "."
	for _, d := range c.module.Declarations {
		switch d := d.(type) {
		case *TypeDecl:
			for _, f := range d.Fields {
				if strings.HasPrefix(f.Type.Name, prefix) {
					return true
				}
			}
		case *ExternalDecl:
			for _, p := range d.Parameters {
				if strings.HasPrefix(p.Type.Name, prefix) {
					return true
				}
			}
			if strings.HasPrefix(d.Result.Name, prefix) {
				return true
			}
		case *TemplateDecl:
			for _, p := range d.Parameters {
				if strings.HasPrefix(p.Type.Name, prefix) {
					return true
				}
			}
		}
	}
	return false
}

func (e *goEmitter) emitJSONHelpers() {
	types := map[string]valueType{}
	for expr, t := range e.c.exprTypes {
		call, ok := expr.(*CallExpr)
		if !ok {
			continue
		}
		id, ok := call.Callee.(*IdentifierExpr)
		if !ok || id.Name != "JsonForScript" {
			continue
		}
		arg := e.c.exprTypes[call.Arguments[0]]
		collectJSONTypes(types, arg, e.c)
		_ = t
	}
	keys := make([]string, 0, len(types))
	for key := range types {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		e.emitJSONHelper(types[key])
	}
}

func collectJSONTypes(out map[string]valueType, t valueType, c *compiler) {
	key := jsonTypeKey(t)
	if _, ok := out[key]; ok {
		return
	}
	out[key] = t
	base := t.required()
	if base.kind == kindArray && base.elem != nil {
		collectJSONTypes(out, *base.elem, c)
	}
	if base.kind == kindRecord {
		for _, f := range c.records[base.name].Fields {
			ft, _ := c.resolveType(f.Type)
			collectJSONTypes(out, ft, c)
		}
	}
}
func jsonTypeKey(t valueType) string {
	prefix := ""
	if t.optional {
		prefix = "Optional"
		t.optional = false
	}
	switch t.kind {
	case kindArray:
		return prefix + "Array" + jsonTypeKey(*t.elem)
	case kindRecord, kindEnum:
		return prefix + t.name
	default:
		return prefix + goPublicName(string(t.kind))
	}
}

func (e *goEmitter) emitJSONHelper(t valueType) {
	name := "_tinybindJSON" + jsonTypeKey(t)
	fmt.Fprintf(&e.b, "func %s(value %s) string {\n", name, goType(t))
	if t.optional {
		e.b.WriteString("\tif value == nil { return \"null\" }\n\treturn _tinybindJSON" + jsonTypeKey(t.required()) + "(*value)\n}\n\n")
		return
	}
	switch t.kind {
	case kindString, kindDecimal:
		e.b.WriteString("\treturn _tinybindJSONQuote(value)\n")
	case kindEnum:
		e.b.WriteString("\treturn _tinybindJSONQuote(string(value))\n")
	case kindBool:
		e.b.WriteString("\treturn strconv.FormatBool(value)\n")
	case kindInt:
		e.b.WriteString("\treturn strconv.Itoa(value)\n")
	case kindFloat:
		e.b.WriteString("\treturn strconv.FormatFloat(value, 'g', -1, 64)\n")
	case kindArray:
		e.b.WriteString("\tvar out strings.Builder\n\tout.WriteByte('[')\n\tfor index, item := range value {\n\t\tif index > 0 { out.WriteByte(',') }\n\t\tout.WriteString(_tinybindJSON" + jsonTypeKey(*t.elem) + "(item))\n\t}\n\tout.WriteByte(']')\n\treturn out.String()\n")
	case kindRecord:
		e.b.WriteString("\tvar out strings.Builder\n\tout.WriteByte('{')\n")
		for i, f := range e.c.records[t.name].Fields {
			ft, _ := e.c.resolveType(f.Type)
			if i > 0 {
				e.b.WriteString("\tout.WriteByte(',')\n")
			}
			fmt.Fprintf(&e.b, "\tout.WriteString(%q)\n\tout.WriteString(_tinybindJSON%s(value.%s))\n", strconv.Quote(f.Name)+":", jsonTypeKey(ft), goPublicName(f.Name))
		}
		e.b.WriteString("\tout.WriteByte('}')\n\treturn out.String()\n")
	}
	e.b.WriteString("}\n\n")
}
