// Code generated by tinybind; DO NOT EDIT.

package rest__

import (
	"github.com/shibukawa/tinygodriver/fasthttp"

	httpbind "github.com/shibukawa/tinybind-go/fasthttpbind"
)

// RouteParams holds the URL inputs of GET /files/{rest...}.
type RouteParams struct {
	Rest string
}

// DecodeRoute reads the path and query values of GET /files/{rest...}.
// An unparsable value produces an error rather than a zero value.
func DecodeRoute(ctx *fasthttp.RequestCtx) (RouteParams, error) {
	var out RouteParams
	out.Rest = httpbind.PathValue(ctx, "rest")
	return out, nil
}
